// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_performance.sql

package sqlcgen

import (
	"context"

	"stackd/storage/sqlite"
)

const deleteInstancePerformanceGroups = `-- name: DeleteInstancePerformanceGroups :exec
DELETE FROM ec2_instance_performance_groups
WHERE partition = ?1 AND account_id = ?2
  AND region = ?3 AND resource_id = ?4
`

type DeleteInstancePerformanceGroupsParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteInstancePerformanceGroups(ctx context.Context, arg DeleteInstancePerformanceGroupsParams) error {
	_, err := q.db.ExecContext(ctx, deleteInstancePerformanceGroups,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	return err
}

const listInstancePerformanceGroups = `-- name: ListInstancePerformanceGroups :many
SELECT "partition", account_id, region, resource_id, group_name, cpu_count, cpu_sum, cpu_min, cpu_max, network_in, network_out, network_observed FROM ec2_instance_performance_groups
WHERE partition = ?1 AND account_id = ?2
  AND region = ?3 AND resource_id = ?4
ORDER BY group_name
`

type ListInstancePerformanceGroupsParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) ListInstancePerformanceGroups(ctx context.Context, arg ListInstancePerformanceGroupsParams) ([]Ec2InstancePerformanceGroup, error) {
	rows, err := q.db.QueryContext(ctx, listInstancePerformanceGroups,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2InstancePerformanceGroup{}
	for rows.Next() {
		var i Ec2InstancePerformanceGroup
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.GroupName,
			&i.CpuCount,
			&i.CpuSum,
			&i.CpuMin,
			&i.CpuMax,
			&i.NetworkIn,
			&i.NetworkOut,
			&i.NetworkObserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putInstancePerformanceGroup = `-- name: PutInstancePerformanceGroup :exec
INSERT INTO ec2_instance_performance_groups (
 partition, account_id, region, resource_id, group_name,
 cpu_count, cpu_sum, cpu_min, cpu_max, network_in, network_out, network_observed
) VALUES (
 ?1, ?2, ?3, ?4, ?5,
 ?6, ?7, ?8, ?9,
 ?10, ?11, ?12
)
`

type PutInstancePerformanceGroupParams struct {
	Partition       string
	AccountID       string
	Region          string
	ResourceID      string
	GroupName       string
	CpuCount        int64
	CpuSum          float64
	CpuMin          float64
	CpuMax          float64
	NetworkIn       sqlite.Uint64
	NetworkOut      sqlite.Uint64
	NetworkObserved bool
}

func (q *Queries) PutInstancePerformanceGroup(ctx context.Context, arg PutInstancePerformanceGroupParams) error {
	_, err := q.db.ExecContext(ctx, putInstancePerformanceGroup,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.GroupName,
		arg.CpuCount,
		arg.CpuSum,
		arg.CpuMin,
		arg.CpuMax,
		arg.NetworkIn,
		arg.NetworkOut,
		arg.NetworkObserved,
	)
	return err
}
