// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: network_owner.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteNatGateway = `-- name: DeleteNatGateway :execrows
DELETE FROM ec2_nat_gateways WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type DeleteNatGatewayParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteNatGateway(ctx context.Context, arg DeleteNatGatewayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNatGateway,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNatGatewayAddresses = `-- name: DeleteNatGatewayAddresses :exec
DELETE FROM ec2_nat_gateway_addresses WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type DeleteNatGatewayAddressesParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteNatGatewayAddresses(ctx context.Context, arg DeleteNatGatewayAddressesParams) error {
	_, err := q.db.ExecContext(ctx, deleteNatGatewayAddresses,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	return err
}

const deleteNatGatewayTags = `-- name: DeleteNatGatewayTags :exec
DELETE FROM ec2_nat_gateway_tags WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type DeleteNatGatewayTagsParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteNatGatewayTags(ctx context.Context, arg DeleteNatGatewayTagsParams) error {
	_, err := q.db.ExecContext(ctx, deleteNatGatewayTags,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	return err
}

const deleteVPCEndpoint = `-- name: DeleteVPCEndpoint :execrows
DELETE FROM ec2_vpc_endpoints WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type DeleteVPCEndpointParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteVPCEndpoint(ctx context.Context, arg DeleteVPCEndpointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVPCEndpoint,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVPCEndpointDNSEntries = `-- name: DeleteVPCEndpointDNSEntries :exec
DELETE FROM ec2_vpc_endpoint_dns_entries WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type DeleteVPCEndpointDNSEntriesParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteVPCEndpointDNSEntries(ctx context.Context, arg DeleteVPCEndpointDNSEntriesParams) error {
	_, err := q.db.ExecContext(ctx, deleteVPCEndpointDNSEntries,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	return err
}

const deleteVPCEndpointGroups = `-- name: DeleteVPCEndpointGroups :exec
DELETE FROM ec2_vpc_endpoint_groups WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type DeleteVPCEndpointGroupsParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteVPCEndpointGroups(ctx context.Context, arg DeleteVPCEndpointGroupsParams) error {
	_, err := q.db.ExecContext(ctx, deleteVPCEndpointGroups,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	return err
}

const deleteVPCEndpointInterfaces = `-- name: DeleteVPCEndpointInterfaces :exec
DELETE FROM ec2_vpc_endpoint_interfaces WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type DeleteVPCEndpointInterfacesParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteVPCEndpointInterfaces(ctx context.Context, arg DeleteVPCEndpointInterfacesParams) error {
	_, err := q.db.ExecContext(ctx, deleteVPCEndpointInterfaces,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	return err
}

const deleteVPCEndpointRouteTables = `-- name: DeleteVPCEndpointRouteTables :exec
DELETE FROM ec2_vpc_endpoint_route_tables WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type DeleteVPCEndpointRouteTablesParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteVPCEndpointRouteTables(ctx context.Context, arg DeleteVPCEndpointRouteTablesParams) error {
	_, err := q.db.ExecContext(ctx, deleteVPCEndpointRouteTables,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	return err
}

const deleteVPCEndpointSubnets = `-- name: DeleteVPCEndpointSubnets :exec
DELETE FROM ec2_vpc_endpoint_subnets WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type DeleteVPCEndpointSubnetsParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteVPCEndpointSubnets(ctx context.Context, arg DeleteVPCEndpointSubnetsParams) error {
	_, err := q.db.ExecContext(ctx, deleteVPCEndpointSubnets,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	return err
}

const deleteVPCEndpointTags = `-- name: DeleteVPCEndpointTags :exec
DELETE FROM ec2_vpc_endpoint_tags WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type DeleteVPCEndpointTagsParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) DeleteVPCEndpointTags(ctx context.Context, arg DeleteVPCEndpointTagsParams) error {
	_, err := q.db.ExecContext(ctx, deleteVPCEndpointTags,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	return err
}

const getNatGateway = `-- name: GetNatGateway :one
SELECT "partition", account_id, region, resource_id, nat_gateway_id, vpc_id, subnet_id, connectivity_type, availability_mode, state, create_time, delete_time, failure_code, failure_message, tags_present, nat_gateway_addresses_present, cloudformation_resource_type, cloudformation_owner FROM ec2_nat_gateways WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type GetNatGatewayParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) GetNatGateway(ctx context.Context, arg GetNatGatewayParams) (Ec2NatGateway, error) {
	row := q.db.QueryRowContext(ctx, getNatGateway,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	var i Ec2NatGateway
	err := row.Scan(
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.ResourceID,
		&i.NatGatewayID,
		&i.VpcID,
		&i.SubnetID,
		&i.ConnectivityType,
		&i.AvailabilityMode,
		&i.State,
		&i.CreateTime,
		&i.DeleteTime,
		&i.FailureCode,
		&i.FailureMessage,
		&i.TagsPresent,
		&i.NatGatewayAddressesPresent,
		&i.CloudformationResourceType,
		&i.CloudformationOwner,
	)
	return i, err
}

const getNetworkOwnerCreation = `-- name: GetNetworkOwnerCreation :one
SELECT "partition", account_id, region, "action", token, resource_id, fingerprint FROM ec2_network_owner_creations WHERE partition=?1 AND account_id=?2 AND region=?3 AND action=?4 AND token=?5
`

type GetNetworkOwnerCreationParams struct {
	Partition string
	AccountID string
	Region    string
	Action    string
	Token     string
}

func (q *Queries) GetNetworkOwnerCreation(ctx context.Context, arg GetNetworkOwnerCreationParams) (Ec2NetworkOwnerCreation, error) {
	row := q.db.QueryRowContext(ctx, getNetworkOwnerCreation,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Action,
		arg.Token,
	)
	var i Ec2NetworkOwnerCreation
	err := row.Scan(
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Action,
		&i.Token,
		&i.ResourceID,
		&i.Fingerprint,
	)
	return i, err
}

const getVPCEndpoint = `-- name: GetVPCEndpoint :one
SELECT "partition", account_id, region, resource_id, vpc_endpoint_id, vpc_id, vpc_endpoint_type, service_name, service_region, owner_id, requester_managed, state, creation_timestamp, policy_document, private_dns_enabled, ip_address_type, tags_present, groups_present, route_table_ids_present, subnet_ids_present, network_interface_ids_present, dns_entries_present, dns_options_present, dns_record_ip_type, private_dns_only_for_inbound_resolver_endpoint, cloudformation_resource_type, cloudformation_owner FROM ec2_vpc_endpoints WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4
`

type GetVPCEndpointParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) GetVPCEndpoint(ctx context.Context, arg GetVPCEndpointParams) (Ec2VpcEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getVPCEndpoint,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	var i Ec2VpcEndpoint
	err := row.Scan(
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.ResourceID,
		&i.VpcEndpointID,
		&i.VpcID,
		&i.VpcEndpointType,
		&i.ServiceName,
		&i.ServiceRegion,
		&i.OwnerID,
		&i.RequesterManaged,
		&i.State,
		&i.CreationTimestamp,
		&i.PolicyDocument,
		&i.PrivateDnsEnabled,
		&i.IpAddressType,
		&i.TagsPresent,
		&i.GroupsPresent,
		&i.RouteTableIdsPresent,
		&i.SubnetIdsPresent,
		&i.NetworkInterfaceIdsPresent,
		&i.DnsEntriesPresent,
		&i.DnsOptionsPresent,
		&i.DnsRecordIpType,
		&i.PrivateDnsOnlyForInboundResolverEndpoint,
		&i.CloudformationResourceType,
		&i.CloudformationOwner,
	)
	return i, err
}

const listNatGatewayAddresses = `-- name: ListNatGatewayAddresses :many
SELECT "partition", account_id, region, resource_id, position, allocation_id, association_id, network_interface_id, private_ip, public_ip, is_primary, status FROM ec2_nat_gateway_addresses WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4 ORDER BY position
`

type ListNatGatewayAddressesParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) ListNatGatewayAddresses(ctx context.Context, arg ListNatGatewayAddressesParams) ([]Ec2NatGatewayAddress, error) {
	rows, err := q.db.QueryContext(ctx, listNatGatewayAddresses,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2NatGatewayAddress{}
	for rows.Next() {
		var i Ec2NatGatewayAddress
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.Position,
			&i.AllocationID,
			&i.AssociationID,
			&i.NetworkInterfaceID,
			&i.PrivateIp,
			&i.PublicIp,
			&i.IsPrimary,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNatGatewayTags = `-- name: ListNatGatewayTags :many
SELECT "partition", account_id, region, resource_id, position, "key", value FROM ec2_nat_gateway_tags WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4 ORDER BY position
`

type ListNatGatewayTagsParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) ListNatGatewayTags(ctx context.Context, arg ListNatGatewayTagsParams) ([]Ec2NatGatewayTag, error) {
	rows, err := q.db.QueryContext(ctx, listNatGatewayTags,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2NatGatewayTag{}
	for rows.Next() {
		var i Ec2NatGatewayTag
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.Position,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNatGateways = `-- name: ListNatGateways :many
SELECT "partition", account_id, region, resource_id, nat_gateway_id, vpc_id, subnet_id, connectivity_type, availability_mode, state, create_time, delete_time, failure_code, failure_message, tags_present, nat_gateway_addresses_present, cloudformation_resource_type, cloudformation_owner FROM ec2_nat_gateways WHERE partition = ?1 AND account_id = ?2 AND region = ?3 ORDER BY resource_id
`

type ListNatGatewaysParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) ListNatGateways(ctx context.Context, arg ListNatGatewaysParams) ([]Ec2NatGateway, error) {
	rows, err := q.db.QueryContext(ctx, listNatGateways, arg.Partition, arg.AccountID, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2NatGateway{}
	for rows.Next() {
		var i Ec2NatGateway
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.NatGatewayID,
			&i.VpcID,
			&i.SubnetID,
			&i.ConnectivityType,
			&i.AvailabilityMode,
			&i.State,
			&i.CreateTime,
			&i.DeleteTime,
			&i.FailureCode,
			&i.FailureMessage,
			&i.TagsPresent,
			&i.NatGatewayAddressesPresent,
			&i.CloudformationResourceType,
			&i.CloudformationOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPCEndpointDNSEntries = `-- name: ListVPCEndpointDNSEntries :many
SELECT "partition", account_id, region, resource_id, position, dns_name, hosted_zone_id FROM ec2_vpc_endpoint_dns_entries WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4 ORDER BY position
`

type ListVPCEndpointDNSEntriesParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) ListVPCEndpointDNSEntries(ctx context.Context, arg ListVPCEndpointDNSEntriesParams) ([]Ec2VpcEndpointDnsEntry, error) {
	rows, err := q.db.QueryContext(ctx, listVPCEndpointDNSEntries,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2VpcEndpointDnsEntry{}
	for rows.Next() {
		var i Ec2VpcEndpointDnsEntry
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.Position,
			&i.DnsName,
			&i.HostedZoneID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPCEndpointGroups = `-- name: ListVPCEndpointGroups :many
SELECT "partition", account_id, region, resource_id, position, group_id, group_name FROM ec2_vpc_endpoint_groups WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4 ORDER BY position
`

type ListVPCEndpointGroupsParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) ListVPCEndpointGroups(ctx context.Context, arg ListVPCEndpointGroupsParams) ([]Ec2VpcEndpointGroup, error) {
	rows, err := q.db.QueryContext(ctx, listVPCEndpointGroups,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2VpcEndpointGroup{}
	for rows.Next() {
		var i Ec2VpcEndpointGroup
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.Position,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPCEndpointInterfaces = `-- name: ListVPCEndpointInterfaces :many
SELECT "partition", account_id, region, resource_id, position, value FROM ec2_vpc_endpoint_interfaces WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4 ORDER BY position
`

type ListVPCEndpointInterfacesParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) ListVPCEndpointInterfaces(ctx context.Context, arg ListVPCEndpointInterfacesParams) ([]Ec2VpcEndpointInterface, error) {
	rows, err := q.db.QueryContext(ctx, listVPCEndpointInterfaces,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2VpcEndpointInterface{}
	for rows.Next() {
		var i Ec2VpcEndpointInterface
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.Position,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPCEndpointRouteTables = `-- name: ListVPCEndpointRouteTables :many
SELECT "partition", account_id, region, resource_id, position, value FROM ec2_vpc_endpoint_route_tables WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4 ORDER BY position
`

type ListVPCEndpointRouteTablesParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) ListVPCEndpointRouteTables(ctx context.Context, arg ListVPCEndpointRouteTablesParams) ([]Ec2VpcEndpointRouteTable, error) {
	rows, err := q.db.QueryContext(ctx, listVPCEndpointRouteTables,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2VpcEndpointRouteTable{}
	for rows.Next() {
		var i Ec2VpcEndpointRouteTable
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.Position,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPCEndpointSubnets = `-- name: ListVPCEndpointSubnets :many
SELECT "partition", account_id, region, resource_id, position, value FROM ec2_vpc_endpoint_subnets WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4 ORDER BY position
`

type ListVPCEndpointSubnetsParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) ListVPCEndpointSubnets(ctx context.Context, arg ListVPCEndpointSubnetsParams) ([]Ec2VpcEndpointSubnet, error) {
	rows, err := q.db.QueryContext(ctx, listVPCEndpointSubnets,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2VpcEndpointSubnet{}
	for rows.Next() {
		var i Ec2VpcEndpointSubnet
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.Position,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPCEndpointTags = `-- name: ListVPCEndpointTags :many
SELECT "partition", account_id, region, resource_id, position, "key", value FROM ec2_vpc_endpoint_tags WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND resource_id = ?4 ORDER BY position
`

type ListVPCEndpointTagsParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
}

func (q *Queries) ListVPCEndpointTags(ctx context.Context, arg ListVPCEndpointTagsParams) ([]Ec2VpcEndpointTag, error) {
	rows, err := q.db.QueryContext(ctx, listVPCEndpointTags,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2VpcEndpointTag{}
	for rows.Next() {
		var i Ec2VpcEndpointTag
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.Position,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPCEndpoints = `-- name: ListVPCEndpoints :many
SELECT "partition", account_id, region, resource_id, vpc_endpoint_id, vpc_id, vpc_endpoint_type, service_name, service_region, owner_id, requester_managed, state, creation_timestamp, policy_document, private_dns_enabled, ip_address_type, tags_present, groups_present, route_table_ids_present, subnet_ids_present, network_interface_ids_present, dns_entries_present, dns_options_present, dns_record_ip_type, private_dns_only_for_inbound_resolver_endpoint, cloudformation_resource_type, cloudformation_owner FROM ec2_vpc_endpoints WHERE partition = ?1 AND account_id = ?2 AND region = ?3 ORDER BY resource_id
`

type ListVPCEndpointsParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) ListVPCEndpoints(ctx context.Context, arg ListVPCEndpointsParams) ([]Ec2VpcEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listVPCEndpoints, arg.Partition, arg.AccountID, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ec2VpcEndpoint{}
	for rows.Next() {
		var i Ec2VpcEndpoint
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceID,
			&i.VpcEndpointID,
			&i.VpcID,
			&i.VpcEndpointType,
			&i.ServiceName,
			&i.ServiceRegion,
			&i.OwnerID,
			&i.RequesterManaged,
			&i.State,
			&i.CreationTimestamp,
			&i.PolicyDocument,
			&i.PrivateDnsEnabled,
			&i.IpAddressType,
			&i.TagsPresent,
			&i.GroupsPresent,
			&i.RouteTableIdsPresent,
			&i.SubnetIdsPresent,
			&i.NetworkInterfaceIdsPresent,
			&i.DnsEntriesPresent,
			&i.DnsOptionsPresent,
			&i.DnsRecordIpType,
			&i.PrivateDnsOnlyForInboundResolverEndpoint,
			&i.CloudformationResourceType,
			&i.CloudformationOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putNatGateway = `-- name: PutNatGateway :exec
INSERT INTO ec2_nat_gateways (partition, account_id, region, resource_id, nat_gateway_id, vpc_id, subnet_id, connectivity_type, availability_mode, state, create_time, delete_time, failure_code, failure_message, tags_present, nat_gateway_addresses_present) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16) ON CONFLICT (partition, account_id, region, resource_id) DO UPDATE SET nat_gateway_id = excluded.nat_gateway_id, vpc_id = excluded.vpc_id, subnet_id = excluded.subnet_id, connectivity_type = excluded.connectivity_type, availability_mode = excluded.availability_mode, state = excluded.state, create_time = excluded.create_time, delete_time = excluded.delete_time, failure_code = excluded.failure_code, failure_message = excluded.failure_message, tags_present = excluded.tags_present, nat_gateway_addresses_present = excluded.nat_gateway_addresses_present
`

type PutNatGatewayParams struct {
	Partition                  string
	AccountID                  string
	Region                     string
	ResourceID                 string
	NatGatewayID               sql.NullString
	VpcID                      sql.NullString
	SubnetID                   sql.NullString
	ConnectivityType           sql.NullString
	AvailabilityMode           sql.NullString
	State                      sql.NullString
	CreateTime                 sql.NullString
	DeleteTime                 sql.NullString
	FailureCode                sql.NullString
	FailureMessage             sql.NullString
	TagsPresent                bool
	NatGatewayAddressesPresent bool
}

func (q *Queries) PutNatGateway(ctx context.Context, arg PutNatGatewayParams) error {
	_, err := q.db.ExecContext(ctx, putNatGateway,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.NatGatewayID,
		arg.VpcID,
		arg.SubnetID,
		arg.ConnectivityType,
		arg.AvailabilityMode,
		arg.State,
		arg.CreateTime,
		arg.DeleteTime,
		arg.FailureCode,
		arg.FailureMessage,
		arg.TagsPresent,
		arg.NatGatewayAddressesPresent,
	)
	return err
}

const putNatGatewayAddress = `-- name: PutNatGatewayAddress :exec
INSERT INTO ec2_nat_gateway_addresses (partition, account_id, region, resource_id, position, allocation_id, association_id, network_interface_id, private_ip, public_ip, is_primary, status) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
`

type PutNatGatewayAddressParams struct {
	Partition          string
	AccountID          string
	Region             string
	ResourceID         string
	Position           int64
	AllocationID       sql.NullString
	AssociationID      sql.NullString
	NetworkInterfaceID sql.NullString
	PrivateIp          sql.NullString
	PublicIp           sql.NullString
	IsPrimary          sql.NullBool
	Status             sql.NullString
}

func (q *Queries) PutNatGatewayAddress(ctx context.Context, arg PutNatGatewayAddressParams) error {
	_, err := q.db.ExecContext(ctx, putNatGatewayAddress,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.Position,
		arg.AllocationID,
		arg.AssociationID,
		arg.NetworkInterfaceID,
		arg.PrivateIp,
		arg.PublicIp,
		arg.IsPrimary,
		arg.Status,
	)
	return err
}

const putNatGatewayTag = `-- name: PutNatGatewayTag :exec
INSERT INTO ec2_nat_gateway_tags (partition, account_id, region, resource_id, position, key, value) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type PutNatGatewayTagParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
	Position   int64
	Key        sql.NullString
	Value      sql.NullString
}

func (q *Queries) PutNatGatewayTag(ctx context.Context, arg PutNatGatewayTagParams) error {
	_, err := q.db.ExecContext(ctx, putNatGatewayTag,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.Position,
		arg.Key,
		arg.Value,
	)
	return err
}

const putNetworkOwnerCreation = `-- name: PutNetworkOwnerCreation :exec
INSERT INTO ec2_network_owner_creations(partition,account_id,region,action,token,resource_id,fingerprint) VALUES(?1,?2,?3,?4,?5,?6,?7)
`

type PutNetworkOwnerCreationParams struct {
	Partition   string
	AccountID   string
	Region      string
	Action      string
	Token       string
	ResourceID  string
	Fingerprint string
}

func (q *Queries) PutNetworkOwnerCreation(ctx context.Context, arg PutNetworkOwnerCreationParams) error {
	_, err := q.db.ExecContext(ctx, putNetworkOwnerCreation,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Action,
		arg.Token,
		arg.ResourceID,
		arg.Fingerprint,
	)
	return err
}

const putNetworkRelationOwner = `-- name: PutNetworkRelationOwner :exec
INSERT INTO ec2_network_owner_creations(partition,account_id,region,action,token,resource_id,fingerprint)
VALUES(?1,?2,?3,?4,'',?5,?6)
ON CONFLICT(partition,account_id,region,action,token) DO UPDATE SET resource_id=excluded.resource_id,fingerprint=excluded.fingerprint
`

type PutNetworkRelationOwnerParams struct {
	Partition   string
	AccountID   string
	Region      string
	Action      string
	ResourceID  string
	Fingerprint string
}

func (q *Queries) PutNetworkRelationOwner(ctx context.Context, arg PutNetworkRelationOwnerParams) error {
	_, err := q.db.ExecContext(ctx, putNetworkRelationOwner,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Action,
		arg.ResourceID,
		arg.Fingerprint,
	)
	return err
}

const putVPCEndpoint = `-- name: PutVPCEndpoint :exec
INSERT INTO ec2_vpc_endpoints (partition, account_id, region, resource_id, vpc_endpoint_id, vpc_id, vpc_endpoint_type, service_name, service_region, owner_id, requester_managed, state, creation_timestamp, policy_document, private_dns_enabled, ip_address_type, tags_present, groups_present, route_table_ids_present, subnet_ids_present, network_interface_ids_present, dns_entries_present, dns_options_present, dns_record_ip_type, private_dns_only_for_inbound_resolver_endpoint) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25) ON CONFLICT (partition, account_id, region, resource_id) DO UPDATE SET vpc_endpoint_id = excluded.vpc_endpoint_id, vpc_id = excluded.vpc_id, vpc_endpoint_type = excluded.vpc_endpoint_type, service_name = excluded.service_name, service_region = excluded.service_region, owner_id = excluded.owner_id, requester_managed = excluded.requester_managed, state = excluded.state, creation_timestamp = excluded.creation_timestamp, policy_document = excluded.policy_document, private_dns_enabled = excluded.private_dns_enabled, ip_address_type = excluded.ip_address_type, tags_present = excluded.tags_present, groups_present = excluded.groups_present, route_table_ids_present = excluded.route_table_ids_present, subnet_ids_present = excluded.subnet_ids_present, network_interface_ids_present = excluded.network_interface_ids_present, dns_entries_present = excluded.dns_entries_present, dns_options_present = excluded.dns_options_present, dns_record_ip_type = excluded.dns_record_ip_type, private_dns_only_for_inbound_resolver_endpoint = excluded.private_dns_only_for_inbound_resolver_endpoint
`

type PutVPCEndpointParams struct {
	Partition                                string
	AccountID                                string
	Region                                   string
	ResourceID                               string
	VpcEndpointID                            sql.NullString
	VpcID                                    sql.NullString
	VpcEndpointType                          sql.NullString
	ServiceName                              sql.NullString
	ServiceRegion                            sql.NullString
	OwnerID                                  sql.NullString
	RequesterManaged                         sql.NullBool
	State                                    sql.NullString
	CreationTimestamp                        sql.NullString
	PolicyDocument                           sql.NullString
	PrivateDnsEnabled                        sql.NullBool
	IpAddressType                            sql.NullString
	TagsPresent                              bool
	GroupsPresent                            bool
	RouteTableIdsPresent                     bool
	SubnetIdsPresent                         bool
	NetworkInterfaceIdsPresent               bool
	DnsEntriesPresent                        bool
	DnsOptionsPresent                        bool
	DnsRecordIpType                          sql.NullString
	PrivateDnsOnlyForInboundResolverEndpoint sql.NullBool
}

func (q *Queries) PutVPCEndpoint(ctx context.Context, arg PutVPCEndpointParams) error {
	_, err := q.db.ExecContext(ctx, putVPCEndpoint,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.VpcEndpointID,
		arg.VpcID,
		arg.VpcEndpointType,
		arg.ServiceName,
		arg.ServiceRegion,
		arg.OwnerID,
		arg.RequesterManaged,
		arg.State,
		arg.CreationTimestamp,
		arg.PolicyDocument,
		arg.PrivateDnsEnabled,
		arg.IpAddressType,
		arg.TagsPresent,
		arg.GroupsPresent,
		arg.RouteTableIdsPresent,
		arg.SubnetIdsPresent,
		arg.NetworkInterfaceIdsPresent,
		arg.DnsEntriesPresent,
		arg.DnsOptionsPresent,
		arg.DnsRecordIpType,
		arg.PrivateDnsOnlyForInboundResolverEndpoint,
	)
	return err
}

const putVPCEndpointDNSEntry = `-- name: PutVPCEndpointDNSEntry :exec
INSERT INTO ec2_vpc_endpoint_dns_entries (partition, account_id, region, resource_id, position, dns_name, hosted_zone_id) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type PutVPCEndpointDNSEntryParams struct {
	Partition    string
	AccountID    string
	Region       string
	ResourceID   string
	Position     int64
	DnsName      sql.NullString
	HostedZoneID sql.NullString
}

func (q *Queries) PutVPCEndpointDNSEntry(ctx context.Context, arg PutVPCEndpointDNSEntryParams) error {
	_, err := q.db.ExecContext(ctx, putVPCEndpointDNSEntry,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.Position,
		arg.DnsName,
		arg.HostedZoneID,
	)
	return err
}

const putVPCEndpointGroup = `-- name: PutVPCEndpointGroup :exec
INSERT INTO ec2_vpc_endpoint_groups (partition, account_id, region, resource_id, position, group_id, group_name) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type PutVPCEndpointGroupParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
	Position   int64
	GroupID    sql.NullString
	GroupName  sql.NullString
}

func (q *Queries) PutVPCEndpointGroup(ctx context.Context, arg PutVPCEndpointGroupParams) error {
	_, err := q.db.ExecContext(ctx, putVPCEndpointGroup,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.Position,
		arg.GroupID,
		arg.GroupName,
	)
	return err
}

const putVPCEndpointInterface = `-- name: PutVPCEndpointInterface :exec
INSERT INTO ec2_vpc_endpoint_interfaces (partition, account_id, region, resource_id, position, value) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type PutVPCEndpointInterfaceParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
	Position   int64
	Value      sql.NullString
}

func (q *Queries) PutVPCEndpointInterface(ctx context.Context, arg PutVPCEndpointInterfaceParams) error {
	_, err := q.db.ExecContext(ctx, putVPCEndpointInterface,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.Position,
		arg.Value,
	)
	return err
}

const putVPCEndpointRouteTable = `-- name: PutVPCEndpointRouteTable :exec
INSERT INTO ec2_vpc_endpoint_route_tables (partition, account_id, region, resource_id, position, value) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type PutVPCEndpointRouteTableParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
	Position   int64
	Value      sql.NullString
}

func (q *Queries) PutVPCEndpointRouteTable(ctx context.Context, arg PutVPCEndpointRouteTableParams) error {
	_, err := q.db.ExecContext(ctx, putVPCEndpointRouteTable,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.Position,
		arg.Value,
	)
	return err
}

const putVPCEndpointSubnet = `-- name: PutVPCEndpointSubnet :exec
INSERT INTO ec2_vpc_endpoint_subnets (partition, account_id, region, resource_id, position, value) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type PutVPCEndpointSubnetParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
	Position   int64
	Value      sql.NullString
}

func (q *Queries) PutVPCEndpointSubnet(ctx context.Context, arg PutVPCEndpointSubnetParams) error {
	_, err := q.db.ExecContext(ctx, putVPCEndpointSubnet,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.Position,
		arg.Value,
	)
	return err
}

const putVPCEndpointTag = `-- name: PutVPCEndpointTag :exec
INSERT INTO ec2_vpc_endpoint_tags (partition, account_id, region, resource_id, position, key, value) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type PutVPCEndpointTagParams struct {
	Partition  string
	AccountID  string
	Region     string
	ResourceID string
	Position   int64
	Key        sql.NullString
	Value      sql.NullString
}

func (q *Queries) PutVPCEndpointTag(ctx context.Context, arg PutVPCEndpointTagParams) error {
	_, err := q.db.ExecContext(ctx, putVPCEndpointTag,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceID,
		arg.Position,
		arg.Key,
		arg.Value,
	)
	return err
}
