// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"stackd/storage/sqlite"
)

type CloudtrailAdvancedSelector struct {
	TrailID  string
	Position int64
	Name     string
}

type CloudtrailBasicSelector struct {
	TrailID           string
	Position          int64
	ReadOnly          *bool
	IncludeManagement bool
}

type CloudtrailDataPrefix struct {
	TrailID          string
	SelectorPosition int64
	ResourcePosition int64
	Position         int64
	Prefix           string
}

type CloudtrailDataResource struct {
	TrailID          string
	SelectorPosition int64
	Position         int64
	Type             string
}

type CloudtrailDelivery struct {
	ID             string
	TrailID        string
	AccountID      string
	Region         string
	Bucket         string
	ObjectKey      string
	Created        time.Time
	Due            time.Time
	Expires        time.Time
	Sealed         bool
	EventCount     int64
	Attempts       int64
	Version        sqlite.Uint64
	Destination    string
	LogsGroupArn   string
	LogsRoleArn    string
	OrganizationID string
}

type CloudtrailDeliveryEvent struct {
	DeliveryID string
	Position   int64
	EventID    string
}

type CloudtrailDeliveryStatus struct {
	TrailID     string
	Destination string
	LastAttempt *time.Time
	LastSuccess *time.Time
	LastError   string
}

type CloudtrailDigestKey struct {
	Partition   string
	Region      string
	Fingerprint string
	Start       time.Time
	End         time.Time
	PrivateDer  []byte
	PublicDer   []byte
}

type CloudtrailDigestLog struct {
	StreamID   string
	DeliveryID string
	Bucket     string
	Object     string
	Hash       string
	Delivered  time.Time
	Oldest     time.Time
	Newest     time.Time
}

type CloudtrailDigestStatus struct {
	TrailID     string
	AccountID   string
	Region      string
	LastAttempt *time.Time
	LastSuccess *time.Time
	LastError   string
}

type CloudtrailDigestStream struct {
	ID                string
	TrailID           string
	Partition         string
	TrailAccount      string
	HomeRegion        string
	TrailName         string
	AccountID         string
	Region            string
	OrganizationID    string
	Bucket            string
	Prefix            string
	KmsKeyID          string
	Start             time.Time
	End               time.Time
	Due               time.Time
	Closed            bool
	ClosedAt          time.Time
	Version           int64
	PreviousBucket    string
	PreviousObject    string
	PreviousHash      string
	PreviousSignature string
	Pending           []byte
	PendingObject     string
	PendingHash       string
	PendingSignature  string
}

type CloudtrailExcludedSource struct {
	TrailID          string
	SelectorPosition int64
	Position         int64
	Source           string
}

type CloudtrailField struct {
	TrailID          string
	SelectorPosition int64
	Position         int64
	Field            string
}

type CloudtrailTag struct {
	TrailID string
	Key     string
	Value   string
}

type CloudtrailTest struct {
	TrailID          string
	SelectorPosition int64
	FieldPosition    int64
	Position         int64
	Operator         string
}

type CloudtrailTestValue struct {
	TrailID          string
	SelectorPosition int64
	FieldPosition    int64
	TestPosition     int64
	Position         int64
	Value            string
}

type CloudtrailTrail struct {
	Partition         string
	AccountID         string
	Region            string
	Name              string
	ID                string
	Bucket            string
	Prefix            string
	IncludeGlobal     bool
	MultiRegion       bool
	RecursiveLogging  bool
	Logging           bool
	Created           time.Time
	Modified          time.Time
	Started           *time.Time
	Stopped           *time.Time
	StopAfter         *time.Time
	LogsGroupArn      string
	LogsRoleArn       string
	KmsKeyID          string
	SnsTopicName      string
	OrganizationID    string
	LogFileValidation bool
	CfnOwner          string
}
