// Code generated by awsgen from AWS SDK for Go v2 Smithy models; DO NOT EDIT.
package pipes

import "time"

// Arn represents Smithy shape com.amazonaws.pipes#Arn.
type Arn string

// ArnOrJsonPath represents Smithy shape com.amazonaws.pipes#ArnOrJsonPath.
type ArnOrJsonPath string

// ArnOrUrl represents Smithy shape com.amazonaws.pipes#ArnOrUrl.
type ArnOrUrl string

// AssignPublicIp represents Smithy shape com.amazonaws.pipes#AssignPublicIp.
type AssignPublicIp string

// AwsVpcConfiguration represents Smithy shape com.amazonaws.pipes#AwsVpcConfiguration.
type AwsVpcConfiguration struct {
	AssignPublicIp *AssignPublicIp `json:"AssignPublicIp,omitempty" smithy:"AssignPublicIp"`
	SecurityGroups SecurityGroups  `json:"SecurityGroups,omitzero" smithy:"SecurityGroups"`
	// Required by the AWS service model.
	Subnets Subnets `json:"Subnets,omitzero" smithy:"Subnets"`
}

// BatchArrayProperties represents Smithy shape com.amazonaws.pipes#BatchArrayProperties.
type BatchArrayProperties struct {
	Size *BatchArraySize `json:"Size,omitempty" smithy:"Size"`
}

// BatchArraySize represents Smithy shape com.amazonaws.pipes#BatchArraySize.
type BatchArraySize int32

// BatchContainerOverrides represents Smithy shape com.amazonaws.pipes#BatchContainerOverrides.
type BatchContainerOverrides struct {
	Command              StringList                    `json:"Command,omitzero" smithy:"Command"`
	Environment          BatchEnvironmentVariableList  `json:"Environment,omitzero" smithy:"Environment"`
	InstanceType         *String                       `json:"InstanceType,omitempty" smithy:"InstanceType"`
	ResourceRequirements BatchResourceRequirementsList `json:"ResourceRequirements,omitzero" smithy:"ResourceRequirements"`
}

// BatchDependsOn represents Smithy shape com.amazonaws.pipes#BatchDependsOn.
type BatchDependsOn []BatchJobDependency

// BatchEnvironmentVariable represents Smithy shape com.amazonaws.pipes#BatchEnvironmentVariable.
type BatchEnvironmentVariable struct {
	Name  *String `json:"Name,omitempty" smithy:"Name"`
	Value *String `json:"Value,omitempty" smithy:"Value"`
}

// BatchEnvironmentVariableList represents Smithy shape com.amazonaws.pipes#BatchEnvironmentVariableList.
type BatchEnvironmentVariableList []BatchEnvironmentVariable

// BatchJobDependency represents Smithy shape com.amazonaws.pipes#BatchJobDependency.
type BatchJobDependency struct {
	JobId *String                 `json:"JobId,omitempty" smithy:"JobId"`
	Type  *BatchJobDependencyType `json:"Type,omitempty" smithy:"Type"`
}

// BatchJobDependencyType represents Smithy shape com.amazonaws.pipes#BatchJobDependencyType.
type BatchJobDependencyType string

// BatchParametersMap represents Smithy shape com.amazonaws.pipes#BatchParametersMap.
type BatchParametersMap map[String]String

// BatchResourceRequirement represents Smithy shape com.amazonaws.pipes#BatchResourceRequirement.
type BatchResourceRequirement struct {
	// Required by the AWS service model.
	Type *BatchResourceRequirementType `json:"Type,omitempty" smithy:"Type"`
	// Required by the AWS service model.
	Value *String `json:"Value,omitempty" smithy:"Value"`
}

// BatchResourceRequirementType represents Smithy shape com.amazonaws.pipes#BatchResourceRequirementType.
type BatchResourceRequirementType string

// BatchResourceRequirementsList represents Smithy shape com.amazonaws.pipes#BatchResourceRequirementsList.
type BatchResourceRequirementsList []BatchResourceRequirement

// BatchRetryAttempts represents Smithy shape com.amazonaws.pipes#BatchRetryAttempts.
type BatchRetryAttempts int32

// BatchRetryStrategy represents Smithy shape com.amazonaws.pipes#BatchRetryStrategy.
type BatchRetryStrategy struct {
	Attempts *BatchRetryAttempts `json:"Attempts,omitempty" smithy:"Attempts"`
}

// Boolean represents Smithy shape com.amazonaws.pipes#Boolean.
type Boolean bool

// CapacityProvider represents Smithy shape com.amazonaws.pipes#CapacityProvider.
type CapacityProvider string

// CapacityProviderStrategy represents Smithy shape com.amazonaws.pipes#CapacityProviderStrategy.
type CapacityProviderStrategy []CapacityProviderStrategyItem

// CapacityProviderStrategyItem represents Smithy shape com.amazonaws.pipes#CapacityProviderStrategyItem.
type CapacityProviderStrategyItem struct {
	Base *CapacityProviderStrategyItemBase `json:"base,omitempty" smithy:"base"`
	// Required by the AWS service model.
	CapacityProvider *CapacityProvider                   `json:"capacityProvider,omitempty" smithy:"capacityProvider"`
	Weight           *CapacityProviderStrategyItemWeight `json:"weight,omitempty" smithy:"weight"`
}

// CapacityProviderStrategyItemBase represents Smithy shape com.amazonaws.pipes#CapacityProviderStrategyItemBase.
type CapacityProviderStrategyItemBase int32

// CapacityProviderStrategyItemWeight represents Smithy shape com.amazonaws.pipes#CapacityProviderStrategyItemWeight.
type CapacityProviderStrategyItemWeight int32

// CloudwatchLogGroupArn represents Smithy shape com.amazonaws.pipes#CloudwatchLogGroupArn.
type CloudwatchLogGroupArn string

// CloudwatchLogsLogDestination represents Smithy shape com.amazonaws.pipes#CloudwatchLogsLogDestination.
type CloudwatchLogsLogDestination struct {
	LogGroupArn *CloudwatchLogGroupArn `json:"LogGroupArn,omitempty" smithy:"LogGroupArn"`
}

// CloudwatchLogsLogDestinationParameters represents Smithy shape com.amazonaws.pipes#CloudwatchLogsLogDestinationParameters.
type CloudwatchLogsLogDestinationParameters struct {
	// Required by the AWS service model.
	LogGroupArn *CloudwatchLogGroupArn `json:"LogGroupArn,omitempty" smithy:"LogGroupArn"`
}

// ConflictException represents Smithy shape com.amazonaws.pipes#ConflictException.
type ConflictException struct {
	// Required by the AWS service model.
	Message *String `json:"message,omitempty" smithy:"message"`
	// Required by the AWS service model.
	ResourceId *String `json:"resourceId,omitempty" smithy:"resourceId"`
	// Required by the AWS service model.
	ResourceType *String `json:"resourceType,omitempty" smithy:"resourceType"`
}

// CreatePipeRequest represents Smithy shape com.amazonaws.pipes#CreatePipeRequest.
type CreatePipeRequest struct {
	Description          *PipeDescription                `json:"Description,omitempty" smithy:"Description"`
	DesiredState         *RequestedPipeState             `json:"DesiredState,omitempty" smithy:"DesiredState"`
	Enrichment           *OptionalArn                    `json:"Enrichment,omitempty" smithy:"Enrichment"`
	EnrichmentParameters *PipeEnrichmentParameters       `json:"EnrichmentParameters,omitempty" smithy:"EnrichmentParameters"`
	KmsKeyIdentifier     *KmsKeyIdentifier               `json:"KmsKeyIdentifier,omitempty" smithy:"KmsKeyIdentifier"`
	LogConfiguration     *PipeLogConfigurationParameters `json:"LogConfiguration,omitempty" smithy:"LogConfiguration"`
	// Required by the AWS service model.
	Name *PipeName `json:"Name,omitempty" smithy:"Name"`
	// Required by the AWS service model.
	RoleArn *RoleArn `json:"RoleArn,omitempty" smithy:"RoleArn"`
	// Required by the AWS service model.
	Source           *ArnOrUrl             `json:"Source,omitempty" smithy:"Source"`
	SourceParameters *PipeSourceParameters `json:"SourceParameters,omitempty" smithy:"SourceParameters"`
	Tags             TagMap                `json:"Tags,omitzero" smithy:"Tags"`
	// Required by the AWS service model.
	Target           *Arn                  `json:"Target,omitempty" smithy:"Target"`
	TargetParameters *PipeTargetParameters `json:"TargetParameters,omitempty" smithy:"TargetParameters"`
}

// CreatePipeResponse represents Smithy shape com.amazonaws.pipes#CreatePipeResponse.
type CreatePipeResponse struct {
	Arn              *PipeArn            `json:"Arn,omitempty" smithy:"Arn"`
	CreationTime     *Timestamp          `json:"CreationTime,omitempty" smithy:"CreationTime"`
	CurrentState     *PipeState          `json:"CurrentState,omitempty" smithy:"CurrentState"`
	DesiredState     *RequestedPipeState `json:"DesiredState,omitempty" smithy:"DesiredState"`
	LastModifiedTime *Timestamp          `json:"LastModifiedTime,omitempty" smithy:"LastModifiedTime"`
	Name             *PipeName           `json:"Name,omitempty" smithy:"Name"`
}

// Database represents Smithy shape com.amazonaws.pipes#Database.
type Database string

// DbUser represents Smithy shape com.amazonaws.pipes#DbUser.
type DbUser string

// DeadLetterConfig represents Smithy shape com.amazonaws.pipes#DeadLetterConfig.
type DeadLetterConfig struct {
	Arn *Arn `json:"Arn,omitempty" smithy:"Arn"`
}

// DeletePipeRequest represents Smithy shape com.amazonaws.pipes#DeletePipeRequest.
type DeletePipeRequest struct {
	// Required by the AWS service model.
	Name *PipeName `json:"Name,omitempty" smithy:"Name"`
}

// DeletePipeResponse represents Smithy shape com.amazonaws.pipes#DeletePipeResponse.
type DeletePipeResponse struct {
	Arn              *PipeArn                            `json:"Arn,omitempty" smithy:"Arn"`
	CreationTime     *Timestamp                          `json:"CreationTime,omitempty" smithy:"CreationTime"`
	CurrentState     *PipeState                          `json:"CurrentState,omitempty" smithy:"CurrentState"`
	DesiredState     *RequestedPipeStateDescribeResponse `json:"DesiredState,omitempty" smithy:"DesiredState"`
	LastModifiedTime *Timestamp                          `json:"LastModifiedTime,omitempty" smithy:"LastModifiedTime"`
	Name             *PipeName                           `json:"Name,omitempty" smithy:"Name"`
}

// DescribePipeRequest represents Smithy shape com.amazonaws.pipes#DescribePipeRequest.
type DescribePipeRequest struct {
	// Required by the AWS service model.
	Name *PipeName `json:"Name,omitempty" smithy:"Name"`
}

// DescribePipeResponse represents Smithy shape com.amazonaws.pipes#DescribePipeResponse.
type DescribePipeResponse struct {
	Arn                  *PipeArn                            `json:"Arn,omitempty" smithy:"Arn"`
	CreationTime         *Timestamp                          `json:"CreationTime,omitempty" smithy:"CreationTime"`
	CurrentState         *PipeState                          `json:"CurrentState,omitempty" smithy:"CurrentState"`
	Description          *PipeDescription                    `json:"Description,omitempty" smithy:"Description"`
	DesiredState         *RequestedPipeStateDescribeResponse `json:"DesiredState,omitempty" smithy:"DesiredState"`
	Enrichment           *OptionalArn                        `json:"Enrichment,omitempty" smithy:"Enrichment"`
	EnrichmentParameters *PipeEnrichmentParameters           `json:"EnrichmentParameters,omitempty" smithy:"EnrichmentParameters"`
	KmsKeyIdentifier     *KmsKeyIdentifier                   `json:"KmsKeyIdentifier,omitempty" smithy:"KmsKeyIdentifier"`
	LastModifiedTime     *Timestamp                          `json:"LastModifiedTime,omitempty" smithy:"LastModifiedTime"`
	LogConfiguration     *PipeLogConfiguration               `json:"LogConfiguration,omitempty" smithy:"LogConfiguration"`
	Name                 *PipeName                           `json:"Name,omitempty" smithy:"Name"`
	RoleArn              *RoleArn                            `json:"RoleArn,omitempty" smithy:"RoleArn"`
	Source               *ArnOrUrl                           `json:"Source,omitempty" smithy:"Source"`
	SourceParameters     *PipeSourceParameters               `json:"SourceParameters,omitempty" smithy:"SourceParameters"`
	StateReason          *PipeStateReason                    `json:"StateReason,omitempty" smithy:"StateReason"`
	Tags                 TagMap                              `json:"Tags,omitzero" smithy:"Tags"`
	Target               *Arn                                `json:"Target,omitempty" smithy:"Target"`
	TargetParameters     *PipeTargetParameters               `json:"TargetParameters,omitempty" smithy:"TargetParameters"`
}

// DimensionMapping represents Smithy shape com.amazonaws.pipes#DimensionMapping.
type DimensionMapping struct {
	// Required by the AWS service model.
	DimensionName *DimensionName `json:"DimensionName,omitempty" smithy:"DimensionName"`
	// Required by the AWS service model.
	DimensionValue *DimensionValue `json:"DimensionValue,omitempty" smithy:"DimensionValue"`
	// Required by the AWS service model.
	DimensionValueType *DimensionValueType `json:"DimensionValueType,omitempty" smithy:"DimensionValueType"`
}

// DimensionMappings represents Smithy shape com.amazonaws.pipes#DimensionMappings.
type DimensionMappings []DimensionMapping

// DimensionName represents Smithy shape com.amazonaws.pipes#DimensionName.
type DimensionName string

// DimensionValue represents Smithy shape com.amazonaws.pipes#DimensionValue.
type DimensionValue string

// DimensionValueType represents Smithy shape com.amazonaws.pipes#DimensionValueType.
type DimensionValueType string

// DynamoDBStreamStartPosition represents Smithy shape com.amazonaws.pipes#DynamoDBStreamStartPosition.
type DynamoDBStreamStartPosition string

// EcsContainerOverride represents Smithy shape com.amazonaws.pipes#EcsContainerOverride.
type EcsContainerOverride struct {
	Command              StringList                  `json:"Command,omitzero" smithy:"Command"`
	Cpu                  *Integer                    `json:"Cpu,omitempty" smithy:"Cpu"`
	Environment          EcsEnvironmentVariableList  `json:"Environment,omitzero" smithy:"Environment"`
	EnvironmentFiles     EcsEnvironmentFileList      `json:"EnvironmentFiles,omitzero" smithy:"EnvironmentFiles"`
	Memory               *Integer                    `json:"Memory,omitempty" smithy:"Memory"`
	MemoryReservation    *Integer                    `json:"MemoryReservation,omitempty" smithy:"MemoryReservation"`
	Name                 *String                     `json:"Name,omitempty" smithy:"Name"`
	ResourceRequirements EcsResourceRequirementsList `json:"ResourceRequirements,omitzero" smithy:"ResourceRequirements"`
}

// EcsContainerOverrideList represents Smithy shape com.amazonaws.pipes#EcsContainerOverrideList.
type EcsContainerOverrideList []EcsContainerOverride

// EcsEnvironmentFile represents Smithy shape com.amazonaws.pipes#EcsEnvironmentFile.
type EcsEnvironmentFile struct {
	// Required by the AWS service model.
	Type *EcsEnvironmentFileType `json:"type,omitempty" smithy:"type"`
	// Required by the AWS service model.
	Value *String `json:"value,omitempty" smithy:"value"`
}

// EcsEnvironmentFileList represents Smithy shape com.amazonaws.pipes#EcsEnvironmentFileList.
type EcsEnvironmentFileList []EcsEnvironmentFile

// EcsEnvironmentFileType represents Smithy shape com.amazonaws.pipes#EcsEnvironmentFileType.
type EcsEnvironmentFileType string

// EcsEnvironmentVariable represents Smithy shape com.amazonaws.pipes#EcsEnvironmentVariable.
type EcsEnvironmentVariable struct {
	Name  *String `json:"name,omitempty" smithy:"name"`
	Value *String `json:"value,omitempty" smithy:"value"`
}

// EcsEnvironmentVariableList represents Smithy shape com.amazonaws.pipes#EcsEnvironmentVariableList.
type EcsEnvironmentVariableList []EcsEnvironmentVariable

// EcsEphemeralStorage represents Smithy shape com.amazonaws.pipes#EcsEphemeralStorage.
type EcsEphemeralStorage struct {
	// Required by the AWS service model.
	SizeInGiB *EphemeralStorageSize `json:"sizeInGiB,omitempty" smithy:"sizeInGiB"`
}

// EcsInferenceAcceleratorOverride represents Smithy shape com.amazonaws.pipes#EcsInferenceAcceleratorOverride.
type EcsInferenceAcceleratorOverride struct {
	DeviceName *String `json:"deviceName,omitempty" smithy:"deviceName"`
	DeviceType *String `json:"deviceType,omitempty" smithy:"deviceType"`
}

// EcsInferenceAcceleratorOverrideList represents Smithy shape com.amazonaws.pipes#EcsInferenceAcceleratorOverrideList.
type EcsInferenceAcceleratorOverrideList []EcsInferenceAcceleratorOverride

// EcsResourceRequirement represents Smithy shape com.amazonaws.pipes#EcsResourceRequirement.
type EcsResourceRequirement struct {
	// Required by the AWS service model.
	Type *EcsResourceRequirementType `json:"type,omitempty" smithy:"type"`
	// Required by the AWS service model.
	Value *String `json:"value,omitempty" smithy:"value"`
}

// EcsResourceRequirementType represents Smithy shape com.amazonaws.pipes#EcsResourceRequirementType.
type EcsResourceRequirementType string

// EcsResourceRequirementsList represents Smithy shape com.amazonaws.pipes#EcsResourceRequirementsList.
type EcsResourceRequirementsList []EcsResourceRequirement

// EcsTaskOverride represents Smithy shape com.amazonaws.pipes#EcsTaskOverride.
type EcsTaskOverride struct {
	ContainerOverrides            EcsContainerOverrideList            `json:"ContainerOverrides,omitzero" smithy:"ContainerOverrides"`
	Cpu                           *String                             `json:"Cpu,omitempty" smithy:"Cpu"`
	EphemeralStorage              *EcsEphemeralStorage                `json:"EphemeralStorage,omitempty" smithy:"EphemeralStorage"`
	ExecutionRoleArn              *ArnOrJsonPath                      `json:"ExecutionRoleArn,omitempty" smithy:"ExecutionRoleArn"`
	InferenceAcceleratorOverrides EcsInferenceAcceleratorOverrideList `json:"InferenceAcceleratorOverrides,omitzero" smithy:"InferenceAcceleratorOverrides"`
	Memory                        *String                             `json:"Memory,omitempty" smithy:"Memory"`
	TaskRoleArn                   *ArnOrJsonPath                      `json:"TaskRoleArn,omitempty" smithy:"TaskRoleArn"`
}

// EndpointString represents Smithy shape com.amazonaws.pipes#EndpointString.
type EndpointString string

// EphemeralStorageSize represents Smithy shape com.amazonaws.pipes#EphemeralStorageSize.
type EphemeralStorageSize int32

// EpochTimeUnit represents Smithy shape com.amazonaws.pipes#EpochTimeUnit.
type EpochTimeUnit string

// ErrorMessage represents Smithy shape com.amazonaws.pipes#ErrorMessage.
type ErrorMessage string

// EventBridgeDetailType represents Smithy shape com.amazonaws.pipes#EventBridgeDetailType.
type EventBridgeDetailType string

// EventBridgeEndpointId represents Smithy shape com.amazonaws.pipes#EventBridgeEndpointId.
type EventBridgeEndpointId string

// EventBridgeEventResourceList represents Smithy shape com.amazonaws.pipes#EventBridgeEventResourceList.
type EventBridgeEventResourceList []ArnOrJsonPath

// EventBridgeEventSource represents Smithy shape com.amazonaws.pipes#EventBridgeEventSource.
type EventBridgeEventSource string

// EventPattern represents Smithy shape com.amazonaws.pipes#EventPattern.
type EventPattern string

// Filter represents Smithy shape com.amazonaws.pipes#Filter.
type Filter struct {
	Pattern *EventPattern `json:"Pattern,omitempty" smithy:"Pattern"`
}

// FilterCriteria represents Smithy shape com.amazonaws.pipes#FilterCriteria.
type FilterCriteria struct {
	Filters FilterList `json:"Filters,omitzero" smithy:"Filters"`
}

// FilterList represents Smithy shape com.amazonaws.pipes#FilterList.
type FilterList []Filter

// FirehoseArn represents Smithy shape com.amazonaws.pipes#FirehoseArn.
type FirehoseArn string

// FirehoseLogDestination represents Smithy shape com.amazonaws.pipes#FirehoseLogDestination.
type FirehoseLogDestination struct {
	DeliveryStreamArn *FirehoseArn `json:"DeliveryStreamArn,omitempty" smithy:"DeliveryStreamArn"`
}

// FirehoseLogDestinationParameters represents Smithy shape com.amazonaws.pipes#FirehoseLogDestinationParameters.
type FirehoseLogDestinationParameters struct {
	// Required by the AWS service model.
	DeliveryStreamArn *FirehoseArn `json:"DeliveryStreamArn,omitempty" smithy:"DeliveryStreamArn"`
}

// HeaderKey represents Smithy shape com.amazonaws.pipes#HeaderKey.
type HeaderKey string

// HeaderParametersMap represents Smithy shape com.amazonaws.pipes#HeaderParametersMap.
type HeaderParametersMap map[HeaderKey]HeaderValue

// HeaderValue represents Smithy shape com.amazonaws.pipes#HeaderValue.
type HeaderValue string

// IncludeExecutionData represents Smithy shape com.amazonaws.pipes#IncludeExecutionData.
type IncludeExecutionData []IncludeExecutionDataOption

// IncludeExecutionDataOption represents Smithy shape com.amazonaws.pipes#IncludeExecutionDataOption.
type IncludeExecutionDataOption string

// InputTemplate represents Smithy shape com.amazonaws.pipes#InputTemplate.
type InputTemplate string

// InternalException represents Smithy shape com.amazonaws.pipes#InternalException.
type InternalException struct {
	// Required by the AWS service model.
	Message           *String  `json:"message,omitempty" smithy:"message"`
	RetryAfterSeconds *Integer `json:"retryAfterSeconds,omitempty" smithy:"retryAfterSeconds"`
}

// JsonPath represents Smithy shape com.amazonaws.pipes#JsonPath.
type JsonPath string

// KafkaBootstrapServers represents Smithy shape com.amazonaws.pipes#KafkaBootstrapServers.
type KafkaBootstrapServers []EndpointString

// KafkaTopicName represents Smithy shape com.amazonaws.pipes#KafkaTopicName.
type KafkaTopicName string

// KinesisPartitionKey represents Smithy shape com.amazonaws.pipes#KinesisPartitionKey.
type KinesisPartitionKey string

// KinesisStreamStartPosition represents Smithy shape com.amazonaws.pipes#KinesisStreamStartPosition.
type KinesisStreamStartPosition string

// KmsKeyIdentifier represents Smithy shape com.amazonaws.pipes#KmsKeyIdentifier.
type KmsKeyIdentifier string

// LaunchType represents Smithy shape com.amazonaws.pipes#LaunchType.
type LaunchType string

// LimitMax10 represents Smithy shape com.amazonaws.pipes#LimitMax10.
type LimitMax10 int32

// LimitMax100 represents Smithy shape com.amazonaws.pipes#LimitMax100.
type LimitMax100 int32

// LimitMax10000 represents Smithy shape com.amazonaws.pipes#LimitMax10000.
type LimitMax10000 int32

// LimitMin1 represents Smithy shape com.amazonaws.pipes#LimitMin1.
type LimitMin1 int32

// ListPipesRequest represents Smithy shape com.amazonaws.pipes#ListPipesRequest.
type ListPipesRequest struct {
	CurrentState *PipeState          `json:"CurrentState,omitempty" smithy:"CurrentState"`
	DesiredState *RequestedPipeState `json:"DesiredState,omitempty" smithy:"DesiredState"`
	Limit        *LimitMax100        `json:"Limit,omitempty" smithy:"Limit"`
	NamePrefix   *PipeName           `json:"NamePrefix,omitempty" smithy:"NamePrefix"`
	NextToken    *NextToken          `json:"NextToken,omitempty" smithy:"NextToken"`
	SourcePrefix *ResourceArn        `json:"SourcePrefix,omitempty" smithy:"SourcePrefix"`
	TargetPrefix *ResourceArn        `json:"TargetPrefix,omitempty" smithy:"TargetPrefix"`
}

// ListPipesResponse represents Smithy shape com.amazonaws.pipes#ListPipesResponse.
type ListPipesResponse struct {
	NextToken *NextToken `json:"NextToken,omitempty" smithy:"NextToken"`
	Pipes     PipeList   `json:"Pipes,omitzero" smithy:"Pipes"`
}

// ListTagsForResourceRequest represents Smithy shape com.amazonaws.pipes#ListTagsForResourceRequest.
type ListTagsForResourceRequest struct {
	// Required by the AWS service model.
	ResourceArn *PipeArn `json:"resourceArn,omitempty" smithy:"resourceArn"`
}

// ListTagsForResourceResponse represents Smithy shape com.amazonaws.pipes#ListTagsForResourceResponse.
type ListTagsForResourceResponse struct {
	Tags TagMap `json:"tags,omitzero" smithy:"tags"`
}

// LogLevel represents Smithy shape com.amazonaws.pipes#LogLevel.
type LogLevel string

// LogStreamName represents Smithy shape com.amazonaws.pipes#LogStreamName.
type LogStreamName string

// MQBrokerAccessCredentials represents Smithy shape com.amazonaws.pipes#MQBrokerAccessCredentials.
type MQBrokerAccessCredentials struct {
	BasicAuth *SecretManagerArn `json:"BasicAuth,omitempty" smithy:"BasicAuth"`
}

// MQBrokerQueueName represents Smithy shape com.amazonaws.pipes#MQBrokerQueueName.
type MQBrokerQueueName string

// MSKAccessCredentials represents Smithy shape com.amazonaws.pipes#MSKAccessCredentials.
type MSKAccessCredentials struct {
	ClientCertificateTlsAuth *SecretManagerArn `json:"ClientCertificateTlsAuth,omitempty" smithy:"ClientCertificateTlsAuth"`
	SaslScram512Auth         *SecretManagerArn `json:"SaslScram512Auth,omitempty" smithy:"SaslScram512Auth"`
}

// MSKStartPosition represents Smithy shape com.amazonaws.pipes#MSKStartPosition.
type MSKStartPosition string

// MaximumBatchingWindowInSeconds represents Smithy shape com.amazonaws.pipes#MaximumBatchingWindowInSeconds.
type MaximumBatchingWindowInSeconds int32

// MaximumRecordAgeInSeconds represents Smithy shape com.amazonaws.pipes#MaximumRecordAgeInSeconds.
type MaximumRecordAgeInSeconds int32

// MaximumRetryAttemptsESM represents Smithy shape com.amazonaws.pipes#MaximumRetryAttemptsESM.
type MaximumRetryAttemptsESM int32

// MeasureName represents Smithy shape com.amazonaws.pipes#MeasureName.
type MeasureName string

// MeasureValue represents Smithy shape com.amazonaws.pipes#MeasureValue.
type MeasureValue string

// MeasureValueType represents Smithy shape com.amazonaws.pipes#MeasureValueType.
type MeasureValueType string

// MessageDeduplicationId represents Smithy shape com.amazonaws.pipes#MessageDeduplicationId.
type MessageDeduplicationId string

// MessageGroupId represents Smithy shape com.amazonaws.pipes#MessageGroupId.
type MessageGroupId string

// MultiMeasureAttributeMapping represents Smithy shape com.amazonaws.pipes#MultiMeasureAttributeMapping.
type MultiMeasureAttributeMapping struct {
	// Required by the AWS service model.
	MeasureValue *MeasureValue `json:"MeasureValue,omitempty" smithy:"MeasureValue"`
	// Required by the AWS service model.
	MeasureValueType *MeasureValueType `json:"MeasureValueType,omitempty" smithy:"MeasureValueType"`
	// Required by the AWS service model.
	MultiMeasureAttributeName *MultiMeasureAttributeName `json:"MultiMeasureAttributeName,omitempty" smithy:"MultiMeasureAttributeName"`
}

// MultiMeasureAttributeMappings represents Smithy shape com.amazonaws.pipes#MultiMeasureAttributeMappings.
type MultiMeasureAttributeMappings []MultiMeasureAttributeMapping

// MultiMeasureAttributeName represents Smithy shape com.amazonaws.pipes#MultiMeasureAttributeName.
type MultiMeasureAttributeName string

// MultiMeasureMapping represents Smithy shape com.amazonaws.pipes#MultiMeasureMapping.
type MultiMeasureMapping struct {
	// Required by the AWS service model.
	MultiMeasureAttributeMappings MultiMeasureAttributeMappings `json:"MultiMeasureAttributeMappings,omitzero" smithy:"MultiMeasureAttributeMappings"`
	// Required by the AWS service model.
	MultiMeasureName *MultiMeasureName `json:"MultiMeasureName,omitempty" smithy:"MultiMeasureName"`
}

// MultiMeasureMappings represents Smithy shape com.amazonaws.pipes#MultiMeasureMappings.
type MultiMeasureMappings []MultiMeasureMapping

// MultiMeasureName represents Smithy shape com.amazonaws.pipes#MultiMeasureName.
type MultiMeasureName string

// NetworkConfiguration represents Smithy shape com.amazonaws.pipes#NetworkConfiguration.
type NetworkConfiguration struct {
	AwsvpcConfiguration *AwsVpcConfiguration `json:"awsvpcConfiguration,omitempty" smithy:"awsvpcConfiguration"`
}

// NextToken represents Smithy shape com.amazonaws.pipes#NextToken.
type NextToken string

// NotFoundException represents Smithy shape com.amazonaws.pipes#NotFoundException.
type NotFoundException struct {
	Message *ErrorMessage `json:"message,omitempty" smithy:"message"`
}

// OnPartialBatchItemFailureStreams represents Smithy shape com.amazonaws.pipes#OnPartialBatchItemFailureStreams.
type OnPartialBatchItemFailureStreams string

// OptionalArn represents Smithy shape com.amazonaws.pipes#OptionalArn.
type OptionalArn string

// PathParameter represents Smithy shape com.amazonaws.pipes#PathParameter.
type PathParameter string

// PathParameterList represents Smithy shape com.amazonaws.pipes#PathParameterList.
type PathParameterList []PathParameter

// Pipe represents Smithy shape com.amazonaws.pipes#Pipe.
type Pipe struct {
	Arn              *PipeArn            `json:"Arn,omitempty" smithy:"Arn"`
	CreationTime     *Timestamp          `json:"CreationTime,omitempty" smithy:"CreationTime"`
	CurrentState     *PipeState          `json:"CurrentState,omitempty" smithy:"CurrentState"`
	DesiredState     *RequestedPipeState `json:"DesiredState,omitempty" smithy:"DesiredState"`
	Enrichment       *OptionalArn        `json:"Enrichment,omitempty" smithy:"Enrichment"`
	LastModifiedTime *Timestamp          `json:"LastModifiedTime,omitempty" smithy:"LastModifiedTime"`
	Name             *PipeName           `json:"Name,omitempty" smithy:"Name"`
	Source           *ArnOrUrl           `json:"Source,omitempty" smithy:"Source"`
	StateReason      *PipeStateReason    `json:"StateReason,omitempty" smithy:"StateReason"`
	Target           *Arn                `json:"Target,omitempty" smithy:"Target"`
}

// PipeArn represents Smithy shape com.amazonaws.pipes#PipeArn.
type PipeArn string

// PipeDescription represents Smithy shape com.amazonaws.pipes#PipeDescription.
type PipeDescription string

// PipeEnrichmentHttpParameters represents Smithy shape com.amazonaws.pipes#PipeEnrichmentHttpParameters.
type PipeEnrichmentHttpParameters struct {
	HeaderParameters      HeaderParametersMap      `json:"HeaderParameters,omitzero" smithy:"HeaderParameters"`
	PathParameterValues   PathParameterList        `json:"PathParameterValues,omitzero" smithy:"PathParameterValues"`
	QueryStringParameters QueryStringParametersMap `json:"QueryStringParameters,omitzero" smithy:"QueryStringParameters"`
}

// PipeEnrichmentParameters represents Smithy shape com.amazonaws.pipes#PipeEnrichmentParameters.
type PipeEnrichmentParameters struct {
	HttpParameters *PipeEnrichmentHttpParameters `json:"HttpParameters,omitempty" smithy:"HttpParameters"`
	InputTemplate  *InputTemplate                `json:"InputTemplate,omitempty" smithy:"InputTemplate"`
}

// PipeList represents Smithy shape com.amazonaws.pipes#PipeList.
type PipeList []Pipe

// PipeLogConfiguration represents Smithy shape com.amazonaws.pipes#PipeLogConfiguration.
type PipeLogConfiguration struct {
	CloudwatchLogsLogDestination *CloudwatchLogsLogDestination `json:"CloudwatchLogsLogDestination,omitempty" smithy:"CloudwatchLogsLogDestination"`
	FirehoseLogDestination       *FirehoseLogDestination       `json:"FirehoseLogDestination,omitempty" smithy:"FirehoseLogDestination"`
	IncludeExecutionData         IncludeExecutionData          `json:"IncludeExecutionData,omitzero" smithy:"IncludeExecutionData"`
	Level                        *LogLevel                     `json:"Level,omitempty" smithy:"Level"`
	S3LogDestination             *S3LogDestination             `json:"S3LogDestination,omitempty" smithy:"S3LogDestination"`
}

// PipeLogConfigurationParameters represents Smithy shape com.amazonaws.pipes#PipeLogConfigurationParameters.
type PipeLogConfigurationParameters struct {
	CloudwatchLogsLogDestination *CloudwatchLogsLogDestinationParameters `json:"CloudwatchLogsLogDestination,omitempty" smithy:"CloudwatchLogsLogDestination"`
	FirehoseLogDestination       *FirehoseLogDestinationParameters       `json:"FirehoseLogDestination,omitempty" smithy:"FirehoseLogDestination"`
	IncludeExecutionData         IncludeExecutionData                    `json:"IncludeExecutionData,omitzero" smithy:"IncludeExecutionData"`
	// Required by the AWS service model.
	Level            *LogLevel                   `json:"Level,omitempty" smithy:"Level"`
	S3LogDestination *S3LogDestinationParameters `json:"S3LogDestination,omitempty" smithy:"S3LogDestination"`
}

// PipeName represents Smithy shape com.amazonaws.pipes#PipeName.
type PipeName string

// PipeSourceActiveMQBrokerParameters represents Smithy shape com.amazonaws.pipes#PipeSourceActiveMQBrokerParameters.
type PipeSourceActiveMQBrokerParameters struct {
	BatchSize *LimitMax10000 `json:"BatchSize,omitempty" smithy:"BatchSize"`
	// Required by the AWS service model.
	Credentials                    *MQBrokerAccessCredentials      `json:"Credentials,omitempty" smithy:"Credentials"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
	// Required by the AWS service model.
	QueueName *MQBrokerQueueName `json:"QueueName,omitempty" smithy:"QueueName"`
}

// PipeSourceDynamoDBStreamParameters represents Smithy shape com.amazonaws.pipes#PipeSourceDynamoDBStreamParameters.
type PipeSourceDynamoDBStreamParameters struct {
	BatchSize                      *LimitMax10000                    `json:"BatchSize,omitempty" smithy:"BatchSize"`
	DeadLetterConfig               *DeadLetterConfig                 `json:"DeadLetterConfig,omitempty" smithy:"DeadLetterConfig"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds   `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
	MaximumRecordAgeInSeconds      *MaximumRecordAgeInSeconds        `json:"MaximumRecordAgeInSeconds,omitempty" smithy:"MaximumRecordAgeInSeconds"`
	MaximumRetryAttempts           *MaximumRetryAttemptsESM          `json:"MaximumRetryAttempts,omitempty" smithy:"MaximumRetryAttempts"`
	OnPartialBatchItemFailure      *OnPartialBatchItemFailureStreams `json:"OnPartialBatchItemFailure,omitempty" smithy:"OnPartialBatchItemFailure"`
	ParallelizationFactor          *LimitMax10                       `json:"ParallelizationFactor,omitempty" smithy:"ParallelizationFactor"`
	// Required by the AWS service model.
	StartingPosition *DynamoDBStreamStartPosition `json:"StartingPosition,omitempty" smithy:"StartingPosition"`
}

// PipeSourceKinesisStreamParameters represents Smithy shape com.amazonaws.pipes#PipeSourceKinesisStreamParameters.
type PipeSourceKinesisStreamParameters struct {
	BatchSize                      *LimitMax10000                    `json:"BatchSize,omitempty" smithy:"BatchSize"`
	DeadLetterConfig               *DeadLetterConfig                 `json:"DeadLetterConfig,omitempty" smithy:"DeadLetterConfig"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds   `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
	MaximumRecordAgeInSeconds      *MaximumRecordAgeInSeconds        `json:"MaximumRecordAgeInSeconds,omitempty" smithy:"MaximumRecordAgeInSeconds"`
	MaximumRetryAttempts           *MaximumRetryAttemptsESM          `json:"MaximumRetryAttempts,omitempty" smithy:"MaximumRetryAttempts"`
	OnPartialBatchItemFailure      *OnPartialBatchItemFailureStreams `json:"OnPartialBatchItemFailure,omitempty" smithy:"OnPartialBatchItemFailure"`
	ParallelizationFactor          *LimitMax10                       `json:"ParallelizationFactor,omitempty" smithy:"ParallelizationFactor"`
	// Required by the AWS service model.
	StartingPosition          *KinesisStreamStartPosition `json:"StartingPosition,omitempty" smithy:"StartingPosition"`
	StartingPositionTimestamp *Timestamp                  `json:"StartingPositionTimestamp,omitempty" smithy:"StartingPositionTimestamp"`
}

// PipeSourceManagedStreamingKafkaParameters represents Smithy shape com.amazonaws.pipes#PipeSourceManagedStreamingKafkaParameters.
type PipeSourceManagedStreamingKafkaParameters struct {
	BatchSize                      *LimitMax10000                  `json:"BatchSize,omitempty" smithy:"BatchSize"`
	ConsumerGroupID                *URI                            `json:"ConsumerGroupID,omitempty" smithy:"ConsumerGroupID"`
	Credentials                    *MSKAccessCredentials           `json:"Credentials,omitempty" smithy:"Credentials"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
	StartingPosition               *MSKStartPosition               `json:"StartingPosition,omitempty" smithy:"StartingPosition"`
	// Required by the AWS service model.
	TopicName *KafkaTopicName `json:"TopicName,omitempty" smithy:"TopicName"`
}

// PipeSourceParameters represents Smithy shape com.amazonaws.pipes#PipeSourceParameters.
type PipeSourceParameters struct {
	ActiveMQBrokerParameters        *PipeSourceActiveMQBrokerParameters        `json:"ActiveMQBrokerParameters,omitempty" smithy:"ActiveMQBrokerParameters"`
	DynamoDBStreamParameters        *PipeSourceDynamoDBStreamParameters        `json:"DynamoDBStreamParameters,omitempty" smithy:"DynamoDBStreamParameters"`
	FilterCriteria                  *FilterCriteria                            `json:"FilterCriteria,omitempty" smithy:"FilterCriteria"`
	KinesisStreamParameters         *PipeSourceKinesisStreamParameters         `json:"KinesisStreamParameters,omitempty" smithy:"KinesisStreamParameters"`
	ManagedStreamingKafkaParameters *PipeSourceManagedStreamingKafkaParameters `json:"ManagedStreamingKafkaParameters,omitempty" smithy:"ManagedStreamingKafkaParameters"`
	RabbitMQBrokerParameters        *PipeSourceRabbitMQBrokerParameters        `json:"RabbitMQBrokerParameters,omitempty" smithy:"RabbitMQBrokerParameters"`
	SelfManagedKafkaParameters      *PipeSourceSelfManagedKafkaParameters      `json:"SelfManagedKafkaParameters,omitempty" smithy:"SelfManagedKafkaParameters"`
	SqsQueueParameters              *PipeSourceSqsQueueParameters              `json:"SqsQueueParameters,omitempty" smithy:"SqsQueueParameters"`
}

// PipeSourceRabbitMQBrokerParameters represents Smithy shape com.amazonaws.pipes#PipeSourceRabbitMQBrokerParameters.
type PipeSourceRabbitMQBrokerParameters struct {
	BatchSize *LimitMax10000 `json:"BatchSize,omitempty" smithy:"BatchSize"`
	// Required by the AWS service model.
	Credentials                    *MQBrokerAccessCredentials      `json:"Credentials,omitempty" smithy:"Credentials"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
	// Required by the AWS service model.
	QueueName   *MQBrokerQueueName `json:"QueueName,omitempty" smithy:"QueueName"`
	VirtualHost *URI               `json:"VirtualHost,omitempty" smithy:"VirtualHost"`
}

// PipeSourceSelfManagedKafkaParameters represents Smithy shape com.amazonaws.pipes#PipeSourceSelfManagedKafkaParameters.
type PipeSourceSelfManagedKafkaParameters struct {
	AdditionalBootstrapServers     KafkaBootstrapServers                           `json:"AdditionalBootstrapServers,omitzero" smithy:"AdditionalBootstrapServers"`
	BatchSize                      *LimitMax10000                                  `json:"BatchSize,omitempty" smithy:"BatchSize"`
	ConsumerGroupID                *URI                                            `json:"ConsumerGroupID,omitempty" smithy:"ConsumerGroupID"`
	Credentials                    *SelfManagedKafkaAccessConfigurationCredentials `json:"Credentials,omitempty" smithy:"Credentials"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds                 `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
	ServerRootCaCertificate        *SecretManagerArn                               `json:"ServerRootCaCertificate,omitempty" smithy:"ServerRootCaCertificate"`
	StartingPosition               *SelfManagedKafkaStartPosition                  `json:"StartingPosition,omitempty" smithy:"StartingPosition"`
	// Required by the AWS service model.
	TopicName *KafkaTopicName                         `json:"TopicName,omitempty" smithy:"TopicName"`
	Vpc       *SelfManagedKafkaAccessConfigurationVpc `json:"Vpc,omitempty" smithy:"Vpc"`
}

// PipeSourceSqsQueueParameters represents Smithy shape com.amazonaws.pipes#PipeSourceSqsQueueParameters.
type PipeSourceSqsQueueParameters struct {
	BatchSize                      *LimitMax10000                  `json:"BatchSize,omitempty" smithy:"BatchSize"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
}

// PipeState represents Smithy shape com.amazonaws.pipes#PipeState.
type PipeState string

// PipeStateReason represents Smithy shape com.amazonaws.pipes#PipeStateReason.
type PipeStateReason string

// PipeTargetBatchJobParameters represents Smithy shape com.amazonaws.pipes#PipeTargetBatchJobParameters.
type PipeTargetBatchJobParameters struct {
	ArrayProperties    *BatchArrayProperties    `json:"ArrayProperties,omitempty" smithy:"ArrayProperties"`
	ContainerOverrides *BatchContainerOverrides `json:"ContainerOverrides,omitempty" smithy:"ContainerOverrides"`
	DependsOn          BatchDependsOn           `json:"DependsOn,omitzero" smithy:"DependsOn"`
	// Required by the AWS service model.
	JobDefinition *String `json:"JobDefinition,omitempty" smithy:"JobDefinition"`
	// Required by the AWS service model.
	JobName       *String             `json:"JobName,omitempty" smithy:"JobName"`
	Parameters    BatchParametersMap  `json:"Parameters,omitzero" smithy:"Parameters"`
	RetryStrategy *BatchRetryStrategy `json:"RetryStrategy,omitempty" smithy:"RetryStrategy"`
}

// PipeTargetCloudWatchLogsParameters represents Smithy shape com.amazonaws.pipes#PipeTargetCloudWatchLogsParameters.
type PipeTargetCloudWatchLogsParameters struct {
	LogStreamName *LogStreamName `json:"LogStreamName,omitempty" smithy:"LogStreamName"`
	Timestamp     *JsonPath      `json:"Timestamp,omitempty" smithy:"Timestamp"`
}

// PipeTargetEcsTaskParameters represents Smithy shape com.amazonaws.pipes#PipeTargetEcsTaskParameters.
type PipeTargetEcsTaskParameters struct {
	CapacityProviderStrategy CapacityProviderStrategy `json:"CapacityProviderStrategy,omitzero" smithy:"CapacityProviderStrategy"`
	EnableECSManagedTags     *Boolean                 `json:"EnableECSManagedTags,omitempty" smithy:"EnableECSManagedTags"`
	EnableExecuteCommand     *Boolean                 `json:"EnableExecuteCommand,omitempty" smithy:"EnableExecuteCommand"`
	Group                    *String                  `json:"Group,omitempty" smithy:"Group"`
	LaunchType               *LaunchType              `json:"LaunchType,omitempty" smithy:"LaunchType"`
	NetworkConfiguration     *NetworkConfiguration    `json:"NetworkConfiguration,omitempty" smithy:"NetworkConfiguration"`
	Overrides                *EcsTaskOverride         `json:"Overrides,omitempty" smithy:"Overrides"`
	PlacementConstraints     PlacementConstraints     `json:"PlacementConstraints,omitzero" smithy:"PlacementConstraints"`
	PlacementStrategy        PlacementStrategies      `json:"PlacementStrategy,omitzero" smithy:"PlacementStrategy"`
	PlatformVersion          *String                  `json:"PlatformVersion,omitempty" smithy:"PlatformVersion"`
	PropagateTags            *PropagateTags           `json:"PropagateTags,omitempty" smithy:"PropagateTags"`
	ReferenceId              *ReferenceId             `json:"ReferenceId,omitempty" smithy:"ReferenceId"`
	Tags                     TagList                  `json:"Tags,omitzero" smithy:"Tags"`
	TaskCount                *LimitMin1               `json:"TaskCount,omitempty" smithy:"TaskCount"`
	// Required by the AWS service model.
	TaskDefinitionArn *ArnOrJsonPath `json:"TaskDefinitionArn,omitempty" smithy:"TaskDefinitionArn"`
}

// PipeTargetEventBridgeEventBusParameters represents Smithy shape com.amazonaws.pipes#PipeTargetEventBridgeEventBusParameters.
type PipeTargetEventBridgeEventBusParameters struct {
	DetailType *EventBridgeDetailType       `json:"DetailType,omitempty" smithy:"DetailType"`
	EndpointId *EventBridgeEndpointId       `json:"EndpointId,omitempty" smithy:"EndpointId"`
	Resources  EventBridgeEventResourceList `json:"Resources,omitzero" smithy:"Resources"`
	Source     *EventBridgeEventSource      `json:"Source,omitempty" smithy:"Source"`
	Time       *JsonPath                    `json:"Time,omitempty" smithy:"Time"`
}

// PipeTargetHttpParameters represents Smithy shape com.amazonaws.pipes#PipeTargetHttpParameters.
type PipeTargetHttpParameters struct {
	HeaderParameters      HeaderParametersMap      `json:"HeaderParameters,omitzero" smithy:"HeaderParameters"`
	PathParameterValues   PathParameterList        `json:"PathParameterValues,omitzero" smithy:"PathParameterValues"`
	QueryStringParameters QueryStringParametersMap `json:"QueryStringParameters,omitzero" smithy:"QueryStringParameters"`
}

// PipeTargetInvocationType represents Smithy shape com.amazonaws.pipes#PipeTargetInvocationType.
type PipeTargetInvocationType string

// PipeTargetKinesisStreamParameters represents Smithy shape com.amazonaws.pipes#PipeTargetKinesisStreamParameters.
type PipeTargetKinesisStreamParameters struct {
	// Required by the AWS service model.
	PartitionKey *KinesisPartitionKey `json:"PartitionKey,omitempty" smithy:"PartitionKey"`
}

// PipeTargetLambdaFunctionParameters represents Smithy shape com.amazonaws.pipes#PipeTargetLambdaFunctionParameters.
type PipeTargetLambdaFunctionParameters struct {
	InvocationType *PipeTargetInvocationType `json:"InvocationType,omitempty" smithy:"InvocationType"`
}

// PipeTargetParameters represents Smithy shape com.amazonaws.pipes#PipeTargetParameters.
type PipeTargetParameters struct {
	BatchJobParameters                 *PipeTargetBatchJobParameters            `json:"BatchJobParameters,omitempty" smithy:"BatchJobParameters"`
	CloudWatchLogsParameters           *PipeTargetCloudWatchLogsParameters      `json:"CloudWatchLogsParameters,omitempty" smithy:"CloudWatchLogsParameters"`
	EcsTaskParameters                  *PipeTargetEcsTaskParameters             `json:"EcsTaskParameters,omitempty" smithy:"EcsTaskParameters"`
	EventBridgeEventBusParameters      *PipeTargetEventBridgeEventBusParameters `json:"EventBridgeEventBusParameters,omitempty" smithy:"EventBridgeEventBusParameters"`
	HttpParameters                     *PipeTargetHttpParameters                `json:"HttpParameters,omitempty" smithy:"HttpParameters"`
	InputTemplate                      *InputTemplate                           `json:"InputTemplate,omitempty" smithy:"InputTemplate"`
	KinesisStreamParameters            *PipeTargetKinesisStreamParameters       `json:"KinesisStreamParameters,omitempty" smithy:"KinesisStreamParameters"`
	LambdaFunctionParameters           *PipeTargetLambdaFunctionParameters      `json:"LambdaFunctionParameters,omitempty" smithy:"LambdaFunctionParameters"`
	RedshiftDataParameters             *PipeTargetRedshiftDataParameters        `json:"RedshiftDataParameters,omitempty" smithy:"RedshiftDataParameters"`
	SageMakerPipelineParameters        *PipeTargetSageMakerPipelineParameters   `json:"SageMakerPipelineParameters,omitempty" smithy:"SageMakerPipelineParameters"`
	SqsQueueParameters                 *PipeTargetSqsQueueParameters            `json:"SqsQueueParameters,omitempty" smithy:"SqsQueueParameters"`
	StepFunctionStateMachineParameters *PipeTargetStateMachineParameters        `json:"StepFunctionStateMachineParameters,omitempty" smithy:"StepFunctionStateMachineParameters"`
	TimestreamParameters               *PipeTargetTimestreamParameters          `json:"TimestreamParameters,omitempty" smithy:"TimestreamParameters"`
}

// PipeTargetRedshiftDataParameters represents Smithy shape com.amazonaws.pipes#PipeTargetRedshiftDataParameters.
type PipeTargetRedshiftDataParameters struct {
	// Required by the AWS service model.
	Database         *Database                   `json:"Database,omitempty" smithy:"Database"`
	DbUser           *DbUser                     `json:"DbUser,omitempty" smithy:"DbUser"`
	SecretManagerArn *SecretManagerArnOrJsonPath `json:"SecretManagerArn,omitempty" smithy:"SecretManagerArn"`
	// Required by the AWS service model.
	Sqls          Sqls           `json:"Sqls,omitzero" smithy:"Sqls"`
	StatementName *StatementName `json:"StatementName,omitempty" smithy:"StatementName"`
	WithEvent     *Boolean       `json:"WithEvent,omitempty" smithy:"WithEvent"`
}

// PipeTargetSageMakerPipelineParameters represents Smithy shape com.amazonaws.pipes#PipeTargetSageMakerPipelineParameters.
type PipeTargetSageMakerPipelineParameters struct {
	PipelineParameterList SageMakerPipelineParameterList `json:"PipelineParameterList,omitzero" smithy:"PipelineParameterList"`
}

// PipeTargetSqsQueueParameters represents Smithy shape com.amazonaws.pipes#PipeTargetSqsQueueParameters.
type PipeTargetSqsQueueParameters struct {
	MessageDeduplicationId *MessageDeduplicationId `json:"MessageDeduplicationId,omitempty" smithy:"MessageDeduplicationId"`
	MessageGroupId         *MessageGroupId         `json:"MessageGroupId,omitempty" smithy:"MessageGroupId"`
}

// PipeTargetStateMachineParameters represents Smithy shape com.amazonaws.pipes#PipeTargetStateMachineParameters.
type PipeTargetStateMachineParameters struct {
	InvocationType *PipeTargetInvocationType `json:"InvocationType,omitempty" smithy:"InvocationType"`
}

// PipeTargetTimestreamParameters represents Smithy shape com.amazonaws.pipes#PipeTargetTimestreamParameters.
type PipeTargetTimestreamParameters struct {
	// Required by the AWS service model.
	DimensionMappings     DimensionMappings     `json:"DimensionMappings,omitzero" smithy:"DimensionMappings"`
	EpochTimeUnit         *EpochTimeUnit        `json:"EpochTimeUnit,omitempty" smithy:"EpochTimeUnit"`
	MultiMeasureMappings  MultiMeasureMappings  `json:"MultiMeasureMappings,omitzero" smithy:"MultiMeasureMappings"`
	SingleMeasureMappings SingleMeasureMappings `json:"SingleMeasureMappings,omitzero" smithy:"SingleMeasureMappings"`
	TimeFieldType         *TimeFieldType        `json:"TimeFieldType,omitempty" smithy:"TimeFieldType"`
	// Required by the AWS service model.
	TimeValue       *TimeValue       `json:"TimeValue,omitempty" smithy:"TimeValue"`
	TimestampFormat *TimestampFormat `json:"TimestampFormat,omitempty" smithy:"TimestampFormat"`
	// Required by the AWS service model.
	VersionValue *VersionValue `json:"VersionValue,omitempty" smithy:"VersionValue"`
}

// PlacementConstraint represents Smithy shape com.amazonaws.pipes#PlacementConstraint.
type PlacementConstraint struct {
	Expression *PlacementConstraintExpression `json:"expression,omitempty" smithy:"expression"`
	Type       *PlacementConstraintType       `json:"type,omitempty" smithy:"type"`
}

// PlacementConstraintExpression represents Smithy shape com.amazonaws.pipes#PlacementConstraintExpression.
type PlacementConstraintExpression string

// PlacementConstraintType represents Smithy shape com.amazonaws.pipes#PlacementConstraintType.
type PlacementConstraintType string

// PlacementConstraints represents Smithy shape com.amazonaws.pipes#PlacementConstraints.
type PlacementConstraints []PlacementConstraint

// PlacementStrategies represents Smithy shape com.amazonaws.pipes#PlacementStrategies.
type PlacementStrategies []PlacementStrategy

// PlacementStrategy represents Smithy shape com.amazonaws.pipes#PlacementStrategy.
type PlacementStrategy struct {
	Field *PlacementStrategyField `json:"field,omitempty" smithy:"field"`
	Type  *PlacementStrategyType  `json:"type,omitempty" smithy:"type"`
}

// PlacementStrategyField represents Smithy shape com.amazonaws.pipes#PlacementStrategyField.
type PlacementStrategyField string

// PlacementStrategyType represents Smithy shape com.amazonaws.pipes#PlacementStrategyType.
type PlacementStrategyType string

// PropagateTags represents Smithy shape com.amazonaws.pipes#PropagateTags.
type PropagateTags string

// QueryStringKey represents Smithy shape com.amazonaws.pipes#QueryStringKey.
type QueryStringKey string

// QueryStringParametersMap represents Smithy shape com.amazonaws.pipes#QueryStringParametersMap.
type QueryStringParametersMap map[QueryStringKey]QueryStringValue

// QueryStringValue represents Smithy shape com.amazonaws.pipes#QueryStringValue.
type QueryStringValue string

// ReferenceId represents Smithy shape com.amazonaws.pipes#ReferenceId.
type ReferenceId string

// RequestedPipeState represents Smithy shape com.amazonaws.pipes#RequestedPipeState.
type RequestedPipeState string

// RequestedPipeStateDescribeResponse represents Smithy shape com.amazonaws.pipes#RequestedPipeStateDescribeResponse.
type RequestedPipeStateDescribeResponse string

// ResourceArn represents Smithy shape com.amazonaws.pipes#ResourceArn.
type ResourceArn string

// RoleArn represents Smithy shape com.amazonaws.pipes#RoleArn.
type RoleArn string

// S3LogDestination represents Smithy shape com.amazonaws.pipes#S3LogDestination.
type S3LogDestination struct {
	BucketName   *String         `json:"BucketName,omitempty" smithy:"BucketName"`
	BucketOwner  *String         `json:"BucketOwner,omitempty" smithy:"BucketOwner"`
	OutputFormat *S3OutputFormat `json:"OutputFormat,omitempty" smithy:"OutputFormat"`
	Prefix       *String         `json:"Prefix,omitempty" smithy:"Prefix"`
}

// S3LogDestinationParameters represents Smithy shape com.amazonaws.pipes#S3LogDestinationParameters.
type S3LogDestinationParameters struct {
	// Required by the AWS service model.
	BucketName *String `json:"BucketName,omitempty" smithy:"BucketName"`
	// Required by the AWS service model.
	BucketOwner  *String         `json:"BucketOwner,omitempty" smithy:"BucketOwner"`
	OutputFormat *S3OutputFormat `json:"OutputFormat,omitempty" smithy:"OutputFormat"`
	Prefix       *String         `json:"Prefix,omitempty" smithy:"Prefix"`
}

// S3OutputFormat represents Smithy shape com.amazonaws.pipes#S3OutputFormat.
type S3OutputFormat string

// SageMakerPipelineParameter represents Smithy shape com.amazonaws.pipes#SageMakerPipelineParameter.
type SageMakerPipelineParameter struct {
	// Required by the AWS service model.
	Name *SageMakerPipelineParameterName `json:"Name,omitempty" smithy:"Name"`
	// Required by the AWS service model.
	Value *SageMakerPipelineParameterValue `json:"Value,omitempty" smithy:"Value"`
}

// SageMakerPipelineParameterList represents Smithy shape com.amazonaws.pipes#SageMakerPipelineParameterList.
type SageMakerPipelineParameterList []SageMakerPipelineParameter

// SageMakerPipelineParameterName represents Smithy shape com.amazonaws.pipes#SageMakerPipelineParameterName.
type SageMakerPipelineParameterName string

// SageMakerPipelineParameterValue represents Smithy shape com.amazonaws.pipes#SageMakerPipelineParameterValue.
type SageMakerPipelineParameterValue string

// SecretManagerArn represents Smithy shape com.amazonaws.pipes#SecretManagerArn.
type SecretManagerArn string

// SecretManagerArnOrJsonPath represents Smithy shape com.amazonaws.pipes#SecretManagerArnOrJsonPath.
type SecretManagerArnOrJsonPath string

// SecurityGroup represents Smithy shape com.amazonaws.pipes#SecurityGroup.
type SecurityGroup string

// SecurityGroupId represents Smithy shape com.amazonaws.pipes#SecurityGroupId.
type SecurityGroupId string

// SecurityGroupIds represents Smithy shape com.amazonaws.pipes#SecurityGroupIds.
type SecurityGroupIds []SecurityGroupId

// SecurityGroups represents Smithy shape com.amazonaws.pipes#SecurityGroups.
type SecurityGroups []SecurityGroup

// SelfManagedKafkaAccessConfigurationCredentials represents Smithy shape com.amazonaws.pipes#SelfManagedKafkaAccessConfigurationCredentials.
type SelfManagedKafkaAccessConfigurationCredentials struct {
	BasicAuth                *SecretManagerArn `json:"BasicAuth,omitempty" smithy:"BasicAuth"`
	ClientCertificateTlsAuth *SecretManagerArn `json:"ClientCertificateTlsAuth,omitempty" smithy:"ClientCertificateTlsAuth"`
	SaslScram256Auth         *SecretManagerArn `json:"SaslScram256Auth,omitempty" smithy:"SaslScram256Auth"`
	SaslScram512Auth         *SecretManagerArn `json:"SaslScram512Auth,omitempty" smithy:"SaslScram512Auth"`
}

// SelfManagedKafkaAccessConfigurationVpc represents Smithy shape com.amazonaws.pipes#SelfManagedKafkaAccessConfigurationVpc.
type SelfManagedKafkaAccessConfigurationVpc struct {
	SecurityGroup SecurityGroupIds `json:"SecurityGroup,omitzero" smithy:"SecurityGroup"`
	Subnets       SubnetIds        `json:"Subnets,omitzero" smithy:"Subnets"`
}

// SelfManagedKafkaStartPosition represents Smithy shape com.amazonaws.pipes#SelfManagedKafkaStartPosition.
type SelfManagedKafkaStartPosition string

// ServiceQuotaExceededException represents Smithy shape com.amazonaws.pipes#ServiceQuotaExceededException.
type ServiceQuotaExceededException struct {
	// Required by the AWS service model.
	Message *String `json:"message,omitempty" smithy:"message"`
	// Required by the AWS service model.
	QuotaCode *String `json:"quotaCode,omitempty" smithy:"quotaCode"`
	// Required by the AWS service model.
	ResourceId *String `json:"resourceId,omitempty" smithy:"resourceId"`
	// Required by the AWS service model.
	ResourceType *String `json:"resourceType,omitempty" smithy:"resourceType"`
	// Required by the AWS service model.
	ServiceCode *String `json:"serviceCode,omitempty" smithy:"serviceCode"`
}

// SingleMeasureMapping represents Smithy shape com.amazonaws.pipes#SingleMeasureMapping.
type SingleMeasureMapping struct {
	// Required by the AWS service model.
	MeasureName *MeasureName `json:"MeasureName,omitempty" smithy:"MeasureName"`
	// Required by the AWS service model.
	MeasureValue *MeasureValue `json:"MeasureValue,omitempty" smithy:"MeasureValue"`
	// Required by the AWS service model.
	MeasureValueType *MeasureValueType `json:"MeasureValueType,omitempty" smithy:"MeasureValueType"`
}

// SingleMeasureMappings represents Smithy shape com.amazonaws.pipes#SingleMeasureMappings.
type SingleMeasureMappings []SingleMeasureMapping

// Sql represents Smithy shape com.amazonaws.pipes#Sql.
type Sql string

// Sqls represents Smithy shape com.amazonaws.pipes#Sqls.
type Sqls []Sql

// StartPipeRequest represents Smithy shape com.amazonaws.pipes#StartPipeRequest.
type StartPipeRequest struct {
	// Required by the AWS service model.
	Name *PipeName `json:"Name,omitempty" smithy:"Name"`
}

// StartPipeResponse represents Smithy shape com.amazonaws.pipes#StartPipeResponse.
type StartPipeResponse struct {
	Arn              *PipeArn            `json:"Arn,omitempty" smithy:"Arn"`
	CreationTime     *Timestamp          `json:"CreationTime,omitempty" smithy:"CreationTime"`
	CurrentState     *PipeState          `json:"CurrentState,omitempty" smithy:"CurrentState"`
	DesiredState     *RequestedPipeState `json:"DesiredState,omitempty" smithy:"DesiredState"`
	LastModifiedTime *Timestamp          `json:"LastModifiedTime,omitempty" smithy:"LastModifiedTime"`
	Name             *PipeName           `json:"Name,omitempty" smithy:"Name"`
}

// StatementName represents Smithy shape com.amazonaws.pipes#StatementName.
type StatementName string

// StopPipeRequest represents Smithy shape com.amazonaws.pipes#StopPipeRequest.
type StopPipeRequest struct {
	// Required by the AWS service model.
	Name *PipeName `json:"Name,omitempty" smithy:"Name"`
}

// StopPipeResponse represents Smithy shape com.amazonaws.pipes#StopPipeResponse.
type StopPipeResponse struct {
	Arn              *PipeArn            `json:"Arn,omitempty" smithy:"Arn"`
	CreationTime     *Timestamp          `json:"CreationTime,omitempty" smithy:"CreationTime"`
	CurrentState     *PipeState          `json:"CurrentState,omitempty" smithy:"CurrentState"`
	DesiredState     *RequestedPipeState `json:"DesiredState,omitempty" smithy:"DesiredState"`
	LastModifiedTime *Timestamp          `json:"LastModifiedTime,omitempty" smithy:"LastModifiedTime"`
	Name             *PipeName           `json:"Name,omitempty" smithy:"Name"`
}

// String represents Smithy shape com.amazonaws.pipes#String.
type String string

// StringList represents Smithy shape com.amazonaws.pipes#StringList.
type StringList []String

// Subnet represents Smithy shape com.amazonaws.pipes#Subnet.
type Subnet string

// SubnetId represents Smithy shape com.amazonaws.pipes#SubnetId.
type SubnetId string

// SubnetIds represents Smithy shape com.amazonaws.pipes#SubnetIds.
type SubnetIds []SubnetId

// Subnets represents Smithy shape com.amazonaws.pipes#Subnets.
type Subnets []Subnet

// Tag represents Smithy shape com.amazonaws.pipes#Tag.
type Tag struct {
	// Required by the AWS service model.
	Key *TagKey `json:"Key,omitempty" smithy:"Key"`
	// Required by the AWS service model.
	Value *TagValue `json:"Value,omitempty" smithy:"Value"`
}

// TagKey represents Smithy shape com.amazonaws.pipes#TagKey.
type TagKey string

// TagKeyList represents Smithy shape com.amazonaws.pipes#TagKeyList.
type TagKeyList []TagKey

// TagList represents Smithy shape com.amazonaws.pipes#TagList.
type TagList []Tag

// TagMap represents Smithy shape com.amazonaws.pipes#TagMap.
type TagMap map[TagKey]TagValue

// TagResourceRequest represents Smithy shape com.amazonaws.pipes#TagResourceRequest.
type TagResourceRequest struct {
	// Required by the AWS service model.
	ResourceArn *PipeArn `json:"resourceArn,omitempty" smithy:"resourceArn"`
	// Required by the AWS service model.
	Tags TagMap `json:"tags,omitzero" smithy:"tags"`
}

// TagResourceResponse represents Smithy shape com.amazonaws.pipes#TagResourceResponse.
type TagResourceResponse struct {
}

// TagValue represents Smithy shape com.amazonaws.pipes#TagValue.
type TagValue string

// ThrottlingException represents Smithy shape com.amazonaws.pipes#ThrottlingException.
type ThrottlingException struct {
	// Required by the AWS service model.
	Message           *String  `json:"message,omitempty" smithy:"message"`
	QuotaCode         *String  `json:"quotaCode,omitempty" smithy:"quotaCode"`
	RetryAfterSeconds *Integer `json:"retryAfterSeconds,omitempty" smithy:"retryAfterSeconds"`
	ServiceCode       *String  `json:"serviceCode,omitempty" smithy:"serviceCode"`
}

// TimeFieldType represents Smithy shape com.amazonaws.pipes#TimeFieldType.
type TimeFieldType string

// TimeValue represents Smithy shape com.amazonaws.pipes#TimeValue.
type TimeValue string

// Timestamp represents Smithy shape com.amazonaws.pipes#Timestamp.
type Timestamp = time.Time

// TimestampFormat represents Smithy shape com.amazonaws.pipes#TimestampFormat.
type TimestampFormat string

// URI represents Smithy shape com.amazonaws.pipes#URI.
type URI string

// UntagResourceRequest represents Smithy shape com.amazonaws.pipes#UntagResourceRequest.
type UntagResourceRequest struct {
	// Required by the AWS service model.
	ResourceArn *PipeArn `json:"resourceArn,omitempty" smithy:"resourceArn"`
	// Required by the AWS service model.
	TagKeys TagKeyList `json:"tagKeys,omitzero" smithy:"tagKeys"`
}

// UntagResourceResponse represents Smithy shape com.amazonaws.pipes#UntagResourceResponse.
type UntagResourceResponse struct {
}

// UpdatePipeRequest represents Smithy shape com.amazonaws.pipes#UpdatePipeRequest.
type UpdatePipeRequest struct {
	Description          *PipeDescription                `json:"Description,omitempty" smithy:"Description"`
	DesiredState         *RequestedPipeState             `json:"DesiredState,omitempty" smithy:"DesiredState"`
	Enrichment           *OptionalArn                    `json:"Enrichment,omitempty" smithy:"Enrichment"`
	EnrichmentParameters *PipeEnrichmentParameters       `json:"EnrichmentParameters,omitempty" smithy:"EnrichmentParameters"`
	KmsKeyIdentifier     *KmsKeyIdentifier               `json:"KmsKeyIdentifier,omitempty" smithy:"KmsKeyIdentifier"`
	LogConfiguration     *PipeLogConfigurationParameters `json:"LogConfiguration,omitempty" smithy:"LogConfiguration"`
	// Required by the AWS service model.
	Name *PipeName `json:"Name,omitempty" smithy:"Name"`
	// Required by the AWS service model.
	RoleArn          *RoleArn                    `json:"RoleArn,omitempty" smithy:"RoleArn"`
	SourceParameters *UpdatePipeSourceParameters `json:"SourceParameters,omitempty" smithy:"SourceParameters"`
	Target           *Arn                        `json:"Target,omitempty" smithy:"Target"`
	TargetParameters *PipeTargetParameters       `json:"TargetParameters,omitempty" smithy:"TargetParameters"`
}

// UpdatePipeResponse represents Smithy shape com.amazonaws.pipes#UpdatePipeResponse.
type UpdatePipeResponse struct {
	Arn              *PipeArn            `json:"Arn,omitempty" smithy:"Arn"`
	CreationTime     *Timestamp          `json:"CreationTime,omitempty" smithy:"CreationTime"`
	CurrentState     *PipeState          `json:"CurrentState,omitempty" smithy:"CurrentState"`
	DesiredState     *RequestedPipeState `json:"DesiredState,omitempty" smithy:"DesiredState"`
	LastModifiedTime *Timestamp          `json:"LastModifiedTime,omitempty" smithy:"LastModifiedTime"`
	Name             *PipeName           `json:"Name,omitempty" smithy:"Name"`
}

// UpdatePipeSourceActiveMQBrokerParameters represents Smithy shape com.amazonaws.pipes#UpdatePipeSourceActiveMQBrokerParameters.
type UpdatePipeSourceActiveMQBrokerParameters struct {
	BatchSize *LimitMax10000 `json:"BatchSize,omitempty" smithy:"BatchSize"`
	// Required by the AWS service model.
	Credentials                    *MQBrokerAccessCredentials      `json:"Credentials,omitempty" smithy:"Credentials"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
}

// UpdatePipeSourceDynamoDBStreamParameters represents Smithy shape com.amazonaws.pipes#UpdatePipeSourceDynamoDBStreamParameters.
type UpdatePipeSourceDynamoDBStreamParameters struct {
	BatchSize                      *LimitMax10000                    `json:"BatchSize,omitempty" smithy:"BatchSize"`
	DeadLetterConfig               *DeadLetterConfig                 `json:"DeadLetterConfig,omitempty" smithy:"DeadLetterConfig"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds   `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
	MaximumRecordAgeInSeconds      *MaximumRecordAgeInSeconds        `json:"MaximumRecordAgeInSeconds,omitempty" smithy:"MaximumRecordAgeInSeconds"`
	MaximumRetryAttempts           *MaximumRetryAttemptsESM          `json:"MaximumRetryAttempts,omitempty" smithy:"MaximumRetryAttempts"`
	OnPartialBatchItemFailure      *OnPartialBatchItemFailureStreams `json:"OnPartialBatchItemFailure,omitempty" smithy:"OnPartialBatchItemFailure"`
	ParallelizationFactor          *LimitMax10                       `json:"ParallelizationFactor,omitempty" smithy:"ParallelizationFactor"`
}

// UpdatePipeSourceKinesisStreamParameters represents Smithy shape com.amazonaws.pipes#UpdatePipeSourceKinesisStreamParameters.
type UpdatePipeSourceKinesisStreamParameters struct {
	BatchSize                      *LimitMax10000                    `json:"BatchSize,omitempty" smithy:"BatchSize"`
	DeadLetterConfig               *DeadLetterConfig                 `json:"DeadLetterConfig,omitempty" smithy:"DeadLetterConfig"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds   `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
	MaximumRecordAgeInSeconds      *MaximumRecordAgeInSeconds        `json:"MaximumRecordAgeInSeconds,omitempty" smithy:"MaximumRecordAgeInSeconds"`
	MaximumRetryAttempts           *MaximumRetryAttemptsESM          `json:"MaximumRetryAttempts,omitempty" smithy:"MaximumRetryAttempts"`
	OnPartialBatchItemFailure      *OnPartialBatchItemFailureStreams `json:"OnPartialBatchItemFailure,omitempty" smithy:"OnPartialBatchItemFailure"`
	ParallelizationFactor          *LimitMax10                       `json:"ParallelizationFactor,omitempty" smithy:"ParallelizationFactor"`
}

// UpdatePipeSourceManagedStreamingKafkaParameters represents Smithy shape com.amazonaws.pipes#UpdatePipeSourceManagedStreamingKafkaParameters.
type UpdatePipeSourceManagedStreamingKafkaParameters struct {
	BatchSize                      *LimitMax10000                  `json:"BatchSize,omitempty" smithy:"BatchSize"`
	Credentials                    *MSKAccessCredentials           `json:"Credentials,omitempty" smithy:"Credentials"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
}

// UpdatePipeSourceParameters represents Smithy shape com.amazonaws.pipes#UpdatePipeSourceParameters.
type UpdatePipeSourceParameters struct {
	ActiveMQBrokerParameters        *UpdatePipeSourceActiveMQBrokerParameters        `json:"ActiveMQBrokerParameters,omitempty" smithy:"ActiveMQBrokerParameters"`
	DynamoDBStreamParameters        *UpdatePipeSourceDynamoDBStreamParameters        `json:"DynamoDBStreamParameters,omitempty" smithy:"DynamoDBStreamParameters"`
	FilterCriteria                  *FilterCriteria                                  `json:"FilterCriteria,omitempty" smithy:"FilterCriteria"`
	KinesisStreamParameters         *UpdatePipeSourceKinesisStreamParameters         `json:"KinesisStreamParameters,omitempty" smithy:"KinesisStreamParameters"`
	ManagedStreamingKafkaParameters *UpdatePipeSourceManagedStreamingKafkaParameters `json:"ManagedStreamingKafkaParameters,omitempty" smithy:"ManagedStreamingKafkaParameters"`
	RabbitMQBrokerParameters        *UpdatePipeSourceRabbitMQBrokerParameters        `json:"RabbitMQBrokerParameters,omitempty" smithy:"RabbitMQBrokerParameters"`
	SelfManagedKafkaParameters      *UpdatePipeSourceSelfManagedKafkaParameters      `json:"SelfManagedKafkaParameters,omitempty" smithy:"SelfManagedKafkaParameters"`
	SqsQueueParameters              *UpdatePipeSourceSqsQueueParameters              `json:"SqsQueueParameters,omitempty" smithy:"SqsQueueParameters"`
}

// UpdatePipeSourceRabbitMQBrokerParameters represents Smithy shape com.amazonaws.pipes#UpdatePipeSourceRabbitMQBrokerParameters.
type UpdatePipeSourceRabbitMQBrokerParameters struct {
	BatchSize *LimitMax10000 `json:"BatchSize,omitempty" smithy:"BatchSize"`
	// Required by the AWS service model.
	Credentials                    *MQBrokerAccessCredentials      `json:"Credentials,omitempty" smithy:"Credentials"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
}

// UpdatePipeSourceSelfManagedKafkaParameters represents Smithy shape com.amazonaws.pipes#UpdatePipeSourceSelfManagedKafkaParameters.
type UpdatePipeSourceSelfManagedKafkaParameters struct {
	BatchSize                      *LimitMax10000                                  `json:"BatchSize,omitempty" smithy:"BatchSize"`
	Credentials                    *SelfManagedKafkaAccessConfigurationCredentials `json:"Credentials,omitempty" smithy:"Credentials"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds                 `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
	ServerRootCaCertificate        *SecretManagerArn                               `json:"ServerRootCaCertificate,omitempty" smithy:"ServerRootCaCertificate"`
	Vpc                            *SelfManagedKafkaAccessConfigurationVpc         `json:"Vpc,omitempty" smithy:"Vpc"`
}

// UpdatePipeSourceSqsQueueParameters represents Smithy shape com.amazonaws.pipes#UpdatePipeSourceSqsQueueParameters.
type UpdatePipeSourceSqsQueueParameters struct {
	BatchSize                      *LimitMax10000                  `json:"BatchSize,omitempty" smithy:"BatchSize"`
	MaximumBatchingWindowInSeconds *MaximumBatchingWindowInSeconds `json:"MaximumBatchingWindowInSeconds,omitempty" smithy:"MaximumBatchingWindowInSeconds"`
}

// ValidationException represents Smithy shape com.amazonaws.pipes#ValidationException.
type ValidationException struct {
	FieldList ValidationExceptionFieldList `json:"fieldList,omitzero" smithy:"fieldList"`
	Message   *ErrorMessage                `json:"message,omitempty" smithy:"message"`
}

// ValidationExceptionField represents Smithy shape com.amazonaws.pipes#ValidationExceptionField.
type ValidationExceptionField struct {
	// Required by the AWS service model.
	Message *ErrorMessage `json:"message,omitempty" smithy:"message"`
	// Required by the AWS service model.
	Name *String `json:"name,omitempty" smithy:"name"`
}

// ValidationExceptionFieldList represents Smithy shape com.amazonaws.pipes#ValidationExceptionFieldList.
type ValidationExceptionFieldList []ValidationExceptionField

// VersionValue represents Smithy shape com.amazonaws.pipes#VersionValue.
type VersionValue string

// Integer represents Smithy shape smithy.api#Integer.
type Integer int32

// Unit represents Smithy shape smithy.api#Unit.
type Unit struct {
}
type CreatePipeInput = CreatePipeRequest
type CreatePipeOutput = CreatePipeResponse
type DeletePipeInput = DeletePipeRequest
type DeletePipeOutput = DeletePipeResponse
type DescribePipeInput = DescribePipeRequest
type DescribePipeOutput = DescribePipeResponse
type ListPipesInput = ListPipesRequest
type ListPipesOutput = ListPipesResponse
type ListTagsForResourceInput = ListTagsForResourceRequest
type ListTagsForResourceOutput = ListTagsForResourceResponse
type StartPipeInput = StartPipeRequest
type StartPipeOutput = StartPipeResponse
type StopPipeInput = StopPipeRequest
type StopPipeOutput = StopPipeResponse
type TagResourceInput = TagResourceRequest
type TagResourceOutput = TagResourceResponse
type UntagResourceInput = UntagResourceRequest
type UntagResourceOutput = UntagResourceResponse
type UpdatePipeInput = UpdatePipeRequest
type UpdatePipeOutput = UpdatePipeResponse
