// Command cfngen derives structural CloudFormation resource contracts from an
// explicitly captured regional AWS registry. Resource commands remain handwritten
// integrations with the real service owners; schemas do not define CRUD effects.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"maps"
	"os"
	"slices"
	"strings"
)

type registry struct {
	Source    string `json:"source"`
	SourceURL string `json:"source_url"`
	Region    string `json:"region"`
	Types     map[string]struct {
		Schema           json.RawMessage `json:"schema"`
		DefaultVersionID string          `json:"default_version_id"`
	} `json:"types"`
}
type schema struct {
	TypeName              string                     `json:"typeName"`
	Properties            map[string]json.RawMessage `json:"properties"`
	Definitions           map[string]json.RawMessage `json:"definitions"`
	Required              []string                   `json:"required"`
	CreateOnly            []string                   `json:"createOnlyProperties"`
	ReadOnly              []string                   `json:"readOnlyProperties"`
	WriteOnly             []string                   `json:"writeOnlyProperties"`
	PrimaryIdentifier     []string                   `json:"primaryIdentifier"`
	AdditionalIdentifiers [][]string                 `json:"additionalIdentifiers"`
	ReplacementStrategy   string                     `json:"replacementStrategy"`
	Tagging               struct {
		Taggable                 bool     `json:"taggable"`
		TagOnCreate              bool     `json:"tagOnCreate"`
		TagUpdatable             bool     `json:"tagUpdatable"`
		CloudFormationSystemTags bool     `json:"cloudFormationSystemTags"`
		TagProperty              string   `json:"tagProperty"`
		Permissions              []string `json:"permissions"`
	} `json:"tagging"`
	Handlers map[string]struct {
		Permissions []string `json:"permissions"`
	} `json:"handlers"`
}

const stringLimits = true

func main() {
	input := flag.String("source", "testdata/aws/cloudformation/resource_schemas_public.json", "pinned regional registry schema source")
	output := flag.String("out", "internal/services/cloudformation/resource_schema_generated.go", "generated contract file")
	check := flag.Bool("check", false, "check committed generated output")
	flag.Parse()
	if err := run(*input, *output, *check); err != nil {
		fmt.Fprintln(os.Stderr, "cfngen:", err)
		os.Exit(1)
	}
}
func run(input, output string, check bool) error {
	data, err := os.ReadFile(input)
	if err != nil {
		return err
	}
	var captured registry
	if err = json.Unmarshal(data, &captured); err != nil {
		return err
	}
	if captured.Region == "" || len(captured.Types) == 0 {
		return fmt.Errorf("captured regional resource schemas are required")
	}
	digest := sha256.Sum256(data)
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cfngen from the AWS CloudFormation registry; DO NOT EDIT.\n// Source: %s; region %s; SHA256 %s\n// Provenance: %s; %s\npackage cloudformation\n\nvar resourceSchemas = map[string]resourceSchema{\n", input, captured.Region, hex.EncodeToString(digest[:]), captured.Source, captured.SourceURL)
	for _, name := range slices.Sorted(maps.Keys(captured.Types)) {
		row := captured.Types[name]
		var s schema
		if err = json.Unmarshal(row.Schema, &s); err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		if s.TypeName != name || len(s.Properties) == 0 {
			return fmt.Errorf("%s: invalid schema identity/properties", name)
		}
		fmt.Fprintf(&b, "%q: {Version:%q, ReplacementStrategy:%q, Properties: []string{", name, row.DefaultVersionID, s.ReplacementStrategy)
		writeStrings(&b, slices.Sorted(maps.Keys(s.Properties)))
		b.WriteString("}, Required: []string{")
		slices.Sort(s.Required)
		writeStrings(&b, s.Required)
		b.WriteString("}, CreateOnly: []string{")
		slices.Sort(s.CreateOnly)
		writeStrings(&b, s.CreateOnly)
		b.WriteString("}, ReadOnly: []string{")
		slices.Sort(s.ReadOnly)
		writeStrings(&b, s.ReadOnly)
		b.WriteString("}, PrimaryIdentifier: []string{")
		writeStrings(&b, s.PrimaryIdentifier)
		b.WriteString("}, AdditionalIdentifiers: [][]string{")
		for _, paths := range s.AdditionalIdentifiers {
			b.WriteString("{")
			writeStrings(&b, paths)
			b.WriteString("},")
		}
		structure, err := structuralSchema(row.Schema, false)
		if err != nil {
			return fmt.Errorf("%s structure: %w", name, err)
		}
		limits, err := structuralSchema(row.Schema, stringLimits)
		if err != nil {
			return fmt.Errorf("%s string limits: %w", name, err)
		}
		templateStructure := ""
		if name == "AWS::CloudFormation::Stack" {
			var nested map[string]any
			if err := json.Unmarshal(row.Schema, &nested); err != nil {
				return err
			}
			// StackName is a provider-root requirement, not a nested-template
			// property. The native child owner generates its retained name.
			nested["required"] = slices.DeleteFunc(slices.Clone(s.Required), func(property string) bool { return property == "StackName" })
			raw, err := json.Marshal(nested)
			if err != nil {
				return err
			}
			templateStructure, err = structuralSchema(raw, false)
			if err != nil {
				return fmt.Errorf("%s nested structure: %w", name, err)
			}
		}
		updateContract, err := updateStructure(row.Schema, s.WriteOnly)
		if err != nil {
			return fmt.Errorf("%s update structure: %w", name, err)
		}
		fmt.Fprintf(&b, "}, StructureJSON:%q, StringLimitsJSON:%q, TemplateStructureJSON:%q, UpdateStructureJSON:%q, Tagging: resourceTaggingSchema{Taggable:%t, TagOnCreate:%t, TagUpdatable:%t, CloudFormationSystemTags:%t, TagProperty:%q, Permissions:[]string{", structure, limits, templateStructure, updateContract, s.Tagging.Taggable, s.Tagging.TagOnCreate, s.Tagging.TagUpdatable, s.Tagging.CloudFormationSystemTags, s.Tagging.TagProperty)
		slices.Sort(s.Tagging.Permissions)
		writeStrings(&b, s.Tagging.Permissions)
		b.WriteString("}}, HandlerPermissions:map[string][]string{")
		for _, handler := range slices.Sorted(maps.Keys(s.Handlers)) {
			fmt.Fprintf(&b, "%q:{", handler)
			permissions := s.Handlers[handler].Permissions
			slices.Sort(permissions)
			writeStrings(&b, permissions)
			b.WriteString("},")
		}
		b.WriteString("}},\n")
	}
	b.WriteString("}\n")
	rendered, err := format.Source([]byte(b.String()))
	if err != nil {
		return err
	}
	if check {
		existing, e := os.ReadFile(output)
		if e != nil {
			return e
		}
		if !bytes.Equal(existing, rendered) {
			return fmt.Errorf("generated resource contracts differ: %s", output)
		}
		return nil
	}
	return os.WriteFile(output, rendered, 0644)
}
func writeStrings(b *strings.Builder, values []string) {
	for _, value := range values {
		fmt.Fprintf(b, "%q,", value)
	}
}
