// Code generated by awsgen from AWS SDK for Go v2 Smithy models; DO NOT EDIT.
package xray

import "time"

// Alias represents Smithy shape com.amazonaws.xray#Alias.
type Alias struct {
	Name  *String    `json:"Name,omitempty" smithy:"Name"`
	Names AliasNames `json:"Names,omitzero" smithy:"Names"`
	Type  *String    `json:"Type,omitempty" smithy:"Type"`
}

// AliasList represents Smithy shape com.amazonaws.xray#AliasList.
type AliasList []Alias

// AliasNames represents Smithy shape com.amazonaws.xray#AliasNames.
type AliasNames []String

// AmazonResourceName represents Smithy shape com.amazonaws.xray#AmazonResourceName.
type AmazonResourceName string

// AnnotationKey represents Smithy shape com.amazonaws.xray#AnnotationKey.
type AnnotationKey string

// AnnotationValue represents Smithy shape com.amazonaws.xray#AnnotationValue.
type AnnotationValue struct {
	BooleanValue *NullableBoolean `json:"BooleanValue,omitempty" smithy:"BooleanValue"`
	NumberValue  *NullableDouble  `json:"NumberValue,omitempty" smithy:"NumberValue"`
	StringValue  *String          `json:"StringValue,omitempty" smithy:"StringValue"`
}

// Annotations represents Smithy shape com.amazonaws.xray#Annotations.
type Annotations map[AnnotationKey]ValuesWithServiceIds

// AnomalousService represents Smithy shape com.amazonaws.xray#AnomalousService.
type AnomalousService struct {
	ServiceId *ServiceId `json:"ServiceId,omitempty" smithy:"ServiceId"`
}

// AnomalousServiceList represents Smithy shape com.amazonaws.xray#AnomalousServiceList.
type AnomalousServiceList []AnomalousService

// AnomalyCount represents Smithy shape com.amazonaws.xray#AnomalyCount.
type AnomalyCount int32

// AttributeKey represents Smithy shape com.amazonaws.xray#AttributeKey.
type AttributeKey string

// AttributeMap represents Smithy shape com.amazonaws.xray#AttributeMap.
type AttributeMap map[AttributeKey]AttributeValue

// AttributeValue represents Smithy shape com.amazonaws.xray#AttributeValue.
type AttributeValue string

// AvailabilityZoneDetail represents Smithy shape com.amazonaws.xray#AvailabilityZoneDetail.
type AvailabilityZoneDetail struct {
	Name *String `json:"Name,omitempty" smithy:"Name"`
}

// BackendConnectionErrors represents Smithy shape com.amazonaws.xray#BackendConnectionErrors.
type BackendConnectionErrors struct {
	ConnectionRefusedCount *NullableInteger `json:"ConnectionRefusedCount,omitempty" smithy:"ConnectionRefusedCount"`
	HTTPCode4XXCount       *NullableInteger `json:"HTTPCode4XXCount,omitempty" smithy:"HTTPCode4XXCount"`
	HTTPCode5XXCount       *NullableInteger `json:"HTTPCode5XXCount,omitempty" smithy:"HTTPCode5XXCount"`
	OtherCount             *NullableInteger `json:"OtherCount,omitempty" smithy:"OtherCount"`
	TimeoutCount           *NullableInteger `json:"TimeoutCount,omitempty" smithy:"TimeoutCount"`
	UnknownHostCount       *NullableInteger `json:"UnknownHostCount,omitempty" smithy:"UnknownHostCount"`
}

// BatchGetTracesRequest represents Smithy shape com.amazonaws.xray#BatchGetTracesRequest.
type BatchGetTracesRequest struct {
	NextToken *String `json:"NextToken,omitempty" smithy:"NextToken"`
	// Required by the AWS service model.
	TraceIds TraceIdList `json:"TraceIds,omitzero" smithy:"TraceIds"`
}

// BatchGetTracesResult represents Smithy shape com.amazonaws.xray#BatchGetTracesResult.
type BatchGetTracesResult struct {
	NextToken           *String                `json:"NextToken,omitempty" smithy:"NextToken"`
	Traces              TraceList              `json:"Traces,omitzero" smithy:"Traces"`
	UnprocessedTraceIds UnprocessedTraceIdList `json:"UnprocessedTraceIds,omitzero" smithy:"UnprocessedTraceIds"`
}

// Boolean represents Smithy shape com.amazonaws.xray#Boolean.
type Boolean bool

// BorrowCount represents Smithy shape com.amazonaws.xray#BorrowCount.
type BorrowCount int32

// CancelTraceRetrievalRequest represents Smithy shape com.amazonaws.xray#CancelTraceRetrievalRequest.
type CancelTraceRetrievalRequest struct {
	// Required by the AWS service model.
	RetrievalToken *RetrievalToken `json:"RetrievalToken,omitempty" smithy:"RetrievalToken"`
}

// CancelTraceRetrievalResult represents Smithy shape com.amazonaws.xray#CancelTraceRetrievalResult.
type CancelTraceRetrievalResult struct {
}

// ClientID represents Smithy shape com.amazonaws.xray#ClientID.
type ClientID string

// CooldownWindowMinutes represents Smithy shape com.amazonaws.xray#CooldownWindowMinutes.
type CooldownWindowMinutes int32

// CreateGroupRequest represents Smithy shape com.amazonaws.xray#CreateGroupRequest.
type CreateGroupRequest struct {
	FilterExpression *FilterExpression `json:"FilterExpression,omitempty" smithy:"FilterExpression"`
	// Required by the AWS service model.
	GroupName             *GroupName             `json:"GroupName,omitempty" smithy:"GroupName"`
	InsightsConfiguration *InsightsConfiguration `json:"InsightsConfiguration,omitempty" smithy:"InsightsConfiguration"`
	Tags                  TagList                `json:"Tags,omitzero" smithy:"Tags"`
}

// CreateGroupResult represents Smithy shape com.amazonaws.xray#CreateGroupResult.
type CreateGroupResult struct {
	Group *Group `json:"Group,omitempty" smithy:"Group"`
}

// CreateSamplingRuleRequest represents Smithy shape com.amazonaws.xray#CreateSamplingRuleRequest.
type CreateSamplingRuleRequest struct {
	// Required by the AWS service model.
	SamplingRule *SamplingRule `json:"SamplingRule,omitempty" smithy:"SamplingRule"`
	Tags         TagList       `json:"Tags,omitzero" smithy:"Tags"`
}

// CreateSamplingRuleResult represents Smithy shape com.amazonaws.xray#CreateSamplingRuleResult.
type CreateSamplingRuleResult struct {
	SamplingRuleRecord *SamplingRuleRecord `json:"SamplingRuleRecord,omitempty" smithy:"SamplingRuleRecord"`
}

// DeleteGroupRequest represents Smithy shape com.amazonaws.xray#DeleteGroupRequest.
type DeleteGroupRequest struct {
	GroupARN  *GroupARN  `json:"GroupARN,omitempty" smithy:"GroupARN"`
	GroupName *GroupName `json:"GroupName,omitempty" smithy:"GroupName"`
}

// DeleteGroupResult represents Smithy shape com.amazonaws.xray#DeleteGroupResult.
type DeleteGroupResult struct {
}

// DeleteResourcePolicyRequest represents Smithy shape com.amazonaws.xray#DeleteResourcePolicyRequest.
type DeleteResourcePolicyRequest struct {
	// Required by the AWS service model.
	PolicyName       *PolicyName       `json:"PolicyName,omitempty" smithy:"PolicyName"`
	PolicyRevisionId *PolicyRevisionId `json:"PolicyRevisionId,omitempty" smithy:"PolicyRevisionId"`
}

// DeleteResourcePolicyResult represents Smithy shape com.amazonaws.xray#DeleteResourcePolicyResult.
type DeleteResourcePolicyResult struct {
}

// DeleteSamplingRuleRequest represents Smithy shape com.amazonaws.xray#DeleteSamplingRuleRequest.
type DeleteSamplingRuleRequest struct {
	RuleARN  *String `json:"RuleARN,omitempty" smithy:"RuleARN"`
	RuleName *String `json:"RuleName,omitempty" smithy:"RuleName"`
}

// DeleteSamplingRuleResult represents Smithy shape com.amazonaws.xray#DeleteSamplingRuleResult.
type DeleteSamplingRuleResult struct {
	SamplingRuleRecord *SamplingRuleRecord `json:"SamplingRuleRecord,omitempty" smithy:"SamplingRuleRecord"`
}

// Double represents Smithy shape com.amazonaws.xray#Double.
type Double float64

// EC2InstanceId represents Smithy shape com.amazonaws.xray#EC2InstanceId.
type EC2InstanceId string

// Edge represents Smithy shape com.amazonaws.xray#Edge.
type Edge struct {
	Aliases                   AliasList        `json:"Aliases,omitzero" smithy:"Aliases"`
	EdgeType                  *String          `json:"EdgeType,omitempty" smithy:"EdgeType"`
	EndTime                   *Timestamp       `json:"EndTime,omitempty" smithy:"EndTime"`
	ReceivedEventAgeHistogram Histogram        `json:"ReceivedEventAgeHistogram,omitzero" smithy:"ReceivedEventAgeHistogram"`
	ReferenceId               *NullableInteger `json:"ReferenceId,omitempty" smithy:"ReferenceId"`
	ResponseTimeHistogram     Histogram        `json:"ResponseTimeHistogram,omitzero" smithy:"ResponseTimeHistogram"`
	StartTime                 *Timestamp       `json:"StartTime,omitempty" smithy:"StartTime"`
	SummaryStatistics         *EdgeStatistics  `json:"SummaryStatistics,omitempty" smithy:"SummaryStatistics"`
}

// EdgeList represents Smithy shape com.amazonaws.xray#EdgeList.
type EdgeList []Edge

// EdgeStatistics represents Smithy shape com.amazonaws.xray#EdgeStatistics.
type EdgeStatistics struct {
	ErrorStatistics   *ErrorStatistics `json:"ErrorStatistics,omitempty" smithy:"ErrorStatistics"`
	FaultStatistics   *FaultStatistics `json:"FaultStatistics,omitempty" smithy:"FaultStatistics"`
	OkCount           *NullableLong    `json:"OkCount,omitempty" smithy:"OkCount"`
	TotalCount        *NullableLong    `json:"TotalCount,omitempty" smithy:"TotalCount"`
	TotalResponseTime *NullableDouble  `json:"TotalResponseTime,omitempty" smithy:"TotalResponseTime"`
}

// EncryptionConfig represents Smithy shape com.amazonaws.xray#EncryptionConfig.
type EncryptionConfig struct {
	KeyId  *String           `json:"KeyId,omitempty" smithy:"KeyId"`
	Status *EncryptionStatus `json:"Status,omitempty" smithy:"Status"`
	Type   *EncryptionType   `json:"Type,omitempty" smithy:"Type"`
}

// EncryptionKeyId represents Smithy shape com.amazonaws.xray#EncryptionKeyId.
type EncryptionKeyId string

// EncryptionStatus represents Smithy shape com.amazonaws.xray#EncryptionStatus.
type EncryptionStatus string

const (
	EncryptionStatusACTIVE   EncryptionStatus = "ACTIVE"
	EncryptionStatusUPDATING EncryptionStatus = "UPDATING"
)

// EncryptionType represents Smithy shape com.amazonaws.xray#EncryptionType.
type EncryptionType string

const (
	EncryptionTypeKMS  EncryptionType = "KMS"
	EncryptionTypeNONE EncryptionType = "NONE"
)

// EntitySelectorExpression represents Smithy shape com.amazonaws.xray#EntitySelectorExpression.
type EntitySelectorExpression string

// ErrorMessage represents Smithy shape com.amazonaws.xray#ErrorMessage.
type ErrorMessage string

// ErrorRootCause represents Smithy shape com.amazonaws.xray#ErrorRootCause.
type ErrorRootCause struct {
	ClientImpacting *NullableBoolean       `json:"ClientImpacting,omitempty" smithy:"ClientImpacting"`
	Services        ErrorRootCauseServices `json:"Services,omitzero" smithy:"Services"`
}

// ErrorRootCauseEntity represents Smithy shape com.amazonaws.xray#ErrorRootCauseEntity.
type ErrorRootCauseEntity struct {
	Exceptions RootCauseExceptions `json:"Exceptions,omitzero" smithy:"Exceptions"`
	Name       *String             `json:"Name,omitempty" smithy:"Name"`
	Remote     *NullableBoolean    `json:"Remote,omitempty" smithy:"Remote"`
}

// ErrorRootCauseEntityPath represents Smithy shape com.amazonaws.xray#ErrorRootCauseEntityPath.
type ErrorRootCauseEntityPath []ErrorRootCauseEntity

// ErrorRootCauseService represents Smithy shape com.amazonaws.xray#ErrorRootCauseService.
type ErrorRootCauseService struct {
	AccountId  *String                  `json:"AccountId,omitempty" smithy:"AccountId"`
	EntityPath ErrorRootCauseEntityPath `json:"EntityPath,omitzero" smithy:"EntityPath"`
	Inferred   *NullableBoolean         `json:"Inferred,omitempty" smithy:"Inferred"`
	Name       *String                  `json:"Name,omitempty" smithy:"Name"`
	Names      ServiceNames             `json:"Names,omitzero" smithy:"Names"`
	Type       *String                  `json:"Type,omitempty" smithy:"Type"`
}

// ErrorRootCauseServices represents Smithy shape com.amazonaws.xray#ErrorRootCauseServices.
type ErrorRootCauseServices []ErrorRootCauseService

// ErrorRootCauses represents Smithy shape com.amazonaws.xray#ErrorRootCauses.
type ErrorRootCauses []ErrorRootCause

// ErrorStatistics represents Smithy shape com.amazonaws.xray#ErrorStatistics.
type ErrorStatistics struct {
	OtherCount    *NullableLong `json:"OtherCount,omitempty" smithy:"OtherCount"`
	ThrottleCount *NullableLong `json:"ThrottleCount,omitempty" smithy:"ThrottleCount"`
	TotalCount    *NullableLong `json:"TotalCount,omitempty" smithy:"TotalCount"`
}

// EventSummaryText represents Smithy shape com.amazonaws.xray#EventSummaryText.
type EventSummaryText string

// FaultRootCause represents Smithy shape com.amazonaws.xray#FaultRootCause.
type FaultRootCause struct {
	ClientImpacting *NullableBoolean       `json:"ClientImpacting,omitempty" smithy:"ClientImpacting"`
	Services        FaultRootCauseServices `json:"Services,omitzero" smithy:"Services"`
}

// FaultRootCauseEntity represents Smithy shape com.amazonaws.xray#FaultRootCauseEntity.
type FaultRootCauseEntity struct {
	Exceptions RootCauseExceptions `json:"Exceptions,omitzero" smithy:"Exceptions"`
	Name       *String             `json:"Name,omitempty" smithy:"Name"`
	Remote     *NullableBoolean    `json:"Remote,omitempty" smithy:"Remote"`
}

// FaultRootCauseEntityPath represents Smithy shape com.amazonaws.xray#FaultRootCauseEntityPath.
type FaultRootCauseEntityPath []FaultRootCauseEntity

// FaultRootCauseService represents Smithy shape com.amazonaws.xray#FaultRootCauseService.
type FaultRootCauseService struct {
	AccountId  *String                  `json:"AccountId,omitempty" smithy:"AccountId"`
	EntityPath FaultRootCauseEntityPath `json:"EntityPath,omitzero" smithy:"EntityPath"`
	Inferred   *NullableBoolean         `json:"Inferred,omitempty" smithy:"Inferred"`
	Name       *String                  `json:"Name,omitempty" smithy:"Name"`
	Names      ServiceNames             `json:"Names,omitzero" smithy:"Names"`
	Type       *String                  `json:"Type,omitempty" smithy:"Type"`
}

// FaultRootCauseServices represents Smithy shape com.amazonaws.xray#FaultRootCauseServices.
type FaultRootCauseServices []FaultRootCauseService

// FaultRootCauses represents Smithy shape com.amazonaws.xray#FaultRootCauses.
type FaultRootCauses []FaultRootCause

// FaultStatistics represents Smithy shape com.amazonaws.xray#FaultStatistics.
type FaultStatistics struct {
	OtherCount *NullableLong `json:"OtherCount,omitempty" smithy:"OtherCount"`
	TotalCount *NullableLong `json:"TotalCount,omitempty" smithy:"TotalCount"`
}

// FilterExpression represents Smithy shape com.amazonaws.xray#FilterExpression.
type FilterExpression string

// FixedRate represents Smithy shape com.amazonaws.xray#FixedRate.
type FixedRate float64

// ForecastStatistics represents Smithy shape com.amazonaws.xray#ForecastStatistics.
type ForecastStatistics struct {
	FaultCountHigh *NullableLong `json:"FaultCountHigh,omitempty" smithy:"FaultCountHigh"`
	FaultCountLow  *NullableLong `json:"FaultCountLow,omitempty" smithy:"FaultCountLow"`
}

// GetEncryptionConfigRequest represents Smithy shape com.amazonaws.xray#GetEncryptionConfigRequest.
type GetEncryptionConfigRequest struct {
}

// GetEncryptionConfigResult represents Smithy shape com.amazonaws.xray#GetEncryptionConfigResult.
type GetEncryptionConfigResult struct {
	EncryptionConfig *EncryptionConfig `json:"EncryptionConfig,omitempty" smithy:"EncryptionConfig"`
}

// GetGroupRequest represents Smithy shape com.amazonaws.xray#GetGroupRequest.
type GetGroupRequest struct {
	GroupARN  *GroupARN  `json:"GroupARN,omitempty" smithy:"GroupARN"`
	GroupName *GroupName `json:"GroupName,omitempty" smithy:"GroupName"`
}

// GetGroupResult represents Smithy shape com.amazonaws.xray#GetGroupResult.
type GetGroupResult struct {
	Group *Group `json:"Group,omitempty" smithy:"Group"`
}

// GetGroupsNextToken represents Smithy shape com.amazonaws.xray#GetGroupsNextToken.
type GetGroupsNextToken string

// GetGroupsRequest represents Smithy shape com.amazonaws.xray#GetGroupsRequest.
type GetGroupsRequest struct {
	NextToken *GetGroupsNextToken `json:"NextToken,omitempty" smithy:"NextToken"`
}

// GetGroupsResult represents Smithy shape com.amazonaws.xray#GetGroupsResult.
type GetGroupsResult struct {
	Groups    GroupSummaryList `json:"Groups,omitzero" smithy:"Groups"`
	NextToken *String          `json:"NextToken,omitempty" smithy:"NextToken"`
}

// GetIndexingRulesRequest represents Smithy shape com.amazonaws.xray#GetIndexingRulesRequest.
type GetIndexingRulesRequest struct {
	NextToken *String `json:"NextToken,omitempty" smithy:"NextToken"`
}

// GetIndexingRulesResult represents Smithy shape com.amazonaws.xray#GetIndexingRulesResult.
type GetIndexingRulesResult struct {
	IndexingRules IndexingRuleList `json:"IndexingRules,omitzero" smithy:"IndexingRules"`
	NextToken     *String          `json:"NextToken,omitempty" smithy:"NextToken"`
}

// GetInsightEventsMaxResults represents Smithy shape com.amazonaws.xray#GetInsightEventsMaxResults.
type GetInsightEventsMaxResults int32

// GetInsightEventsRequest represents Smithy shape com.amazonaws.xray#GetInsightEventsRequest.
type GetInsightEventsRequest struct {
	// Required by the AWS service model.
	InsightId  *InsightId                  `json:"InsightId,omitempty" smithy:"InsightId"`
	MaxResults *GetInsightEventsMaxResults `json:"MaxResults,omitempty" smithy:"MaxResults"`
	NextToken  *Token                      `json:"NextToken,omitempty" smithy:"NextToken"`
}

// GetInsightEventsResult represents Smithy shape com.amazonaws.xray#GetInsightEventsResult.
type GetInsightEventsResult struct {
	InsightEvents InsightEventList `json:"InsightEvents,omitzero" smithy:"InsightEvents"`
	NextToken     *Token           `json:"NextToken,omitempty" smithy:"NextToken"`
}

// GetInsightImpactGraphRequest represents Smithy shape com.amazonaws.xray#GetInsightImpactGraphRequest.
type GetInsightImpactGraphRequest struct {
	// Required by the AWS service model.
	EndTime *Timestamp `json:"EndTime,omitempty" smithy:"EndTime"`
	// Required by the AWS service model.
	InsightId *InsightId `json:"InsightId,omitempty" smithy:"InsightId"`
	NextToken *Token     `json:"NextToken,omitempty" smithy:"NextToken"`
	// Required by the AWS service model.
	StartTime *Timestamp `json:"StartTime,omitempty" smithy:"StartTime"`
}

// GetInsightImpactGraphResult represents Smithy shape com.amazonaws.xray#GetInsightImpactGraphResult.
type GetInsightImpactGraphResult struct {
	EndTime               *Timestamp                    `json:"EndTime,omitempty" smithy:"EndTime"`
	InsightId             *InsightId                    `json:"InsightId,omitempty" smithy:"InsightId"`
	NextToken             *Token                        `json:"NextToken,omitempty" smithy:"NextToken"`
	ServiceGraphEndTime   *Timestamp                    `json:"ServiceGraphEndTime,omitempty" smithy:"ServiceGraphEndTime"`
	ServiceGraphStartTime *Timestamp                    `json:"ServiceGraphStartTime,omitempty" smithy:"ServiceGraphStartTime"`
	Services              InsightImpactGraphServiceList `json:"Services,omitzero" smithy:"Services"`
	StartTime             *Timestamp                    `json:"StartTime,omitempty" smithy:"StartTime"`
}

// GetInsightRequest represents Smithy shape com.amazonaws.xray#GetInsightRequest.
type GetInsightRequest struct {
	// Required by the AWS service model.
	InsightId *InsightId `json:"InsightId,omitempty" smithy:"InsightId"`
}

// GetInsightResult represents Smithy shape com.amazonaws.xray#GetInsightResult.
type GetInsightResult struct {
	Insight *Insight `json:"Insight,omitempty" smithy:"Insight"`
}

// GetInsightSummariesMaxResults represents Smithy shape com.amazonaws.xray#GetInsightSummariesMaxResults.
type GetInsightSummariesMaxResults int32

// GetInsightSummariesRequest represents Smithy shape com.amazonaws.xray#GetInsightSummariesRequest.
type GetInsightSummariesRequest struct {
	// Required by the AWS service model.
	EndTime    *Timestamp                     `json:"EndTime,omitempty" smithy:"EndTime"`
	GroupARN   *GroupARN                      `json:"GroupARN,omitempty" smithy:"GroupARN"`
	GroupName  *GroupName                     `json:"GroupName,omitempty" smithy:"GroupName"`
	MaxResults *GetInsightSummariesMaxResults `json:"MaxResults,omitempty" smithy:"MaxResults"`
	NextToken  *Token                         `json:"NextToken,omitempty" smithy:"NextToken"`
	// Required by the AWS service model.
	StartTime *Timestamp       `json:"StartTime,omitempty" smithy:"StartTime"`
	States    InsightStateList `json:"States,omitzero" smithy:"States"`
}

// GetInsightSummariesResult represents Smithy shape com.amazonaws.xray#GetInsightSummariesResult.
type GetInsightSummariesResult struct {
	InsightSummaries InsightSummaryList `json:"InsightSummaries,omitzero" smithy:"InsightSummaries"`
	NextToken        *Token             `json:"NextToken,omitempty" smithy:"NextToken"`
}

// GetRetrievedTracesGraphRequest represents Smithy shape com.amazonaws.xray#GetRetrievedTracesGraphRequest.
type GetRetrievedTracesGraphRequest struct {
	NextToken *String `json:"NextToken,omitempty" smithy:"NextToken"`
	// Required by the AWS service model.
	RetrievalToken *RetrievalToken `json:"RetrievalToken,omitempty" smithy:"RetrievalToken"`
}

// GetRetrievedTracesGraphResult represents Smithy shape com.amazonaws.xray#GetRetrievedTracesGraphResult.
type GetRetrievedTracesGraphResult struct {
	NextToken       *String               `json:"NextToken,omitempty" smithy:"NextToken"`
	RetrievalStatus *RetrievalStatus      `json:"RetrievalStatus,omitempty" smithy:"RetrievalStatus"`
	Services        RetrievedServicesList `json:"Services,omitzero" smithy:"Services"`
}

// GetSamplingRulesRequest represents Smithy shape com.amazonaws.xray#GetSamplingRulesRequest.
type GetSamplingRulesRequest struct {
	NextToken *String `json:"NextToken,omitempty" smithy:"NextToken"`
}

// GetSamplingRulesResult represents Smithy shape com.amazonaws.xray#GetSamplingRulesResult.
type GetSamplingRulesResult struct {
	NextToken           *String                `json:"NextToken,omitempty" smithy:"NextToken"`
	SamplingRuleRecords SamplingRuleRecordList `json:"SamplingRuleRecords,omitzero" smithy:"SamplingRuleRecords"`
}

// GetSamplingStatisticSummariesRequest represents Smithy shape com.amazonaws.xray#GetSamplingStatisticSummariesRequest.
type GetSamplingStatisticSummariesRequest struct {
	NextToken *String `json:"NextToken,omitempty" smithy:"NextToken"`
}

// GetSamplingStatisticSummariesResult represents Smithy shape com.amazonaws.xray#GetSamplingStatisticSummariesResult.
type GetSamplingStatisticSummariesResult struct {
	NextToken                  *String                      `json:"NextToken,omitempty" smithy:"NextToken"`
	SamplingStatisticSummaries SamplingStatisticSummaryList `json:"SamplingStatisticSummaries,omitzero" smithy:"SamplingStatisticSummaries"`
}

// GetSamplingTargetsRequest represents Smithy shape com.amazonaws.xray#GetSamplingTargetsRequest.
type GetSamplingTargetsRequest struct {
	SamplingBoostStatisticsDocuments SamplingBoostStatisticsDocumentList `json:"SamplingBoostStatisticsDocuments,omitzero" smithy:"SamplingBoostStatisticsDocuments"`
	// Required by the AWS service model.
	SamplingStatisticsDocuments SamplingStatisticsDocumentList `json:"SamplingStatisticsDocuments,omitzero" smithy:"SamplingStatisticsDocuments"`
}

// GetSamplingTargetsResult represents Smithy shape com.amazonaws.xray#GetSamplingTargetsResult.
type GetSamplingTargetsResult struct {
	LastRuleModification       *Timestamp                 `json:"LastRuleModification,omitempty" smithy:"LastRuleModification"`
	SamplingTargetDocuments    SamplingTargetDocumentList `json:"SamplingTargetDocuments,omitzero" smithy:"SamplingTargetDocuments"`
	UnprocessedBoostStatistics UnprocessedStatisticsList  `json:"UnprocessedBoostStatistics,omitzero" smithy:"UnprocessedBoostStatistics"`
	UnprocessedStatistics      UnprocessedStatisticsList  `json:"UnprocessedStatistics,omitzero" smithy:"UnprocessedStatistics"`
}

// GetServiceGraphRequest represents Smithy shape com.amazonaws.xray#GetServiceGraphRequest.
type GetServiceGraphRequest struct {
	// Required by the AWS service model.
	EndTime   *Timestamp `json:"EndTime,omitempty" smithy:"EndTime"`
	GroupARN  *GroupARN  `json:"GroupARN,omitempty" smithy:"GroupARN"`
	GroupName *GroupName `json:"GroupName,omitempty" smithy:"GroupName"`
	NextToken *String    `json:"NextToken,omitempty" smithy:"NextToken"`
	// Required by the AWS service model.
	StartTime *Timestamp `json:"StartTime,omitempty" smithy:"StartTime"`
}

// GetServiceGraphResult represents Smithy shape com.amazonaws.xray#GetServiceGraphResult.
type GetServiceGraphResult struct {
	ContainsOldGroupVersions *Boolean    `json:"ContainsOldGroupVersions,omitempty" smithy:"ContainsOldGroupVersions"`
	EndTime                  *Timestamp  `json:"EndTime,omitempty" smithy:"EndTime"`
	NextToken                *String     `json:"NextToken,omitempty" smithy:"NextToken"`
	Services                 ServiceList `json:"Services,omitzero" smithy:"Services"`
	StartTime                *Timestamp  `json:"StartTime,omitempty" smithy:"StartTime"`
}

// GetTimeSeriesServiceStatisticsRequest represents Smithy shape com.amazonaws.xray#GetTimeSeriesServiceStatisticsRequest.
type GetTimeSeriesServiceStatisticsRequest struct {
	// Required by the AWS service model.
	EndTime                  *Timestamp                `json:"EndTime,omitempty" smithy:"EndTime"`
	EntitySelectorExpression *EntitySelectorExpression `json:"EntitySelectorExpression,omitempty" smithy:"EntitySelectorExpression"`
	ForecastStatistics       *NullableBoolean          `json:"ForecastStatistics,omitempty" smithy:"ForecastStatistics"`
	GroupARN                 *GroupARN                 `json:"GroupARN,omitempty" smithy:"GroupARN"`
	GroupName                *GroupName                `json:"GroupName,omitempty" smithy:"GroupName"`
	NextToken                *String                   `json:"NextToken,omitempty" smithy:"NextToken"`
	Period                   *NullableInteger          `json:"Period,omitempty" smithy:"Period"`
	// Required by the AWS service model.
	StartTime *Timestamp `json:"StartTime,omitempty" smithy:"StartTime"`
}

// GetTimeSeriesServiceStatisticsResult represents Smithy shape com.amazonaws.xray#GetTimeSeriesServiceStatisticsResult.
type GetTimeSeriesServiceStatisticsResult struct {
	ContainsOldGroupVersions    *Boolean                        `json:"ContainsOldGroupVersions,omitempty" smithy:"ContainsOldGroupVersions"`
	NextToken                   *String                         `json:"NextToken,omitempty" smithy:"NextToken"`
	TimeSeriesServiceStatistics TimeSeriesServiceStatisticsList `json:"TimeSeriesServiceStatistics,omitzero" smithy:"TimeSeriesServiceStatistics"`
}

// GetTraceGraphRequest represents Smithy shape com.amazonaws.xray#GetTraceGraphRequest.
type GetTraceGraphRequest struct {
	NextToken *String `json:"NextToken,omitempty" smithy:"NextToken"`
	// Required by the AWS service model.
	TraceIds TraceIdList `json:"TraceIds,omitzero" smithy:"TraceIds"`
}

// GetTraceGraphResult represents Smithy shape com.amazonaws.xray#GetTraceGraphResult.
type GetTraceGraphResult struct {
	NextToken *String     `json:"NextToken,omitempty" smithy:"NextToken"`
	Services  ServiceList `json:"Services,omitzero" smithy:"Services"`
}

// GetTraceSegmentDestinationRequest represents Smithy shape com.amazonaws.xray#GetTraceSegmentDestinationRequest.
type GetTraceSegmentDestinationRequest struct {
}

// GetTraceSegmentDestinationResult represents Smithy shape com.amazonaws.xray#GetTraceSegmentDestinationResult.
type GetTraceSegmentDestinationResult struct {
	Destination *TraceSegmentDestination       `json:"Destination,omitempty" smithy:"Destination"`
	Status      *TraceSegmentDestinationStatus `json:"Status,omitempty" smithy:"Status"`
}

// GetTraceSummariesRequest represents Smithy shape com.amazonaws.xray#GetTraceSummariesRequest.
type GetTraceSummariesRequest struct {
	// Required by the AWS service model.
	EndTime          *Timestamp        `json:"EndTime,omitempty" smithy:"EndTime"`
	FilterExpression *FilterExpression `json:"FilterExpression,omitempty" smithy:"FilterExpression"`
	NextToken        *String           `json:"NextToken,omitempty" smithy:"NextToken"`
	Sampling         *NullableBoolean  `json:"Sampling,omitempty" smithy:"Sampling"`
	SamplingStrategy *SamplingStrategy `json:"SamplingStrategy,omitempty" smithy:"SamplingStrategy"`
	// Required by the AWS service model.
	StartTime     *Timestamp     `json:"StartTime,omitempty" smithy:"StartTime"`
	TimeRangeType *TimeRangeType `json:"TimeRangeType,omitempty" smithy:"TimeRangeType"`
}

// GetTraceSummariesResult represents Smithy shape com.amazonaws.xray#GetTraceSummariesResult.
type GetTraceSummariesResult struct {
	ApproximateTime      *Timestamp       `json:"ApproximateTime,omitempty" smithy:"ApproximateTime"`
	NextToken            *String          `json:"NextToken,omitempty" smithy:"NextToken"`
	TraceSummaries       TraceSummaryList `json:"TraceSummaries,omitzero" smithy:"TraceSummaries"`
	TracesProcessedCount *NullableLong    `json:"TracesProcessedCount,omitempty" smithy:"TracesProcessedCount"`
}

// GraphLink represents Smithy shape com.amazonaws.xray#GraphLink.
type GraphLink struct {
	DestinationTraceIds TraceIdList `json:"DestinationTraceIds,omitzero" smithy:"DestinationTraceIds"`
	ReferenceType       *String     `json:"ReferenceType,omitempty" smithy:"ReferenceType"`
	SourceTraceId       *String     `json:"SourceTraceId,omitempty" smithy:"SourceTraceId"`
}

// Group represents Smithy shape com.amazonaws.xray#Group.
type Group struct {
	FilterExpression      *String                `json:"FilterExpression,omitempty" smithy:"FilterExpression"`
	GroupARN              *String                `json:"GroupARN,omitempty" smithy:"GroupARN"`
	GroupName             *String                `json:"GroupName,omitempty" smithy:"GroupName"`
	InsightsConfiguration *InsightsConfiguration `json:"InsightsConfiguration,omitempty" smithy:"InsightsConfiguration"`
}

// GroupARN represents Smithy shape com.amazonaws.xray#GroupARN.
type GroupARN string

// GroupName represents Smithy shape com.amazonaws.xray#GroupName.
type GroupName string

// GroupSummary represents Smithy shape com.amazonaws.xray#GroupSummary.
type GroupSummary struct {
	FilterExpression      *String                `json:"FilterExpression,omitempty" smithy:"FilterExpression"`
	GroupARN              *String                `json:"GroupARN,omitempty" smithy:"GroupARN"`
	GroupName             *String                `json:"GroupName,omitempty" smithy:"GroupName"`
	InsightsConfiguration *InsightsConfiguration `json:"InsightsConfiguration,omitempty" smithy:"InsightsConfiguration"`
}

// GroupSummaryList represents Smithy shape com.amazonaws.xray#GroupSummaryList.
type GroupSummaryList []GroupSummary

// HTTPMethod represents Smithy shape com.amazonaws.xray#HTTPMethod.
type HTTPMethod string

// Histogram represents Smithy shape com.amazonaws.xray#Histogram.
type Histogram []HistogramEntry

// HistogramEntry represents Smithy shape com.amazonaws.xray#HistogramEntry.
type HistogramEntry struct {
	Count *Integer `json:"Count,omitempty" smithy:"Count"`
	Value *Double  `json:"Value,omitempty" smithy:"Value"`
}

// Host represents Smithy shape com.amazonaws.xray#Host.
type Host string

// Hostname represents Smithy shape com.amazonaws.xray#Hostname.
type Hostname string

// Http represents Smithy shape com.amazonaws.xray#Http.
type Http struct {
	ClientIp   *String          `json:"ClientIp,omitempty" smithy:"ClientIp"`
	HttpMethod *String          `json:"HttpMethod,omitempty" smithy:"HttpMethod"`
	HttpStatus *NullableInteger `json:"HttpStatus,omitempty" smithy:"HttpStatus"`
	HttpURL    *String          `json:"HttpURL,omitempty" smithy:"HttpURL"`
	UserAgent  *String          `json:"UserAgent,omitempty" smithy:"UserAgent"`
}

// IndexingRule represents Smithy shape com.amazonaws.xray#IndexingRule.
type IndexingRule struct {
	ModifiedAt *Timestamp         `json:"ModifiedAt,omitempty" smithy:"ModifiedAt"`
	Name       *RuleName          `json:"Name,omitempty" smithy:"Name"`
	Rule       *IndexingRuleValue `json:"Rule,omitempty" smithy:"Rule"`
}

// IndexingRuleList represents Smithy shape com.amazonaws.xray#IndexingRuleList.
type IndexingRuleList []IndexingRule

// IndexingRuleValue represents Smithy shape com.amazonaws.xray#IndexingRuleValue.
type IndexingRuleValue struct {
	Probabilistic *ProbabilisticRuleValue `json:"Probabilistic,omitempty" smithy:"Probabilistic"`
}

// IndexingRuleValueUpdate represents Smithy shape com.amazonaws.xray#IndexingRuleValueUpdate.
type IndexingRuleValueUpdate struct {
	Probabilistic *ProbabilisticRuleValueUpdate `json:"Probabilistic,omitempty" smithy:"Probabilistic"`
}

// Insight represents Smithy shape com.amazonaws.xray#Insight.
type Insight struct {
	Categories                              InsightCategoryList      `json:"Categories,omitzero" smithy:"Categories"`
	ClientRequestImpactStatistics           *RequestImpactStatistics `json:"ClientRequestImpactStatistics,omitempty" smithy:"ClientRequestImpactStatistics"`
	EndTime                                 *Timestamp               `json:"EndTime,omitempty" smithy:"EndTime"`
	GroupARN                                *GroupARN                `json:"GroupARN,omitempty" smithy:"GroupARN"`
	GroupName                               *GroupName               `json:"GroupName,omitempty" smithy:"GroupName"`
	InsightId                               *InsightId               `json:"InsightId,omitempty" smithy:"InsightId"`
	RootCauseServiceId                      *ServiceId               `json:"RootCauseServiceId,omitempty" smithy:"RootCauseServiceId"`
	RootCauseServiceRequestImpactStatistics *RequestImpactStatistics `json:"RootCauseServiceRequestImpactStatistics,omitempty" smithy:"RootCauseServiceRequestImpactStatistics"`
	StartTime                               *Timestamp               `json:"StartTime,omitempty" smithy:"StartTime"`
	State                                   *InsightState            `json:"State,omitempty" smithy:"State"`
	Summary                                 *InsightSummaryText      `json:"Summary,omitempty" smithy:"Summary"`
	TopAnomalousServices                    AnomalousServiceList     `json:"TopAnomalousServices,omitzero" smithy:"TopAnomalousServices"`
}

// InsightCategory represents Smithy shape com.amazonaws.xray#InsightCategory.
type InsightCategory string

const (
	InsightCategoryFAULT InsightCategory = "FAULT"
)

// InsightCategoryList represents Smithy shape com.amazonaws.xray#InsightCategoryList.
type InsightCategoryList []InsightCategory

// InsightEvent represents Smithy shape com.amazonaws.xray#InsightEvent.
type InsightEvent struct {
	ClientRequestImpactStatistics           *RequestImpactStatistics `json:"ClientRequestImpactStatistics,omitempty" smithy:"ClientRequestImpactStatistics"`
	EventTime                               *Timestamp               `json:"EventTime,omitempty" smithy:"EventTime"`
	RootCauseServiceRequestImpactStatistics *RequestImpactStatistics `json:"RootCauseServiceRequestImpactStatistics,omitempty" smithy:"RootCauseServiceRequestImpactStatistics"`
	Summary                                 *EventSummaryText        `json:"Summary,omitempty" smithy:"Summary"`
	TopAnomalousServices                    AnomalousServiceList     `json:"TopAnomalousServices,omitzero" smithy:"TopAnomalousServices"`
}

// InsightEventList represents Smithy shape com.amazonaws.xray#InsightEventList.
type InsightEventList []InsightEvent

// InsightId represents Smithy shape com.amazonaws.xray#InsightId.
type InsightId string

// InsightImpactGraphEdge represents Smithy shape com.amazonaws.xray#InsightImpactGraphEdge.
type InsightImpactGraphEdge struct {
	ReferenceId *NullableInteger `json:"ReferenceId,omitempty" smithy:"ReferenceId"`
}

// InsightImpactGraphEdgeList represents Smithy shape com.amazonaws.xray#InsightImpactGraphEdgeList.
type InsightImpactGraphEdgeList []InsightImpactGraphEdge

// InsightImpactGraphService represents Smithy shape com.amazonaws.xray#InsightImpactGraphService.
type InsightImpactGraphService struct {
	AccountId   *String                    `json:"AccountId,omitempty" smithy:"AccountId"`
	Edges       InsightImpactGraphEdgeList `json:"Edges,omitzero" smithy:"Edges"`
	Name        *String                    `json:"Name,omitempty" smithy:"Name"`
	Names       ServiceNames               `json:"Names,omitzero" smithy:"Names"`
	ReferenceId *NullableInteger           `json:"ReferenceId,omitempty" smithy:"ReferenceId"`
	Type        *String                    `json:"Type,omitempty" smithy:"Type"`
}

// InsightImpactGraphServiceList represents Smithy shape com.amazonaws.xray#InsightImpactGraphServiceList.
type InsightImpactGraphServiceList []InsightImpactGraphService

// InsightState represents Smithy shape com.amazonaws.xray#InsightState.
type InsightState string

const (
	InsightStateACTIVE InsightState = "ACTIVE"
	InsightStateCLOSED InsightState = "CLOSED"
)

// InsightStateList represents Smithy shape com.amazonaws.xray#InsightStateList.
type InsightStateList []InsightState

// InsightSummary represents Smithy shape com.amazonaws.xray#InsightSummary.
type InsightSummary struct {
	Categories                              InsightCategoryList      `json:"Categories,omitzero" smithy:"Categories"`
	ClientRequestImpactStatistics           *RequestImpactStatistics `json:"ClientRequestImpactStatistics,omitempty" smithy:"ClientRequestImpactStatistics"`
	EndTime                                 *Timestamp               `json:"EndTime,omitempty" smithy:"EndTime"`
	GroupARN                                *GroupARN                `json:"GroupARN,omitempty" smithy:"GroupARN"`
	GroupName                               *GroupName               `json:"GroupName,omitempty" smithy:"GroupName"`
	InsightId                               *InsightId               `json:"InsightId,omitempty" smithy:"InsightId"`
	LastUpdateTime                          *Timestamp               `json:"LastUpdateTime,omitempty" smithy:"LastUpdateTime"`
	RootCauseServiceId                      *ServiceId               `json:"RootCauseServiceId,omitempty" smithy:"RootCauseServiceId"`
	RootCauseServiceRequestImpactStatistics *RequestImpactStatistics `json:"RootCauseServiceRequestImpactStatistics,omitempty" smithy:"RootCauseServiceRequestImpactStatistics"`
	StartTime                               *Timestamp               `json:"StartTime,omitempty" smithy:"StartTime"`
	State                                   *InsightState            `json:"State,omitempty" smithy:"State"`
	Summary                                 *InsightSummaryText      `json:"Summary,omitempty" smithy:"Summary"`
	TopAnomalousServices                    AnomalousServiceList     `json:"TopAnomalousServices,omitzero" smithy:"TopAnomalousServices"`
}

// InsightSummaryList represents Smithy shape com.amazonaws.xray#InsightSummaryList.
type InsightSummaryList []InsightSummary

// InsightSummaryText represents Smithy shape com.amazonaws.xray#InsightSummaryText.
type InsightSummaryText string

// InsightsConfiguration represents Smithy shape com.amazonaws.xray#InsightsConfiguration.
type InsightsConfiguration struct {
	InsightsEnabled      *NullableBoolean `json:"InsightsEnabled,omitempty" smithy:"InsightsEnabled"`
	NotificationsEnabled *NullableBoolean `json:"NotificationsEnabled,omitempty" smithy:"NotificationsEnabled"`
}

// InstanceIdDetail represents Smithy shape com.amazonaws.xray#InstanceIdDetail.
type InstanceIdDetail struct {
	Id *String `json:"Id,omitempty" smithy:"Id"`
}

// Integer represents Smithy shape com.amazonaws.xray#Integer.
type Integer int32

// InvalidPolicyRevisionIdException represents Smithy shape com.amazonaws.xray#InvalidPolicyRevisionIdException.
type InvalidPolicyRevisionIdException struct {
	Message *ErrorMessage `json:"Message,omitempty" smithy:"Message"`
}

// InvalidRequestException represents Smithy shape com.amazonaws.xray#InvalidRequestException.
type InvalidRequestException struct {
	Message *ErrorMessage `json:"Message,omitempty" smithy:"Message"`
}

// LinksList represents Smithy shape com.amazonaws.xray#LinksList.
type LinksList []GraphLink

// ListResourcePoliciesRequest represents Smithy shape com.amazonaws.xray#ListResourcePoliciesRequest.
type ListResourcePoliciesRequest struct {
	NextToken *ResourcePolicyNextToken `json:"NextToken,omitempty" smithy:"NextToken"`
}

// ListResourcePoliciesResult represents Smithy shape com.amazonaws.xray#ListResourcePoliciesResult.
type ListResourcePoliciesResult struct {
	NextToken        *ResourcePolicyNextToken `json:"NextToken,omitempty" smithy:"NextToken"`
	ResourcePolicies ResourcePolicyList       `json:"ResourcePolicies,omitzero" smithy:"ResourcePolicies"`
}

// ListRetrievedTracesRequest represents Smithy shape com.amazonaws.xray#ListRetrievedTracesRequest.
type ListRetrievedTracesRequest struct {
	NextToken *String `json:"NextToken,omitempty" smithy:"NextToken"`
	// Required by the AWS service model.
	RetrievalToken *RetrievalToken  `json:"RetrievalToken,omitempty" smithy:"RetrievalToken"`
	TraceFormat    *TraceFormatType `json:"TraceFormat,omitempty" smithy:"TraceFormat"`
}

// ListRetrievedTracesResult represents Smithy shape com.amazonaws.xray#ListRetrievedTracesResult.
type ListRetrievedTracesResult struct {
	NextToken       *String          `json:"NextToken,omitempty" smithy:"NextToken"`
	RetrievalStatus *RetrievalStatus `json:"RetrievalStatus,omitempty" smithy:"RetrievalStatus"`
	TraceFormat     *TraceFormatType `json:"TraceFormat,omitempty" smithy:"TraceFormat"`
	Traces          TraceSpanList    `json:"Traces,omitzero" smithy:"Traces"`
}

// ListTagsForResourceRequest represents Smithy shape com.amazonaws.xray#ListTagsForResourceRequest.
type ListTagsForResourceRequest struct {
	NextToken *String `json:"NextToken,omitempty" smithy:"NextToken"`
	// Required by the AWS service model.
	ResourceARN *AmazonResourceName `json:"ResourceARN,omitempty" smithy:"ResourceARN"`
}

// ListTagsForResourceResponse represents Smithy shape com.amazonaws.xray#ListTagsForResourceResponse.
type ListTagsForResourceResponse struct {
	NextToken *String `json:"NextToken,omitempty" smithy:"NextToken"`
	Tags      TagList `json:"Tags,omitzero" smithy:"Tags"`
}

// LockoutPreventionException represents Smithy shape com.amazonaws.xray#LockoutPreventionException.
type LockoutPreventionException struct {
	Message *ErrorMessage `json:"Message,omitempty" smithy:"Message"`
}

// MalformedPolicyDocumentException represents Smithy shape com.amazonaws.xray#MalformedPolicyDocumentException.
type MalformedPolicyDocumentException struct {
	Message *ErrorMessage `json:"Message,omitempty" smithy:"Message"`
}

// MaxRate represents Smithy shape com.amazonaws.xray#MaxRate.
type MaxRate float64

// NullableBoolean represents Smithy shape com.amazonaws.xray#NullableBoolean.
type NullableBoolean bool

// NullableDouble represents Smithy shape com.amazonaws.xray#NullableDouble.
type NullableDouble float64

// NullableInteger represents Smithy shape com.amazonaws.xray#NullableInteger.
type NullableInteger int32

// NullableLong represents Smithy shape com.amazonaws.xray#NullableLong.
type NullableLong int64

// PolicyCountLimitExceededException represents Smithy shape com.amazonaws.xray#PolicyCountLimitExceededException.
type PolicyCountLimitExceededException struct {
	Message *ErrorMessage `json:"Message,omitempty" smithy:"Message"`
}

// PolicyDocument represents Smithy shape com.amazonaws.xray#PolicyDocument.
type PolicyDocument string

// PolicyName represents Smithy shape com.amazonaws.xray#PolicyName.
type PolicyName string

// PolicyRevisionId represents Smithy shape com.amazonaws.xray#PolicyRevisionId.
type PolicyRevisionId string

// PolicySizeLimitExceededException represents Smithy shape com.amazonaws.xray#PolicySizeLimitExceededException.
type PolicySizeLimitExceededException struct {
	Message *ErrorMessage `json:"Message,omitempty" smithy:"Message"`
}

// Priority represents Smithy shape com.amazonaws.xray#Priority.
type Priority int32

// ProbabilisticRuleValue represents Smithy shape com.amazonaws.xray#ProbabilisticRuleValue.
type ProbabilisticRuleValue struct {
	ActualSamplingPercentage *NullableDouble `json:"ActualSamplingPercentage,omitempty" smithy:"ActualSamplingPercentage"`
	// Required by the AWS service model.
	DesiredSamplingPercentage *NullableDouble `json:"DesiredSamplingPercentage,omitempty" smithy:"DesiredSamplingPercentage"`
}

// ProbabilisticRuleValueUpdate represents Smithy shape com.amazonaws.xray#ProbabilisticRuleValueUpdate.
type ProbabilisticRuleValueUpdate struct {
	// Required by the AWS service model.
	DesiredSamplingPercentage *NullableDouble `json:"DesiredSamplingPercentage,omitempty" smithy:"DesiredSamplingPercentage"`
}

// PutEncryptionConfigRequest represents Smithy shape com.amazonaws.xray#PutEncryptionConfigRequest.
type PutEncryptionConfigRequest struct {
	KeyId *EncryptionKeyId `json:"KeyId,omitempty" smithy:"KeyId"`
	// Required by the AWS service model.
	Type *EncryptionType `json:"Type,omitempty" smithy:"Type"`
}

// PutEncryptionConfigResult represents Smithy shape com.amazonaws.xray#PutEncryptionConfigResult.
type PutEncryptionConfigResult struct {
	EncryptionConfig *EncryptionConfig `json:"EncryptionConfig,omitempty" smithy:"EncryptionConfig"`
}

// PutResourcePolicyRequest represents Smithy shape com.amazonaws.xray#PutResourcePolicyRequest.
type PutResourcePolicyRequest struct {
	BypassPolicyLockoutCheck *Boolean `json:"BypassPolicyLockoutCheck,omitempty" smithy:"BypassPolicyLockoutCheck"`
	// Required by the AWS service model.
	PolicyDocument *PolicyDocument `json:"PolicyDocument,omitempty" smithy:"PolicyDocument"`
	// Required by the AWS service model.
	PolicyName       *PolicyName       `json:"PolicyName,omitempty" smithy:"PolicyName"`
	PolicyRevisionId *PolicyRevisionId `json:"PolicyRevisionId,omitempty" smithy:"PolicyRevisionId"`
}

// PutResourcePolicyResult represents Smithy shape com.amazonaws.xray#PutResourcePolicyResult.
type PutResourcePolicyResult struct {
	ResourcePolicy *ResourcePolicy `json:"ResourcePolicy,omitempty" smithy:"ResourcePolicy"`
}

// PutTelemetryRecordsRequest represents Smithy shape com.amazonaws.xray#PutTelemetryRecordsRequest.
type PutTelemetryRecordsRequest struct {
	EC2InstanceId *EC2InstanceId `json:"EC2InstanceId,omitempty" smithy:"EC2InstanceId"`
	Hostname      *Hostname      `json:"Hostname,omitempty" smithy:"Hostname"`
	ResourceARN   *ResourceARN   `json:"ResourceARN,omitempty" smithy:"ResourceARN"`
	// Required by the AWS service model.
	TelemetryRecords TelemetryRecordList `json:"TelemetryRecords,omitzero" smithy:"TelemetryRecords"`
}

// PutTelemetryRecordsResult represents Smithy shape com.amazonaws.xray#PutTelemetryRecordsResult.
type PutTelemetryRecordsResult struct {
}

// PutTraceSegmentsRequest represents Smithy shape com.amazonaws.xray#PutTraceSegmentsRequest.
type PutTraceSegmentsRequest struct {
	// Required by the AWS service model.
	TraceSegmentDocuments TraceSegmentDocumentList `json:"TraceSegmentDocuments,omitzero" smithy:"TraceSegmentDocuments"`
}

// PutTraceSegmentsResult represents Smithy shape com.amazonaws.xray#PutTraceSegmentsResult.
type PutTraceSegmentsResult struct {
	UnprocessedTraceSegments UnprocessedTraceSegmentList `json:"UnprocessedTraceSegments,omitzero" smithy:"UnprocessedTraceSegments"`
}

// RequestCount represents Smithy shape com.amazonaws.xray#RequestCount.
type RequestCount int32

// RequestImpactStatistics represents Smithy shape com.amazonaws.xray#RequestImpactStatistics.
type RequestImpactStatistics struct {
	FaultCount *NullableLong `json:"FaultCount,omitempty" smithy:"FaultCount"`
	OkCount    *NullableLong `json:"OkCount,omitempty" smithy:"OkCount"`
	TotalCount *NullableLong `json:"TotalCount,omitempty" smithy:"TotalCount"`
}

// ReservoirSize represents Smithy shape com.amazonaws.xray#ReservoirSize.
type ReservoirSize int32

// ResourceARN represents Smithy shape com.amazonaws.xray#ResourceARN.
type ResourceARN string

// ResourceARNDetail represents Smithy shape com.amazonaws.xray#ResourceARNDetail.
type ResourceARNDetail struct {
	ARN *String `json:"ARN,omitempty" smithy:"ARN"`
}

// ResourceNotFoundException represents Smithy shape com.amazonaws.xray#ResourceNotFoundException.
type ResourceNotFoundException struct {
	Message      *ErrorMessage       `json:"Message,omitempty" smithy:"Message"`
	ResourceName *AmazonResourceName `json:"ResourceName,omitempty" smithy:"ResourceName"`
}

// ResourcePolicy represents Smithy shape com.amazonaws.xray#ResourcePolicy.
type ResourcePolicy struct {
	LastUpdatedTime  *Timestamp        `json:"LastUpdatedTime,omitempty" smithy:"LastUpdatedTime"`
	PolicyDocument   *PolicyDocument   `json:"PolicyDocument,omitempty" smithy:"PolicyDocument"`
	PolicyName       *PolicyName       `json:"PolicyName,omitempty" smithy:"PolicyName"`
	PolicyRevisionId *PolicyRevisionId `json:"PolicyRevisionId,omitempty" smithy:"PolicyRevisionId"`
}

// ResourcePolicyList represents Smithy shape com.amazonaws.xray#ResourcePolicyList.
type ResourcePolicyList []ResourcePolicy

// ResourcePolicyNextToken represents Smithy shape com.amazonaws.xray#ResourcePolicyNextToken.
type ResourcePolicyNextToken string

// ResponseTimeRootCause represents Smithy shape com.amazonaws.xray#ResponseTimeRootCause.
type ResponseTimeRootCause struct {
	ClientImpacting *NullableBoolean              `json:"ClientImpacting,omitempty" smithy:"ClientImpacting"`
	Services        ResponseTimeRootCauseServices `json:"Services,omitzero" smithy:"Services"`
}

// ResponseTimeRootCauseEntity represents Smithy shape com.amazonaws.xray#ResponseTimeRootCauseEntity.
type ResponseTimeRootCauseEntity struct {
	Coverage *NullableDouble  `json:"Coverage,omitempty" smithy:"Coverage"`
	Name     *String          `json:"Name,omitempty" smithy:"Name"`
	Remote   *NullableBoolean `json:"Remote,omitempty" smithy:"Remote"`
}

// ResponseTimeRootCauseEntityPath represents Smithy shape com.amazonaws.xray#ResponseTimeRootCauseEntityPath.
type ResponseTimeRootCauseEntityPath []ResponseTimeRootCauseEntity

// ResponseTimeRootCauseService represents Smithy shape com.amazonaws.xray#ResponseTimeRootCauseService.
type ResponseTimeRootCauseService struct {
	AccountId  *String                         `json:"AccountId,omitempty" smithy:"AccountId"`
	EntityPath ResponseTimeRootCauseEntityPath `json:"EntityPath,omitzero" smithy:"EntityPath"`
	Inferred   *NullableBoolean                `json:"Inferred,omitempty" smithy:"Inferred"`
	Name       *String                         `json:"Name,omitempty" smithy:"Name"`
	Names      ServiceNames                    `json:"Names,omitzero" smithy:"Names"`
	Type       *String                         `json:"Type,omitempty" smithy:"Type"`
}

// ResponseTimeRootCauseServices represents Smithy shape com.amazonaws.xray#ResponseTimeRootCauseServices.
type ResponseTimeRootCauseServices []ResponseTimeRootCauseService

// ResponseTimeRootCauses represents Smithy shape com.amazonaws.xray#ResponseTimeRootCauses.
type ResponseTimeRootCauses []ResponseTimeRootCause

// RetrievalStatus represents Smithy shape com.amazonaws.xray#RetrievalStatus.
type RetrievalStatus string

const (
	RetrievalStatusCANCELLED RetrievalStatus = "CANCELLED"
	RetrievalStatusCOMPLETE  RetrievalStatus = "COMPLETE"
	RetrievalStatusFAILED    RetrievalStatus = "FAILED"
	RetrievalStatusRUNNING   RetrievalStatus = "RUNNING"
	RetrievalStatusSCHEDULED RetrievalStatus = "SCHEDULED"
	RetrievalStatusTIMEOUT   RetrievalStatus = "TIMEOUT"
)

// RetrievalToken represents Smithy shape com.amazonaws.xray#RetrievalToken.
type RetrievalToken string

// RetrievedService represents Smithy shape com.amazonaws.xray#RetrievedService.
type RetrievedService struct {
	Links   LinksList `json:"Links,omitzero" smithy:"Links"`
	Service *Service  `json:"Service,omitempty" smithy:"Service"`
}

// RetrievedServicesList represents Smithy shape com.amazonaws.xray#RetrievedServicesList.
type RetrievedServicesList []RetrievedService

// RetrievedTrace represents Smithy shape com.amazonaws.xray#RetrievedTrace.
type RetrievedTrace struct {
	Duration *NullableDouble `json:"Duration,omitempty" smithy:"Duration"`
	Id       *TraceId        `json:"Id,omitempty" smithy:"Id"`
	Spans    SpanList        `json:"Spans,omitzero" smithy:"Spans"`
}

// RootCauseException represents Smithy shape com.amazonaws.xray#RootCauseException.
type RootCauseException struct {
	Message *String `json:"Message,omitempty" smithy:"Message"`
	Name    *String `json:"Name,omitempty" smithy:"Name"`
}

// RootCauseExceptions represents Smithy shape com.amazonaws.xray#RootCauseExceptions.
type RootCauseExceptions []RootCauseException

// RuleLimitExceededException represents Smithy shape com.amazonaws.xray#RuleLimitExceededException.
type RuleLimitExceededException struct {
	Message *ErrorMessage `json:"Message,omitempty" smithy:"Message"`
}

// RuleName represents Smithy shape com.amazonaws.xray#RuleName.
type RuleName string

// SampledAnomalyCount represents Smithy shape com.amazonaws.xray#SampledAnomalyCount.
type SampledAnomalyCount int32

// SampledCount represents Smithy shape com.amazonaws.xray#SampledCount.
type SampledCount int32

// SamplingBoost represents Smithy shape com.amazonaws.xray#SamplingBoost.
type SamplingBoost struct {
	// Required by the AWS service model.
	BoostRate *Double `json:"BoostRate,omitempty" smithy:"BoostRate"`
	// Required by the AWS service model.
	BoostRateTTL *Timestamp `json:"BoostRateTTL,omitempty" smithy:"BoostRateTTL"`
}

// SamplingBoostStatisticsDocument represents Smithy shape com.amazonaws.xray#SamplingBoostStatisticsDocument.
type SamplingBoostStatisticsDocument struct {
	// Required by the AWS service model.
	AnomalyCount *AnomalyCount `json:"AnomalyCount,omitempty" smithy:"AnomalyCount"`
	// Required by the AWS service model.
	RuleName *RuleName `json:"RuleName,omitempty" smithy:"RuleName"`
	// Required by the AWS service model.
	SampledAnomalyCount *SampledAnomalyCount `json:"SampledAnomalyCount,omitempty" smithy:"SampledAnomalyCount"`
	// Required by the AWS service model.
	ServiceName *ServiceName `json:"ServiceName,omitempty" smithy:"ServiceName"`
	// Required by the AWS service model.
	Timestamp *Timestamp `json:"Timestamp,omitempty" smithy:"Timestamp"`
	// Required by the AWS service model.
	TotalCount *TotalCount `json:"TotalCount,omitempty" smithy:"TotalCount"`
}

// SamplingBoostStatisticsDocumentList represents Smithy shape com.amazonaws.xray#SamplingBoostStatisticsDocumentList.
type SamplingBoostStatisticsDocumentList []SamplingBoostStatisticsDocument

// SamplingRateBoost represents Smithy shape com.amazonaws.xray#SamplingRateBoost.
type SamplingRateBoost struct {
	// Required by the AWS service model.
	CooldownWindowMinutes *CooldownWindowMinutes `json:"CooldownWindowMinutes,omitempty" smithy:"CooldownWindowMinutes"`
	// Required by the AWS service model.
	MaxRate *MaxRate `json:"MaxRate,omitempty" smithy:"MaxRate"`
}

// SamplingRule represents Smithy shape com.amazonaws.xray#SamplingRule.
type SamplingRule struct {
	Attributes AttributeMap `json:"Attributes,omitzero" smithy:"Attributes"`
	// Required by the AWS service model.
	FixedRate *FixedRate `json:"FixedRate,omitempty" smithy:"FixedRate"`
	// Required by the AWS service model.
	HTTPMethod *HTTPMethod `json:"HTTPMethod,omitempty" smithy:"HTTPMethod"`
	// Required by the AWS service model.
	Host *Host `json:"Host,omitempty" smithy:"Host"`
	// Required by the AWS service model.
	Priority *Priority `json:"Priority,omitempty" smithy:"Priority"`
	// Required by the AWS service model.
	ReservoirSize *ReservoirSize `json:"ReservoirSize,omitempty" smithy:"ReservoirSize"`
	// Required by the AWS service model.
	ResourceARN       *ResourceARN       `json:"ResourceARN,omitempty" smithy:"ResourceARN"`
	RuleARN           *String            `json:"RuleARN,omitempty" smithy:"RuleARN"`
	RuleName          *RuleName          `json:"RuleName,omitempty" smithy:"RuleName"`
	SamplingRateBoost *SamplingRateBoost `json:"SamplingRateBoost,omitempty" smithy:"SamplingRateBoost"`
	// Required by the AWS service model.
	ServiceName *ServiceName `json:"ServiceName,omitempty" smithy:"ServiceName"`
	// Required by the AWS service model.
	ServiceType *ServiceType `json:"ServiceType,omitempty" smithy:"ServiceType"`
	// Required by the AWS service model.
	URLPath *URLPath `json:"URLPath,omitempty" smithy:"URLPath"`
	// Required by the AWS service model.
	Version *Version `json:"Version,omitempty" smithy:"Version"`
}

// SamplingRuleRecord represents Smithy shape com.amazonaws.xray#SamplingRuleRecord.
type SamplingRuleRecord struct {
	CreatedAt    *Timestamp    `json:"CreatedAt,omitempty" smithy:"CreatedAt"`
	ModifiedAt   *Timestamp    `json:"ModifiedAt,omitempty" smithy:"ModifiedAt"`
	SamplingRule *SamplingRule `json:"SamplingRule,omitempty" smithy:"SamplingRule"`
}

// SamplingRuleRecordList represents Smithy shape com.amazonaws.xray#SamplingRuleRecordList.
type SamplingRuleRecordList []SamplingRuleRecord

// SamplingRuleUpdate represents Smithy shape com.amazonaws.xray#SamplingRuleUpdate.
type SamplingRuleUpdate struct {
	Attributes        AttributeMap       `json:"Attributes,omitzero" smithy:"Attributes"`
	FixedRate         *NullableDouble    `json:"FixedRate,omitempty" smithy:"FixedRate"`
	HTTPMethod        *HTTPMethod        `json:"HTTPMethod,omitempty" smithy:"HTTPMethod"`
	Host              *Host              `json:"Host,omitempty" smithy:"Host"`
	Priority          *NullableInteger   `json:"Priority,omitempty" smithy:"Priority"`
	ReservoirSize     *NullableInteger   `json:"ReservoirSize,omitempty" smithy:"ReservoirSize"`
	ResourceARN       *ResourceARN       `json:"ResourceARN,omitempty" smithy:"ResourceARN"`
	RuleARN           *String            `json:"RuleARN,omitempty" smithy:"RuleARN"`
	RuleName          *RuleName          `json:"RuleName,omitempty" smithy:"RuleName"`
	SamplingRateBoost *SamplingRateBoost `json:"SamplingRateBoost,omitempty" smithy:"SamplingRateBoost"`
	ServiceName       *ServiceName       `json:"ServiceName,omitempty" smithy:"ServiceName"`
	ServiceType       *ServiceType       `json:"ServiceType,omitempty" smithy:"ServiceType"`
	URLPath           *URLPath           `json:"URLPath,omitempty" smithy:"URLPath"`
}

// SamplingStatisticSummary represents Smithy shape com.amazonaws.xray#SamplingStatisticSummary.
type SamplingStatisticSummary struct {
	BorrowCount  *Integer   `json:"BorrowCount,omitempty" smithy:"BorrowCount"`
	RequestCount *Integer   `json:"RequestCount,omitempty" smithy:"RequestCount"`
	RuleName     *String    `json:"RuleName,omitempty" smithy:"RuleName"`
	SampledCount *Integer   `json:"SampledCount,omitempty" smithy:"SampledCount"`
	Timestamp    *Timestamp `json:"Timestamp,omitempty" smithy:"Timestamp"`
}

// SamplingStatisticSummaryList represents Smithy shape com.amazonaws.xray#SamplingStatisticSummaryList.
type SamplingStatisticSummaryList []SamplingStatisticSummary

// SamplingStatisticsDocument represents Smithy shape com.amazonaws.xray#SamplingStatisticsDocument.
type SamplingStatisticsDocument struct {
	BorrowCount *BorrowCount `json:"BorrowCount,omitempty" smithy:"BorrowCount"`
	// Required by the AWS service model.
	ClientID     *ClientID     `json:"ClientID,omitempty" smithy:"ClientID"`
	RequestCount *RequestCount `json:"RequestCount,omitempty" smithy:"RequestCount"`
	// Required by the AWS service model.
	RuleName     *RuleName     `json:"RuleName,omitempty" smithy:"RuleName"`
	SampledCount *SampledCount `json:"SampledCount,omitempty" smithy:"SampledCount"`
	// Required by the AWS service model.
	Timestamp *Timestamp `json:"Timestamp,omitempty" smithy:"Timestamp"`
}

// SamplingStatisticsDocumentList represents Smithy shape com.amazonaws.xray#SamplingStatisticsDocumentList.
type SamplingStatisticsDocumentList []SamplingStatisticsDocument

// SamplingStrategy represents Smithy shape com.amazonaws.xray#SamplingStrategy.
type SamplingStrategy struct {
	Name  *SamplingStrategyName `json:"Name,omitempty" smithy:"Name"`
	Value *NullableDouble       `json:"Value,omitempty" smithy:"Value"`
}

// SamplingStrategyName represents Smithy shape com.amazonaws.xray#SamplingStrategyName.
type SamplingStrategyName string

const (
	SamplingStrategyNameFixedRate   SamplingStrategyName = "FixedRate"
	SamplingStrategyNamePartialScan SamplingStrategyName = "PartialScan"
)

// SamplingTargetDocument represents Smithy shape com.amazonaws.xray#SamplingTargetDocument.
type SamplingTargetDocument struct {
	FixedRate         *Double          `json:"FixedRate,omitempty" smithy:"FixedRate"`
	Interval          *NullableInteger `json:"Interval,omitempty" smithy:"Interval"`
	ReservoirQuota    *NullableInteger `json:"ReservoirQuota,omitempty" smithy:"ReservoirQuota"`
	ReservoirQuotaTTL *Timestamp       `json:"ReservoirQuotaTTL,omitempty" smithy:"ReservoirQuotaTTL"`
	RuleName          *String          `json:"RuleName,omitempty" smithy:"RuleName"`
	SamplingBoost     *SamplingBoost   `json:"SamplingBoost,omitempty" smithy:"SamplingBoost"`
}

// SamplingTargetDocumentList represents Smithy shape com.amazonaws.xray#SamplingTargetDocumentList.
type SamplingTargetDocumentList []SamplingTargetDocument

// Segment represents Smithy shape com.amazonaws.xray#Segment.
type Segment struct {
	Document *SegmentDocument `json:"Document,omitempty" smithy:"Document"`
	Id       *SegmentId       `json:"Id,omitempty" smithy:"Id"`
}

// SegmentDocument represents Smithy shape com.amazonaws.xray#SegmentDocument.
type SegmentDocument string

// SegmentId represents Smithy shape com.amazonaws.xray#SegmentId.
type SegmentId string

// SegmentList represents Smithy shape com.amazonaws.xray#SegmentList.
type SegmentList []Segment

// Service represents Smithy shape com.amazonaws.xray#Service.
type Service struct {
	AccountId             *String            `json:"AccountId,omitempty" smithy:"AccountId"`
	DurationHistogram     Histogram          `json:"DurationHistogram,omitzero" smithy:"DurationHistogram"`
	Edges                 EdgeList           `json:"Edges,omitzero" smithy:"Edges"`
	EndTime               *Timestamp         `json:"EndTime,omitempty" smithy:"EndTime"`
	HostedIn              Document           `json:"HostedIn,omitempty" smithy:"HostedIn"`
	KeyAttributes         Document           `json:"KeyAttributes,omitempty" smithy:"KeyAttributes"`
	Name                  *String            `json:"Name,omitempty" smithy:"Name"`
	Names                 ServiceNames       `json:"Names,omitzero" smithy:"Names"`
	ReferenceId           *NullableInteger   `json:"ReferenceId,omitempty" smithy:"ReferenceId"`
	Region                *String            `json:"Region,omitempty" smithy:"Region"`
	ResponseTimeHistogram Histogram          `json:"ResponseTimeHistogram,omitzero" smithy:"ResponseTimeHistogram"`
	Root                  *NullableBoolean   `json:"Root,omitempty" smithy:"Root"`
	StartTime             *Timestamp         `json:"StartTime,omitempty" smithy:"StartTime"`
	State                 *String            `json:"State,omitempty" smithy:"State"`
	SummaryStatistics     *ServiceStatistics `json:"SummaryStatistics,omitempty" smithy:"SummaryStatistics"`
	Type                  *String            `json:"Type,omitempty" smithy:"Type"`
}

// ServiceId represents Smithy shape com.amazonaws.xray#ServiceId.
type ServiceId struct {
	AccountId *String      `json:"AccountId,omitempty" smithy:"AccountId"`
	Name      *String      `json:"Name,omitempty" smithy:"Name"`
	Names     ServiceNames `json:"Names,omitzero" smithy:"Names"`
	Type      *String      `json:"Type,omitempty" smithy:"Type"`
}

// ServiceIds represents Smithy shape com.amazonaws.xray#ServiceIds.
type ServiceIds []ServiceId

// ServiceList represents Smithy shape com.amazonaws.xray#ServiceList.
type ServiceList []Service

// ServiceName represents Smithy shape com.amazonaws.xray#ServiceName.
type ServiceName string

// ServiceNames represents Smithy shape com.amazonaws.xray#ServiceNames.
type ServiceNames []String

// ServiceStatistics represents Smithy shape com.amazonaws.xray#ServiceStatistics.
type ServiceStatistics struct {
	ErrorStatistics   *ErrorStatistics `json:"ErrorStatistics,omitempty" smithy:"ErrorStatistics"`
	FaultStatistics   *FaultStatistics `json:"FaultStatistics,omitempty" smithy:"FaultStatistics"`
	OkCount           *NullableLong    `json:"OkCount,omitempty" smithy:"OkCount"`
	TotalCount        *NullableLong    `json:"TotalCount,omitempty" smithy:"TotalCount"`
	TotalResponseTime *NullableDouble  `json:"TotalResponseTime,omitempty" smithy:"TotalResponseTime"`
}

// ServiceType represents Smithy shape com.amazonaws.xray#ServiceType.
type ServiceType string

// Span represents Smithy shape com.amazonaws.xray#Span.
type Span struct {
	Document *SpanDocument `json:"Document,omitempty" smithy:"Document"`
	Id       *SpanId       `json:"Id,omitempty" smithy:"Id"`
}

// SpanDocument represents Smithy shape com.amazonaws.xray#SpanDocument.
type SpanDocument string

// SpanId represents Smithy shape com.amazonaws.xray#SpanId.
type SpanId string

// SpanList represents Smithy shape com.amazonaws.xray#SpanList.
type SpanList []Span

// StartTraceRetrievalRequest represents Smithy shape com.amazonaws.xray#StartTraceRetrievalRequest.
type StartTraceRetrievalRequest struct {
	// Required by the AWS service model.
	EndTime *Timestamp `json:"EndTime,omitempty" smithy:"EndTime"`
	// Required by the AWS service model.
	StartTime *Timestamp `json:"StartTime,omitempty" smithy:"StartTime"`
	// Required by the AWS service model.
	TraceIds TraceIdListForRetrieval `json:"TraceIds,omitzero" smithy:"TraceIds"`
}

// StartTraceRetrievalResult represents Smithy shape com.amazonaws.xray#StartTraceRetrievalResult.
type StartTraceRetrievalResult struct {
	RetrievalToken *RetrievalToken `json:"RetrievalToken,omitempty" smithy:"RetrievalToken"`
}

// String represents Smithy shape com.amazonaws.xray#String.
type String string

// Tag represents Smithy shape com.amazonaws.xray#Tag.
type Tag struct {
	// Required by the AWS service model.
	Key *TagKey `json:"Key,omitempty" smithy:"Key"`
	// Required by the AWS service model.
	Value *TagValue `json:"Value,omitempty" smithy:"Value"`
}

// TagKey represents Smithy shape com.amazonaws.xray#TagKey.
type TagKey string

// TagKeyList represents Smithy shape com.amazonaws.xray#TagKeyList.
type TagKeyList []TagKey

// TagList represents Smithy shape com.amazonaws.xray#TagList.
type TagList []Tag

// TagResourceRequest represents Smithy shape com.amazonaws.xray#TagResourceRequest.
type TagResourceRequest struct {
	// Required by the AWS service model.
	ResourceARN *AmazonResourceName `json:"ResourceARN,omitempty" smithy:"ResourceARN"`
	// Required by the AWS service model.
	Tags TagList `json:"Tags,omitzero" smithy:"Tags"`
}

// TagResourceResponse represents Smithy shape com.amazonaws.xray#TagResourceResponse.
type TagResourceResponse struct {
}

// TagValue represents Smithy shape com.amazonaws.xray#TagValue.
type TagValue string

// TelemetryRecord represents Smithy shape com.amazonaws.xray#TelemetryRecord.
type TelemetryRecord struct {
	BackendConnectionErrors *BackendConnectionErrors `json:"BackendConnectionErrors,omitempty" smithy:"BackendConnectionErrors"`
	SegmentsReceivedCount   *NullableInteger         `json:"SegmentsReceivedCount,omitempty" smithy:"SegmentsReceivedCount"`
	SegmentsRejectedCount   *NullableInteger         `json:"SegmentsRejectedCount,omitempty" smithy:"SegmentsRejectedCount"`
	SegmentsSentCount       *NullableInteger         `json:"SegmentsSentCount,omitempty" smithy:"SegmentsSentCount"`
	SegmentsSpilloverCount  *NullableInteger         `json:"SegmentsSpilloverCount,omitempty" smithy:"SegmentsSpilloverCount"`
	// Required by the AWS service model.
	Timestamp *Timestamp `json:"Timestamp,omitempty" smithy:"Timestamp"`
}

// TelemetryRecordList represents Smithy shape com.amazonaws.xray#TelemetryRecordList.
type TelemetryRecordList []TelemetryRecord

// ThrottledException represents Smithy shape com.amazonaws.xray#ThrottledException.
type ThrottledException struct {
	Message *ErrorMessage `json:"Message,omitempty" smithy:"Message"`
}

// TimeRangeType represents Smithy shape com.amazonaws.xray#TimeRangeType.
type TimeRangeType string

const (
	TimeRangeTypeEvent   TimeRangeType = "Event"
	TimeRangeTypeService TimeRangeType = "Service"
	TimeRangeTypeTraceId TimeRangeType = "TraceId"
)

// TimeSeriesServiceStatistics represents Smithy shape com.amazonaws.xray#TimeSeriesServiceStatistics.
type TimeSeriesServiceStatistics struct {
	EdgeSummaryStatistics     *EdgeStatistics     `json:"EdgeSummaryStatistics,omitempty" smithy:"EdgeSummaryStatistics"`
	ResponseTimeHistogram     Histogram           `json:"ResponseTimeHistogram,omitzero" smithy:"ResponseTimeHistogram"`
	ServiceForecastStatistics *ForecastStatistics `json:"ServiceForecastStatistics,omitempty" smithy:"ServiceForecastStatistics"`
	ServiceSummaryStatistics  *ServiceStatistics  `json:"ServiceSummaryStatistics,omitempty" smithy:"ServiceSummaryStatistics"`
	Timestamp                 *Timestamp          `json:"Timestamp,omitempty" smithy:"Timestamp"`
}

// TimeSeriesServiceStatisticsList represents Smithy shape com.amazonaws.xray#TimeSeriesServiceStatisticsList.
type TimeSeriesServiceStatisticsList []TimeSeriesServiceStatistics

// Timestamp represents Smithy shape com.amazonaws.xray#Timestamp.
type Timestamp = time.Time

// Token represents Smithy shape com.amazonaws.xray#Token.
type Token string

// TooManyTagsException represents Smithy shape com.amazonaws.xray#TooManyTagsException.
type TooManyTagsException struct {
	Message      *ErrorMessage       `json:"Message,omitempty" smithy:"Message"`
	ResourceName *AmazonResourceName `json:"ResourceName,omitempty" smithy:"ResourceName"`
}

// TotalCount represents Smithy shape com.amazonaws.xray#TotalCount.
type TotalCount int32

// Trace represents Smithy shape com.amazonaws.xray#Trace.
type Trace struct {
	Duration      *NullableDouble  `json:"Duration,omitempty" smithy:"Duration"`
	Id            *TraceId         `json:"Id,omitempty" smithy:"Id"`
	LimitExceeded *NullableBoolean `json:"LimitExceeded,omitempty" smithy:"LimitExceeded"`
	Segments      SegmentList      `json:"Segments,omitzero" smithy:"Segments"`
}

// TraceAvailabilityZones represents Smithy shape com.amazonaws.xray#TraceAvailabilityZones.
type TraceAvailabilityZones []AvailabilityZoneDetail

// TraceFormatType represents Smithy shape com.amazonaws.xray#TraceFormatType.
type TraceFormatType string

const (
	TraceFormatTypeOTEL TraceFormatType = "OTEL"
	TraceFormatTypeXRAY TraceFormatType = "XRAY"
)

// TraceId represents Smithy shape com.amazonaws.xray#TraceId.
type TraceId string

// TraceIdList represents Smithy shape com.amazonaws.xray#TraceIdList.
type TraceIdList []TraceId

// TraceIdListForRetrieval represents Smithy shape com.amazonaws.xray#TraceIdListForRetrieval.
type TraceIdListForRetrieval []TraceId

// TraceInstanceIds represents Smithy shape com.amazonaws.xray#TraceInstanceIds.
type TraceInstanceIds []InstanceIdDetail

// TraceList represents Smithy shape com.amazonaws.xray#TraceList.
type TraceList []Trace

// TraceResourceARNs represents Smithy shape com.amazonaws.xray#TraceResourceARNs.
type TraceResourceARNs []ResourceARNDetail

// TraceSegmentDestination represents Smithy shape com.amazonaws.xray#TraceSegmentDestination.
type TraceSegmentDestination string

const (
	TraceSegmentDestinationCloudWatchLogs TraceSegmentDestination = "CloudWatchLogs"
	TraceSegmentDestinationXRay           TraceSegmentDestination = "XRay"
)

// TraceSegmentDestinationStatus represents Smithy shape com.amazonaws.xray#TraceSegmentDestinationStatus.
type TraceSegmentDestinationStatus string

const (
	TraceSegmentDestinationStatusACTIVE  TraceSegmentDestinationStatus = "ACTIVE"
	TraceSegmentDestinationStatusPENDING TraceSegmentDestinationStatus = "PENDING"
)

// TraceSegmentDocument represents Smithy shape com.amazonaws.xray#TraceSegmentDocument.
type TraceSegmentDocument string

// TraceSegmentDocumentList represents Smithy shape com.amazonaws.xray#TraceSegmentDocumentList.
type TraceSegmentDocumentList []TraceSegmentDocument

// TraceSpanList represents Smithy shape com.amazonaws.xray#TraceSpanList.
type TraceSpanList []RetrievedTrace

// TraceSummary represents Smithy shape com.amazonaws.xray#TraceSummary.
type TraceSummary struct {
	Annotations            Annotations            `json:"Annotations,omitzero" smithy:"Annotations"`
	AvailabilityZones      TraceAvailabilityZones `json:"AvailabilityZones,omitzero" smithy:"AvailabilityZones"`
	Duration               *NullableDouble        `json:"Duration,omitempty" smithy:"Duration"`
	EntryPoint             *ServiceId             `json:"EntryPoint,omitempty" smithy:"EntryPoint"`
	ErrorRootCauses        ErrorRootCauses        `json:"ErrorRootCauses,omitzero" smithy:"ErrorRootCauses"`
	FaultRootCauses        FaultRootCauses        `json:"FaultRootCauses,omitzero" smithy:"FaultRootCauses"`
	HasError               *NullableBoolean       `json:"HasError,omitempty" smithy:"HasError"`
	HasFault               *NullableBoolean       `json:"HasFault,omitempty" smithy:"HasFault"`
	HasThrottle            *NullableBoolean       `json:"HasThrottle,omitempty" smithy:"HasThrottle"`
	Http                   *Http                  `json:"Http,omitempty" smithy:"Http"`
	Id                     *TraceId               `json:"Id,omitempty" smithy:"Id"`
	InstanceIds            TraceInstanceIds       `json:"InstanceIds,omitzero" smithy:"InstanceIds"`
	IsPartial              *NullableBoolean       `json:"IsPartial,omitempty" smithy:"IsPartial"`
	MatchedEdge            Document               `json:"MatchedEdge,omitempty" smithy:"MatchedEdge"`
	MatchedEventTime       *Timestamp             `json:"MatchedEventTime,omitempty" smithy:"MatchedEventTime"`
	MatchedService         Document               `json:"MatchedService,omitempty" smithy:"MatchedService"`
	ResourceARNs           TraceResourceARNs      `json:"ResourceARNs,omitzero" smithy:"ResourceARNs"`
	ResponseTime           *NullableDouble        `json:"ResponseTime,omitempty" smithy:"ResponseTime"`
	ResponseTimeRootCauses ResponseTimeRootCauses `json:"ResponseTimeRootCauses,omitzero" smithy:"ResponseTimeRootCauses"`
	Revision               *Integer               `json:"Revision,omitempty" smithy:"Revision"`
	ServiceIds             ServiceIds             `json:"ServiceIds,omitzero" smithy:"ServiceIds"`
	StartTime              *Timestamp             `json:"StartTime,omitempty" smithy:"StartTime"`
	Users                  TraceUsers             `json:"Users,omitzero" smithy:"Users"`
}

// TraceSummaryList represents Smithy shape com.amazonaws.xray#TraceSummaryList.
type TraceSummaryList []TraceSummary

// TraceUser represents Smithy shape com.amazonaws.xray#TraceUser.
type TraceUser struct {
	ServiceIds ServiceIds `json:"ServiceIds,omitzero" smithy:"ServiceIds"`
	UserName   *String    `json:"UserName,omitempty" smithy:"UserName"`
}

// TraceUsers represents Smithy shape com.amazonaws.xray#TraceUsers.
type TraceUsers []TraceUser

// URLPath represents Smithy shape com.amazonaws.xray#URLPath.
type URLPath string

// UnprocessedStatistics represents Smithy shape com.amazonaws.xray#UnprocessedStatistics.
type UnprocessedStatistics struct {
	ErrorCode *String `json:"ErrorCode,omitempty" smithy:"ErrorCode"`
	Message   *String `json:"Message,omitempty" smithy:"Message"`
	RuleName  *String `json:"RuleName,omitempty" smithy:"RuleName"`
}

// UnprocessedStatisticsList represents Smithy shape com.amazonaws.xray#UnprocessedStatisticsList.
type UnprocessedStatisticsList []UnprocessedStatistics

// UnprocessedTraceIdList represents Smithy shape com.amazonaws.xray#UnprocessedTraceIdList.
type UnprocessedTraceIdList []TraceId

// UnprocessedTraceSegment represents Smithy shape com.amazonaws.xray#UnprocessedTraceSegment.
type UnprocessedTraceSegment struct {
	ErrorCode *String `json:"ErrorCode,omitempty" smithy:"ErrorCode"`
	Id        *String `json:"Id,omitempty" smithy:"Id"`
	Message   *String `json:"Message,omitempty" smithy:"Message"`
}

// UnprocessedTraceSegmentList represents Smithy shape com.amazonaws.xray#UnprocessedTraceSegmentList.
type UnprocessedTraceSegmentList []UnprocessedTraceSegment

// UntagResourceRequest represents Smithy shape com.amazonaws.xray#UntagResourceRequest.
type UntagResourceRequest struct {
	// Required by the AWS service model.
	ResourceARN *AmazonResourceName `json:"ResourceARN,omitempty" smithy:"ResourceARN"`
	// Required by the AWS service model.
	TagKeys TagKeyList `json:"TagKeys,omitzero" smithy:"TagKeys"`
}

// UntagResourceResponse represents Smithy shape com.amazonaws.xray#UntagResourceResponse.
type UntagResourceResponse struct {
}

// UpdateGroupRequest represents Smithy shape com.amazonaws.xray#UpdateGroupRequest.
type UpdateGroupRequest struct {
	FilterExpression      *FilterExpression      `json:"FilterExpression,omitempty" smithy:"FilterExpression"`
	GroupARN              *GroupARN              `json:"GroupARN,omitempty" smithy:"GroupARN"`
	GroupName             *GroupName             `json:"GroupName,omitempty" smithy:"GroupName"`
	InsightsConfiguration *InsightsConfiguration `json:"InsightsConfiguration,omitempty" smithy:"InsightsConfiguration"`
}

// UpdateGroupResult represents Smithy shape com.amazonaws.xray#UpdateGroupResult.
type UpdateGroupResult struct {
	Group *Group `json:"Group,omitempty" smithy:"Group"`
}

// UpdateIndexingRuleRequest represents Smithy shape com.amazonaws.xray#UpdateIndexingRuleRequest.
type UpdateIndexingRuleRequest struct {
	// Required by the AWS service model.
	Name *String `json:"Name,omitempty" smithy:"Name"`
	// Required by the AWS service model.
	Rule *IndexingRuleValueUpdate `json:"Rule,omitempty" smithy:"Rule"`
}

// UpdateIndexingRuleResult represents Smithy shape com.amazonaws.xray#UpdateIndexingRuleResult.
type UpdateIndexingRuleResult struct {
	IndexingRule *IndexingRule `json:"IndexingRule,omitempty" smithy:"IndexingRule"`
}

// UpdateSamplingRuleRequest represents Smithy shape com.amazonaws.xray#UpdateSamplingRuleRequest.
type UpdateSamplingRuleRequest struct {
	// Required by the AWS service model.
	SamplingRuleUpdate *SamplingRuleUpdate `json:"SamplingRuleUpdate,omitempty" smithy:"SamplingRuleUpdate"`
}

// UpdateSamplingRuleResult represents Smithy shape com.amazonaws.xray#UpdateSamplingRuleResult.
type UpdateSamplingRuleResult struct {
	SamplingRuleRecord *SamplingRuleRecord `json:"SamplingRuleRecord,omitempty" smithy:"SamplingRuleRecord"`
}

// UpdateTraceSegmentDestinationRequest represents Smithy shape com.amazonaws.xray#UpdateTraceSegmentDestinationRequest.
type UpdateTraceSegmentDestinationRequest struct {
	Destination *TraceSegmentDestination `json:"Destination,omitempty" smithy:"Destination"`
}

// UpdateTraceSegmentDestinationResult represents Smithy shape com.amazonaws.xray#UpdateTraceSegmentDestinationResult.
type UpdateTraceSegmentDestinationResult struct {
	Destination *TraceSegmentDestination       `json:"Destination,omitempty" smithy:"Destination"`
	Status      *TraceSegmentDestinationStatus `json:"Status,omitempty" smithy:"Status"`
}

// ValueWithServiceIds represents Smithy shape com.amazonaws.xray#ValueWithServiceIds.
type ValueWithServiceIds struct {
	AnnotationValue *AnnotationValue `json:"AnnotationValue,omitempty" smithy:"AnnotationValue"`
	ServiceIds      ServiceIds       `json:"ServiceIds,omitzero" smithy:"ServiceIds"`
}

// ValuesWithServiceIds represents Smithy shape com.amazonaws.xray#ValuesWithServiceIds.
type ValuesWithServiceIds []ValueWithServiceIds

// Version represents Smithy shape com.amazonaws.xray#Version.
type Version int32

// Document represents Smithy shape smithy.api#Document.
type Document any

// Unit represents Smithy shape smithy.api#Unit.
type Unit struct {
}
type BatchGetTracesInput = BatchGetTracesRequest
type BatchGetTracesOutput = BatchGetTracesResult
type CancelTraceRetrievalInput = CancelTraceRetrievalRequest
type CancelTraceRetrievalOutput = CancelTraceRetrievalResult
type CreateGroupInput = CreateGroupRequest
type CreateGroupOutput = CreateGroupResult
type CreateSamplingRuleInput = CreateSamplingRuleRequest
type CreateSamplingRuleOutput = CreateSamplingRuleResult
type DeleteGroupInput = DeleteGroupRequest
type DeleteGroupOutput = DeleteGroupResult
type DeleteResourcePolicyInput = DeleteResourcePolicyRequest
type DeleteResourcePolicyOutput = DeleteResourcePolicyResult
type DeleteSamplingRuleInput = DeleteSamplingRuleRequest
type DeleteSamplingRuleOutput = DeleteSamplingRuleResult
type GetEncryptionConfigInput = GetEncryptionConfigRequest
type GetEncryptionConfigOutput = GetEncryptionConfigResult
type GetGroupInput = GetGroupRequest
type GetGroupOutput = GetGroupResult
type GetGroupsInput = GetGroupsRequest
type GetGroupsOutput = GetGroupsResult
type GetIndexingRulesInput = GetIndexingRulesRequest
type GetIndexingRulesOutput = GetIndexingRulesResult
type GetInsightInput = GetInsightRequest
type GetInsightOutput = GetInsightResult
type GetInsightEventsInput = GetInsightEventsRequest
type GetInsightEventsOutput = GetInsightEventsResult
type GetInsightImpactGraphInput = GetInsightImpactGraphRequest
type GetInsightImpactGraphOutput = GetInsightImpactGraphResult
type GetInsightSummariesInput = GetInsightSummariesRequest
type GetInsightSummariesOutput = GetInsightSummariesResult
type GetRetrievedTracesGraphInput = GetRetrievedTracesGraphRequest
type GetRetrievedTracesGraphOutput = GetRetrievedTracesGraphResult
type GetSamplingRulesInput = GetSamplingRulesRequest
type GetSamplingRulesOutput = GetSamplingRulesResult
type GetSamplingStatisticSummariesInput = GetSamplingStatisticSummariesRequest
type GetSamplingStatisticSummariesOutput = GetSamplingStatisticSummariesResult
type GetSamplingTargetsInput = GetSamplingTargetsRequest
type GetSamplingTargetsOutput = GetSamplingTargetsResult
type GetServiceGraphInput = GetServiceGraphRequest
type GetServiceGraphOutput = GetServiceGraphResult
type GetTimeSeriesServiceStatisticsInput = GetTimeSeriesServiceStatisticsRequest
type GetTimeSeriesServiceStatisticsOutput = GetTimeSeriesServiceStatisticsResult
type GetTraceGraphInput = GetTraceGraphRequest
type GetTraceGraphOutput = GetTraceGraphResult
type GetTraceSegmentDestinationInput = GetTraceSegmentDestinationRequest
type GetTraceSegmentDestinationOutput = GetTraceSegmentDestinationResult
type GetTraceSummariesInput = GetTraceSummariesRequest
type GetTraceSummariesOutput = GetTraceSummariesResult
type ListResourcePoliciesInput = ListResourcePoliciesRequest
type ListResourcePoliciesOutput = ListResourcePoliciesResult
type ListRetrievedTracesInput = ListRetrievedTracesRequest
type ListRetrievedTracesOutput = ListRetrievedTracesResult
type ListTagsForResourceInput = ListTagsForResourceRequest
type ListTagsForResourceOutput = ListTagsForResourceResponse
type PutEncryptionConfigInput = PutEncryptionConfigRequest
type PutEncryptionConfigOutput = PutEncryptionConfigResult
type PutResourcePolicyInput = PutResourcePolicyRequest
type PutResourcePolicyOutput = PutResourcePolicyResult
type PutTelemetryRecordsInput = PutTelemetryRecordsRequest
type PutTelemetryRecordsOutput = PutTelemetryRecordsResult
type PutTraceSegmentsInput = PutTraceSegmentsRequest
type PutTraceSegmentsOutput = PutTraceSegmentsResult
type StartTraceRetrievalInput = StartTraceRetrievalRequest
type StartTraceRetrievalOutput = StartTraceRetrievalResult
type TagResourceInput = TagResourceRequest
type TagResourceOutput = TagResourceResponse
type UntagResourceInput = UntagResourceRequest
type UntagResourceOutput = UntagResourceResponse
type UpdateGroupInput = UpdateGroupRequest
type UpdateGroupOutput = UpdateGroupResult
type UpdateIndexingRuleInput = UpdateIndexingRuleRequest
type UpdateIndexingRuleOutput = UpdateIndexingRuleResult
type UpdateSamplingRuleInput = UpdateSamplingRuleRequest
type UpdateSamplingRuleOutput = UpdateSamplingRuleResult
type UpdateTraceSegmentDestinationInput = UpdateTraceSegmentDestinationRequest
type UpdateTraceSegmentDestinationOutput = UpdateTraceSegmentDestinationResult
