-- Retained task state and admitted snapshots are independent of catalog lifecycle.
-- Current tags belong only to ecs_tag_sets/ecs_tags.
CREATE TABLE ecs_tasks (
 partition TEXT NOT NULL,
 account_id TEXT NOT NULL,
 region TEXT NOT NULL,
 cluster_name TEXT NOT NULL,
 task_id TEXT NOT NULL,
 task_attachments BLOB NOT NULL,
 task_attributes BLOB NOT NULL,
 task_availability_zone TEXT,
 task_capacity_provider_name TEXT,
 task_cluster_arn TEXT,
 task_connectivity TEXT,
 task_connectivity_at TIMESTAMP,
 task_container_instance_arn TEXT,
 task_containers BLOB NOT NULL,
 task_cpu TEXT,
 task_created_at TIMESTAMP,
 task_desired_status TEXT,
 task_enable_execute_command BOOLEAN,
 task_ephemeral_storage BLOB NOT NULL,
 task_execution_stopped_at TIMESTAMP,
 task_fargate_ephemeral_storage BLOB NOT NULL,
 task_group TEXT,
 task_health_status TEXT,
 task_inference_accelerators BLOB NOT NULL,
 task_last_status TEXT,
 task_launch_type TEXT,
 task_memory TEXT,
 task_overrides BLOB NOT NULL,
 task_platform_family TEXT,
 task_platform_version TEXT,
 task_pull_started_at TIMESTAMP,
 task_pull_stopped_at TIMESTAMP,
 task_started_at TIMESTAMP,
 task_started_by TEXT,
 task_stop_code TEXT,
 task_stopped_at TIMESTAMP,
 task_stopped_reason TEXT,
 task_stopping_at TIMESTAMP,
 task_task_arn TEXT,
 task_task_definition_arn TEXT,
 task_version INTEGER,
 definition_compatibilities BLOB NOT NULL,
 definition_container_definitions BLOB NOT NULL,
 definition_cpu TEXT,
 definition_delete_requested_at TIMESTAMP,
 definition_deregistered_at TIMESTAMP,
 definition_enable_fault_injection BOOLEAN,
 definition_ephemeral_storage BLOB NOT NULL,
 definition_execution_role_arn TEXT,
 definition_family TEXT,
 definition_inference_accelerators BLOB NOT NULL,
 definition_ipc_mode TEXT,
 definition_memory TEXT,
 definition_network_mode TEXT,
 definition_pid_mode TEXT,
 definition_placement_constraints BLOB NOT NULL,
 definition_previous_status TEXT,
 definition_proxy_configuration BLOB NOT NULL,
 definition_registered_at TIMESTAMP,
 definition_registered_by TEXT,
 definition_requires_attributes BLOB NOT NULL,
 definition_requires_compatibilities BLOB NOT NULL,
 definition_revision INTEGER,
 definition_runtime_platform BLOB NOT NULL,
 definition_status TEXT,
 definition_task_definition_arn TEXT,
 definition_task_role_arn TEXT,
 definition_volumes BLOB NOT NULL,
 network_configuration BLOB NOT NULL,
 accepted_event_id TEXT NOT NULL,
 credential_token TEXT NOT NULL,
 metadata_tokens BLOB NOT NULL,
 log_cursors BLOB NOT NULL,
 dependency_wait_started BLOB NOT NULL,
 PRIMARY KEY (partition, account_id, region, cluster_name, task_id)
);
CREATE INDEX ecs_tasks_active ON ecs_tasks(partition, account_id, region, cluster_name, task_id) WHERE task_last_status IS NULL OR task_last_status <> 'STOPPED';
CREATE INDEX ecs_tasks_family ON ecs_tasks(partition, account_id, region, cluster_name, definition_family, task_id);
CREATE TABLE ecs_task_runs (
 partition TEXT NOT NULL,
 account_id TEXT NOT NULL,
 region TEXT NOT NULL,
 cluster_name TEXT NOT NULL,
 client_token TEXT NOT NULL,
 input_capacity_provider_strategy BLOB NOT NULL,
 input_client_token TEXT,
 input_cluster TEXT,
 input_count INTEGER,
 input_enable_ecs_managed_tags BOOLEAN,
 input_enable_execute_command BOOLEAN,
 input_group TEXT,
 input_launch_type TEXT,
 input_network_configuration BLOB NOT NULL,
 input_overrides BLOB NOT NULL,
 input_placement_constraints BLOB NOT NULL,
 input_placement_strategy BLOB NOT NULL,
 input_platform_version TEXT,
 input_propagate_tags TEXT,
 input_reference_id TEXT,
 input_started_by TEXT,
 input_tags BLOB NOT NULL,
 input_task_definition TEXT,
 input_volume_configurations BLOB NOT NULL,
 task_ids BLOB NOT NULL,
 created TIMESTAMP NOT NULL,
 PRIMARY KEY (partition, account_id, region, cluster_name, client_token)
);
