-- Replica services retain normalized admitted requests and immutable deployment snapshots.
-- Only generated nested configurations are JSON; current tags remain in ecs_tags.
CREATE TABLE ecs_services (
 partition TEXT NOT NULL,
 account_id TEXT NOT NULL,
 region TEXT NOT NULL,
 cluster_name TEXT NOT NULL,
 service_name TEXT NOT NULL,
 service_availability_zone_rebalancing TEXT,
 service_capacity_provider_strategy BLOB NOT NULL,
 service_cluster_arn TEXT,
 service_created_at TIMESTAMP,
 service_created_by TEXT,
 service_current_service_deployment TEXT,
 service_current_service_revisions BLOB NOT NULL,
 service_deployment_configuration BLOB NOT NULL,
 service_deployment_controller BLOB NOT NULL,
 service_desired_count INTEGER,
 service_enable_ecs_managed_tags BOOLEAN,
 service_enable_execute_command BOOLEAN,
 service_events BLOB NOT NULL,
 service_health_check_grace_period_seconds INTEGER,
 service_launch_type TEXT,
 service_effective_launch_type TEXT NOT NULL,
 service_load_balancers BLOB NOT NULL,
 service_network_configuration BLOB NOT NULL,
 service_pending_count INTEGER,
 service_placement_constraints BLOB NOT NULL,
 service_placement_strategy BLOB NOT NULL,
 service_platform_family TEXT,
 service_platform_version TEXT,
 service_propagate_tags TEXT,
 service_resource_management_type TEXT,
 service_role_arn TEXT,
 service_running_count INTEGER,
 service_scheduling_strategy TEXT,
 service_service_arn TEXT,
 service_service_name TEXT,
 service_service_registries BLOB NOT NULL,
 service_status TEXT,
 service_task_definition TEXT,
 service_task_sets BLOB NOT NULL,
 create_availability_zone_rebalancing TEXT,
 create_capacity_provider_strategy BLOB NOT NULL,
 create_client_token TEXT,
 create_cluster TEXT,
 create_deployment_configuration BLOB NOT NULL,
 create_deployment_controller BLOB NOT NULL,
 create_desired_count INTEGER,
 create_enable_ecs_managed_tags BOOLEAN,
 create_enable_execute_command BOOLEAN,
 create_health_check_grace_period_seconds INTEGER,
 create_launch_type TEXT,
 create_load_balancers BLOB NOT NULL,
 create_monitoring BLOB NOT NULL,
 create_network_configuration BLOB NOT NULL,
 create_placement_constraints BLOB NOT NULL,
 create_placement_strategy BLOB NOT NULL,
 create_platform_version TEXT,
 create_propagate_tags TEXT,
 create_role TEXT,
 create_scheduling_strategy TEXT,
 create_service_connect_configuration BLOB NOT NULL,
 create_service_name TEXT,
 create_service_registries BLOB NOT NULL,
 create_tags BLOB NOT NULL,
 create_task_definition TEXT,
 create_volume_configurations BLOB NOT NULL,
 create_vpc_lattice_configurations BLOB NOT NULL,
 accepted_event_id TEXT NOT NULL,
 drain_after TIMESTAMP NOT NULL,
 deployments_present BOOLEAN NOT NULL,
 PRIMARY KEY (partition, account_id, region, cluster_name, service_name)
);
CREATE INDEX ecs_services_active ON ecs_services(partition, account_id, region, cluster_name, service_name) WHERE service_status IN ('ACTIVE', 'DRAINING');
CREATE TABLE ecs_service_deployments (
 partition TEXT NOT NULL,
 account_id TEXT NOT NULL,
 region TEXT NOT NULL,
 cluster_name TEXT NOT NULL,
 service_name TEXT NOT NULL,
 position INTEGER NOT NULL,
 deployment_capacity_provider_strategy BLOB NOT NULL,
 deployment_created_at TIMESTAMP,
 deployment_desired_count INTEGER,
 deployment_failed_tasks INTEGER,
 deployment_fargate_ephemeral_storage BLOB NOT NULL,
 deployment_id TEXT,
 deployment_launch_type TEXT,
 deployment_network_configuration BLOB NOT NULL,
 deployment_pending_count INTEGER,
 deployment_platform_family TEXT,
 deployment_platform_version TEXT,
 deployment_rollout_state TEXT,
 deployment_rollout_state_reason TEXT,
 deployment_running_count INTEGER,
 deployment_service_connect_configuration BLOB NOT NULL,
 deployment_service_connect_resources BLOB NOT NULL,
 deployment_status TEXT,
 deployment_task_definition TEXT,
 deployment_updated_at TIMESTAMP,
 deployment_volume_configurations BLOB NOT NULL,
 deployment_vpc_lattice_configurations BLOB NOT NULL,
 definition_compatibilities BLOB NOT NULL,
 definition_container_definitions BLOB NOT NULL,
 definition_cpu TEXT,
 definition_delete_requested_at TIMESTAMP,
 definition_deregistered_at TIMESTAMP,
 definition_enable_fault_injection BOOLEAN,
 definition_ephemeral_storage BLOB NOT NULL,
 definition_execution_role_arn TEXT,
 definition_family TEXT,
 definition_inference_accelerators BLOB NOT NULL,
 definition_ipc_mode TEXT,
 definition_memory TEXT,
 definition_network_mode TEXT,
 definition_pid_mode TEXT,
 definition_placement_constraints BLOB NOT NULL,
 definition_previous_status TEXT,
 definition_proxy_configuration BLOB NOT NULL,
 definition_registered_at TIMESTAMP,
 definition_registered_by TEXT,
 definition_requires_attributes BLOB NOT NULL,
 definition_requires_compatibilities BLOB NOT NULL,
 definition_revision INTEGER,
 definition_runtime_platform BLOB NOT NULL,
 definition_status TEXT,
 definition_task_definition_arn TEXT,
 definition_task_role_arn TEXT,
 definition_volumes BLOB NOT NULL,
 input_capacity_provider_strategy BLOB NOT NULL,
 input_client_token TEXT,
 input_cluster TEXT,
 input_count INTEGER,
 input_enable_ecs_managed_tags BOOLEAN,
 input_enable_execute_command BOOLEAN,
 input_group TEXT,
 input_launch_type TEXT,
 input_network_configuration BLOB NOT NULL,
 input_overrides BLOB NOT NULL,
 input_placement_constraints BLOB NOT NULL,
 input_placement_strategy BLOB NOT NULL,
 input_platform_version TEXT,
 input_propagate_tags TEXT,
 input_reference_id TEXT,
 input_started_by TEXT,
 input_tags BLOB NOT NULL,
 input_task_definition TEXT,
 input_volume_configurations BLOB NOT NULL,
 accepted_event_id TEXT NOT NULL,
 failures INTEGER NOT NULL,
 retry_after TIMESTAMP NOT NULL,
 deadline TIMESTAMP NOT NULL,
 completed BOOLEAN NOT NULL,
 observed_tasks_present BOOLEAN NOT NULL,
 resolved_images_present BOOLEAN NOT NULL,
 PRIMARY KEY (partition, account_id, region, cluster_name, service_name, position),
 FOREIGN KEY (partition, account_id, region, cluster_name, service_name) REFERENCES ecs_services(partition, account_id, region, cluster_name, service_name) ON DELETE CASCADE
);
CREATE TABLE ecs_service_observed_tasks (
 partition TEXT NOT NULL,
 account_id TEXT NOT NULL,
 region TEXT NOT NULL,
 cluster_name TEXT NOT NULL,
 service_name TEXT NOT NULL,
 position INTEGER NOT NULL,
 task_id TEXT NOT NULL,
 status TEXT NOT NULL,
 PRIMARY KEY (partition, account_id, region, cluster_name, service_name, position, task_id),
 FOREIGN KEY (partition, account_id, region, cluster_name, service_name, position) REFERENCES ecs_service_deployments(partition, account_id, region, cluster_name, service_name, position) ON DELETE CASCADE
);
CREATE TABLE ecs_service_resolved_images (
 partition TEXT NOT NULL,
 account_id TEXT NOT NULL,
 region TEXT NOT NULL,
 cluster_name TEXT NOT NULL,
 service_name TEXT NOT NULL,
 position INTEGER NOT NULL,
 container_name TEXT NOT NULL,
 image_reference TEXT NOT NULL,
 PRIMARY KEY (partition, account_id, region, cluster_name, service_name, position, container_name),
 FOREIGN KEY (partition, account_id, region, cluster_name, service_name, position) REFERENCES ecs_service_deployments(partition, account_id, region, cluster_name, service_name, position) ON DELETE CASCADE
);

-- Scheduler ownership is distinct from customer-controlled Group and StartedBy.
ALTER TABLE ecs_tasks ADD COLUMN service_name TEXT NOT NULL DEFAULT '';
ALTER TABLE ecs_tasks ADD COLUMN service_deployment_id TEXT NOT NULL DEFAULT '';
