-- ECS invocation parameters are captured separately on accepted deliveries.
ALTER TABLE eventbridge_targets ADD COLUMN ecs_present BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE eventbridge_targets ADD COLUMN ecs_task_definition TEXT;
ALTER TABLE eventbridge_targets ADD COLUMN ecs_task_count INTEGER;
ALTER TABLE eventbridge_targets ADD COLUMN ecs_launch_type TEXT;
ALTER TABLE eventbridge_targets ADD COLUMN ecs_group TEXT;
ALTER TABLE eventbridge_targets ADD COLUMN ecs_platform_version TEXT;
ALTER TABLE eventbridge_targets ADD COLUMN ecs_reference_id TEXT;
ALTER TABLE eventbridge_targets ADD COLUMN ecs_propagate_tags TEXT;
ALTER TABLE eventbridge_targets ADD COLUMN ecs_enable_managed_tags BOOLEAN;
ALTER TABLE eventbridge_targets ADD COLUMN ecs_enable_execute_command BOOLEAN;
ALTER TABLE eventbridge_targets ADD COLUMN ecs_network_configuration BLOB NOT NULL DEFAULT X'6e756c6c';
ALTER TABLE eventbridge_targets ADD COLUMN ecs_capacity_provider_strategy BLOB NOT NULL DEFAULT X'6e756c6c';
ALTER TABLE eventbridge_targets ADD COLUMN ecs_placement_constraints BLOB NOT NULL DEFAULT X'6e756c6c';
ALTER TABLE eventbridge_targets ADD COLUMN ecs_placement_strategy BLOB NOT NULL DEFAULT X'6e756c6c';
ALTER TABLE eventbridge_targets ADD COLUMN ecs_tags BLOB NOT NULL DEFAULT X'6e756c6c';
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_present BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_task_definition TEXT;
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_task_count INTEGER;
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_launch_type TEXT;
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_group TEXT;
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_platform_version TEXT;
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_reference_id TEXT;
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_propagate_tags TEXT;
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_enable_managed_tags BOOLEAN;
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_enable_execute_command BOOLEAN;
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_network_configuration BLOB NOT NULL DEFAULT X'6e756c6c';
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_capacity_provider_strategy BLOB NOT NULL DEFAULT X'6e756c6c';
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_placement_constraints BLOB NOT NULL DEFAULT X'6e756c6c';
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_placement_strategy BLOB NOT NULL DEFAULT X'6e756c6c';
ALTER TABLE eventbridge_deliveries ADD COLUMN ecs_tags BLOB NOT NULL DEFAULT X'6e756c6c';
