-- Glue definitions, attempts and execution intents share the native transaction domain.
-- Runs deliberately outlive job deletion. Credentials are never stored here.
CREATE TABLE glue_jobs (
    partition TEXT NOT NULL,
    account_id TEXT NOT NULL,
    region TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    role TEXT NOT NULL,
    command TEXT NOT NULL,
    script_location TEXT NOT NULL,
    python_version TEXT NOT NULL,
    glue_version TEXT NOT NULL,
    worker_type TEXT NOT NULL,
    execution_class TEXT NOT NULL,
    security_configuration TEXT NOT NULL,
    max_concurrent_runs INTEGER NOT NULL,
    max_retries INTEGER NOT NULL,
    timeout INTEGER NOT NULL,
    number_of_workers INTEGER NOT NULL,
    max_capacity REAL NOT NULL,
    default_arguments TEXT NOT NULL,
    non_overridable_arguments TEXT NOT NULL,
    tags TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    PRIMARY KEY (partition, account_id, region, name)
);

CREATE TABLE glue_job_runs (
    partition TEXT NOT NULL,
    account_id TEXT NOT NULL,
    region TEXT NOT NULL,
    name TEXT NOT NULL,
    id TEXT NOT NULL,
    state TEXT NOT NULL,
    role TEXT NOT NULL,
    command TEXT NOT NULL,
    script_location TEXT NOT NULL,
    python_version TEXT NOT NULL,
    glue_version TEXT NOT NULL,
    worker_type TEXT NOT NULL,
    execution_class TEXT NOT NULL,
    security_configuration TEXT NOT NULL,
    previous_run_id TEXT NOT NULL,
    trigger_name TEXT NOT NULL,
    workflow_name TEXT NOT NULL,
    workflow_run_id TEXT NOT NULL,
    timeout INTEGER NOT NULL,
    number_of_workers INTEGER NOT NULL,
    attempt INTEGER NOT NULL,
    max_capacity REAL NOT NULL,
    arguments TEXT NOT NULL,
    started_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    completed_at INTEGER NOT NULL,
    next_attempt INTEGER NOT NULL,
    version INTEGER NOT NULL,
    launch_attempted INTEGER NOT NULL,
    cleanup_pending INTEGER NOT NULL,
    published INTEGER NOT NULL,
    error TEXT NOT NULL,
    output TEXT NOT NULL,
    s3_encryption_mode TEXT NOT NULL,
    s3_kms_key TEXT NOT NULL,
    logs_kms_key TEXT NOT NULL,
    max_retries INTEGER NOT NULL,
    run_arguments TEXT NOT NULL,
    retry_pending INTEGER NOT NULL,
    metrics_published INTEGER NOT NULL,
    log_error TEXT NOT NULL,
    metrics_observed INTEGER NOT NULL,
    metrics_completed_tasks INTEGER NOT NULL,
    metrics_failed_tasks INTEGER NOT NULL,
    metrics_killed_tasks INTEGER NOT NULL,
    metrics_completed_stages INTEGER NOT NULL,
    metrics_bytes_read INTEGER NOT NULL,
    metrics_records_read INTEGER NOT NULL,
    error_output TEXT NOT NULL,
    execution_seconds INTEGER NOT NULL,
    PRIMARY KEY (partition, account_id, region, name, id)
);

CREATE TABLE glue_job_attempts (
    partition TEXT NOT NULL,
    account_id TEXT NOT NULL,
    region TEXT NOT NULL,
    name TEXT NOT NULL,
    id TEXT NOT NULL,
    attempt INTEGER NOT NULL,
    state TEXT NOT NULL,
    error TEXT NOT NULL,
    output TEXT NOT NULL,
    error_output TEXT NOT NULL,
    started_at INTEGER NOT NULL,
    completed_at INTEGER NOT NULL,
    PRIMARY KEY (partition, account_id, region, name, id, attempt)
);

CREATE INDEX glue_job_runs_pending ON glue_job_runs(next_attempt) WHERE state IN ('STARTING','RUNNING','STOPPING') OR cleanup_pending = 1 OR published = 0;
