CREATE TABLE glue_crawlers (
    partition TEXT NOT NULL,
    account_id TEXT NOT NULL,
    region TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    database_name TEXT NOT NULL,
    description TEXT,
    table_prefix TEXT,
    configuration TEXT,
    security_configuration TEXT,
    targets TEXT NOT NULL,
    classifiers TEXT NOT NULL,
    schema_change_policy TEXT NOT NULL,
    recrawl_policy TEXT NOT NULL,
    lake_formation TEXT NOT NULL,
    lineage TEXT NOT NULL,
    schedule TEXT NOT NULL,
    tags TEXT NOT NULL,
    state TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    last_crawl TEXT NOT NULL,
    elapsed_ms INTEGER NOT NULL,
    run_id TEXT NOT NULL,
    next_scheduled INTEGER,
    PRIMARY KEY (partition, account_id, region, name)
);
CREATE TABLE glue_crawler_runs (
    id TEXT NOT NULL PRIMARY KEY,
    partition TEXT NOT NULL,
    account_id TEXT NOT NULL,
    region TEXT NOT NULL,
    crawler_name TEXT NOT NULL,
    state TEXT NOT NULL,
    phase TEXT NOT NULL,
    started_at INTEGER NOT NULL,
    completed_at INTEGER,
    error_message TEXT NOT NULL,
    tables_created INTEGER NOT NULL,
    tables_updated INTEGER NOT NULL,
    partitions_created INTEGER NOT NULL,
    parent_event_id TEXT NOT NULL,
    trigger_name TEXT NOT NULL,
    workflow_name TEXT NOT NULL,
    workflow_run_id TEXT NOT NULL,
    FOREIGN KEY (partition, account_id, region, crawler_name) REFERENCES glue_crawlers(partition, account_id, region, name) ON DELETE CASCADE
);
CREATE INDEX glue_crawler_runs_pending ON glue_crawler_runs(state, started_at, id);
CREATE INDEX glue_crawler_runs_history ON glue_crawler_runs(partition, account_id, region, crawler_name, started_at DESC, id DESC);
CREATE TABLE glue_classifiers (
    partition TEXT NOT NULL,
    account_id TEXT NOT NULL,
    region TEXT NOT NULL,
    name TEXT NOT NULL,
    kind TEXT NOT NULL,
    classification TEXT,
    grok_pattern TEXT,
    custom_patterns TEXT,
    json_path TEXT,
    row_tag TEXT,
    delimiter TEXT,
    quote_symbol TEXT,
    contains_header TEXT,
    header TEXT NOT NULL,
    allow_single_column INTEGER,
    disable_value_trimming INTEGER,
    custom_datatype_configured INTEGER,
    custom_datatypes TEXT NOT NULL,
    serde TEXT,
    version INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    PRIMARY KEY (partition, account_id, region, name)
);
CREATE TABLE glue_connections (
    partition TEXT NOT NULL,
    account_id TEXT NOT NULL,
    region TEXT NOT NULL,
    name TEXT NOT NULL,
    connection_type TEXT NOT NULL,
    description TEXT,
    properties TEXT NOT NULL,
    match_criteria TEXT NOT NULL,
    physical_requirements TEXT NOT NULL,
    athena_properties TEXT NOT NULL,
    spark_properties TEXT NOT NULL,
    python_properties TEXT NOT NULL,
    tags TEXT NOT NULL,
    password TEXT NOT NULL,
    password_cipher BLOB NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    last_updated_by TEXT NOT NULL,
    PRIMARY KEY (partition, account_id, region, name)
);
CREATE TABLE glue_connection_encryption (
    partition TEXT NOT NULL,
    account_id TEXT NOT NULL,
    region TEXT NOT NULL,
    key_id TEXT NOT NULL,
    return_encrypted INTEGER NOT NULL,
    PRIMARY KEY (partition, account_id, region)
);
