-- EKS native runtime configuration, managed capacity and scoped workload intent.
ALTER TABLE eks_cluster ADD COLUMN enabled_log_types TEXT NOT NULL DEFAULT '[]';
ALTER TABLE eks_update ADD COLUMN enabled_log_types TEXT NOT NULL DEFAULT 'null';
ALTER TABLE eks_update ADD COLUMN resource_type TEXT NOT NULL DEFAULT '';
ALTER TABLE eks_update ADD COLUMN resource_name TEXT NOT NULL DEFAULT '';
ALTER TABLE eks_update ADD COLUMN params_json TEXT NOT NULL DEFAULT '[]';
CREATE TABLE eks_addons (
 partition TEXT NOT NULL, account_id TEXT NOT NULL, region TEXT NOT NULL, name TEXT NOT NULL,
 addon_name TEXT NOT NULL, id TEXT NOT NULL, version TEXT NOT NULL, applied_version TEXT NOT NULL,
 configuration TEXT NOT NULL, applied_configuration TEXT NOT NULL,
 status TEXT NOT NULL, operation TEXT NOT NULL, error TEXT NOT NULL, error_code TEXT NOT NULL,
 resolve_conflicts TEXT NOT NULL, update_id TEXT NOT NULL,
 client_token TEXT NOT NULL, request_hash TEXT NOT NULL, tags TEXT NOT NULL,
 created INTEGER NOT NULL, modified INTEGER NOT NULL, due INTEGER NOT NULL,
 generation INTEGER NOT NULL, preserve INTEGER NOT NULL,
 PRIMARY KEY(partition,account_id,region,name,addon_name),
 FOREIGN KEY(partition,account_id,region,name) REFERENCES eks_cluster(partition,account_id,region,name) ON DELETE CASCADE
);
CREATE TABLE eks_fargate_profiles (
 partition TEXT NOT NULL, account_id TEXT NOT NULL, region TEXT NOT NULL, name TEXT NOT NULL,
 profile_name TEXT NOT NULL, id TEXT NOT NULL, role_arn TEXT NOT NULL, role_id TEXT NOT NULL,
 status TEXT NOT NULL, operation TEXT NOT NULL, error TEXT NOT NULL,
 client_token TEXT NOT NULL, request_hash TEXT NOT NULL,
 selectors TEXT NOT NULL, subnets TEXT NOT NULL, tags TEXT NOT NULL,
 created INTEGER NOT NULL, due INTEGER NOT NULL, generation INTEGER NOT NULL,
 PRIMARY KEY(partition,account_id,region,name,profile_name),
 FOREIGN KEY(partition,account_id,region,name) REFERENCES eks_cluster(partition,account_id,region,name) ON DELETE CASCADE
);
CREATE TABLE eks_nodegroup (
 partition TEXT NOT NULL,
 account_id TEXT NOT NULL,
 region TEXT NOT NULL,
 cluster_name TEXT NOT NULL,
 name TEXT NOT NULL,
 id TEXT NOT NULL,
 cluster_id TEXT NOT NULL,
 status TEXT NOT NULL,
 operation TEXT NOT NULL,
 error_code TEXT NOT NULL,
 error_message TEXT NOT NULL,
 node_role_arn TEXT NOT NULL,
 node_role_id TEXT NOT NULL,
 version TEXT NOT NULL,
 release_version TEXT NOT NULL,
 ami_type TEXT NOT NULL,
 capacity_type TEXT NOT NULL,
 image_id TEXT NOT NULL,
 launch_template_id TEXT NOT NULL,
 launch_template_name TEXT NOT NULL,
 launch_template_version TEXT NOT NULL,
 managed_template_id TEXT NOT NULL,
 managed_template_version TEXT NOT NULL,
 group_name TEXT NOT NULL,
 group_arn TEXT NOT NULL,
 profile_name TEXT NOT NULL,
 client_token TEXT NOT NULL,
 request_hash TEXT NOT NULL,
 update_id TEXT NOT NULL,
 generation INTEGER NOT NULL,
 template_generation INTEGER NOT NULL,
 applied_template_generation INTEGER NOT NULL,
 min_size INTEGER NOT NULL,
 max_size INTEGER NOT NULL,
 desired_size INTEGER NOT NULL,
 disk_size INTEGER NOT NULL,
 max_unavailable INTEGER NOT NULL,
 max_unavailable_percentage INTEGER NOT NULL,
 update_strategy TEXT NOT NULL,
 force INTEGER NOT NULL,
 created INTEGER NOT NULL,
 modified INTEGER NOT NULL,
 due INTEGER NOT NULL,
 deadline INTEGER NOT NULL,
 instance_types TEXT NOT NULL,
 subnets TEXT NOT NULL,
 labels TEXT NOT NULL,
 tags TEXT NOT NULL,
 taints TEXT NOT NULL,
 PRIMARY KEY (partition, account_id, region, cluster_name, name)
);
CREATE TABLE eks_nodegroup_update (
 partition TEXT NOT NULL,
 account_id TEXT NOT NULL,
 region TEXT NOT NULL,
 cluster_name TEXT NOT NULL,
 name TEXT NOT NULL,
 id TEXT NOT NULL,
 type TEXT NOT NULL,
 status TEXT NOT NULL,
 client_token TEXT NOT NULL,
 request_hash TEXT NOT NULL,
 error_code TEXT NOT NULL,
 error_message TEXT NOT NULL,
 created INTEGER NOT NULL,
 version TEXT NOT NULL,
 release_version TEXT NOT NULL,
 launch_template_version TEXT NOT NULL,
 params_json TEXT NOT NULL,
 PRIMARY KEY (partition, account_id, region, cluster_name, name, id),
 FOREIGN KEY (partition, account_id, region, cluster_name, name) REFERENCES eks_nodegroup (partition, account_id, region, cluster_name, name) ON DELETE CASCADE
);
CREATE TABLE eks_nodegroup_worker (
 partition TEXT NOT NULL,
 account_id TEXT NOT NULL,
 region TEXT NOT NULL,
 cluster_name TEXT NOT NULL,
 name TEXT NOT NULL,
 instance_id TEXT NOT NULL,
 private_ip TEXT NOT NULL,
 availability_zone TEXT NOT NULL,
 template_id TEXT NOT NULL,
 template_version TEXT NOT NULL,
 lifecycle_state TEXT NOT NULL,
 node_name TEXT NOT NULL,
 node_uid TEXT NOT NULL,
 kubelet_version TEXT NOT NULL,
 ready INTEGER NOT NULL,
 unschedulable INTEGER NOT NULL,
 bootstrap_started INTEGER NOT NULL,
 drain_started INTEGER NOT NULL,
 drain_completed INTEGER NOT NULL,
 PRIMARY KEY (partition, account_id, region, cluster_name, name, instance_id),
 FOREIGN KEY (partition, account_id, region, cluster_name, name) REFERENCES eks_nodegroup (partition, account_id, region, cluster_name, name) ON DELETE CASCADE
);
CREATE TABLE eks_pod_identity_association (
 partition TEXT NOT NULL,
 account_id TEXT NOT NULL,
 region TEXT NOT NULL,
 name TEXT NOT NULL,
 id TEXT NOT NULL,
 cluster_id TEXT NOT NULL,
 namespace TEXT NOT NULL,
 service_account TEXT NOT NULL,
 role_arn TEXT NOT NULL,
 role_id TEXT NOT NULL,
 target_role_arn TEXT NOT NULL,
 target_role_id TEXT NOT NULL,
 external_id TEXT NOT NULL,
 owner_arn TEXT NOT NULL,
 policy TEXT NOT NULL,
 disable_session_tags INTEGER NOT NULL,
 tags TEXT NOT NULL,
 created INTEGER NOT NULL,
 modified INTEGER NOT NULL,
 client_token TEXT NOT NULL,
 PRIMARY KEY (partition,account_id,region,name,id),
 UNIQUE (partition,account_id,region,name,namespace,service_account)
);
