// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const deleteBackupConfiguration = `-- name: DeleteBackupConfiguration :exec
DELETE FROM firehose_configurations WHERE parent_configuration_id = ?
`

func (q *Queries) DeleteBackupConfiguration(ctx context.Context, parentConfigurationID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteBackupConfiguration, parentConfigurationID)
	return err
}

const deleteBuffer = `-- name: DeleteBuffer :exec
DELETE FROM firehose_buffers WHERE id = ?
`

func (q *Queries) DeleteBuffer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBuffer, id)
	return err
}

const deleteConfiguration = `-- name: DeleteConfiguration :exec
DELETE FROM firehose_configurations WHERE id = ?
`

func (q *Queries) DeleteConfiguration(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConfiguration, id)
	return err
}

const deleteMetricPublication = `-- name: DeleteMetricPublication :exec
DELETE FROM firehose_metric_samples WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4 AND minute = ?5
`

type DeleteMetricPublicationParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
	Minute    time.Time
}

func (q *Queries) DeleteMetricPublication(ctx context.Context, arg DeleteMetricPublicationParams) error {
	_, err := q.db.ExecContext(ctx, deleteMetricPublication,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.Minute,
	)
	return err
}

const deleteProcessors = `-- name: DeleteProcessors :exec
DELETE FROM firehose_processors WHERE configuration_id = ?
`

func (q *Queries) DeleteProcessors(ctx context.Context, configurationID string) error {
	_, err := q.db.ExecContext(ctx, deleteProcessors, configurationID)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM firehose_sources WHERE stream_id = ?
`

func (q *Queries) DeleteSource(ctx context.Context, streamID string) error {
	_, err := q.db.ExecContext(ctx, deleteSource, streamID)
	return err
}

const deleteStream = `-- name: DeleteStream :exec
DELETE FROM firehose_streams WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4
`

type DeleteStreamParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

func (q *Queries) DeleteStream(ctx context.Context, arg DeleteStreamParams) error {
	_, err := q.db.ExecContext(ctx, deleteStream,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	return err
}

const deleteTags = `-- name: DeleteTags :exec
DELETE FROM firehose_tags WHERE stream_id = ?
`

func (q *Queries) DeleteTags(ctx context.Context, streamID string) error {
	_, err := q.db.ExecContext(ctx, deleteTags, streamID)
	return err
}

const getBackupConfiguration = `-- name: GetBackupConfiguration :one
SELECT id, stream_id, buffer_id, bucket_arn, role_arn, prefix, error_output_prefix, compression_format, custom_time_zone, file_extension, backup_mode, buffering_present, interval_seconds, size_mbs, logging_present, logging_enabled, log_group, log_stream, encryption_present, no_encryption, processing_present, processing_enabled, processors_present, parent_configuration_id, kms_key_arn FROM firehose_configurations WHERE parent_configuration_id = ?
`

func (q *Queries) GetBackupConfiguration(ctx context.Context, parentConfigurationID sql.NullString) (FirehoseConfiguration, error) {
	row := q.db.QueryRowContext(ctx, getBackupConfiguration, parentConfigurationID)
	var i FirehoseConfiguration
	err := row.Scan(
		&i.ID,
		&i.StreamID,
		&i.BufferID,
		&i.BucketArn,
		&i.RoleArn,
		&i.Prefix,
		&i.ErrorOutputPrefix,
		&i.CompressionFormat,
		&i.CustomTimeZone,
		&i.FileExtension,
		&i.BackupMode,
		&i.BufferingPresent,
		&i.IntervalSeconds,
		&i.SizeMbs,
		&i.LoggingPresent,
		&i.LoggingEnabled,
		&i.LogGroup,
		&i.LogStream,
		&i.EncryptionPresent,
		&i.NoEncryption,
		&i.ProcessingPresent,
		&i.ProcessingEnabled,
		&i.ProcessorsPresent,
		&i.ParentConfigurationID,
		&i.KmsKeyArn,
	)
	return i, err
}

const getBuffer = `-- name: GetBuffer :one
SELECT id, stream_id, "partition", account_id, region, name, created, due, count, bytes, parent_event_id, object_key, stream_version, kind FROM firehose_buffers WHERE id = ?
`

func (q *Queries) GetBuffer(ctx context.Context, id string) (FirehoseBuffer, error) {
	row := q.db.QueryRowContext(ctx, getBuffer, id)
	var i FirehoseBuffer
	err := row.Scan(
		&i.ID,
		&i.StreamID,
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.Created,
		&i.Due,
		&i.Count,
		&i.Bytes,
		&i.ParentEventID,
		&i.ObjectKey,
		&i.StreamVersion,
		&i.Kind,
	)
	return i, err
}

const getConfiguration = `-- name: GetConfiguration :one
SELECT id, stream_id, buffer_id, bucket_arn, role_arn, prefix, error_output_prefix, compression_format, custom_time_zone, file_extension, backup_mode, buffering_present, interval_seconds, size_mbs, logging_present, logging_enabled, log_group, log_stream, encryption_present, no_encryption, processing_present, processing_enabled, processors_present, parent_configuration_id, kms_key_arn FROM firehose_configurations WHERE id = ?
`

func (q *Queries) GetConfiguration(ctx context.Context, id string) (FirehoseConfiguration, error) {
	row := q.db.QueryRowContext(ctx, getConfiguration, id)
	var i FirehoseConfiguration
	err := row.Scan(
		&i.ID,
		&i.StreamID,
		&i.BufferID,
		&i.BucketArn,
		&i.RoleArn,
		&i.Prefix,
		&i.ErrorOutputPrefix,
		&i.CompressionFormat,
		&i.CustomTimeZone,
		&i.FileExtension,
		&i.BackupMode,
		&i.BufferingPresent,
		&i.IntervalSeconds,
		&i.SizeMbs,
		&i.LoggingPresent,
		&i.LoggingEnabled,
		&i.LogGroup,
		&i.LogStream,
		&i.EncryptionPresent,
		&i.NoEncryption,
		&i.ProcessingPresent,
		&i.ProcessingEnabled,
		&i.ProcessorsPresent,
		&i.ParentConfigurationID,
		&i.KmsKeyArn,
	)
	return i, err
}

const getProcessing = `-- name: GetProcessing :one
SELECT buffer_id, state, attempts, due FROM firehose_processing WHERE buffer_id = ?
`

func (q *Queries) GetProcessing(ctx context.Context, bufferID string) (FirehoseProcessing, error) {
	row := q.db.QueryRowContext(ctx, getProcessing, bufferID)
	var i FirehoseProcessing
	err := row.Scan(
		&i.BufferID,
		&i.State,
		&i.Attempts,
		&i.Due,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT stream_id, arn, role_arn, created, delivery_start, due, retention_hours FROM firehose_sources WHERE stream_id = ?
`

func (q *Queries) GetSource(ctx context.Context, streamID string) (FirehoseSource, error) {
	row := q.db.QueryRowContext(ctx, getSource, streamID)
	var i FirehoseSource
	err := row.Scan(
		&i.StreamID,
		&i.Arn,
		&i.RoleArn,
		&i.Created,
		&i.DeliveryStart,
		&i.Due,
		&i.RetentionHours,
	)
	return i, err
}

const getStream = `-- name: GetStream :one
SELECT id, "partition", account_id, region, name, status, version, created, updated, lifecycle_due, buffer_id, tags_present, cfn_owner FROM firehose_streams WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4
`

type GetStreamParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

func (q *Queries) GetStream(ctx context.Context, arg GetStreamParams) (FirehoseStream, error) {
	row := q.db.QueryRowContext(ctx, getStream,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	var i FirehoseStream
	err := row.Scan(
		&i.ID,
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.Created,
		&i.Updated,
		&i.LifecycleDue,
		&i.BufferID,
		&i.TagsPresent,
		&i.CfnOwner,
	)
	return i, err
}

const getStreamByID = `-- name: GetStreamByID :one
SELECT id, "partition", account_id, region, name, status, version, created, updated, lifecycle_due, buffer_id, tags_present, cfn_owner FROM firehose_streams WHERE id = ?
`

func (q *Queries) GetStreamByID(ctx context.Context, id string) (FirehoseStream, error) {
	row := q.db.QueryRowContext(ctx, getStreamByID, id)
	var i FirehoseStream
	err := row.Scan(
		&i.ID,
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.Created,
		&i.Updated,
		&i.LifecycleDue,
		&i.BufferID,
		&i.TagsPresent,
		&i.CfnOwner,
	)
	return i, err
}

const inFlightProcessing = `-- name: InFlightProcessing :many
SELECT buffer_id, state, attempts, due FROM firehose_processing WHERE state = 'in-flight' ORDER BY buffer_id
`

func (q *Queries) InFlightProcessing(ctx context.Context) ([]FirehoseProcessing, error) {
	rows, err := q.db.QueryContext(ctx, inFlightProcessing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirehoseProcessing{}
	for rows.Next() {
		var i FirehoseProcessing
		if err := rows.Scan(
			&i.BufferID,
			&i.State,
			&i.Attempts,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckpoints = `-- name: ListCheckpoints :many
SELECT stream_id, shard_id, sequence, closed FROM firehose_checkpoints WHERE stream_id = ? ORDER BY shard_id
`

func (q *Queries) ListCheckpoints(ctx context.Context, streamID string) ([]FirehoseCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listCheckpoints, streamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirehoseCheckpoint{}
	for rows.Next() {
		var i FirehoseCheckpoint
		if err := rows.Scan(
			&i.StreamID,
			&i.ShardID,
			&i.Sequence,
			&i.Closed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricSamples = `-- name: ListMetricSamples :many
SELECT metric_name, value, sample_count FROM firehose_metric_samples WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4 AND minute = ?5 ORDER BY metric_name, value
`

type ListMetricSamplesParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
	Minute    time.Time
}

type ListMetricSamplesRow struct {
	MetricName  string
	Value       float64
	SampleCount int64
}

func (q *Queries) ListMetricSamples(ctx context.Context, arg ListMetricSamplesParams) ([]ListMetricSamplesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMetricSamples,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.Minute,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMetricSamplesRow{}
	for rows.Next() {
		var i ListMetricSamplesRow
		if err := rows.Scan(&i.MetricName, &i.Value, &i.SampleCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessorParameters = `-- name: ListProcessorParameters :many
SELECT configuration_id, processor_position, position, name, value FROM firehose_processor_parameters WHERE configuration_id = ? ORDER BY processor_position, position
`

func (q *Queries) ListProcessorParameters(ctx context.Context, configurationID string) ([]FirehoseProcessorParameter, error) {
	rows, err := q.db.QueryContext(ctx, listProcessorParameters, configurationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirehoseProcessorParameter{}
	for rows.Next() {
		var i FirehoseProcessorParameter
		if err := rows.Scan(
			&i.ConfigurationID,
			&i.ProcessorPosition,
			&i.Position,
			&i.Name,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessors = `-- name: ListProcessors :many
SELECT configuration_id, position, type, parameters_present FROM firehose_processors WHERE configuration_id = ? ORDER BY position
`

func (q *Queries) ListProcessors(ctx context.Context, configurationID string) ([]FirehoseProcessor, error) {
	rows, err := q.db.QueryContext(ctx, listProcessors, configurationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirehoseProcessor{}
	for rows.Next() {
		var i FirehoseProcessor
		if err := rows.Scan(
			&i.ConfigurationID,
			&i.Position,
			&i.Type,
			&i.ParametersPresent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
SELECT buffer_id, position, data, arrived, original_bytes, kinesis_shard_id, kinesis_partition_key, kinesis_sequence_number, kinesis_subsequence_number FROM firehose_records WHERE buffer_id = ? ORDER BY position
`

func (q *Queries) ListRecords(ctx context.Context, bufferID string) ([]FirehoseRecord, error) {
	rows, err := q.db.QueryContext(ctx, listRecords, bufferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirehoseRecord{}
	for rows.Next() {
		var i FirehoseRecord
		if err := rows.Scan(
			&i.BufferID,
			&i.Position,
			&i.Data,
			&i.Arrived,
			&i.OriginalBytes,
			&i.KinesisShardID,
			&i.KinesisPartitionKey,
			&i.KinesisSequenceNumber,
			&i.KinesisSubsequenceNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreams = `-- name: ListStreams :many
SELECT id, "partition", account_id, region, name, status, version, created, updated, lifecycle_due, buffer_id, tags_present, cfn_owner FROM firehose_streams WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name > ?4 AND (?5 = '' OR CASE WHEN EXISTS (SELECT 1 FROM firehose_sources WHERE stream_id = firehose_streams.id) THEN 'KinesisStreamAsSource' ELSE 'DirectPut' END = ?5) ORDER BY name LIMIT ?6
`

type ListStreamsParams struct {
	Partition  string
	AccountID  string
	Region     string
	AfterName  string
	StreamType interface{}
	RowLimit   int64
}

func (q *Queries) ListStreams(ctx context.Context, arg ListStreamsParams) ([]FirehoseStream, error) {
	rows, err := q.db.QueryContext(ctx, listStreams,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.AfterName,
		arg.StreamType,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirehoseStream{}
	for rows.Next() {
		var i FirehoseStream
		if err := rows.Scan(
			&i.ID,
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.Created,
			&i.Updated,
			&i.LifecycleDue,
			&i.BufferID,
			&i.TagsPresent,
			&i.CfnOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT stream_id, "key", value FROM firehose_tags WHERE stream_id = ? ORDER BY key
`

func (q *Queries) ListTags(ctx context.Context, streamID string) ([]FirehoseTag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, streamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirehoseTag{}
	for rows.Next() {
		var i FirehoseTag
		if err := rows.Scan(&i.StreamID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDelivery = `-- name: NextDelivery :one
SELECT id, stream_id, "partition", account_id, region, name, created, due, count, bytes, parent_event_id, object_key, stream_version, kind FROM firehose_buffers WHERE NOT EXISTS (SELECT 1 FROM firehose_processing WHERE buffer_id = firehose_buffers.id) ORDER BY due, id LIMIT 1
`

func (q *Queries) NextDelivery(ctx context.Context) (FirehoseBuffer, error) {
	row := q.db.QueryRowContext(ctx, nextDelivery)
	var i FirehoseBuffer
	err := row.Scan(
		&i.ID,
		&i.StreamID,
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.Created,
		&i.Due,
		&i.Count,
		&i.Bytes,
		&i.ParentEventID,
		&i.ObjectKey,
		&i.StreamVersion,
		&i.Kind,
	)
	return i, err
}

const nextLifecycle = `-- name: NextLifecycle :one
SELECT id, "partition", account_id, region, name, status, version, created, updated, lifecycle_due, buffer_id, tags_present, cfn_owner FROM firehose_streams WHERE status IN ('CREATING', 'DELETING') ORDER BY lifecycle_due, id LIMIT 1
`

func (q *Queries) NextLifecycle(ctx context.Context) (FirehoseStream, error) {
	row := q.db.QueryRowContext(ctx, nextLifecycle)
	var i FirehoseStream
	err := row.Scan(
		&i.ID,
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.Created,
		&i.Updated,
		&i.LifecycleDue,
		&i.BufferID,
		&i.TagsPresent,
		&i.CfnOwner,
	)
	return i, err
}

const nextMetricPublication = `-- name: NextMetricPublication :one
SELECT partition, account_id, region, name, minute FROM firehose_metric_samples ORDER BY minute, partition, account_id, region, name LIMIT 1
`

type NextMetricPublicationRow struct {
	Partition string
	AccountID string
	Region    string
	Name      string
	Minute    time.Time
}

func (q *Queries) NextMetricPublication(ctx context.Context) (NextMetricPublicationRow, error) {
	row := q.db.QueryRowContext(ctx, nextMetricPublication)
	var i NextMetricPublicationRow
	err := row.Scan(
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.Minute,
	)
	return i, err
}

const nextProcessing = `-- name: NextProcessing :one
SELECT buffer_id, state, attempts, due FROM firehose_processing WHERE state = 'queued' ORDER BY due, buffer_id LIMIT 1
`

func (q *Queries) NextProcessing(ctx context.Context) (FirehoseProcessing, error) {
	row := q.db.QueryRowContext(ctx, nextProcessing)
	var i FirehoseProcessing
	err := row.Scan(
		&i.BufferID,
		&i.State,
		&i.Attempts,
		&i.Due,
	)
	return i, err
}

const nextSource = `-- name: NextSource :one
SELECT firehose_streams.id, firehose_streams."partition", firehose_streams.account_id, firehose_streams.region, firehose_streams.name, firehose_streams.status, firehose_streams.version, firehose_streams.created, firehose_streams.updated, firehose_streams.lifecycle_due, firehose_streams.buffer_id, firehose_streams.tags_present, firehose_streams.cfn_owner FROM firehose_streams JOIN firehose_sources ON firehose_sources.stream_id = firehose_streams.id WHERE status = 'ACTIVE' ORDER BY firehose_sources.due, firehose_streams.id LIMIT 1
`

func (q *Queries) NextSource(ctx context.Context) (FirehoseStream, error) {
	row := q.db.QueryRowContext(ctx, nextSource)
	var i FirehoseStream
	err := row.Scan(
		&i.ID,
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.Created,
		&i.Updated,
		&i.LifecycleDue,
		&i.BufferID,
		&i.TagsPresent,
		&i.CfnOwner,
	)
	return i, err
}

const openOutputBuffer = `-- name: OpenOutputBuffer :one
SELECT id, stream_id, "partition", account_id, region, name, created, due, count, bytes, parent_event_id, object_key, stream_version, kind FROM firehose_buffers WHERE stream_id = ?1 AND stream_version = ?2 AND kind = ?3 AND object_key = '' ORDER BY created, id LIMIT 1
`

type OpenOutputBufferParams struct {
	StreamID      string
	StreamVersion int64
	Kind          string
}

func (q *Queries) OpenOutputBuffer(ctx context.Context, arg OpenOutputBufferParams) (FirehoseBuffer, error) {
	row := q.db.QueryRowContext(ctx, openOutputBuffer, arg.StreamID, arg.StreamVersion, arg.Kind)
	var i FirehoseBuffer
	err := row.Scan(
		&i.ID,
		&i.StreamID,
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.Created,
		&i.Due,
		&i.Count,
		&i.Bytes,
		&i.ParentEventID,
		&i.ObjectKey,
		&i.StreamVersion,
		&i.Kind,
	)
	return i, err
}

const putBuffer = `-- name: PutBuffer :exec
INSERT INTO firehose_buffers (id, stream_id, partition, account_id, region, name, created, due, count, bytes, parent_event_id, object_key, stream_version, kind)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14)
ON CONFLICT (id) DO UPDATE SET stream_id = excluded.stream_id, partition = excluded.partition, account_id = excluded.account_id, region = excluded.region, name = excluded.name, created = excluded.created, due = excluded.due, count = excluded.count, bytes = excluded.bytes, parent_event_id = excluded.parent_event_id, object_key = excluded.object_key, stream_version = excluded.stream_version, kind = excluded.kind
`

type PutBufferParams struct {
	ID            string
	StreamID      string
	Partition     string
	AccountID     string
	Region        string
	Name          string
	Created       time.Time
	Due           time.Time
	Count         int64
	Bytes         int64
	ParentEventID string
	ObjectKey     string
	StreamVersion int64
	Kind          string
}

func (q *Queries) PutBuffer(ctx context.Context, arg PutBufferParams) error {
	_, err := q.db.ExecContext(ctx, putBuffer,
		arg.ID,
		arg.StreamID,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.Created,
		arg.Due,
		arg.Count,
		arg.Bytes,
		arg.ParentEventID,
		arg.ObjectKey,
		arg.StreamVersion,
		arg.Kind,
	)
	return err
}

const putCheckpoint = `-- name: PutCheckpoint :exec
INSERT INTO firehose_checkpoints (stream_id, shard_id, sequence, closed)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (stream_id, shard_id) DO UPDATE SET sequence = excluded.sequence, closed = excluded.closed
`

type PutCheckpointParams struct {
	StreamID string
	ShardID  string
	Sequence string
	Closed   bool
}

func (q *Queries) PutCheckpoint(ctx context.Context, arg PutCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, putCheckpoint,
		arg.StreamID,
		arg.ShardID,
		arg.Sequence,
		arg.Closed,
	)
	return err
}

const putConfiguration = `-- name: PutConfiguration :exec
INSERT INTO firehose_configurations (id, stream_id, buffer_id, bucket_arn, role_arn, prefix, error_output_prefix, compression_format, custom_time_zone, file_extension, backup_mode, buffering_present, interval_seconds, size_mbs, logging_present, logging_enabled, log_group, log_stream, encryption_present, no_encryption, processing_present, processing_enabled, processors_present, parent_configuration_id, kms_key_arn)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25)
ON CONFLICT (id) DO UPDATE SET stream_id = excluded.stream_id, buffer_id = excluded.buffer_id, bucket_arn = excluded.bucket_arn, role_arn = excluded.role_arn, prefix = excluded.prefix, error_output_prefix = excluded.error_output_prefix, compression_format = excluded.compression_format, custom_time_zone = excluded.custom_time_zone, file_extension = excluded.file_extension, backup_mode = excluded.backup_mode, buffering_present = excluded.buffering_present, interval_seconds = excluded.interval_seconds, size_mbs = excluded.size_mbs, logging_present = excluded.logging_present, logging_enabled = excluded.logging_enabled, log_group = excluded.log_group, log_stream = excluded.log_stream, encryption_present = excluded.encryption_present, no_encryption = excluded.no_encryption, processing_present = excluded.processing_present, processing_enabled = excluded.processing_enabled, processors_present = excluded.processors_present, parent_configuration_id = excluded.parent_configuration_id, kms_key_arn = excluded.kms_key_arn
`

type PutConfigurationParams struct {
	ID                    string
	StreamID              string
	BufferID              sql.NullString
	BucketArn             sql.NullString
	RoleArn               sql.NullString
	Prefix                sql.NullString
	ErrorOutputPrefix     sql.NullString
	CompressionFormat     sql.NullString
	CustomTimeZone        sql.NullString
	FileExtension         sql.NullString
	BackupMode            sql.NullString
	BufferingPresent      bool
	IntervalSeconds       sql.NullInt64
	SizeMbs               sql.NullInt64
	LoggingPresent        bool
	LoggingEnabled        sql.NullBool
	LogGroup              sql.NullString
	LogStream             sql.NullString
	EncryptionPresent     bool
	NoEncryption          sql.NullString
	ProcessingPresent     bool
	ProcessingEnabled     sql.NullBool
	ProcessorsPresent     bool
	ParentConfigurationID sql.NullString
	KmsKeyArn             sql.NullString
}

func (q *Queries) PutConfiguration(ctx context.Context, arg PutConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, putConfiguration,
		arg.ID,
		arg.StreamID,
		arg.BufferID,
		arg.BucketArn,
		arg.RoleArn,
		arg.Prefix,
		arg.ErrorOutputPrefix,
		arg.CompressionFormat,
		arg.CustomTimeZone,
		arg.FileExtension,
		arg.BackupMode,
		arg.BufferingPresent,
		arg.IntervalSeconds,
		arg.SizeMbs,
		arg.LoggingPresent,
		arg.LoggingEnabled,
		arg.LogGroup,
		arg.LogStream,
		arg.EncryptionPresent,
		arg.NoEncryption,
		arg.ProcessingPresent,
		arg.ProcessingEnabled,
		arg.ProcessorsPresent,
		arg.ParentConfigurationID,
		arg.KmsKeyArn,
	)
	return err
}

const putMetricSample = `-- name: PutMetricSample :exec
INSERT INTO firehose_metric_samples (partition, account_id, region, name, minute, metric_name, value, sample_count)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
ON CONFLICT (partition, account_id, region, name, minute, metric_name, value) DO UPDATE SET sample_count = firehose_metric_samples.sample_count + excluded.sample_count
`

type PutMetricSampleParams struct {
	Partition   string
	AccountID   string
	Region      string
	Name        string
	Minute      time.Time
	MetricName  string
	Value       float64
	SampleCount int64
}

func (q *Queries) PutMetricSample(ctx context.Context, arg PutMetricSampleParams) error {
	_, err := q.db.ExecContext(ctx, putMetricSample,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.Minute,
		arg.MetricName,
		arg.Value,
		arg.SampleCount,
	)
	return err
}

const putProcessing = `-- name: PutProcessing :exec
INSERT INTO firehose_processing (buffer_id, state, attempts, due)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (buffer_id) DO UPDATE SET state = excluded.state, attempts = excluded.attempts, due = excluded.due
`

type PutProcessingParams struct {
	BufferID string
	State    string
	Attempts int64
	Due      time.Time
}

func (q *Queries) PutProcessing(ctx context.Context, arg PutProcessingParams) error {
	_, err := q.db.ExecContext(ctx, putProcessing,
		arg.BufferID,
		arg.State,
		arg.Attempts,
		arg.Due,
	)
	return err
}

const putProcessor = `-- name: PutProcessor :exec
INSERT INTO firehose_processors (configuration_id, position, type, parameters_present)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (configuration_id, position) DO UPDATE SET type = excluded.type, parameters_present = excluded.parameters_present
`

type PutProcessorParams struct {
	ConfigurationID   string
	Position          int64
	Type              sql.NullString
	ParametersPresent bool
}

func (q *Queries) PutProcessor(ctx context.Context, arg PutProcessorParams) error {
	_, err := q.db.ExecContext(ctx, putProcessor,
		arg.ConfigurationID,
		arg.Position,
		arg.Type,
		arg.ParametersPresent,
	)
	return err
}

const putProcessorParameter = `-- name: PutProcessorParameter :exec
INSERT INTO firehose_processor_parameters (configuration_id, processor_position, position, name, value)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (configuration_id, processor_position, position) DO UPDATE SET name = excluded.name, value = excluded.value
`

type PutProcessorParameterParams struct {
	ConfigurationID   string
	ProcessorPosition int64
	Position          int64
	Name              sql.NullString
	Value             sql.NullString
}

func (q *Queries) PutProcessorParameter(ctx context.Context, arg PutProcessorParameterParams) error {
	_, err := q.db.ExecContext(ctx, putProcessorParameter,
		arg.ConfigurationID,
		arg.ProcessorPosition,
		arg.Position,
		arg.Name,
		arg.Value,
	)
	return err
}

const putRecord = `-- name: PutRecord :exec
INSERT INTO firehose_records (buffer_id, position, data, arrived, original_bytes, kinesis_shard_id, kinesis_partition_key, kinesis_sequence_number, kinesis_subsequence_number)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
ON CONFLICT (buffer_id, position) DO UPDATE SET data = excluded.data, arrived = excluded.arrived, original_bytes = excluded.original_bytes, kinesis_shard_id = excluded.kinesis_shard_id, kinesis_partition_key = excluded.kinesis_partition_key, kinesis_sequence_number = excluded.kinesis_sequence_number, kinesis_subsequence_number = excluded.kinesis_subsequence_number
`

type PutRecordParams struct {
	BufferID                 string
	Position                 int64
	Data                     []byte
	Arrived                  time.Time
	OriginalBytes            int64
	KinesisShardID           sql.NullString
	KinesisPartitionKey      sql.NullString
	KinesisSequenceNumber    sql.NullString
	KinesisSubsequenceNumber int64
}

func (q *Queries) PutRecord(ctx context.Context, arg PutRecordParams) error {
	_, err := q.db.ExecContext(ctx, putRecord,
		arg.BufferID,
		arg.Position,
		arg.Data,
		arg.Arrived,
		arg.OriginalBytes,
		arg.KinesisShardID,
		arg.KinesisPartitionKey,
		arg.KinesisSequenceNumber,
		arg.KinesisSubsequenceNumber,
	)
	return err
}

const putSource = `-- name: PutSource :exec
INSERT INTO firehose_sources (stream_id, arn, role_arn, created, delivery_start, due, retention_hours)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT (stream_id) DO UPDATE SET arn = excluded.arn, role_arn = excluded.role_arn, created = excluded.created, delivery_start = excluded.delivery_start, due = excluded.due, retention_hours = excluded.retention_hours
`

type PutSourceParams struct {
	StreamID       string
	Arn            string
	RoleArn        string
	Created        time.Time
	DeliveryStart  time.Time
	Due            time.Time
	RetentionHours int64
}

func (q *Queries) PutSource(ctx context.Context, arg PutSourceParams) error {
	_, err := q.db.ExecContext(ctx, putSource,
		arg.StreamID,
		arg.Arn,
		arg.RoleArn,
		arg.Created,
		arg.DeliveryStart,
		arg.Due,
		arg.RetentionHours,
	)
	return err
}

const putStream = `-- name: PutStream :exec
INSERT INTO firehose_streams (id, partition, account_id, region, name, status, version, created, updated, lifecycle_due, buffer_id, tags_present, cfn_owner)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)
ON CONFLICT (id) DO UPDATE SET partition = excluded.partition, account_id = excluded.account_id, region = excluded.region, name = excluded.name, status = excluded.status, version = excluded.version, created = excluded.created, updated = excluded.updated, lifecycle_due = excluded.lifecycle_due, buffer_id = excluded.buffer_id, tags_present = excluded.tags_present
`

type PutStreamParams struct {
	ID           string
	Partition    string
	AccountID    string
	Region       string
	Name         string
	Status       string
	Version      int64
	Created      time.Time
	Updated      sql.NullTime
	LifecycleDue time.Time
	BufferID     string
	TagsPresent  bool
	CfnOwner     string
}

func (q *Queries) PutStream(ctx context.Context, arg PutStreamParams) error {
	_, err := q.db.ExecContext(ctx, putStream,
		arg.ID,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.Status,
		arg.Version,
		arg.Created,
		arg.Updated,
		arg.LifecycleDue,
		arg.BufferID,
		arg.TagsPresent,
		arg.CfnOwner,
	)
	return err
}

const putTag = `-- name: PutTag :exec
INSERT INTO firehose_tags (stream_id, key, value)
VALUES (?1, ?2, ?3)
ON CONFLICT (stream_id, key) DO UPDATE SET value = excluded.value
`

type PutTagParams struct {
	StreamID string
	Key      string
	Value    string
}

func (q *Queries) PutTag(ctx context.Context, arg PutTagParams) error {
	_, err := q.db.ExecContext(ctx, putTag, arg.StreamID, arg.Key, arg.Value)
	return err
}
