// Code generated by awsgen from AWS SDK for Go v2 Smithy models; DO NOT EDIT.
// Source: codegen/sdk-codegen/aws-models/cloudcontrol.json at 113bc91bf12edc3af1d3aba1c70be28494d54c2a; SHA256 ec2ed017988bfa9acdd47f24d164558416a9b5becc57c8088eb92799016ce1d9
package awscatalog

const (
	CloudControlOpCancelResourceRequest    OperationName = "CancelResourceRequest"
	CloudControlOpCreateResource           OperationName = "CreateResource"
	CloudControlOpDeleteResource           OperationName = "DeleteResource"
	CloudControlOpGetResource              OperationName = "GetResource"
	CloudControlOpGetResourceRequestStatus OperationName = "GetResourceRequestStatus"
	CloudControlOpListResourceRequests     OperationName = "ListResourceRequests"
	CloudControlOpListResources            OperationName = "ListResources"
	CloudControlOpUpdateResource           OperationName = "UpdateResource"
)
