// Command lambdaruntimegen generates Lambda extension and telemetry bindings from
// pinned AWS specifications. Generation is offline; source updates are explicit.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

type options struct {
	Source, Out string
	Check       bool
}

type source struct {
	File              string   `json:"file"`
	URL               string   `json:"url"`
	Revision          string   `json:"revision"`
	API               string   `json:"api"`
	Version           string   `json:"version"`
	Role              string   `json:"role"`
	Root              string   `json:"root"`
	Prefix            string   `json:"prefix"`
	DefinitionsRefFix bool     `json:"definitionsRefFix"`
	Limitations       []string `json:"limitations"`
}

type manifest struct {
	Sources []source `json:"sources"`
}

type delta struct {
	SchemaVersions        []string                     `json:"schemaVersions"`
	SchemaVersionRules    map[string]SchemaVersionRule `json:"schemaVersionRules"`
	Buffering             map[string]map[string]uint64 `json:"buffering"`
	NativeEventTypeValues []string                     `json:"nativeEventTypeValues"`
	Evidence              []RequestDeltaEvidence       `json:"evidence"`
}

type RequestDeltaEvidence struct{ Source, Revision, Description string }
type SchemaVersionRule struct {
	Required bool   `json:"required"`
	Default  string `json:"default"`
}

func main() {
	var o options
	flag.StringVar(&o.Source, "source", "compute/lambda/internal", "root containing extensionapi/source and telemetryapi/source")
	flag.StringVar(&o.Out, "out", "compute/lambda/internal", "root for generated extensionapi and telemetryapi packages")
	flag.BoolVar(&o.Check, "check", false, "check generated bytes without changing files")
	flag.Parse()
	if flag.NArg() != 0 {
		fmt.Fprintln(os.Stderr, "lambdaruntimegen: unexpected positional arguments")
		os.Exit(2)
	}
	if err := run(o); err != nil {
		fmt.Fprintln(os.Stderr, "lambdaruntimegen:", err)
		os.Exit(1)
	}
}

func readJSON(path string, target any) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	if err := decoder.Decode(new(any)); err != io.EOF {
		return fmt.Errorf("%s: expected one JSON document", path)
	}
	return nil
}

func run(o options) error {
	files := map[string][]byte{}
	for _, pkg := range []string{"extensionapi", "telemetryapi"} {
		dir := filepath.Join(o.Source, pkg, "source")
		var m manifest
		if err := readJSON(filepath.Join(dir, "sources.json"), &m); err != nil {
			return err
		}
		var docs []*document
		for _, input := range m.Sources {
			if input.File == "" || input.URL == "" || input.Revision == "" || input.Root == "" {
				return fmt.Errorf("%s: incomplete source metadata", dir)
			}
			if filepath.Base(input.File) != input.File {
				return fmt.Errorf("invalid source filename %q", input.File)
			}
			doc, err := loadDocument(filepath.Join(dir, input.File), input)
			if err != nil {
				return err
			}
			docs = append(docs, doc)
		}
		var d delta
		if pkg == "telemetryapi" {
			if err := readJSON(filepath.Join(dir, "request-deltas.json"), &d); err != nil {
				return err
			}
			if err := applyDeltas(docs, d); err != nil {
				return err
			}
		}
		types, err := renderTypes(pkg, docs)
		if err != nil {
			return err
		}
		metadata, err := renderMetadata(pkg, docs, d)
		if err != nil {
			return err
		}
		for name, data := range map[string][]byte{"types_generated.go": types, "metadata_generated.go": metadata} {
			formatted, err := format.Source(data)
			if err != nil {
				return fmt.Errorf("format %s/%s: %w", pkg, name, err)
			}
			files[filepath.Join(o.Out, pkg, name)] = formatted
		}
	}
	return writeFiles(files, o.Check)
}

func writeFiles(files map[string][]byte, check bool) error {
	var drift []string
	for _, path := range sortedKeys(files) {
		current, err := os.ReadFile(path)
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if bytes.Equal(current, files[path]) {
			continue
		}
		if check {
			drift = append(drift, path)
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := writeAtomic(path, files[path]); err != nil {
			return err
		}
	}
	if len(drift) > 0 {
		return fmt.Errorf("generated Lambda bindings differ: %s; run go run ./cmd/lambdaruntimegen", strings.Join(drift, ", "))
	}
	return nil
}

func writeAtomic(path string, data []byte) error {
	file, err := os.CreateTemp(filepath.Dir(path), ".lambdaruntimegen-*")
	if err != nil {
		return err
	}
	defer os.Remove(file.Name())
	if err := file.Chmod(0o644); err != nil {
		_ = file.Close()
		return err
	}
	if _, err := file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	return os.Rename(file.Name(), path)
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	return keys
}
