// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type ResourcegroupstaggingapiMembership struct {
	Partition string
	AccountID string
	Region    string
	Service   string
	Arn       string
}

type ResourcegroupstaggingapiReport struct {
	Partition      string
	AccountID      string
	Region         string
	Version        int64
	OrganizationID string
	Bucket         string
	ObjectKey      string
	Status         string
	ErrorMessage   string
	StartedAt      int64
	CompletedAt    int64
	Due            int64
	CallerJson     string
}
