// Code generated by awsgen from AWS SDK for Go v2 Smithy models; DO NOT EDIT.
package stepfunctions

// CloneActivityFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneActivityFailedEventDetails(value ActivityFailedEventDetails) ActivityFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneActivityScheduleFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneActivityScheduleFailedEventDetails(value ActivityScheduleFailedEventDetails) ActivityScheduleFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneActivityScheduledEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneActivityScheduledEventDetails(value ActivityScheduledEventDetails) ActivityScheduledEventDetails {
	if value.HeartbeatInSeconds != nil {
		cloned := *value.HeartbeatInSeconds
		value.HeartbeatInSeconds = &cloned
	}
	if value.Input != nil {
		cloned := *value.Input
		value.Input = &cloned
	}
	if value.InputDetails != nil {
		cloned := CloneHistoryEventExecutionDataDetails(*value.InputDetails)
		value.InputDetails = &cloned
	}
	if value.Resource != nil {
		cloned := *value.Resource
		value.Resource = &cloned
	}
	if value.TimeoutInSeconds != nil {
		cloned := *value.TimeoutInSeconds
		value.TimeoutInSeconds = &cloned
	}
	return value
}

// CloneActivityStartedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneActivityStartedEventDetails(value ActivityStartedEventDetails) ActivityStartedEventDetails {
	if value.WorkerName != nil {
		cloned := *value.WorkerName
		value.WorkerName = &cloned
	}
	return value
}

// CloneActivitySucceededEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneActivitySucceededEventDetails(value ActivitySucceededEventDetails) ActivitySucceededEventDetails {
	if value.Output != nil {
		cloned := *value.Output
		value.Output = &cloned
	}
	if value.OutputDetails != nil {
		cloned := CloneHistoryEventExecutionDataDetails(*value.OutputDetails)
		value.OutputDetails = &cloned
	}
	return value
}

// CloneActivityTimedOutEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneActivityTimedOutEventDetails(value ActivityTimedOutEventDetails) ActivityTimedOutEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneAssignedVariables returns an independent copy, preserving nil collections and pointer presence.
func CloneAssignedVariables(value AssignedVariables) AssignedVariables {
	if value == nil {
		return nil
	}
	out := make(AssignedVariables, len(value))
	for key, element := range value {
		out[key] = element
	}
	return out
}

// CloneAssignedVariablesDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneAssignedVariablesDetails(value AssignedVariablesDetails) AssignedVariablesDetails {
	if value.Truncated != nil {
		cloned := *value.Truncated
		value.Truncated = &cloned
	}
	return value
}

// CloneEvaluationFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneEvaluationFailedEventDetails(value EvaluationFailedEventDetails) EvaluationFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	if value.Location != nil {
		cloned := *value.Location
		value.Location = &cloned
	}
	if value.State != nil {
		cloned := *value.State
		value.State = &cloned
	}
	return value
}

// CloneExecutionAbortedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneExecutionAbortedEventDetails(value ExecutionAbortedEventDetails) ExecutionAbortedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneExecutionFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneExecutionFailedEventDetails(value ExecutionFailedEventDetails) ExecutionFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneExecutionRedrivenEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneExecutionRedrivenEventDetails(value ExecutionRedrivenEventDetails) ExecutionRedrivenEventDetails {
	if value.RedriveCount != nil {
		cloned := *value.RedriveCount
		value.RedriveCount = &cloned
	}
	return value
}

// CloneExecutionStartedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneExecutionStartedEventDetails(value ExecutionStartedEventDetails) ExecutionStartedEventDetails {
	if value.Input != nil {
		cloned := *value.Input
		value.Input = &cloned
	}
	if value.InputDetails != nil {
		cloned := CloneHistoryEventExecutionDataDetails(*value.InputDetails)
		value.InputDetails = &cloned
	}
	if value.RoleArn != nil {
		cloned := *value.RoleArn
		value.RoleArn = &cloned
	}
	if value.StateMachineAliasArn != nil {
		cloned := *value.StateMachineAliasArn
		value.StateMachineAliasArn = &cloned
	}
	if value.StateMachineVersionArn != nil {
		cloned := *value.StateMachineVersionArn
		value.StateMachineVersionArn = &cloned
	}
	return value
}

// CloneExecutionSucceededEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneExecutionSucceededEventDetails(value ExecutionSucceededEventDetails) ExecutionSucceededEventDetails {
	if value.Output != nil {
		cloned := *value.Output
		value.Output = &cloned
	}
	if value.OutputDetails != nil {
		cloned := CloneHistoryEventExecutionDataDetails(*value.OutputDetails)
		value.OutputDetails = &cloned
	}
	return value
}

// CloneExecutionTimedOutEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneExecutionTimedOutEventDetails(value ExecutionTimedOutEventDetails) ExecutionTimedOutEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneHistoryEvent returns an independent copy, preserving nil collections and pointer presence.
func CloneHistoryEvent(value HistoryEvent) HistoryEvent {
	if value.ActivityFailedEventDetails != nil {
		cloned := CloneActivityFailedEventDetails(*value.ActivityFailedEventDetails)
		value.ActivityFailedEventDetails = &cloned
	}
	if value.ActivityScheduleFailedEventDetails != nil {
		cloned := CloneActivityScheduleFailedEventDetails(*value.ActivityScheduleFailedEventDetails)
		value.ActivityScheduleFailedEventDetails = &cloned
	}
	if value.ActivityScheduledEventDetails != nil {
		cloned := CloneActivityScheduledEventDetails(*value.ActivityScheduledEventDetails)
		value.ActivityScheduledEventDetails = &cloned
	}
	if value.ActivityStartedEventDetails != nil {
		cloned := CloneActivityStartedEventDetails(*value.ActivityStartedEventDetails)
		value.ActivityStartedEventDetails = &cloned
	}
	if value.ActivitySucceededEventDetails != nil {
		cloned := CloneActivitySucceededEventDetails(*value.ActivitySucceededEventDetails)
		value.ActivitySucceededEventDetails = &cloned
	}
	if value.ActivityTimedOutEventDetails != nil {
		cloned := CloneActivityTimedOutEventDetails(*value.ActivityTimedOutEventDetails)
		value.ActivityTimedOutEventDetails = &cloned
	}
	if value.EvaluationFailedEventDetails != nil {
		cloned := CloneEvaluationFailedEventDetails(*value.EvaluationFailedEventDetails)
		value.EvaluationFailedEventDetails = &cloned
	}
	if value.ExecutionAbortedEventDetails != nil {
		cloned := CloneExecutionAbortedEventDetails(*value.ExecutionAbortedEventDetails)
		value.ExecutionAbortedEventDetails = &cloned
	}
	if value.ExecutionFailedEventDetails != nil {
		cloned := CloneExecutionFailedEventDetails(*value.ExecutionFailedEventDetails)
		value.ExecutionFailedEventDetails = &cloned
	}
	if value.ExecutionRedrivenEventDetails != nil {
		cloned := CloneExecutionRedrivenEventDetails(*value.ExecutionRedrivenEventDetails)
		value.ExecutionRedrivenEventDetails = &cloned
	}
	if value.ExecutionStartedEventDetails != nil {
		cloned := CloneExecutionStartedEventDetails(*value.ExecutionStartedEventDetails)
		value.ExecutionStartedEventDetails = &cloned
	}
	if value.ExecutionSucceededEventDetails != nil {
		cloned := CloneExecutionSucceededEventDetails(*value.ExecutionSucceededEventDetails)
		value.ExecutionSucceededEventDetails = &cloned
	}
	if value.ExecutionTimedOutEventDetails != nil {
		cloned := CloneExecutionTimedOutEventDetails(*value.ExecutionTimedOutEventDetails)
		value.ExecutionTimedOutEventDetails = &cloned
	}
	if value.Id != nil {
		cloned := *value.Id
		value.Id = &cloned
	}
	if value.LambdaFunctionFailedEventDetails != nil {
		cloned := CloneLambdaFunctionFailedEventDetails(*value.LambdaFunctionFailedEventDetails)
		value.LambdaFunctionFailedEventDetails = &cloned
	}
	if value.LambdaFunctionScheduleFailedEventDetails != nil {
		cloned := CloneLambdaFunctionScheduleFailedEventDetails(*value.LambdaFunctionScheduleFailedEventDetails)
		value.LambdaFunctionScheduleFailedEventDetails = &cloned
	}
	if value.LambdaFunctionScheduledEventDetails != nil {
		cloned := CloneLambdaFunctionScheduledEventDetails(*value.LambdaFunctionScheduledEventDetails)
		value.LambdaFunctionScheduledEventDetails = &cloned
	}
	if value.LambdaFunctionStartFailedEventDetails != nil {
		cloned := CloneLambdaFunctionStartFailedEventDetails(*value.LambdaFunctionStartFailedEventDetails)
		value.LambdaFunctionStartFailedEventDetails = &cloned
	}
	if value.LambdaFunctionSucceededEventDetails != nil {
		cloned := CloneLambdaFunctionSucceededEventDetails(*value.LambdaFunctionSucceededEventDetails)
		value.LambdaFunctionSucceededEventDetails = &cloned
	}
	if value.LambdaFunctionTimedOutEventDetails != nil {
		cloned := CloneLambdaFunctionTimedOutEventDetails(*value.LambdaFunctionTimedOutEventDetails)
		value.LambdaFunctionTimedOutEventDetails = &cloned
	}
	if value.MapIterationAbortedEventDetails != nil {
		cloned := CloneMapIterationEventDetails(*value.MapIterationAbortedEventDetails)
		value.MapIterationAbortedEventDetails = &cloned
	}
	if value.MapIterationFailedEventDetails != nil {
		cloned := CloneMapIterationEventDetails(*value.MapIterationFailedEventDetails)
		value.MapIterationFailedEventDetails = &cloned
	}
	if value.MapIterationStartedEventDetails != nil {
		cloned := CloneMapIterationEventDetails(*value.MapIterationStartedEventDetails)
		value.MapIterationStartedEventDetails = &cloned
	}
	if value.MapIterationSucceededEventDetails != nil {
		cloned := CloneMapIterationEventDetails(*value.MapIterationSucceededEventDetails)
		value.MapIterationSucceededEventDetails = &cloned
	}
	if value.MapRunFailedEventDetails != nil {
		cloned := CloneMapRunFailedEventDetails(*value.MapRunFailedEventDetails)
		value.MapRunFailedEventDetails = &cloned
	}
	if value.MapRunRedrivenEventDetails != nil {
		cloned := CloneMapRunRedrivenEventDetails(*value.MapRunRedrivenEventDetails)
		value.MapRunRedrivenEventDetails = &cloned
	}
	if value.MapRunStartedEventDetails != nil {
		cloned := CloneMapRunStartedEventDetails(*value.MapRunStartedEventDetails)
		value.MapRunStartedEventDetails = &cloned
	}
	if value.MapStateStartedEventDetails != nil {
		cloned := CloneMapStateStartedEventDetails(*value.MapStateStartedEventDetails)
		value.MapStateStartedEventDetails = &cloned
	}
	if value.PreviousEventId != nil {
		cloned := *value.PreviousEventId
		value.PreviousEventId = &cloned
	}
	if value.StateEnteredEventDetails != nil {
		cloned := CloneStateEnteredEventDetails(*value.StateEnteredEventDetails)
		value.StateEnteredEventDetails = &cloned
	}
	if value.StateExitedEventDetails != nil {
		cloned := CloneStateExitedEventDetails(*value.StateExitedEventDetails)
		value.StateExitedEventDetails = &cloned
	}
	if value.TaskFailedEventDetails != nil {
		cloned := CloneTaskFailedEventDetails(*value.TaskFailedEventDetails)
		value.TaskFailedEventDetails = &cloned
	}
	if value.TaskScheduledEventDetails != nil {
		cloned := CloneTaskScheduledEventDetails(*value.TaskScheduledEventDetails)
		value.TaskScheduledEventDetails = &cloned
	}
	if value.TaskStartFailedEventDetails != nil {
		cloned := CloneTaskStartFailedEventDetails(*value.TaskStartFailedEventDetails)
		value.TaskStartFailedEventDetails = &cloned
	}
	if value.TaskStartedEventDetails != nil {
		cloned := CloneTaskStartedEventDetails(*value.TaskStartedEventDetails)
		value.TaskStartedEventDetails = &cloned
	}
	if value.TaskSubmitFailedEventDetails != nil {
		cloned := CloneTaskSubmitFailedEventDetails(*value.TaskSubmitFailedEventDetails)
		value.TaskSubmitFailedEventDetails = &cloned
	}
	if value.TaskSubmittedEventDetails != nil {
		cloned := CloneTaskSubmittedEventDetails(*value.TaskSubmittedEventDetails)
		value.TaskSubmittedEventDetails = &cloned
	}
	if value.TaskSucceededEventDetails != nil {
		cloned := CloneTaskSucceededEventDetails(*value.TaskSucceededEventDetails)
		value.TaskSucceededEventDetails = &cloned
	}
	if value.TaskTimedOutEventDetails != nil {
		cloned := CloneTaskTimedOutEventDetails(*value.TaskTimedOutEventDetails)
		value.TaskTimedOutEventDetails = &cloned
	}
	if value.Timestamp != nil {
		cloned := *value.Timestamp
		value.Timestamp = &cloned
	}
	if value.Type != nil {
		cloned := *value.Type
		value.Type = &cloned
	}
	return value
}

// CloneHistoryEventExecutionDataDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneHistoryEventExecutionDataDetails(value HistoryEventExecutionDataDetails) HistoryEventExecutionDataDetails {
	if value.Truncated != nil {
		cloned := *value.Truncated
		value.Truncated = &cloned
	}
	return value
}

// CloneLambdaFunctionFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneLambdaFunctionFailedEventDetails(value LambdaFunctionFailedEventDetails) LambdaFunctionFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneLambdaFunctionScheduleFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneLambdaFunctionScheduleFailedEventDetails(value LambdaFunctionScheduleFailedEventDetails) LambdaFunctionScheduleFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneLambdaFunctionScheduledEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneLambdaFunctionScheduledEventDetails(value LambdaFunctionScheduledEventDetails) LambdaFunctionScheduledEventDetails {
	if value.Input != nil {
		cloned := *value.Input
		value.Input = &cloned
	}
	if value.InputDetails != nil {
		cloned := CloneHistoryEventExecutionDataDetails(*value.InputDetails)
		value.InputDetails = &cloned
	}
	if value.Resource != nil {
		cloned := *value.Resource
		value.Resource = &cloned
	}
	if value.TaskCredentials != nil {
		cloned := CloneTaskCredentials(*value.TaskCredentials)
		value.TaskCredentials = &cloned
	}
	if value.TimeoutInSeconds != nil {
		cloned := *value.TimeoutInSeconds
		value.TimeoutInSeconds = &cloned
	}
	return value
}

// CloneLambdaFunctionStartFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneLambdaFunctionStartFailedEventDetails(value LambdaFunctionStartFailedEventDetails) LambdaFunctionStartFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneLambdaFunctionSucceededEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneLambdaFunctionSucceededEventDetails(value LambdaFunctionSucceededEventDetails) LambdaFunctionSucceededEventDetails {
	if value.Output != nil {
		cloned := *value.Output
		value.Output = &cloned
	}
	if value.OutputDetails != nil {
		cloned := CloneHistoryEventExecutionDataDetails(*value.OutputDetails)
		value.OutputDetails = &cloned
	}
	return value
}

// CloneLambdaFunctionTimedOutEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneLambdaFunctionTimedOutEventDetails(value LambdaFunctionTimedOutEventDetails) LambdaFunctionTimedOutEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneMapIterationEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneMapIterationEventDetails(value MapIterationEventDetails) MapIterationEventDetails {
	if value.Index != nil {
		cloned := *value.Index
		value.Index = &cloned
	}
	if value.Name != nil {
		cloned := *value.Name
		value.Name = &cloned
	}
	return value
}

// CloneMapRunFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneMapRunFailedEventDetails(value MapRunFailedEventDetails) MapRunFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	return value
}

// CloneMapRunRedrivenEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneMapRunRedrivenEventDetails(value MapRunRedrivenEventDetails) MapRunRedrivenEventDetails {
	if value.MapRunArn != nil {
		cloned := *value.MapRunArn
		value.MapRunArn = &cloned
	}
	if value.RedriveCount != nil {
		cloned := *value.RedriveCount
		value.RedriveCount = &cloned
	}
	return value
}

// CloneMapRunStartedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneMapRunStartedEventDetails(value MapRunStartedEventDetails) MapRunStartedEventDetails {
	if value.MapRunArn != nil {
		cloned := *value.MapRunArn
		value.MapRunArn = &cloned
	}
	return value
}

// CloneMapStateStartedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneMapStateStartedEventDetails(value MapStateStartedEventDetails) MapStateStartedEventDetails {
	if value.Length != nil {
		cloned := *value.Length
		value.Length = &cloned
	}
	return value
}

// CloneStateEnteredEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneStateEnteredEventDetails(value StateEnteredEventDetails) StateEnteredEventDetails {
	if value.Input != nil {
		cloned := *value.Input
		value.Input = &cloned
	}
	if value.InputDetails != nil {
		cloned := CloneHistoryEventExecutionDataDetails(*value.InputDetails)
		value.InputDetails = &cloned
	}
	if value.Name != nil {
		cloned := *value.Name
		value.Name = &cloned
	}
	return value
}

// CloneStateExitedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneStateExitedEventDetails(value StateExitedEventDetails) StateExitedEventDetails {
	value.AssignedVariables = CloneAssignedVariables(value.AssignedVariables)
	if value.AssignedVariablesDetails != nil {
		cloned := CloneAssignedVariablesDetails(*value.AssignedVariablesDetails)
		value.AssignedVariablesDetails = &cloned
	}
	if value.Name != nil {
		cloned := *value.Name
		value.Name = &cloned
	}
	if value.Output != nil {
		cloned := *value.Output
		value.Output = &cloned
	}
	if value.OutputDetails != nil {
		cloned := CloneHistoryEventExecutionDataDetails(*value.OutputDetails)
		value.OutputDetails = &cloned
	}
	return value
}

// CloneTaskCredentials returns an independent copy, preserving nil collections and pointer presence.
func CloneTaskCredentials(value TaskCredentials) TaskCredentials {
	if value.RoleArn != nil {
		cloned := *value.RoleArn
		value.RoleArn = &cloned
	}
	return value
}

// CloneTaskFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneTaskFailedEventDetails(value TaskFailedEventDetails) TaskFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	if value.Resource != nil {
		cloned := *value.Resource
		value.Resource = &cloned
	}
	if value.ResourceType != nil {
		cloned := *value.ResourceType
		value.ResourceType = &cloned
	}
	return value
}

// CloneTaskScheduledEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneTaskScheduledEventDetails(value TaskScheduledEventDetails) TaskScheduledEventDetails {
	if value.HeartbeatInSeconds != nil {
		cloned := *value.HeartbeatInSeconds
		value.HeartbeatInSeconds = &cloned
	}
	if value.Parameters != nil {
		cloned := *value.Parameters
		value.Parameters = &cloned
	}
	if value.Region != nil {
		cloned := *value.Region
		value.Region = &cloned
	}
	if value.Resource != nil {
		cloned := *value.Resource
		value.Resource = &cloned
	}
	if value.ResourceType != nil {
		cloned := *value.ResourceType
		value.ResourceType = &cloned
	}
	if value.TaskCredentials != nil {
		cloned := CloneTaskCredentials(*value.TaskCredentials)
		value.TaskCredentials = &cloned
	}
	if value.TimeoutInSeconds != nil {
		cloned := *value.TimeoutInSeconds
		value.TimeoutInSeconds = &cloned
	}
	return value
}

// CloneTaskStartFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneTaskStartFailedEventDetails(value TaskStartFailedEventDetails) TaskStartFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	if value.Resource != nil {
		cloned := *value.Resource
		value.Resource = &cloned
	}
	if value.ResourceType != nil {
		cloned := *value.ResourceType
		value.ResourceType = &cloned
	}
	return value
}

// CloneTaskStartedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneTaskStartedEventDetails(value TaskStartedEventDetails) TaskStartedEventDetails {
	if value.Resource != nil {
		cloned := *value.Resource
		value.Resource = &cloned
	}
	if value.ResourceType != nil {
		cloned := *value.ResourceType
		value.ResourceType = &cloned
	}
	return value
}

// CloneTaskSubmitFailedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneTaskSubmitFailedEventDetails(value TaskSubmitFailedEventDetails) TaskSubmitFailedEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	if value.Resource != nil {
		cloned := *value.Resource
		value.Resource = &cloned
	}
	if value.ResourceType != nil {
		cloned := *value.ResourceType
		value.ResourceType = &cloned
	}
	return value
}

// CloneTaskSubmittedEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneTaskSubmittedEventDetails(value TaskSubmittedEventDetails) TaskSubmittedEventDetails {
	if value.Output != nil {
		cloned := *value.Output
		value.Output = &cloned
	}
	if value.OutputDetails != nil {
		cloned := CloneHistoryEventExecutionDataDetails(*value.OutputDetails)
		value.OutputDetails = &cloned
	}
	if value.Resource != nil {
		cloned := *value.Resource
		value.Resource = &cloned
	}
	if value.ResourceType != nil {
		cloned := *value.ResourceType
		value.ResourceType = &cloned
	}
	return value
}

// CloneTaskSucceededEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneTaskSucceededEventDetails(value TaskSucceededEventDetails) TaskSucceededEventDetails {
	if value.Output != nil {
		cloned := *value.Output
		value.Output = &cloned
	}
	if value.OutputDetails != nil {
		cloned := CloneHistoryEventExecutionDataDetails(*value.OutputDetails)
		value.OutputDetails = &cloned
	}
	if value.Resource != nil {
		cloned := *value.Resource
		value.Resource = &cloned
	}
	if value.ResourceType != nil {
		cloned := *value.ResourceType
		value.ResourceType = &cloned
	}
	return value
}

// CloneTaskTimedOutEventDetails returns an independent copy, preserving nil collections and pointer presence.
func CloneTaskTimedOutEventDetails(value TaskTimedOutEventDetails) TaskTimedOutEventDetails {
	if value.Cause != nil {
		cloned := *value.Cause
		value.Cause = &cloned
	}
	if value.Error != nil {
		cloned := *value.Error
		value.Error = &cloned
	}
	if value.Resource != nil {
		cloned := *value.Resource
		value.Resource = &cloned
	}
	if value.ResourceType != nil {
		cloned := *value.ResourceType
		value.ResourceType = &cloned
	}
	return value
}
