// Code generated by awsgen from AWS SDK for Go v2 Smithy models; DO NOT EDIT.
package stepfunctions

import (
	"fmt"

	"stackd/internal/awsapi"
	"stackd/internal/awscatalog"
)

// DecodeRequest binds wire input to a generated operation DTO and validates
// its Smithy constraints. Business logic remains the service provider's responsibility.
// Known operation metadata is retained on failure; Input is set only after validation.
func DecodeRequest(operation string, request awsapi.Request) (awsapi.DecodedRequest, error) {
	service, _ := awscatalog.LookupService("stepfunctions")
	if request.Protocol != "" {
		service.Protocol = request.Protocol
	}
	op, ok := service.Operation(operation)
	if !ok {
		return awsapi.DecodedRequest{}, fmt.Errorf("%w: %s", awsapi.ErrUnknownOperation, operation)
	}
	decoded := awsapi.DecodedRequest{Operation: op, Protocol: service.Protocol, Body: request.Body}
	input, err := NewInput(operation)
	if err != nil {
		return decoded, err
	}
	if err := awsapi.Decode(service, op, request, input); err != nil {
		return decoded, err
	}
	decoded.Input = input
	return decoded, nil
}

// NewInput allocates the generated operation DTO without binding or admitting a request.
// Error observers may bind rejected input for service-owned, model-redacted audit projection.
func NewInput(operation string) (any, error) {
	switch operation {
	case "CreateActivity":
		return new(CreateActivityInput), nil
	case "CreateStateMachine":
		return new(CreateStateMachineInput), nil
	case "CreateStateMachineAlias":
		return new(CreateStateMachineAliasInput), nil
	case "DeleteActivity":
		return new(DeleteActivityInput), nil
	case "DeleteStateMachine":
		return new(DeleteStateMachineInput), nil
	case "DeleteStateMachineAlias":
		return new(DeleteStateMachineAliasInput), nil
	case "DeleteStateMachineVersion":
		return new(DeleteStateMachineVersionInput), nil
	case "DescribeActivity":
		return new(DescribeActivityInput), nil
	case "DescribeExecution":
		return new(DescribeExecutionInput), nil
	case "DescribeMapRun":
		return new(DescribeMapRunInput), nil
	case "DescribeStateMachine":
		return new(DescribeStateMachineInput), nil
	case "DescribeStateMachineAlias":
		return new(DescribeStateMachineAliasInput), nil
	case "DescribeStateMachineForExecution":
		return new(DescribeStateMachineForExecutionInput), nil
	case "GetActivityTask":
		return new(GetActivityTaskInput), nil
	case "GetExecutionHistory":
		return new(GetExecutionHistoryInput), nil
	case "ListActivities":
		return new(ListActivitiesInput), nil
	case "ListExecutions":
		return new(ListExecutionsInput), nil
	case "ListMapRuns":
		return new(ListMapRunsInput), nil
	case "ListStateMachineAliases":
		return new(ListStateMachineAliasesInput), nil
	case "ListStateMachineVersions":
		return new(ListStateMachineVersionsInput), nil
	case "ListStateMachines":
		return new(ListStateMachinesInput), nil
	case "ListTagsForResource":
		return new(ListTagsForResourceInput), nil
	case "PublishStateMachineVersion":
		return new(PublishStateMachineVersionInput), nil
	case "RedriveExecution":
		return new(RedriveExecutionInput), nil
	case "SendTaskFailure":
		return new(SendTaskFailureInput), nil
	case "SendTaskHeartbeat":
		return new(SendTaskHeartbeatInput), nil
	case "SendTaskSuccess":
		return new(SendTaskSuccessInput), nil
	case "StartExecution":
		return new(StartExecutionInput), nil
	case "StartSyncExecution":
		return new(StartSyncExecutionInput), nil
	case "StopExecution":
		return new(StopExecutionInput), nil
	case "TagResource":
		return new(TagResourceInput), nil
	case "TestState":
		return new(TestStateInput), nil
	case "UntagResource":
		return new(UntagResourceInput), nil
	case "UpdateMapRun":
		return new(UpdateMapRunInput), nil
	case "UpdateStateMachine":
		return new(UpdateStateMachineInput), nil
	case "UpdateStateMachineAlias":
		return new(UpdateStateMachineAliasInput), nil
	case "ValidateStateMachineDefinition":
		return new(ValidateStateMachineDefinitionInput), nil
	default:
		return nil, fmt.Errorf("%w: %s", awsapi.ErrUnknownOperation, operation)
	}
}
