// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const appendItem = `-- name: AppendItem :one
INSERT INTO config_items (partition, account_id, region, resource_type, resource_id, resource_name, arn, availability_zone, capture_time, creation_time, status, configuration)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING sequence
`

type AppendItemParams struct {
	Partition        string
	AccountID        string
	Region           string
	ResourceType     string
	ResourceID       string
	ResourceName     string
	ARN              string
	AvailabilityZone string
	CaptureTime      time.Time
	CreationTime     time.Time
	Status           string
	Configuration    string
}

func (q *Queries) AppendItem(ctx context.Context, arg AppendItemParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appendItem,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceName,
		arg.ARN,
		arg.AvailabilityZone,
		arg.CaptureTime,
		arg.CreationTime,
		arg.Status,
		arg.Configuration,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const clearAggregatorSources = `-- name: ClearAggregatorSources :exec
DELETE FROM config_aggregator_sources WHERE parent_id=?
`

func (q *Queries) ClearAggregatorSources(ctx context.Context, parentID int64) error {
	_, err := q.db.ExecContext(ctx, clearAggregatorSources, parentID)
	return err
}

const clearRecorderTypes = `-- name: ClearRecorderTypes :exec
DELETE FROM config_recorder_types WHERE parent_id=?
`

func (q *Queries) ClearRecorderTypes(ctx context.Context, parentID int64) error {
	_, err := q.db.ExecContext(ctx, clearRecorderTypes, parentID)
	return err
}

const clearRuleMessages = `-- name: ClearRuleMessages :exec
DELETE FROM config_rule_messages WHERE parent_id=?
`

func (q *Queries) ClearRuleMessages(ctx context.Context, parentID int64) error {
	_, err := q.db.ExecContext(ctx, clearRuleMessages, parentID)
	return err
}

const clearRuleParameters = `-- name: ClearRuleParameters :exec
DELETE FROM config_rule_parameters WHERE parent_id=?
`

func (q *Queries) ClearRuleParameters(ctx context.Context, parentID int64) error {
	_, err := q.db.ExecContext(ctx, clearRuleParameters, parentID)
	return err
}

const clearRuleTypes = `-- name: ClearRuleTypes :exec
DELETE FROM config_rule_types WHERE parent_id=?
`

func (q *Queries) ClearRuleTypes(ctx context.Context, parentID int64) error {
	_, err := q.db.ExecContext(ctx, clearRuleTypes, parentID)
	return err
}

const clearTags = `-- name: ClearTags :exec
DELETE FROM config_tags WHERE partition=? AND account_id=? AND region=? AND arn=?
`

type ClearTagsParams struct {
	Partition string
	AccountID string
	Region    string
	ARN       string
}

func (q *Queries) ClearTags(ctx context.Context, arg ClearTagsParams) error {
	_, err := q.db.ExecContext(ctx, clearTags,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ARN,
	)
	return err
}

const deleteAggregationAuthorization = `-- name: DeleteAggregationAuthorization :exec
DELETE FROM config_aggregation_authorizations WHERE partition=? AND account_id=? AND region=? AND authorized_account_id=? AND authorized_region=?
`

type DeleteAggregationAuthorizationParams struct {
	Partition           string
	AccountID           string
	Region              string
	AuthorizedAccountID string
	AuthorizedRegion    string
}

func (q *Queries) DeleteAggregationAuthorization(ctx context.Context, arg DeleteAggregationAuthorizationParams) error {
	_, err := q.db.ExecContext(ctx, deleteAggregationAuthorization,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.AuthorizedAccountID,
		arg.AuthorizedRegion,
	)
	return err
}

const deleteAggregator = `-- name: DeleteAggregator :exec
DELETE FROM config_aggregators WHERE partition=? AND account_id=? AND region=? AND name=?
`

type DeleteAggregatorParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

func (q *Queries) DeleteAggregator(ctx context.Context, arg DeleteAggregatorParams) error {
	_, err := q.db.ExecContext(ctx, deleteAggregator,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM config_channels WHERE partition=? AND account_id=? AND region=?
`

type DeleteChannelParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) DeleteChannel(ctx context.Context, arg DeleteChannelParams) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, arg.Partition, arg.AccountID, arg.Region)
	return err
}

const deleteEvaluationRuns = `-- name: DeleteEvaluationRuns :exec
DELETE FROM config_evaluation_runs WHERE partition=? AND account_id=? AND region=? AND rule_name=?
`

type DeleteEvaluationRunsParams struct {
	Partition string
	AccountID string
	Region    string
	RuleName  string
}

func (q *Queries) DeleteEvaluationRuns(ctx context.Context, arg DeleteEvaluationRunsParams) error {
	_, err := q.db.ExecContext(ctx, deleteEvaluationRuns,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.RuleName,
	)
	return err
}

const deleteEvaluations = `-- name: DeleteEvaluations :exec
DELETE FROM config_evaluations WHERE partition=? AND account_id=? AND region=? AND rule_name=?
`

type DeleteEvaluationsParams struct {
	Partition string
	AccountID string
	Region    string
	RuleName  string
}

func (q *Queries) DeleteEvaluations(ctx context.Context, arg DeleteEvaluationsParams) error {
	_, err := q.db.ExecContext(ctx, deleteEvaluations,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.RuleName,
	)
	return err
}

const deleteRecorder = `-- name: DeleteRecorder :exec
DELETE FROM config_recorders WHERE partition=? AND account_id=? AND region=?
`

type DeleteRecorderParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) DeleteRecorder(ctx context.Context, arg DeleteRecorderParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecorder, arg.Partition, arg.AccountID, arg.Region)
	return err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM config_rules WHERE partition=? AND account_id=? AND region=? AND name=?
`

type DeleteRuleParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRule,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT row_id, "partition", account_id, region, name, bucket, prefix, kms_key_arn, topic_arn, frequency, last_attempt, last_success, next_delivery, status, error_code, error_message FROM config_channels WHERE partition=? AND account_id=? AND region=?
`

type GetChannelParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) GetChannel(ctx context.Context, arg GetChannelParams) (ConfigChannel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, arg.Partition, arg.AccountID, arg.Region)
	var i ConfigChannel
	err := row.Scan(
		&i.RowID,
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.Bucket,
		&i.Prefix,
		&i.KMSKeyARN,
		&i.TopicARN,
		&i.Frequency,
		&i.LastAttempt,
		&i.LastSuccess,
		&i.NextDelivery,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const getRecorder = `-- name: GetRecorder :one
SELECT row_id, "partition", account_id, region, name, arn, role_arn, all_supported, include_global, recording, last_start, last_stop, last_status_change, last_status, last_error_code, last_error_message FROM config_recorders WHERE partition=? AND account_id=? AND region=?
`

type GetRecorderParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) GetRecorder(ctx context.Context, arg GetRecorderParams) (ConfigRecorder, error) {
	row := q.db.QueryRowContext(ctx, getRecorder, arg.Partition, arg.AccountID, arg.Region)
	var i ConfigRecorder
	err := row.Scan(
		&i.RowID,
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.ARN,
		&i.RoleARN,
		&i.AllSupported,
		&i.IncludeGlobal,
		&i.Recording,
		&i.LastStart,
		&i.LastStop,
		&i.LastStatusChange,
		&i.LastStatus,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const insertAggregatorSource = `-- name: InsertAggregatorSource :exec
INSERT INTO config_aggregator_sources (parent_id, ordinal, source_account_id, source_region) VALUES (?, ?, ?, ?)
`

type InsertAggregatorSourceParams struct {
	ParentID        int64
	Ordinal         int64
	SourceAccountID string
	SourceRegion    string
}

func (q *Queries) InsertAggregatorSource(ctx context.Context, arg InsertAggregatorSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertAggregatorSource,
		arg.ParentID,
		arg.Ordinal,
		arg.SourceAccountID,
		arg.SourceRegion,
	)
	return err
}

const insertItemRelationship = `-- name: InsertItemRelationship :exec
INSERT INTO config_item_relationships (parent_id, ordinal, resource_type, resource_id, resource_name, name) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertItemRelationshipParams struct {
	ParentID     int64
	Ordinal      int64
	ResourceType string
	ResourceID   string
	ResourceName string
	Name         string
}

func (q *Queries) InsertItemRelationship(ctx context.Context, arg InsertItemRelationshipParams) error {
	_, err := q.db.ExecContext(ctx, insertItemRelationship,
		arg.ParentID,
		arg.Ordinal,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceName,
		arg.Name,
	)
	return err
}

const insertItemSupplement = `-- name: InsertItemSupplement :exec
INSERT INTO config_item_supplementary (parent_id, name, document) VALUES (?, ?, ?)
`

type InsertItemSupplementParams struct {
	ParentID int64
	Name     string
	Document string
}

func (q *Queries) InsertItemSupplement(ctx context.Context, arg InsertItemSupplementParams) error {
	_, err := q.db.ExecContext(ctx, insertItemSupplement, arg.ParentID, arg.Name, arg.Document)
	return err
}

const insertItemTag = `-- name: InsertItemTag :exec
INSERT INTO config_item_tags (parent_id, tag_key, value) VALUES (?, ?, ?)
`

type InsertItemTagParams struct {
	ParentID int64
	TagKey   string
	Value    string
}

func (q *Queries) InsertItemTag(ctx context.Context, arg InsertItemTagParams) error {
	_, err := q.db.ExecContext(ctx, insertItemTag, arg.ParentID, arg.TagKey, arg.Value)
	return err
}

const insertRecorderType = `-- name: InsertRecorderType :exec
INSERT INTO config_recorder_types (parent_id, kind, ordinal, resource_type) VALUES (?, ?, ?, ?)
`

type InsertRecorderTypeParams struct {
	ParentID     int64
	Kind         string
	Ordinal      int64
	ResourceType string
}

func (q *Queries) InsertRecorderType(ctx context.Context, arg InsertRecorderTypeParams) error {
	_, err := q.db.ExecContext(ctx, insertRecorderType,
		arg.ParentID,
		arg.Kind,
		arg.Ordinal,
		arg.ResourceType,
	)
	return err
}

const insertRuleMessage = `-- name: InsertRuleMessage :exec
INSERT INTO config_rule_messages (parent_id, ordinal, message) VALUES (?, ?, ?)
`

type InsertRuleMessageParams struct {
	ParentID int64
	Ordinal  int64
	Message  string
}

func (q *Queries) InsertRuleMessage(ctx context.Context, arg InsertRuleMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertRuleMessage, arg.ParentID, arg.Ordinal, arg.Message)
	return err
}

const insertRuleParameter = `-- name: InsertRuleParameter :exec
INSERT INTO config_rule_parameters (parent_id, parameter_key, value) VALUES (?, ?, ?)
`

type InsertRuleParameterParams struct {
	ParentID     int64
	ParameterKey string
	Value        string
}

func (q *Queries) InsertRuleParameter(ctx context.Context, arg InsertRuleParameterParams) error {
	_, err := q.db.ExecContext(ctx, insertRuleParameter, arg.ParentID, arg.ParameterKey, arg.Value)
	return err
}

const insertRuleType = `-- name: InsertRuleType :exec
INSERT INTO config_rule_types (parent_id, ordinal, resource_type) VALUES (?, ?, ?)
`

type InsertRuleTypeParams struct {
	ParentID     int64
	Ordinal      int64
	ResourceType string
}

func (q *Queries) InsertRuleType(ctx context.Context, arg InsertRuleTypeParams) error {
	_, err := q.db.ExecContext(ctx, insertRuleType, arg.ParentID, arg.Ordinal, arg.ResourceType)
	return err
}

const insertTag = `-- name: InsertTag :exec
INSERT INTO config_tags (partition, account_id, region, arn, key, value) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTagParams struct {
	Partition string
	AccountID string
	Region    string
	ARN       string
	Key       string
	Value     string
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTag,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ARN,
		arg.Key,
		arg.Value,
	)
	return err
}

const listAggregationAuthorizations = `-- name: ListAggregationAuthorizations :many
SELECT row_id, "partition", account_id, region, authorized_account_id, authorized_region, arn, created_at FROM config_aggregation_authorizations WHERE partition=? AND account_id=? AND region=? ORDER BY authorized_account_id, authorized_region
`

type ListAggregationAuthorizationsParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) ListAggregationAuthorizations(ctx context.Context, arg ListAggregationAuthorizationsParams) ([]ConfigAggregationAuthorization, error) {
	rows, err := q.db.QueryContext(ctx, listAggregationAuthorizations, arg.Partition, arg.AccountID, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigAggregationAuthorization{}
	for rows.Next() {
		var i ConfigAggregationAuthorization
		if err := rows.Scan(
			&i.RowID,
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.AuthorizedAccountID,
			&i.AuthorizedRegion,
			&i.ARN,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAggregatorSources = `-- name: ListAggregatorSources :many
SELECT parent_id, ordinal, source_account_id, source_region FROM config_aggregator_sources WHERE parent_id=? ORDER BY ordinal
`

func (q *Queries) ListAggregatorSources(ctx context.Context, parentID int64) ([]ConfigAggregatorSource, error) {
	rows, err := q.db.QueryContext(ctx, listAggregatorSources, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigAggregatorSource{}
	for rows.Next() {
		var i ConfigAggregatorSource
		if err := rows.Scan(
			&i.ParentID,
			&i.Ordinal,
			&i.SourceAccountID,
			&i.SourceRegion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAggregators = `-- name: ListAggregators :many
SELECT row_id, "partition", account_id, region, name, arn, created_at, updated_at FROM config_aggregators WHERE partition=? AND account_id=? AND region=? ORDER BY name
`

type ListAggregatorsParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) ListAggregators(ctx context.Context, arg ListAggregatorsParams) ([]ConfigAggregator, error) {
	rows, err := q.db.QueryContext(ctx, listAggregators, arg.Partition, arg.AccountID, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigAggregator{}
	for rows.Next() {
		var i ConfigAggregator
		if err := rows.Scan(
			&i.RowID,
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.Name,
			&i.ARN,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT row_id, "partition", account_id, region, id, channel_name, kind, object_key, due, created_at, completed_at, status, error_code, error_message, attempts, first_sequence, last_sequence FROM config_deliveries ORDER BY due, partition, account_id, region, id
`

func (q *Queries) ListDeliveries(ctx context.Context) ([]ConfigDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigDelivery{}
	for rows.Next() {
		var i ConfigDelivery
		if err := rows.Scan(
			&i.RowID,
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ID,
			&i.ChannelName,
			&i.Kind,
			&i.ObjectKey,
			&i.Due,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Attempts,
			&i.FirstSequence,
			&i.LastSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluationRuns = `-- name: ListEvaluationRuns :many
SELECT row_id, "partition", account_id, region, token, rule_name, item_sequence, due, created_at, completed_at, status, error_code, error_message FROM config_evaluation_runs ORDER BY due, partition, account_id, region, token
`

func (q *Queries) ListEvaluationRuns(ctx context.Context) ([]ConfigEvaluationRun, error) {
	rows, err := q.db.QueryContext(ctx, listEvaluationRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigEvaluationRun{}
	for rows.Next() {
		var i ConfigEvaluationRun
		if err := rows.Scan(
			&i.RowID,
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.Token,
			&i.RuleName,
			&i.ItemSequence,
			&i.Due,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluations = `-- name: ListEvaluations :many
SELECT row_id, "partition", account_id, region, rule_name, resource_type, resource_id, compliance_type, annotation, ordering_time, recorded_at, invoked_at FROM config_evaluations WHERE partition=? AND account_id=? AND region=? ORDER BY rule_name, resource_type, resource_id
`

type ListEvaluationsParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) ListEvaluations(ctx context.Context, arg ListEvaluationsParams) ([]ConfigEvaluation, error) {
	rows, err := q.db.QueryContext(ctx, listEvaluations, arg.Partition, arg.AccountID, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigEvaluation{}
	for rows.Next() {
		var i ConfigEvaluation
		if err := rows.Scan(
			&i.RowID,
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.RuleName,
			&i.ResourceType,
			&i.ResourceID,
			&i.ComplianceType,
			&i.Annotation,
			&i.OrderingTime,
			&i.RecordedAt,
			&i.InvokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemRelationships = `-- name: ListItemRelationships :many
SELECT parent_id, ordinal, resource_type, resource_id, resource_name, name FROM config_item_relationships WHERE parent_id=? ORDER BY ordinal
`

func (q *Queries) ListItemRelationships(ctx context.Context, parentID int64) ([]ConfigItemRelationship, error) {
	rows, err := q.db.QueryContext(ctx, listItemRelationships, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigItemRelationship{}
	for rows.Next() {
		var i ConfigItemRelationship
		if err := rows.Scan(
			&i.ParentID,
			&i.Ordinal,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSupplements = `-- name: ListItemSupplements :many
SELECT parent_id, name, document FROM config_item_supplementary WHERE parent_id=? ORDER BY name
`

func (q *Queries) ListItemSupplements(ctx context.Context, parentID int64) ([]ConfigItemSupplementary, error) {
	rows, err := q.db.QueryContext(ctx, listItemSupplements, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigItemSupplementary{}
	for rows.Next() {
		var i ConfigItemSupplementary
		if err := rows.Scan(&i.ParentID, &i.Name, &i.Document); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTags = `-- name: ListItemTags :many
SELECT parent_id, tag_key, value FROM config_item_tags WHERE parent_id=? ORDER BY tag_key
`

func (q *Queries) ListItemTags(ctx context.Context, parentID int64) ([]ConfigItemTag, error) {
	rows, err := q.db.QueryContext(ctx, listItemTags, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigItemTag{}
	for rows.Next() {
		var i ConfigItemTag
		if err := rows.Scan(&i.ParentID, &i.TagKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT sequence, "partition", account_id, region, resource_type, resource_id, resource_name, arn, availability_zone, capture_time, creation_time, status, configuration FROM config_items WHERE partition=? AND account_id=? AND region=? ORDER BY sequence
`

type ListItemsParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ConfigItem, error) {
	rows, err := q.db.QueryContext(ctx, listItems, arg.Partition, arg.AccountID, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigItem{}
	for rows.Next() {
		var i ConfigItem
		if err := rows.Scan(
			&i.Sequence,
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.ARN,
			&i.AvailabilityZone,
			&i.CaptureTime,
			&i.CreationTime,
			&i.Status,
			&i.Configuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecorderTypes = `-- name: ListRecorderTypes :many
SELECT parent_id, kind, ordinal, resource_type FROM config_recorder_types WHERE parent_id=? ORDER BY kind, ordinal
`

func (q *Queries) ListRecorderTypes(ctx context.Context, parentID int64) ([]ConfigRecorderType, error) {
	rows, err := q.db.QueryContext(ctx, listRecorderTypes, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigRecorderType{}
	for rows.Next() {
		var i ConfigRecorderType
		if err := rows.Scan(
			&i.ParentID,
			&i.Kind,
			&i.Ordinal,
			&i.ResourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleMessages = `-- name: ListRuleMessages :many
SELECT parent_id, ordinal, message FROM config_rule_messages WHERE parent_id=? ORDER BY ordinal
`

func (q *Queries) ListRuleMessages(ctx context.Context, parentID int64) ([]ConfigRuleMessage, error) {
	rows, err := q.db.QueryContext(ctx, listRuleMessages, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigRuleMessage{}
	for rows.Next() {
		var i ConfigRuleMessage
		if err := rows.Scan(&i.ParentID, &i.Ordinal, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleParameters = `-- name: ListRuleParameters :many
SELECT parent_id, parameter_key, value FROM config_rule_parameters WHERE parent_id=? ORDER BY parameter_key
`

func (q *Queries) ListRuleParameters(ctx context.Context, parentID int64) ([]ConfigRuleParameter, error) {
	rows, err := q.db.QueryContext(ctx, listRuleParameters, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigRuleParameter{}
	for rows.Next() {
		var i ConfigRuleParameter
		if err := rows.Scan(&i.ParentID, &i.ParameterKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleTypes = `-- name: ListRuleTypes :many
SELECT parent_id, ordinal, resource_type FROM config_rule_types WHERE parent_id=? ORDER BY ordinal
`

func (q *Queries) ListRuleTypes(ctx context.Context, parentID int64) ([]ConfigRuleType, error) {
	rows, err := q.db.QueryContext(ctx, listRuleTypes, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigRuleType{}
	for rows.Next() {
		var i ConfigRuleType
		if err := rows.Scan(&i.ParentID, &i.Ordinal, &i.ResourceType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT row_id, "partition", account_id, region, name, id, arn, description, owner, source_identifier, parameters_present, resource_id, tag_key, tag_value, created_at, last_evaluation, last_reevaluation, error_code, error_message FROM config_rules WHERE partition=? AND account_id=? AND region=? ORDER BY name
`

type ListRulesParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) ListRules(ctx context.Context, arg ListRulesParams) ([]ConfigRule, error) {
	rows, err := q.db.QueryContext(ctx, listRules, arg.Partition, arg.AccountID, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigRule{}
	for rows.Next() {
		var i ConfigRule
		if err := rows.Scan(
			&i.RowID,
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.Name,
			&i.ID,
			&i.ARN,
			&i.Description,
			&i.Owner,
			&i.SourceIdentifier,
			&i.ParametersPresent,
			&i.ResourceID,
			&i.TagKey,
			&i.TagValue,
			&i.CreatedAt,
			&i.LastEvaluation,
			&i.LastReevaluation,
			&i.ErrorCode,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT key, value FROM config_tags WHERE partition=? AND account_id=? AND region=? AND arn=? ORDER BY key
`

type ListTagsParams struct {
	Partition string
	AccountID string
	Region    string
	ARN       string
}

type ListTagsRow struct {
	Key   string
	Value string
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ARN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putAggregationAuthorization = `-- name: PutAggregationAuthorization :exec
INSERT INTO config_aggregation_authorizations (partition, account_id, region, authorized_account_id, authorized_region, arn, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (partition, account_id, region, authorized_account_id, authorized_region) DO UPDATE SET arn=excluded.arn, created_at=excluded.created_at
`

type PutAggregationAuthorizationParams struct {
	Partition           string
	AccountID           string
	Region              string
	AuthorizedAccountID string
	AuthorizedRegion    string
	ARN                 string
	CreatedAt           time.Time
}

func (q *Queries) PutAggregationAuthorization(ctx context.Context, arg PutAggregationAuthorizationParams) error {
	_, err := q.db.ExecContext(ctx, putAggregationAuthorization,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.AuthorizedAccountID,
		arg.AuthorizedRegion,
		arg.ARN,
		arg.CreatedAt,
	)
	return err
}

const putAggregator = `-- name: PutAggregator :one
INSERT INTO config_aggregators (partition, account_id, region, name, arn, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (partition, account_id, region, name) DO UPDATE SET arn=excluded.arn, created_at=excluded.created_at, updated_at=excluded.updated_at
RETURNING row_id
`

type PutAggregatorParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
	ARN       string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) PutAggregator(ctx context.Context, arg PutAggregatorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, putAggregator,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.ARN,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var row_id int64
	err := row.Scan(&row_id)
	return row_id, err
}

const putChannel = `-- name: PutChannel :exec
INSERT INTO config_channels (partition, account_id, region, name, bucket, prefix, kms_key_arn, topic_arn, frequency, last_attempt, last_success, next_delivery, status, error_code, error_message)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (partition, account_id, region) DO UPDATE SET name=excluded.name, bucket=excluded.bucket, prefix=excluded.prefix, kms_key_arn=excluded.kms_key_arn, topic_arn=excluded.topic_arn, frequency=excluded.frequency, last_attempt=excluded.last_attempt, last_success=excluded.last_success, next_delivery=excluded.next_delivery, status=excluded.status, error_code=excluded.error_code, error_message=excluded.error_message
`

type PutChannelParams struct {
	Partition    string
	AccountID    string
	Region       string
	Name         string
	Bucket       string
	Prefix       string
	KMSKeyARN    string
	TopicARN     string
	Frequency    string
	LastAttempt  time.Time
	LastSuccess  time.Time
	NextDelivery time.Time
	Status       string
	ErrorCode    string
	ErrorMessage string
}

func (q *Queries) PutChannel(ctx context.Context, arg PutChannelParams) error {
	_, err := q.db.ExecContext(ctx, putChannel,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.Bucket,
		arg.Prefix,
		arg.KMSKeyARN,
		arg.TopicARN,
		arg.Frequency,
		arg.LastAttempt,
		arg.LastSuccess,
		arg.NextDelivery,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	return err
}

const putDelivery = `-- name: PutDelivery :exec
INSERT INTO config_deliveries (partition, account_id, region, id, channel_name, kind, object_key, due, created_at, completed_at, status, error_code, error_message, attempts, first_sequence, last_sequence)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (partition, account_id, region, id) DO UPDATE SET channel_name=excluded.channel_name, kind=excluded.kind, object_key=excluded.object_key, due=excluded.due, created_at=excluded.created_at, completed_at=excluded.completed_at, status=excluded.status, error_code=excluded.error_code, error_message=excluded.error_message, attempts=excluded.attempts, first_sequence=excluded.first_sequence, last_sequence=excluded.last_sequence
`

type PutDeliveryParams struct {
	Partition     string
	AccountID     string
	Region        string
	ID            string
	ChannelName   string
	Kind          string
	ObjectKey     string
	Due           time.Time
	CreatedAt     time.Time
	CompletedAt   time.Time
	Status        string
	ErrorCode     string
	ErrorMessage  string
	Attempts      int64
	FirstSequence int64
	LastSequence  int64
}

func (q *Queries) PutDelivery(ctx context.Context, arg PutDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, putDelivery,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.ID,
		arg.ChannelName,
		arg.Kind,
		arg.ObjectKey,
		arg.Due,
		arg.CreatedAt,
		arg.CompletedAt,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Attempts,
		arg.FirstSequence,
		arg.LastSequence,
	)
	return err
}

const putEvaluation = `-- name: PutEvaluation :exec
INSERT INTO config_evaluations (partition, account_id, region, rule_name, resource_type, resource_id, compliance_type, annotation, ordering_time, recorded_at, invoked_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (partition, account_id, region, rule_name, resource_type, resource_id) DO UPDATE SET compliance_type=excluded.compliance_type, annotation=excluded.annotation, ordering_time=excluded.ordering_time, recorded_at=excluded.recorded_at, invoked_at=excluded.invoked_at
`

type PutEvaluationParams struct {
	Partition      string
	AccountID      string
	Region         string
	RuleName       string
	ResourceType   string
	ResourceID     string
	ComplianceType string
	Annotation     string
	OrderingTime   time.Time
	RecordedAt     time.Time
	InvokedAt      time.Time
}

func (q *Queries) PutEvaluation(ctx context.Context, arg PutEvaluationParams) error {
	_, err := q.db.ExecContext(ctx, putEvaluation,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.RuleName,
		arg.ResourceType,
		arg.ResourceID,
		arg.ComplianceType,
		arg.Annotation,
		arg.OrderingTime,
		arg.RecordedAt,
		arg.InvokedAt,
	)
	return err
}

const putEvaluationRun = `-- name: PutEvaluationRun :exec
INSERT INTO config_evaluation_runs (partition, account_id, region, token, rule_name, item_sequence, due, created_at, completed_at, status, error_code, error_message)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (partition, account_id, region, token) DO UPDATE SET rule_name=excluded.rule_name, item_sequence=excluded.item_sequence, due=excluded.due, created_at=excluded.created_at, completed_at=excluded.completed_at, status=excluded.status, error_code=excluded.error_code, error_message=excluded.error_message
`

type PutEvaluationRunParams struct {
	Partition    string
	AccountID    string
	Region       string
	Token        string
	RuleName     string
	ItemSequence int64
	Due          time.Time
	CreatedAt    time.Time
	CompletedAt  time.Time
	Status       string
	ErrorCode    string
	ErrorMessage string
}

func (q *Queries) PutEvaluationRun(ctx context.Context, arg PutEvaluationRunParams) error {
	_, err := q.db.ExecContext(ctx, putEvaluationRun,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Token,
		arg.RuleName,
		arg.ItemSequence,
		arg.Due,
		arg.CreatedAt,
		arg.CompletedAt,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	return err
}

const putRecorder = `-- name: PutRecorder :one
INSERT INTO config_recorders (partition, account_id, region, name, arn, role_arn, all_supported, include_global, recording, last_start, last_stop, last_status_change, last_status, last_error_code, last_error_message)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (partition, account_id, region) DO UPDATE SET name=excluded.name, arn=excluded.arn, role_arn=excluded.role_arn, all_supported=excluded.all_supported, include_global=excluded.include_global, recording=excluded.recording, last_start=excluded.last_start, last_stop=excluded.last_stop, last_status_change=excluded.last_status_change, last_status=excluded.last_status, last_error_code=excluded.last_error_code, last_error_message=excluded.last_error_message
RETURNING row_id
`

type PutRecorderParams struct {
	Partition        string
	AccountID        string
	Region           string
	Name             string
	ARN              string
	RoleARN          string
	AllSupported     bool
	IncludeGlobal    bool
	Recording        bool
	LastStart        time.Time
	LastStop         time.Time
	LastStatusChange time.Time
	LastStatus       string
	LastErrorCode    string
	LastErrorMessage string
}

func (q *Queries) PutRecorder(ctx context.Context, arg PutRecorderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, putRecorder,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.ARN,
		arg.RoleARN,
		arg.AllSupported,
		arg.IncludeGlobal,
		arg.Recording,
		arg.LastStart,
		arg.LastStop,
		arg.LastStatusChange,
		arg.LastStatus,
		arg.LastErrorCode,
		arg.LastErrorMessage,
	)
	var row_id int64
	err := row.Scan(&row_id)
	return row_id, err
}

const putRule = `-- name: PutRule :one
INSERT INTO config_rules (partition, account_id, region, name, id, arn, description, owner, source_identifier, parameters_present, resource_id, tag_key, tag_value, created_at, last_evaluation, last_reevaluation, error_code, error_message)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (partition, account_id, region, name) DO UPDATE SET id=excluded.id, arn=excluded.arn, description=excluded.description, owner=excluded.owner, source_identifier=excluded.source_identifier, parameters_present=excluded.parameters_present, resource_id=excluded.resource_id, tag_key=excluded.tag_key, tag_value=excluded.tag_value, created_at=excluded.created_at, last_evaluation=excluded.last_evaluation, last_reevaluation=excluded.last_reevaluation, error_code=excluded.error_code, error_message=excluded.error_message
RETURNING row_id
`

type PutRuleParams struct {
	Partition         string
	AccountID         string
	Region            string
	Name              string
	ID                string
	ARN               string
	Description       string
	Owner             string
	SourceIdentifier  string
	ParametersPresent bool
	ResourceID        string
	TagKey            string
	TagValue          string
	CreatedAt         time.Time
	LastEvaluation    time.Time
	LastReevaluation  time.Time
	ErrorCode         string
	ErrorMessage      string
}

func (q *Queries) PutRule(ctx context.Context, arg PutRuleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, putRule,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.ID,
		arg.ARN,
		arg.Description,
		arg.Owner,
		arg.SourceIdentifier,
		arg.ParametersPresent,
		arg.ResourceID,
		arg.TagKey,
		arg.TagValue,
		arg.CreatedAt,
		arg.LastEvaluation,
		arg.LastReevaluation,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var row_id int64
	err := row.Scan(&row_id)
	return row_id, err
}
