// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type CognitoidentityIdentity struct {
	Partition  string
	AccountID  string
	Region     string
	PoolID     string
	IdentityID string
	Created    time.Time
	Modified   time.Time
}

type CognitoidentityPool struct {
	Partition            string
	AccountID            string
	Region               string
	PoolID               string
	Name                 string
	AllowUnauthenticated int64
	AllowClassic         int64
	Providers            []byte
	Tags                 []byte
	Roles                []byte
	Mappings             []byte
	PrincipalTagMaps     []byte
}
