// Code generated by awsgen from AWS SDK for Go v2 Smithy models; DO NOT EDIT.
package identitystore

import "time"

// AccessDeniedException represents Smithy shape com.amazonaws.identitystore#AccessDeniedException.
type AccessDeniedException struct {
	Message   *ExceptionMessage            `json:"Message,omitempty" smithy:"Message"`
	Reason    *AccessDeniedExceptionReason `json:"Reason,omitempty" smithy:"Reason"`
	RequestId *RequestId                   `json:"RequestId,omitempty" smithy:"RequestId"`
}

// AccessDeniedExceptionReason represents Smithy shape com.amazonaws.identitystore#AccessDeniedExceptionReason.
type AccessDeniedExceptionReason string

const (
	AccessDeniedExceptionReasonKMS_ACCESS_DENIED AccessDeniedExceptionReason = "KMS_ACCESS_DENIED"
)

// Address represents Smithy shape com.amazonaws.identitystore#Address.
type Address struct {
	Country       *SensitiveStringType `json:"Country,omitempty" smithy:"Country"`
	Formatted     *SensitiveStringType `json:"Formatted,omitempty" smithy:"Formatted"`
	Locality      *SensitiveStringType `json:"Locality,omitempty" smithy:"Locality"`
	PostalCode    *SensitiveStringType `json:"PostalCode,omitempty" smithy:"PostalCode"`
	Primary       *BooleanType         `json:"Primary,omitempty" smithy:"Primary"`
	Region        *SensitiveStringType `json:"Region,omitempty" smithy:"Region"`
	StreetAddress *SensitiveStringType `json:"StreetAddress,omitempty" smithy:"StreetAddress"`
	Type          *SensitiveStringType `json:"Type,omitempty" smithy:"Type"`
}

// Addresses represents Smithy shape com.amazonaws.identitystore#Addresses.
type Addresses []Address

// AlternateIdentifier represents Smithy shape com.amazonaws.identitystore#AlternateIdentifier.
type AlternateIdentifier struct {
	ExternalId      *ExternalId      `json:"ExternalId,omitempty" smithy:"ExternalId"`
	UniqueAttribute *UniqueAttribute `json:"UniqueAttribute,omitempty" smithy:"UniqueAttribute"`
}

// AttributeOperation represents Smithy shape com.amazonaws.identitystore#AttributeOperation.
type AttributeOperation struct {
	// Required by the AWS service model.
	AttributePath  *AttributePath `json:"AttributePath,omitempty" smithy:"AttributePath"`
	AttributeValue AttributeValue `json:"AttributeValue,omitempty" smithy:"AttributeValue"`
}

// AttributeOperations represents Smithy shape com.amazonaws.identitystore#AttributeOperations.
type AttributeOperations []AttributeOperation

// AttributePath represents Smithy shape com.amazonaws.identitystore#AttributePath.
type AttributePath string

// AttributeValue represents Smithy shape com.amazonaws.identitystore#AttributeValue.
type AttributeValue any

// BooleanType represents Smithy shape com.amazonaws.identitystore#BooleanType.
type BooleanType bool

// ConflictException represents Smithy shape com.amazonaws.identitystore#ConflictException.
type ConflictException struct {
	Message   *ExceptionMessage        `json:"Message,omitempty" smithy:"Message"`
	Reason    *ConflictExceptionReason `json:"Reason,omitempty" smithy:"Reason"`
	RequestId *RequestId               `json:"RequestId,omitempty" smithy:"RequestId"`
}

// ConflictExceptionReason represents Smithy shape com.amazonaws.identitystore#ConflictExceptionReason.
type ConflictExceptionReason string

const (
	ConflictExceptionReasonCONCURRENT_MODIFICATION         ConflictExceptionReason = "CONCURRENT_MODIFICATION"
	ConflictExceptionReasonUNIQUENESS_CONSTRAINT_VIOLATION ConflictExceptionReason = "UNIQUENESS_CONSTRAINT_VIOLATION"
)

// CreateGroupMembershipRequest represents Smithy shape com.amazonaws.identitystore#CreateGroupMembershipRequest.
type CreateGroupMembershipRequest struct {
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	MemberId *MemberId `json:"MemberId,omitempty" smithy:"MemberId"`
}

// CreateGroupMembershipResponse represents Smithy shape com.amazonaws.identitystore#CreateGroupMembershipResponse.
type CreateGroupMembershipResponse struct {
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	MembershipId *ResourceId `json:"MembershipId,omitempty" smithy:"MembershipId"`
}

// CreateGroupRequest represents Smithy shape com.amazonaws.identitystore#CreateGroupRequest.
type CreateGroupRequest struct {
	Description *SensitiveStringType `json:"Description,omitempty" smithy:"Description"`
	DisplayName *GroupDisplayName    `json:"DisplayName,omitempty" smithy:"DisplayName"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
}

// CreateGroupResponse represents Smithy shape com.amazonaws.identitystore#CreateGroupResponse.
type CreateGroupResponse struct {
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
}

// CreateUserRequest represents Smithy shape com.amazonaws.identitystore#CreateUserRequest.
type CreateUserRequest struct {
	Addresses   Addresses            `json:"Addresses,omitzero" smithy:"Addresses"`
	Birthdate   *SensitiveStringType `json:"Birthdate,omitempty" smithy:"Birthdate"`
	DisplayName *SensitiveStringType `json:"DisplayName,omitempty" smithy:"DisplayName"`
	Emails      Emails               `json:"Emails,omitzero" smithy:"Emails"`
	Extensions  Extensions           `json:"Extensions,omitzero" smithy:"Extensions"`
	// Required by the AWS service model.
	IdentityStoreId   *IdentityStoreId     `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	Locale            *SensitiveStringType `json:"Locale,omitempty" smithy:"Locale"`
	Name              *Name                `json:"Name,omitempty" smithy:"Name"`
	NickName          *SensitiveStringType `json:"NickName,omitempty" smithy:"NickName"`
	PhoneNumbers      PhoneNumbers         `json:"PhoneNumbers,omitzero" smithy:"PhoneNumbers"`
	Photos            Photos               `json:"Photos,omitzero" smithy:"Photos"`
	PreferredLanguage *SensitiveStringType `json:"PreferredLanguage,omitempty" smithy:"PreferredLanguage"`
	ProfileUrl        *SensitiveStringType `json:"ProfileUrl,omitempty" smithy:"ProfileUrl"`
	Roles             Roles                `json:"Roles,omitzero" smithy:"Roles"`
	Timezone          *SensitiveStringType `json:"Timezone,omitempty" smithy:"Timezone"`
	Title             *SensitiveStringType `json:"Title,omitempty" smithy:"Title"`
	UserName          *UserName            `json:"UserName,omitempty" smithy:"UserName"`
	UserType          *SensitiveStringType `json:"UserType,omitempty" smithy:"UserType"`
	Website           *SensitiveStringType `json:"Website,omitempty" smithy:"Website"`
}

// CreateUserResponse represents Smithy shape com.amazonaws.identitystore#CreateUserResponse.
type CreateUserResponse struct {
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	UserId *ResourceId `json:"UserId,omitempty" smithy:"UserId"`
}

// DateType represents Smithy shape com.amazonaws.identitystore#DateType.
type DateType = time.Time

// DeleteGroupMembershipRequest represents Smithy shape com.amazonaws.identitystore#DeleteGroupMembershipRequest.
type DeleteGroupMembershipRequest struct {
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	MembershipId *ResourceId `json:"MembershipId,omitempty" smithy:"MembershipId"`
}

// DeleteGroupMembershipResponse represents Smithy shape com.amazonaws.identitystore#DeleteGroupMembershipResponse.
type DeleteGroupMembershipResponse struct {
}

// DeleteGroupRequest represents Smithy shape com.amazonaws.identitystore#DeleteGroupRequest.
type DeleteGroupRequest struct {
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
}

// DeleteGroupResponse represents Smithy shape com.amazonaws.identitystore#DeleteGroupResponse.
type DeleteGroupResponse struct {
}

// DeleteUserRequest represents Smithy shape com.amazonaws.identitystore#DeleteUserRequest.
type DeleteUserRequest struct {
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	UserId *ResourceId `json:"UserId,omitempty" smithy:"UserId"`
}

// DeleteUserResponse represents Smithy shape com.amazonaws.identitystore#DeleteUserResponse.
type DeleteUserResponse struct {
}

// DescribeGroupMembershipRequest represents Smithy shape com.amazonaws.identitystore#DescribeGroupMembershipRequest.
type DescribeGroupMembershipRequest struct {
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	MembershipId *ResourceId `json:"MembershipId,omitempty" smithy:"MembershipId"`
}

// DescribeGroupMembershipResponse represents Smithy shape com.amazonaws.identitystore#DescribeGroupMembershipResponse.
type DescribeGroupMembershipResponse struct {
	CreatedAt *DateType   `json:"CreatedAt,omitempty" smithy:"CreatedAt"`
	CreatedBy *StringType `json:"CreatedBy,omitempty" smithy:"CreatedBy"`
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	MemberId *MemberId `json:"MemberId,omitempty" smithy:"MemberId"`
	// Required by the AWS service model.
	MembershipId *ResourceId `json:"MembershipId,omitempty" smithy:"MembershipId"`
	UpdatedAt    *DateType   `json:"UpdatedAt,omitempty" smithy:"UpdatedAt"`
	UpdatedBy    *StringType `json:"UpdatedBy,omitempty" smithy:"UpdatedBy"`
}

// DescribeGroupRequest represents Smithy shape com.amazonaws.identitystore#DescribeGroupRequest.
type DescribeGroupRequest struct {
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
}

// DescribeGroupResponse represents Smithy shape com.amazonaws.identitystore#DescribeGroupResponse.
type DescribeGroupResponse struct {
	CreatedAt   *DateType            `json:"CreatedAt,omitempty" smithy:"CreatedAt"`
	CreatedBy   *StringType          `json:"CreatedBy,omitempty" smithy:"CreatedBy"`
	Description *SensitiveStringType `json:"Description,omitempty" smithy:"Description"`
	DisplayName *GroupDisplayName    `json:"DisplayName,omitempty" smithy:"DisplayName"`
	ExternalIds ExternalIds          `json:"ExternalIds,omitzero" smithy:"ExternalIds"`
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	UpdatedAt       *DateType        `json:"UpdatedAt,omitempty" smithy:"UpdatedAt"`
	UpdatedBy       *StringType      `json:"UpdatedBy,omitempty" smithy:"UpdatedBy"`
}

// DescribeUserRequest represents Smithy shape com.amazonaws.identitystore#DescribeUserRequest.
type DescribeUserRequest struct {
	Extensions ExtensionNames `json:"Extensions,omitzero" smithy:"Extensions"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	UserId *ResourceId `json:"UserId,omitempty" smithy:"UserId"`
}

// DescribeUserResponse represents Smithy shape com.amazonaws.identitystore#DescribeUserResponse.
type DescribeUserResponse struct {
	Addresses   Addresses            `json:"Addresses,omitzero" smithy:"Addresses"`
	Birthdate   *SensitiveStringType `json:"Birthdate,omitempty" smithy:"Birthdate"`
	CreatedAt   *DateType            `json:"CreatedAt,omitempty" smithy:"CreatedAt"`
	CreatedBy   *StringType          `json:"CreatedBy,omitempty" smithy:"CreatedBy"`
	DisplayName *SensitiveStringType `json:"DisplayName,omitempty" smithy:"DisplayName"`
	Emails      Emails               `json:"Emails,omitzero" smithy:"Emails"`
	Extensions  Extensions           `json:"Extensions,omitzero" smithy:"Extensions"`
	ExternalIds ExternalIds          `json:"ExternalIds,omitzero" smithy:"ExternalIds"`
	// Required by the AWS service model.
	IdentityStoreId   *IdentityStoreId     `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	Locale            *SensitiveStringType `json:"Locale,omitempty" smithy:"Locale"`
	Name              *Name                `json:"Name,omitempty" smithy:"Name"`
	NickName          *SensitiveStringType `json:"NickName,omitempty" smithy:"NickName"`
	PhoneNumbers      PhoneNumbers         `json:"PhoneNumbers,omitzero" smithy:"PhoneNumbers"`
	Photos            Photos               `json:"Photos,omitzero" smithy:"Photos"`
	PreferredLanguage *SensitiveStringType `json:"PreferredLanguage,omitempty" smithy:"PreferredLanguage"`
	ProfileUrl        *SensitiveStringType `json:"ProfileUrl,omitempty" smithy:"ProfileUrl"`
	Roles             Roles                `json:"Roles,omitzero" smithy:"Roles"`
	Timezone          *SensitiveStringType `json:"Timezone,omitempty" smithy:"Timezone"`
	Title             *SensitiveStringType `json:"Title,omitempty" smithy:"Title"`
	UpdatedAt         *DateType            `json:"UpdatedAt,omitempty" smithy:"UpdatedAt"`
	UpdatedBy         *StringType          `json:"UpdatedBy,omitempty" smithy:"UpdatedBy"`
	// Required by the AWS service model.
	UserId     *ResourceId          `json:"UserId,omitempty" smithy:"UserId"`
	UserName   *UserName            `json:"UserName,omitempty" smithy:"UserName"`
	UserStatus *UserStatus          `json:"UserStatus,omitempty" smithy:"UserStatus"`
	UserType   *SensitiveStringType `json:"UserType,omitempty" smithy:"UserType"`
	Website    *SensitiveStringType `json:"Website,omitempty" smithy:"Website"`
}

// Email represents Smithy shape com.amazonaws.identitystore#Email.
type Email struct {
	Primary *BooleanType         `json:"Primary,omitempty" smithy:"Primary"`
	Type    *SensitiveStringType `json:"Type,omitempty" smithy:"Type"`
	Value   *SensitiveStringType `json:"Value,omitempty" smithy:"Value"`
}

// Emails represents Smithy shape com.amazonaws.identitystore#Emails.
type Emails []Email

// ExceptionMessage represents Smithy shape com.amazonaws.identitystore#ExceptionMessage.
type ExceptionMessage string

// ExtensionName represents Smithy shape com.amazonaws.identitystore#ExtensionName.
type ExtensionName string

// ExtensionNames represents Smithy shape com.amazonaws.identitystore#ExtensionNames.
type ExtensionNames []ExtensionName

// Extensions represents Smithy shape com.amazonaws.identitystore#Extensions.
type Extensions map[ExtensionName]AttributeValue

// ExternalId represents Smithy shape com.amazonaws.identitystore#ExternalId.
type ExternalId struct {
	// Required by the AWS service model.
	Id *ExternalIdIdentifier `json:"Id,omitempty" smithy:"Id"`
	// Required by the AWS service model.
	Issuer *ExternalIdIssuer `json:"Issuer,omitempty" smithy:"Issuer"`
}

// ExternalIdIdentifier represents Smithy shape com.amazonaws.identitystore#ExternalIdIdentifier.
type ExternalIdIdentifier string

// ExternalIdIssuer represents Smithy shape com.amazonaws.identitystore#ExternalIdIssuer.
type ExternalIdIssuer string

// ExternalIds represents Smithy shape com.amazonaws.identitystore#ExternalIds.
type ExternalIds []ExternalId

// Filter represents Smithy shape com.amazonaws.identitystore#Filter.
type Filter struct {
	// Required by the AWS service model.
	AttributePath *AttributePath `json:"AttributePath,omitempty" smithy:"AttributePath"`
	// Required by the AWS service model.
	AttributeValue *SensitiveStringType `json:"AttributeValue,omitempty" smithy:"AttributeValue"`
}

// Filters represents Smithy shape com.amazonaws.identitystore#Filters.
type Filters []Filter

// GetGroupIdRequest represents Smithy shape com.amazonaws.identitystore#GetGroupIdRequest.
type GetGroupIdRequest struct {
	// Required by the AWS service model.
	AlternateIdentifier *AlternateIdentifier `json:"AlternateIdentifier,omitempty" smithy:"AlternateIdentifier"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
}

// GetGroupIdResponse represents Smithy shape com.amazonaws.identitystore#GetGroupIdResponse.
type GetGroupIdResponse struct {
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
}

// GetGroupMembershipIdRequest represents Smithy shape com.amazonaws.identitystore#GetGroupMembershipIdRequest.
type GetGroupMembershipIdRequest struct {
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	MemberId *MemberId `json:"MemberId,omitempty" smithy:"MemberId"`
}

// GetGroupMembershipIdResponse represents Smithy shape com.amazonaws.identitystore#GetGroupMembershipIdResponse.
type GetGroupMembershipIdResponse struct {
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	MembershipId *ResourceId `json:"MembershipId,omitempty" smithy:"MembershipId"`
}

// GetUserIdRequest represents Smithy shape com.amazonaws.identitystore#GetUserIdRequest.
type GetUserIdRequest struct {
	// Required by the AWS service model.
	AlternateIdentifier *AlternateIdentifier `json:"AlternateIdentifier,omitempty" smithy:"AlternateIdentifier"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
}

// GetUserIdResponse represents Smithy shape com.amazonaws.identitystore#GetUserIdResponse.
type GetUserIdResponse struct {
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	UserId *ResourceId `json:"UserId,omitempty" smithy:"UserId"`
}

// Group represents Smithy shape com.amazonaws.identitystore#Group.
type Group struct {
	CreatedAt   *DateType            `json:"CreatedAt,omitempty" smithy:"CreatedAt"`
	CreatedBy   *StringType          `json:"CreatedBy,omitempty" smithy:"CreatedBy"`
	Description *SensitiveStringType `json:"Description,omitempty" smithy:"Description"`
	DisplayName *GroupDisplayName    `json:"DisplayName,omitempty" smithy:"DisplayName"`
	ExternalIds ExternalIds          `json:"ExternalIds,omitzero" smithy:"ExternalIds"`
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	UpdatedAt       *DateType        `json:"UpdatedAt,omitempty" smithy:"UpdatedAt"`
	UpdatedBy       *StringType      `json:"UpdatedBy,omitempty" smithy:"UpdatedBy"`
}

// GroupDisplayName represents Smithy shape com.amazonaws.identitystore#GroupDisplayName.
type GroupDisplayName string

// GroupIds represents Smithy shape com.amazonaws.identitystore#GroupIds.
type GroupIds []ResourceId

// GroupMembership represents Smithy shape com.amazonaws.identitystore#GroupMembership.
type GroupMembership struct {
	CreatedAt *DateType   `json:"CreatedAt,omitempty" smithy:"CreatedAt"`
	CreatedBy *StringType `json:"CreatedBy,omitempty" smithy:"CreatedBy"`
	GroupId   *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	MemberId        *MemberId        `json:"MemberId,omitempty" smithy:"MemberId"`
	MembershipId    *ResourceId      `json:"MembershipId,omitempty" smithy:"MembershipId"`
	UpdatedAt       *DateType        `json:"UpdatedAt,omitempty" smithy:"UpdatedAt"`
	UpdatedBy       *StringType      `json:"UpdatedBy,omitempty" smithy:"UpdatedBy"`
}

// GroupMembershipExistenceResult represents Smithy shape com.amazonaws.identitystore#GroupMembershipExistenceResult.
type GroupMembershipExistenceResult struct {
	GroupId          *ResourceId  `json:"GroupId,omitempty" smithy:"GroupId"`
	MemberId         *MemberId    `json:"MemberId,omitempty" smithy:"MemberId"`
	MembershipExists *BooleanType `json:"MembershipExists,omitempty" smithy:"MembershipExists"`
}

// GroupMembershipExistenceResults represents Smithy shape com.amazonaws.identitystore#GroupMembershipExistenceResults.
type GroupMembershipExistenceResults []GroupMembershipExistenceResult

// GroupMemberships represents Smithy shape com.amazonaws.identitystore#GroupMemberships.
type GroupMemberships []GroupMembership

// Groups represents Smithy shape com.amazonaws.identitystore#Groups.
type Groups []Group

// IdentityStoreId represents Smithy shape com.amazonaws.identitystore#IdentityStoreId.
type IdentityStoreId string

// InternalServerException represents Smithy shape com.amazonaws.identitystore#InternalServerException.
type InternalServerException struct {
	Message           *ExceptionMessage  `json:"Message,omitempty" smithy:"Message"`
	RequestId         *RequestId         `json:"RequestId,omitempty" smithy:"RequestId"`
	RetryAfterSeconds *RetryAfterSeconds `json:"RetryAfterSeconds,omitempty" smithy:"RetryAfterSeconds"`
}

// IsMemberInGroupsRequest represents Smithy shape com.amazonaws.identitystore#IsMemberInGroupsRequest.
type IsMemberInGroupsRequest struct {
	// Required by the AWS service model.
	GroupIds GroupIds `json:"GroupIds,omitzero" smithy:"GroupIds"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	MemberId *MemberId `json:"MemberId,omitempty" smithy:"MemberId"`
}

// IsMemberInGroupsResponse represents Smithy shape com.amazonaws.identitystore#IsMemberInGroupsResponse.
type IsMemberInGroupsResponse struct {
	// Required by the AWS service model.
	Results GroupMembershipExistenceResults `json:"Results,omitzero" smithy:"Results"`
}

// ListGroupMembershipsForMemberRequest represents Smithy shape com.amazonaws.identitystore#ListGroupMembershipsForMemberRequest.
type ListGroupMembershipsForMemberRequest struct {
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	MaxResults      *MaxResults      `json:"MaxResults,omitempty" smithy:"MaxResults"`
	// Required by the AWS service model.
	MemberId  *MemberId  `json:"MemberId,omitempty" smithy:"MemberId"`
	NextToken *NextToken `json:"NextToken,omitempty" smithy:"NextToken"`
}

// ListGroupMembershipsForMemberResponse represents Smithy shape com.amazonaws.identitystore#ListGroupMembershipsForMemberResponse.
type ListGroupMembershipsForMemberResponse struct {
	// Required by the AWS service model.
	GroupMemberships GroupMemberships `json:"GroupMemberships,omitzero" smithy:"GroupMemberships"`
	NextToken        *NextToken       `json:"NextToken,omitempty" smithy:"NextToken"`
}

// ListGroupMembershipsRequest represents Smithy shape com.amazonaws.identitystore#ListGroupMembershipsRequest.
type ListGroupMembershipsRequest struct {
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	MaxResults      *MaxResults      `json:"MaxResults,omitempty" smithy:"MaxResults"`
	NextToken       *NextToken       `json:"NextToken,omitempty" smithy:"NextToken"`
}

// ListGroupMembershipsResponse represents Smithy shape com.amazonaws.identitystore#ListGroupMembershipsResponse.
type ListGroupMembershipsResponse struct {
	// Required by the AWS service model.
	GroupMemberships GroupMemberships `json:"GroupMemberships,omitzero" smithy:"GroupMemberships"`
	NextToken        *NextToken       `json:"NextToken,omitempty" smithy:"NextToken"`
}

// ListGroupsRequest represents Smithy shape com.amazonaws.identitystore#ListGroupsRequest.
type ListGroupsRequest struct {
	Filters Filters `json:"Filters,omitzero" smithy:"Filters"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	MaxResults      *MaxResults      `json:"MaxResults,omitempty" smithy:"MaxResults"`
	NextToken       *NextToken       `json:"NextToken,omitempty" smithy:"NextToken"`
}

// ListGroupsResponse represents Smithy shape com.amazonaws.identitystore#ListGroupsResponse.
type ListGroupsResponse struct {
	// Required by the AWS service model.
	Groups    Groups     `json:"Groups,omitzero" smithy:"Groups"`
	NextToken *NextToken `json:"NextToken,omitempty" smithy:"NextToken"`
}

// ListUsersRequest represents Smithy shape com.amazonaws.identitystore#ListUsersRequest.
type ListUsersRequest struct {
	Extensions ExtensionNames `json:"Extensions,omitzero" smithy:"Extensions"`
	Filters    Filters        `json:"Filters,omitzero" smithy:"Filters"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	MaxResults      *MaxResults      `json:"MaxResults,omitempty" smithy:"MaxResults"`
	NextToken       *NextToken       `json:"NextToken,omitempty" smithy:"NextToken"`
}

// ListUsersResponse represents Smithy shape com.amazonaws.identitystore#ListUsersResponse.
type ListUsersResponse struct {
	NextToken *NextToken `json:"NextToken,omitempty" smithy:"NextToken"`
	// Required by the AWS service model.
	Users Users `json:"Users,omitzero" smithy:"Users"`
}

// MaxResults represents Smithy shape com.amazonaws.identitystore#MaxResults.
type MaxResults int32

// MemberId represents Smithy shape com.amazonaws.identitystore#MemberId.
type MemberId struct {
	UserId *ResourceId `json:"UserId,omitempty" smithy:"UserId"`
}

// Name represents Smithy shape com.amazonaws.identitystore#Name.
type Name struct {
	FamilyName      *SensitiveStringType `json:"FamilyName,omitempty" smithy:"FamilyName"`
	Formatted       *SensitiveStringType `json:"Formatted,omitempty" smithy:"Formatted"`
	GivenName       *SensitiveStringType `json:"GivenName,omitempty" smithy:"GivenName"`
	HonorificPrefix *SensitiveStringType `json:"HonorificPrefix,omitempty" smithy:"HonorificPrefix"`
	HonorificSuffix *SensitiveStringType `json:"HonorificSuffix,omitempty" smithy:"HonorificSuffix"`
	MiddleName      *SensitiveStringType `json:"MiddleName,omitempty" smithy:"MiddleName"`
}

// NextToken represents Smithy shape com.amazonaws.identitystore#NextToken.
type NextToken string

// PhoneNumber represents Smithy shape com.amazonaws.identitystore#PhoneNumber.
type PhoneNumber struct {
	Primary *BooleanType         `json:"Primary,omitempty" smithy:"Primary"`
	Type    *SensitiveStringType `json:"Type,omitempty" smithy:"Type"`
	Value   *SensitiveStringType `json:"Value,omitempty" smithy:"Value"`
}

// PhoneNumbers represents Smithy shape com.amazonaws.identitystore#PhoneNumbers.
type PhoneNumbers []PhoneNumber

// Photo represents Smithy shape com.amazonaws.identitystore#Photo.
type Photo struct {
	Display *SensitiveStringType `json:"Display,omitempty" smithy:"Display"`
	Primary *BooleanType         `json:"Primary,omitempty" smithy:"Primary"`
	Type    *SensitiveStringType `json:"Type,omitempty" smithy:"Type"`
	// Required by the AWS service model.
	Value *SensitiveStringType `json:"Value,omitempty" smithy:"Value"`
}

// Photos represents Smithy shape com.amazonaws.identitystore#Photos.
type Photos []Photo

// RequestId represents Smithy shape com.amazonaws.identitystore#RequestId.
type RequestId string

// ResourceId represents Smithy shape com.amazonaws.identitystore#ResourceId.
type ResourceId string

// ResourceNotFoundException represents Smithy shape com.amazonaws.identitystore#ResourceNotFoundException.
type ResourceNotFoundException struct {
	Message      *ExceptionMessage                `json:"Message,omitempty" smithy:"Message"`
	Reason       *ResourceNotFoundExceptionReason `json:"Reason,omitempty" smithy:"Reason"`
	RequestId    *RequestId                       `json:"RequestId,omitempty" smithy:"RequestId"`
	ResourceId   *ResourceId                      `json:"ResourceId,omitempty" smithy:"ResourceId"`
	ResourceType *ResourceType                    `json:"ResourceType,omitempty" smithy:"ResourceType"`
}

// ResourceNotFoundExceptionReason represents Smithy shape com.amazonaws.identitystore#ResourceNotFoundExceptionReason.
type ResourceNotFoundExceptionReason string

const (
	ResourceNotFoundExceptionReasonKMS_KEY_NOT_FOUND ResourceNotFoundExceptionReason = "KMS_KEY_NOT_FOUND"
)

// ResourceType represents Smithy shape com.amazonaws.identitystore#ResourceType.
type ResourceType string

const (
	ResourceTypeGROUP            ResourceType = "GROUP"
	ResourceTypeGROUP_MEMBERSHIP ResourceType = "GROUP_MEMBERSHIP"
	ResourceTypeIDENTITY_STORE   ResourceType = "IDENTITY_STORE"
	ResourceTypeRESOURCE_POLICY  ResourceType = "RESOURCE_POLICY"
	ResourceTypeUSER             ResourceType = "USER"
)

// RetryAfterSeconds represents Smithy shape com.amazonaws.identitystore#RetryAfterSeconds.
type RetryAfterSeconds int32

// Role represents Smithy shape com.amazonaws.identitystore#Role.
type Role struct {
	Primary *BooleanType         `json:"Primary,omitempty" smithy:"Primary"`
	Type    *SensitiveStringType `json:"Type,omitempty" smithy:"Type"`
	Value   *SensitiveStringType `json:"Value,omitempty" smithy:"Value"`
}

// Roles represents Smithy shape com.amazonaws.identitystore#Roles.
type Roles []Role

// SensitiveStringType represents Smithy shape com.amazonaws.identitystore#SensitiveStringType.
type SensitiveStringType string

// ServiceQuotaExceededException represents Smithy shape com.amazonaws.identitystore#ServiceQuotaExceededException.
type ServiceQuotaExceededException struct {
	Message   *ExceptionMessage `json:"Message,omitempty" smithy:"Message"`
	RequestId *RequestId        `json:"RequestId,omitempty" smithy:"RequestId"`
}

// StringType represents Smithy shape com.amazonaws.identitystore#StringType.
type StringType string

// ThrottlingException represents Smithy shape com.amazonaws.identitystore#ThrottlingException.
type ThrottlingException struct {
	Message           *ExceptionMessage          `json:"Message,omitempty" smithy:"Message"`
	Reason            *ThrottlingExceptionReason `json:"Reason,omitempty" smithy:"Reason"`
	RequestId         *RequestId                 `json:"RequestId,omitempty" smithy:"RequestId"`
	RetryAfterSeconds *RetryAfterSeconds         `json:"RetryAfterSeconds,omitempty" smithy:"RetryAfterSeconds"`
}

// ThrottlingExceptionReason represents Smithy shape com.amazonaws.identitystore#ThrottlingExceptionReason.
type ThrottlingExceptionReason string

const (
	ThrottlingExceptionReasonKMS_THROTTLING ThrottlingExceptionReason = "KMS_THROTTLING"
)

// UniqueAttribute represents Smithy shape com.amazonaws.identitystore#UniqueAttribute.
type UniqueAttribute struct {
	// Required by the AWS service model.
	AttributePath *AttributePath `json:"AttributePath,omitempty" smithy:"AttributePath"`
	// Required by the AWS service model.
	AttributeValue AttributeValue `json:"AttributeValue,omitempty" smithy:"AttributeValue"`
}

// UpdateGroupRequest represents Smithy shape com.amazonaws.identitystore#UpdateGroupRequest.
type UpdateGroupRequest struct {
	// Required by the AWS service model.
	GroupId *ResourceId `json:"GroupId,omitempty" smithy:"GroupId"`
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	Operations AttributeOperations `json:"Operations,omitzero" smithy:"Operations"`
}

// UpdateGroupResponse represents Smithy shape com.amazonaws.identitystore#UpdateGroupResponse.
type UpdateGroupResponse struct {
}

// UpdateUserRequest represents Smithy shape com.amazonaws.identitystore#UpdateUserRequest.
type UpdateUserRequest struct {
	// Required by the AWS service model.
	IdentityStoreId *IdentityStoreId `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	// Required by the AWS service model.
	Operations AttributeOperations `json:"Operations,omitzero" smithy:"Operations"`
	// Required by the AWS service model.
	UserId *ResourceId `json:"UserId,omitempty" smithy:"UserId"`
}

// UpdateUserResponse represents Smithy shape com.amazonaws.identitystore#UpdateUserResponse.
type UpdateUserResponse struct {
}

// User represents Smithy shape com.amazonaws.identitystore#User.
type User struct {
	Addresses   Addresses            `json:"Addresses,omitzero" smithy:"Addresses"`
	Birthdate   *SensitiveStringType `json:"Birthdate,omitempty" smithy:"Birthdate"`
	CreatedAt   *DateType            `json:"CreatedAt,omitempty" smithy:"CreatedAt"`
	CreatedBy   *StringType          `json:"CreatedBy,omitempty" smithy:"CreatedBy"`
	DisplayName *SensitiveStringType `json:"DisplayName,omitempty" smithy:"DisplayName"`
	Emails      Emails               `json:"Emails,omitzero" smithy:"Emails"`
	Extensions  Extensions           `json:"Extensions,omitzero" smithy:"Extensions"`
	ExternalIds ExternalIds          `json:"ExternalIds,omitzero" smithy:"ExternalIds"`
	// Required by the AWS service model.
	IdentityStoreId   *IdentityStoreId     `json:"IdentityStoreId,omitempty" smithy:"IdentityStoreId"`
	Locale            *SensitiveStringType `json:"Locale,omitempty" smithy:"Locale"`
	Name              *Name                `json:"Name,omitempty" smithy:"Name"`
	NickName          *SensitiveStringType `json:"NickName,omitempty" smithy:"NickName"`
	PhoneNumbers      PhoneNumbers         `json:"PhoneNumbers,omitzero" smithy:"PhoneNumbers"`
	Photos            Photos               `json:"Photos,omitzero" smithy:"Photos"`
	PreferredLanguage *SensitiveStringType `json:"PreferredLanguage,omitempty" smithy:"PreferredLanguage"`
	ProfileUrl        *SensitiveStringType `json:"ProfileUrl,omitempty" smithy:"ProfileUrl"`
	Roles             Roles                `json:"Roles,omitzero" smithy:"Roles"`
	Timezone          *SensitiveStringType `json:"Timezone,omitempty" smithy:"Timezone"`
	Title             *SensitiveStringType `json:"Title,omitempty" smithy:"Title"`
	UpdatedAt         *DateType            `json:"UpdatedAt,omitempty" smithy:"UpdatedAt"`
	UpdatedBy         *StringType          `json:"UpdatedBy,omitempty" smithy:"UpdatedBy"`
	// Required by the AWS service model.
	UserId     *ResourceId          `json:"UserId,omitempty" smithy:"UserId"`
	UserName   *UserName            `json:"UserName,omitempty" smithy:"UserName"`
	UserStatus *UserStatus          `json:"UserStatus,omitempty" smithy:"UserStatus"`
	UserType   *SensitiveStringType `json:"UserType,omitempty" smithy:"UserType"`
	Website    *SensitiveStringType `json:"Website,omitempty" smithy:"Website"`
}

// UserName represents Smithy shape com.amazonaws.identitystore#UserName.
type UserName string

// UserStatus represents Smithy shape com.amazonaws.identitystore#UserStatus.
type UserStatus string

const (
	UserStatusDISABLED UserStatus = "DISABLED"
	UserStatusENABLED  UserStatus = "ENABLED"
)

// Users represents Smithy shape com.amazonaws.identitystore#Users.
type Users []User

// ValidationException represents Smithy shape com.amazonaws.identitystore#ValidationException.
type ValidationException struct {
	Message   *ExceptionMessage          `json:"Message,omitempty" smithy:"Message"`
	Reason    *ValidationExceptionReason `json:"Reason,omitempty" smithy:"Reason"`
	RequestId *RequestId                 `json:"RequestId,omitempty" smithy:"RequestId"`
}

// ValidationExceptionReason represents Smithy shape com.amazonaws.identitystore#ValidationExceptionReason.
type ValidationExceptionReason string

const (
	ValidationExceptionReasonKMS_DISABLED          ValidationExceptionReason = "KMS_DISABLED"
	ValidationExceptionReasonKMS_INVALID_ARN       ValidationExceptionReason = "KMS_INVALID_ARN"
	ValidationExceptionReasonKMS_INVALID_KEY_USAGE ValidationExceptionReason = "KMS_INVALID_KEY_USAGE"
	ValidationExceptionReasonKMS_INVALID_STATE     ValidationExceptionReason = "KMS_INVALID_STATE"
)

// Unit represents Smithy shape smithy.api#Unit.
type Unit struct {
}
type CreateGroupInput = CreateGroupRequest
type CreateGroupOutput = CreateGroupResponse
type CreateGroupMembershipInput = CreateGroupMembershipRequest
type CreateGroupMembershipOutput = CreateGroupMembershipResponse
type CreateUserInput = CreateUserRequest
type CreateUserOutput = CreateUserResponse
type DeleteGroupInput = DeleteGroupRequest
type DeleteGroupOutput = DeleteGroupResponse
type DeleteGroupMembershipInput = DeleteGroupMembershipRequest
type DeleteGroupMembershipOutput = DeleteGroupMembershipResponse
type DeleteUserInput = DeleteUserRequest
type DeleteUserOutput = DeleteUserResponse
type DescribeGroupInput = DescribeGroupRequest
type DescribeGroupOutput = DescribeGroupResponse
type DescribeGroupMembershipInput = DescribeGroupMembershipRequest
type DescribeGroupMembershipOutput = DescribeGroupMembershipResponse
type DescribeUserInput = DescribeUserRequest
type DescribeUserOutput = DescribeUserResponse
type GetGroupIdInput = GetGroupIdRequest
type GetGroupIdOutput = GetGroupIdResponse
type GetGroupMembershipIdInput = GetGroupMembershipIdRequest
type GetGroupMembershipIdOutput = GetGroupMembershipIdResponse
type GetUserIdInput = GetUserIdRequest
type GetUserIdOutput = GetUserIdResponse
type IsMemberInGroupsInput = IsMemberInGroupsRequest
type IsMemberInGroupsOutput = IsMemberInGroupsResponse
type ListGroupMembershipsInput = ListGroupMembershipsRequest
type ListGroupMembershipsOutput = ListGroupMembershipsResponse
type ListGroupMembershipsForMemberInput = ListGroupMembershipsForMemberRequest
type ListGroupMembershipsForMemberOutput = ListGroupMembershipsForMemberResponse
type ListGroupsInput = ListGroupsRequest
type ListGroupsOutput = ListGroupsResponse
type ListUsersInput = ListUsersRequest
type ListUsersOutput = ListUsersResponse
type UpdateGroupInput = UpdateGroupRequest
type UpdateGroupOutput = UpdateGroupResponse
type UpdateUserInput = UpdateUserRequest
type UpdateUserOutput = UpdateUserResponse
