// Code generated from the AWS Organizations AI opt-out policy syntax; DO NOT EDIT.
// Source: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_ai-opt-out_syntax.md
package organizations

var aiOptOutServices = map[string]bool{
	"aidevops":                  true,
	"aiops":                     true,
	"awssupplychain":            true,
	"biodiscovery":              true,
	"chimesdkvoiceanalytics":    true,
	"cloudwatch":                true,
	"codeguruprofiler":          true,
	"codewhisperer":             true,
	"comprehend":                true,
	"config":                    true,
	"connect":                   true,
	"connectamd":                true,
	"connectdecision":           true,
	"connecthealth::operations": true,
	"connecthealth::training":   true,
	"connectoptimization":       true,
	"contactlens":               true,
	"datazone":                  true,
	"default":                   true,
	"dms":                       true,
	"entityresolution":          true,
	"finopsagent":               true,
	"frauddetector":             true,
	"glue":                      true,
	"guardduty":                 true,
	"lex":                       true,
	"polly":                     true,
	"q":                         true,
	"quicksightq":               true,
	"rekognition":               true,
	"scenariodiscovery":         true,
	"securityhub":               true,
	"securitylake":              true,
	"textract":                  true,
	"transcribe":                true,
	"transform":                 true,
	"translate":                 true,
	"workspaces":                true,
}
