// Code generated by awsgen from AWS SDK for Go v2 Smithy models; DO NOT EDIT.
package ecs

import (
	"fmt"

	"stackd/internal/awsapi"
	"stackd/internal/awscatalog"
)

// DecodeRequest binds wire input to a generated operation DTO and validates
// its Smithy constraints. Business logic remains the service provider's responsibility.
// Known operation metadata is retained on failure; Input is set only after validation.
func DecodeRequest(operation string, request awsapi.Request) (awsapi.DecodedRequest, error) {
	service, _ := awscatalog.LookupService("ecs")
	if request.Protocol != "" {
		service.Protocol = request.Protocol
	}
	op, ok := service.Operation(operation)
	if !ok {
		return awsapi.DecodedRequest{}, fmt.Errorf("%w: %s", awsapi.ErrUnknownOperation, operation)
	}
	decoded := awsapi.DecodedRequest{Operation: op, Protocol: service.Protocol, Body: request.Body}
	input, err := NewInput(operation)
	if err != nil {
		return decoded, err
	}
	if err := awsapi.Decode(service, op, request, input); err != nil {
		return decoded, err
	}
	decoded.Input = input
	return decoded, nil
}

// NewInput allocates the generated operation DTO without binding or admitting a request.
// Error observers may bind rejected input for service-owned, model-redacted audit projection.
func NewInput(operation string) (any, error) {
	switch operation {
	case "ContinueServiceDeployment":
		return new(ContinueServiceDeploymentRequest), nil
	case "CreateCapacityProvider":
		return new(CreateCapacityProviderRequest), nil
	case "CreateCluster":
		return new(CreateClusterRequest), nil
	case "CreateDaemon":
		return new(CreateDaemonRequest), nil
	case "CreateExpressGatewayService":
		return new(CreateExpressGatewayServiceRequest), nil
	case "CreateService":
		return new(CreateServiceRequest), nil
	case "CreateTaskSet":
		return new(CreateTaskSetRequest), nil
	case "DeleteAccountSetting":
		return new(DeleteAccountSettingRequest), nil
	case "DeleteAttributes":
		return new(DeleteAttributesRequest), nil
	case "DeleteCapacityProvider":
		return new(DeleteCapacityProviderRequest), nil
	case "DeleteCluster":
		return new(DeleteClusterRequest), nil
	case "DeleteDaemon":
		return new(DeleteDaemonRequest), nil
	case "DeleteDaemonTaskDefinition":
		return new(DeleteDaemonTaskDefinitionRequest), nil
	case "DeleteExpressGatewayService":
		return new(DeleteExpressGatewayServiceRequest), nil
	case "DeleteService":
		return new(DeleteServiceRequest), nil
	case "DeleteTaskDefinitions":
		return new(DeleteTaskDefinitionsRequest), nil
	case "DeleteTaskSet":
		return new(DeleteTaskSetRequest), nil
	case "DeregisterContainerInstance":
		return new(DeregisterContainerInstanceRequest), nil
	case "DeregisterTaskDefinition":
		return new(DeregisterTaskDefinitionRequest), nil
	case "DescribeCapacityProviders":
		return new(DescribeCapacityProvidersRequest), nil
	case "DescribeClusters":
		return new(DescribeClustersRequest), nil
	case "DescribeContainerInstances":
		return new(DescribeContainerInstancesRequest), nil
	case "DescribeDaemon":
		return new(DescribeDaemonRequest), nil
	case "DescribeDaemonDeployments":
		return new(DescribeDaemonDeploymentsRequest), nil
	case "DescribeDaemonRevisions":
		return new(DescribeDaemonRevisionsRequest), nil
	case "DescribeDaemonTaskDefinition":
		return new(DescribeDaemonTaskDefinitionRequest), nil
	case "DescribeExpressGatewayService":
		return new(DescribeExpressGatewayServiceRequest), nil
	case "DescribeServiceDeployments":
		return new(DescribeServiceDeploymentsRequest), nil
	case "DescribeServiceRevisions":
		return new(DescribeServiceRevisionsRequest), nil
	case "DescribeServices":
		return new(DescribeServicesRequest), nil
	case "DescribeTaskDefinition":
		return new(DescribeTaskDefinitionRequest), nil
	case "DescribeTaskSets":
		return new(DescribeTaskSetsRequest), nil
	case "DescribeTasks":
		return new(DescribeTasksRequest), nil
	case "DiscoverPollEndpoint":
		return new(DiscoverPollEndpointRequest), nil
	case "ExecuteCommand":
		return new(ExecuteCommandRequest), nil
	case "GetTaskProtection":
		return new(GetTaskProtectionRequest), nil
	case "ListAccountSettings":
		return new(ListAccountSettingsRequest), nil
	case "ListAttributes":
		return new(ListAttributesRequest), nil
	case "ListClusters":
		return new(ListClustersRequest), nil
	case "ListContainerInstances":
		return new(ListContainerInstancesRequest), nil
	case "ListDaemonDeployments":
		return new(ListDaemonDeploymentsRequest), nil
	case "ListDaemonTaskDefinitions":
		return new(ListDaemonTaskDefinitionsRequest), nil
	case "ListDaemons":
		return new(ListDaemonsRequest), nil
	case "ListServiceDeployments":
		return new(ListServiceDeploymentsRequest), nil
	case "ListServices":
		return new(ListServicesRequest), nil
	case "ListServicesByNamespace":
		return new(ListServicesByNamespaceRequest), nil
	case "ListTagsForResource":
		return new(ListTagsForResourceRequest), nil
	case "ListTaskDefinitionFamilies":
		return new(ListTaskDefinitionFamiliesRequest), nil
	case "ListTaskDefinitions":
		return new(ListTaskDefinitionsRequest), nil
	case "ListTasks":
		return new(ListTasksRequest), nil
	case "PutAccountSetting":
		return new(PutAccountSettingRequest), nil
	case "PutAccountSettingDefault":
		return new(PutAccountSettingDefaultRequest), nil
	case "PutAttributes":
		return new(PutAttributesRequest), nil
	case "PutClusterCapacityProviders":
		return new(PutClusterCapacityProvidersRequest), nil
	case "RegisterContainerInstance":
		return new(RegisterContainerInstanceRequest), nil
	case "RegisterDaemonTaskDefinition":
		return new(RegisterDaemonTaskDefinitionRequest), nil
	case "RegisterTaskDefinition":
		return new(RegisterTaskDefinitionRequest), nil
	case "RunTask":
		return new(RunTaskRequest), nil
	case "StartTask":
		return new(StartTaskRequest), nil
	case "StopServiceDeployment":
		return new(StopServiceDeploymentRequest), nil
	case "StopTask":
		return new(StopTaskRequest), nil
	case "SubmitAttachmentStateChanges":
		return new(SubmitAttachmentStateChangesRequest), nil
	case "SubmitContainerStateChange":
		return new(SubmitContainerStateChangeRequest), nil
	case "SubmitTaskStateChange":
		return new(SubmitTaskStateChangeRequest), nil
	case "TagResource":
		return new(TagResourceRequest), nil
	case "UntagResource":
		return new(UntagResourceRequest), nil
	case "UpdateCapacityProvider":
		return new(UpdateCapacityProviderRequest), nil
	case "UpdateCluster":
		return new(UpdateClusterRequest), nil
	case "UpdateClusterSettings":
		return new(UpdateClusterSettingsRequest), nil
	case "UpdateContainerAgent":
		return new(UpdateContainerAgentRequest), nil
	case "UpdateContainerInstancesState":
		return new(UpdateContainerInstancesStateRequest), nil
	case "UpdateDaemon":
		return new(UpdateDaemonRequest), nil
	case "UpdateExpressGatewayService":
		return new(UpdateExpressGatewayServiceRequest), nil
	case "UpdateService":
		return new(UpdateServiceRequest), nil
	case "UpdateServicePrimaryTaskSet":
		return new(UpdateServicePrimaryTaskSetRequest), nil
	case "UpdateTaskProtection":
		return new(UpdateTaskProtectionRequest), nil
	case "UpdateTaskSet":
		return new(UpdateTaskSetRequest), nil
	default:
		return nil, fmt.Errorf("%w: %s", awsapi.ErrUnknownOperation, operation)
	}
}
