// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Apigatewayv2Api struct {
	Partition                string
	AccountID                string
	Region                   string
	ID                       string
	Name                     string
	Description              string
	Version                  string
	Disabled                 int64
	CreatedAt                time.Time
	Tags                     []byte
	ProtocolType             string
	RouteSelectionExpression string
	OwnerStackID             string
	OwnerLogicalID           string
	OwnerToken               string
}

type Apigatewayv2Authorizer struct {
	Partition            string
	AccountID            string
	Region               string
	GatewayID            string
	ID                   string
	Name                 string
	Issuer               string
	Audiences            []byte
	AuthorizerType       string
	Uri                  string
	FunctionArn          string
	PayloadVersion       string
	IdentitySources      []byte
	TtlSeconds           int64
	SimpleResponses      int64
	CredentialsArn       string
	ValidationExpression string
	OwnerStackID         string
	OwnerLogicalID       string
	OwnerToken           string
}

type Apigatewayv2AuthorizerCache struct {
	Partition      string
	AccountID      string
	Region         string
	GatewayID      string
	StageID        string
	AuthorizerID   string
	IdentityKey    string
	PrincipalID    string
	PolicyDocument []byte
	Context        []byte
	IsAuthorized   sql.NullInt64
	ExpiresAt      time.Time
}

type Apigatewayv2DeployedRoute struct {
	Partition                 string
	AccountID                 string
	Region                    string
	GatewayID                 string
	DeploymentID              string
	RouteID                   string
	RouteKey                  string
	FunctionArn               string
	PayloadVersion            string
	AuthorizationType         string
	Issuer                    string
	Audiences                 []byte
	Scopes                    []byte
	AuthorizerID              string
	AuthorizerType            string
	AuthorizerFunctionArn     string
	AuthorizerPayloadVersion  string
	AuthorizerIdentitySources []byte
	AuthorizerTtlSeconds      int64
	AuthorizerSimpleResponses int64
	AuthorizerCredentialsArn  string
	WebsocketResponseEnabled  int64
	TimeoutMillis             int64
	CredentialsArn            string
}

type Apigatewayv2Deployment struct {
	Partition                string
	AccountID                string
	Region                   string
	GatewayID                string
	ID                       string
	Description              string
	AutoDeployed             int64
	CreatedAt                time.Time
	RouteSelectionExpression string
	OwnerStackID             string
	OwnerLogicalID           string
	OwnerToken               string
}

type Apigatewayv2Domain struct {
	Partition               string
	AccountID               string
	Region                  string
	Name                    string
	OwnerStackID            string
	OwnerLogicalID          string
	OwnerToken              string
	CertificateArn          string
	CertificateID           string
	CertificateName         string
	OwnershipCertificateArn string
	OwnershipCertificateID  string
	SecurityPolicy          string
	IpAddressType           string
	TruststoreUri           string
	TruststoreVersion       string
	TruststorePem           []byte
	Tags                    []byte
}

type Apigatewayv2Integration struct {
	Partition           string
	AccountID           string
	Region              string
	GatewayID           string
	ID                  string
	Description         string
	Uri                 string
	PayloadVersion      string
	TimeoutMillis       int64
	PassthroughBehavior string
	CredentialsArn      string
	OwnerStackID        string
	OwnerLogicalID      string
	OwnerToken          string
}

type Apigatewayv2Mapping struct {
	Partition      string
	AccountID      string
	Region         string
	DomainName     string
	ID             string
	OwnerStackID   string
	OwnerLogicalID string
	OwnerToken     string
	ApiID          string
	Stage          string
	Path           string
}

type Apigatewayv2Route struct {
	Partition                        string
	AccountID                        string
	Region                           string
	GatewayID                        string
	ID                               string
	RouteKey                         string
	Target                           string
	AuthorizationType                string
	AuthorizerID                     string
	OperationName                    string
	Scopes                           []byte
	RouteResponseSelectionExpression string
	OwnerStackID                     string
	OwnerLogicalID                   string
	OwnerToken                       string
}

type Apigatewayv2RouteResponse struct {
	Partition      string
	AccountID      string
	Region         string
	GatewayID      string
	ID             string
	RouteID        string
	ResponseKey    string
	OwnerStackID   string
	OwnerLogicalID string
	OwnerToken     string
}

type Apigatewayv2RouteSetting struct {
	Partition       string
	AccountID       string
	Region          string
	GatewayID       string
	Stage           string
	RouteKey        string
	DetailedMetrics sql.NullBool
	LoggingLevel    string
	DataTrace       sql.NullBool
}

type Apigatewayv2Stage struct {
	Partition                   string
	AccountID                   string
	Region                      string
	GatewayID                   string
	ID                          string
	Description                 string
	DeploymentID                string
	LastDeploymentStatusMessage string
	AutoDeploy                  int64
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	Variables                   []byte
	Tags                        []byte
	DetailedMetrics             bool
	LoggingLevel                string
	DataTrace                   bool
	AccessLogDestinationArn     string
	AccessLogFormat             string
	OwnerStackID                string
	OwnerLogicalID              string
	OwnerToken                  string
}
