// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
)

const allDomains = `-- name: AllDomains :many
SELECT "partition", account_id, region, name, incarnation, engine_version, status, native_endpoint, last_error, access_policy, instance_type, instance_count, created, updated, due, version, config_version FROM opensearch_domain ORDER BY partition, account_id, region, name
`

func (q *Queries) AllDomains(ctx context.Context) ([]OpensearchDomain, error) {
	rows, err := q.db.QueryContext(ctx, allDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpensearchDomain{}
	for rows.Next() {
		var i OpensearchDomain
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.Name,
			&i.Incarnation,
			&i.EngineVersion,
			&i.Status,
			&i.NativeEndpoint,
			&i.LastError,
			&i.AccessPolicy,
			&i.InstanceType,
			&i.InstanceCount,
			&i.Created,
			&i.Updated,
			&i.Due,
			&i.Version,
			&i.ConfigVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAdvancedOptions = `-- name: DeleteAdvancedOptions :exec
DELETE FROM opensearch_advanced_option WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4
`

type DeleteAdvancedOptionsParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

func (q *Queries) DeleteAdvancedOptions(ctx context.Context, arg DeleteAdvancedOptionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteAdvancedOptions,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	return err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM opensearch_domain WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4
`

type DeleteDomainParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) error {
	_, err := q.db.ExecContext(ctx, deleteDomain,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	return err
}

const deletePolicyPrincipals = `-- name: DeletePolicyPrincipals :exec
DELETE FROM opensearch_policy_principal WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4
`

type DeletePolicyPrincipalsParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

func (q *Queries) DeletePolicyPrincipals(ctx context.Context, arg DeletePolicyPrincipalsParams) error {
	_, err := q.db.ExecContext(ctx, deletePolicyPrincipals,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	return err
}

const deleteTags = `-- name: DeleteTags :exec
DELETE FROM opensearch_tag WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4
`

type DeleteTagsParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

func (q *Queries) DeleteTags(ctx context.Context, arg DeleteTagsParams) error {
	_, err := q.db.ExecContext(ctx, deleteTags,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	return err
}

const getDomain = `-- name: GetDomain :one
SELECT "partition", account_id, region, name, incarnation, engine_version, status, native_endpoint, last_error, access_policy, instance_type, instance_count, created, updated, due, version, config_version FROM opensearch_domain WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4
`

type GetDomainParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

func (q *Queries) GetDomain(ctx context.Context, arg GetDomainParams) (OpensearchDomain, error) {
	row := q.db.QueryRowContext(ctx, getDomain,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	var i OpensearchDomain
	err := row.Scan(
		&i.Partition,
		&i.AccountID,
		&i.Region,
		&i.Name,
		&i.Incarnation,
		&i.EngineVersion,
		&i.Status,
		&i.NativeEndpoint,
		&i.LastError,
		&i.AccessPolicy,
		&i.InstanceType,
		&i.InstanceCount,
		&i.Created,
		&i.Updated,
		&i.Due,
		&i.Version,
		&i.ConfigVersion,
	)
	return i, err
}

const listAdvancedOptions = `-- name: ListAdvancedOptions :many
SELECT option_key, option_value FROM opensearch_advanced_option WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4 ORDER BY option_key
`

type ListAdvancedOptionsParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

type ListAdvancedOptionsRow struct {
	OptionKey   string
	OptionValue string
}

func (q *Queries) ListAdvancedOptions(ctx context.Context, arg ListAdvancedOptionsParams) ([]ListAdvancedOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdvancedOptions,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdvancedOptionsRow{}
	for rows.Next() {
		var i ListAdvancedOptionsRow
		if err := rows.Scan(&i.OptionKey, &i.OptionValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT "partition", account_id, region, name, incarnation, engine_version, status, native_endpoint, last_error, access_policy, instance_type, instance_count, created, updated, due, version, config_version FROM opensearch_domain WHERE partition = ?1 AND account_id = ?2 AND region = ?3 ORDER BY name
`

type ListDomainsParams struct {
	Partition string
	AccountID string
	Region    string
}

func (q *Queries) ListDomains(ctx context.Context, arg ListDomainsParams) ([]OpensearchDomain, error) {
	rows, err := q.db.QueryContext(ctx, listDomains, arg.Partition, arg.AccountID, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpensearchDomain{}
	for rows.Next() {
		var i OpensearchDomain
		if err := rows.Scan(
			&i.Partition,
			&i.AccountID,
			&i.Region,
			&i.Name,
			&i.Incarnation,
			&i.EngineVersion,
			&i.Status,
			&i.NativeEndpoint,
			&i.LastError,
			&i.AccessPolicy,
			&i.InstanceType,
			&i.InstanceCount,
			&i.Created,
			&i.Updated,
			&i.Due,
			&i.Version,
			&i.ConfigVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyPrincipals = `-- name: ListPolicyPrincipals :many
SELECT principal_arn, principal_id FROM opensearch_policy_principal WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4 ORDER BY principal_arn
`

type ListPolicyPrincipalsParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

type ListPolicyPrincipalsRow struct {
	PrincipalArn string
	PrincipalID  string
}

func (q *Queries) ListPolicyPrincipals(ctx context.Context, arg ListPolicyPrincipalsParams) ([]ListPolicyPrincipalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPolicyPrincipals,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPolicyPrincipalsRow{}
	for rows.Next() {
		var i ListPolicyPrincipalsRow
		if err := rows.Scan(&i.PrincipalArn, &i.PrincipalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT tag_key, tag_value FROM opensearch_tag WHERE partition = ?1 AND account_id = ?2 AND region = ?3 AND name = ?4 ORDER BY tag_key
`

type ListTagsParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
}

type ListTagsRow struct {
	TagKey   string
	TagValue string
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.TagKey, &i.TagValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putAdvancedOption = `-- name: PutAdvancedOption :exec
INSERT INTO opensearch_advanced_option (partition, account_id, region, name, option_key, option_value) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type PutAdvancedOptionParams struct {
	Partition   string
	AccountID   string
	Region      string
	Name        string
	OptionKey   string
	OptionValue string
}

func (q *Queries) PutAdvancedOption(ctx context.Context, arg PutAdvancedOptionParams) error {
	_, err := q.db.ExecContext(ctx, putAdvancedOption,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.OptionKey,
		arg.OptionValue,
	)
	return err
}

const putDomain = `-- name: PutDomain :exec
INSERT INTO opensearch_domain (
 partition, account_id, region, name, incarnation, engine_version, status,
 native_endpoint, last_error, access_policy, instance_type, instance_count,
 created, updated, due, version, config_version
) VALUES (
 ?1, ?2, ?3, ?4,
 ?5, ?6, ?7,
 ?8, ?9, ?10,
 ?11, ?12, ?13,
 ?14, ?15, ?16, ?17
) ON CONFLICT (partition, account_id, region, name) DO UPDATE SET
 incarnation = excluded.incarnation, engine_version = excluded.engine_version,
 status = excluded.status, native_endpoint = excluded.native_endpoint,
 last_error = excluded.last_error, access_policy = excluded.access_policy,
 instance_type = excluded.instance_type, instance_count = excluded.instance_count,
 created = excluded.created, updated = excluded.updated, due = excluded.due,
 version = excluded.version, config_version = excluded.config_version
`

type PutDomainParams struct {
	Partition      string
	AccountID      string
	Region         string
	Name           string
	Incarnation    string
	EngineVersion  string
	Status         string
	NativeEndpoint string
	LastError      string
	AccessPolicy   string
	InstanceType   string
	InstanceCount  int64
	Created        int64
	Updated        int64
	Due            int64
	Version        int64
	ConfigVersion  int64
}

func (q *Queries) PutDomain(ctx context.Context, arg PutDomainParams) error {
	_, err := q.db.ExecContext(ctx, putDomain,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.Incarnation,
		arg.EngineVersion,
		arg.Status,
		arg.NativeEndpoint,
		arg.LastError,
		arg.AccessPolicy,
		arg.InstanceType,
		arg.InstanceCount,
		arg.Created,
		arg.Updated,
		arg.Due,
		arg.Version,
		arg.ConfigVersion,
	)
	return err
}

const putPolicyPrincipal = `-- name: PutPolicyPrincipal :exec
INSERT INTO opensearch_policy_principal (partition, account_id, region, name, principal_arn, principal_id) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type PutPolicyPrincipalParams struct {
	Partition    string
	AccountID    string
	Region       string
	Name         string
	PrincipalArn string
	PrincipalID  string
}

func (q *Queries) PutPolicyPrincipal(ctx context.Context, arg PutPolicyPrincipalParams) error {
	_, err := q.db.ExecContext(ctx, putPolicyPrincipal,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.PrincipalArn,
		arg.PrincipalID,
	)
	return err
}

const putTag = `-- name: PutTag :exec
INSERT INTO opensearch_tag (partition, account_id, region, name, tag_key, tag_value) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type PutTagParams struct {
	Partition string
	AccountID string
	Region    string
	Name      string
	TagKey    string
	TagValue  string
}

func (q *Queries) PutTag(ctx context.Context, arg PutTagParams) error {
	_, err := q.db.ExecContext(ctx, putTag,
		arg.Partition,
		arg.AccountID,
		arg.Region,
		arg.Name,
		arg.TagKey,
		arg.TagValue,
	)
	return err
}
