// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"stackd/storage/sqlite"
)

const connectionARNs = `-- name: ConnectionARNs :many
SELECT CAST('arn:' || partition || ':events:' || region || ':' || account || ':connection/' || name || '/' || id AS TEXT) AS arn FROM eventbridge_connections WHERE partition=? AND account=? ORDER BY arn
`

type ConnectionARNsParams struct {
	Partition string
	Account   string
}

func (q *Queries) ConnectionARNs(ctx context.Context, arg ConnectionARNsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, connectionARNs, arg.Partition, arg.Account)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var arn string
		if err := rows.Scan(&arn); err != nil {
			return nil, err
		}
		items = append(items, arn)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM eventbridge_connections WHERE partition=? AND account=? AND region=? AND name=?
`

type DeleteConnectionParams struct {
	Partition string
	Account   string
	Region    string
	Name      string
}

func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteConnection,
		arg.Partition,
		arg.Account,
		arg.Region,
		arg.Name,
	)
	return err
}

const deleteConnectionParameters = `-- name: DeleteConnectionParameters :exec
DELETE FROM eventbridge_connection_parameters WHERE connection_id=?
`

func (q *Queries) DeleteConnectionParameters(ctx context.Context, connectionID string) error {
	_, err := q.db.ExecContext(ctx, deleteConnectionParameters, connectionID)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT "partition", account, region, name, id, description, authorization_type, state, state_reason, secret_arn, kms_key_identifier, username, api_key_name, client_id, authorization_endpoint, oauth_method, has_auth, has_invocation, has_oauth_http, created, modified, last_authorized, due_seconds, due_nanos, version FROM eventbridge_connections WHERE partition=? AND account=? AND region=? AND name=?
`

type GetConnectionParams struct {
	Partition string
	Account   string
	Region    string
	Name      string
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (EventbridgeConnection, error) {
	row := q.db.QueryRowContext(ctx, getConnection,
		arg.Partition,
		arg.Account,
		arg.Region,
		arg.Name,
	)
	var i EventbridgeConnection
	err := row.Scan(
		&i.Partition,
		&i.Account,
		&i.Region,
		&i.Name,
		&i.ID,
		&i.Description,
		&i.AuthorizationType,
		&i.State,
		&i.StateReason,
		&i.SecretArn,
		&i.KmsKeyIdentifier,
		&i.Username,
		&i.ApiKeyName,
		&i.ClientID,
		&i.AuthorizationEndpoint,
		&i.OauthMethod,
		&i.HasAuth,
		&i.HasInvocation,
		&i.HasOauthHttp,
		&i.Created,
		&i.Modified,
		&i.LastAuthorized,
		&i.DueSeconds,
		&i.DueNanos,
		&i.Version,
	)
	return i, err
}

const getConnectionByID = `-- name: GetConnectionByID :one
SELECT "partition", account, region, name, id, description, authorization_type, state, state_reason, secret_arn, kms_key_identifier, username, api_key_name, client_id, authorization_endpoint, oauth_method, has_auth, has_invocation, has_oauth_http, created, modified, last_authorized, due_seconds, due_nanos, version FROM eventbridge_connections WHERE id=?
`

func (q *Queries) GetConnectionByID(ctx context.Context, id string) (EventbridgeConnection, error) {
	row := q.db.QueryRowContext(ctx, getConnectionByID, id)
	var i EventbridgeConnection
	err := row.Scan(
		&i.Partition,
		&i.Account,
		&i.Region,
		&i.Name,
		&i.ID,
		&i.Description,
		&i.AuthorizationType,
		&i.State,
		&i.StateReason,
		&i.SecretArn,
		&i.KmsKeyIdentifier,
		&i.Username,
		&i.ApiKeyName,
		&i.ClientID,
		&i.AuthorizationEndpoint,
		&i.OauthMethod,
		&i.HasAuth,
		&i.HasInvocation,
		&i.HasOauthHttp,
		&i.Created,
		&i.Modified,
		&i.LastAuthorized,
		&i.DueSeconds,
		&i.DueNanos,
		&i.Version,
	)
	return i, err
}

const getConnectionParameters = `-- name: GetConnectionParameters :many
SELECT connection_id, ordinal, target, location, "key", value, secret FROM eventbridge_connection_parameters WHERE connection_id=? ORDER BY ordinal
`

func (q *Queries) GetConnectionParameters(ctx context.Context, connectionID string) ([]EventbridgeConnectionParameter, error) {
	rows, err := q.db.QueryContext(ctx, getConnectionParameters, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventbridgeConnectionParameter{}
	for rows.Next() {
		var i EventbridgeConnectionParameter
		if err := rows.Scan(
			&i.ConnectionID,
			&i.Ordinal,
			&i.Target,
			&i.Location,
			&i.Key,
			&i.Value,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnections = `-- name: ListConnections :many
SELECT "partition", account, region, name, id, description, authorization_type, state, state_reason, secret_arn, kms_key_identifier, username, api_key_name, client_id, authorization_endpoint, oauth_method, has_auth, has_invocation, has_oauth_http, created, modified, last_authorized, due_seconds, due_nanos, version FROM eventbridge_connections WHERE partition=? AND account=? AND region=? ORDER BY name
`

type ListConnectionsParams struct {
	Partition string
	Account   string
	Region    string
}

func (q *Queries) ListConnections(ctx context.Context, arg ListConnectionsParams) ([]EventbridgeConnection, error) {
	rows, err := q.db.QueryContext(ctx, listConnections, arg.Partition, arg.Account, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventbridgeConnection{}
	for rows.Next() {
		var i EventbridgeConnection
		if err := rows.Scan(
			&i.Partition,
			&i.Account,
			&i.Region,
			&i.Name,
			&i.ID,
			&i.Description,
			&i.AuthorizationType,
			&i.State,
			&i.StateReason,
			&i.SecretArn,
			&i.KmsKeyIdentifier,
			&i.Username,
			&i.ApiKeyName,
			&i.ClientID,
			&i.AuthorizationEndpoint,
			&i.OauthMethod,
			&i.HasAuth,
			&i.HasInvocation,
			&i.HasOauthHttp,
			&i.Created,
			&i.Modified,
			&i.LastAuthorized,
			&i.DueSeconds,
			&i.DueNanos,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextConnectionJob = `-- name: NextConnectionJob :one
SELECT "partition", account, region, name, id, description, authorization_type, state, state_reason, secret_arn, kms_key_identifier, username, api_key_name, client_id, authorization_endpoint, oauth_method, has_auth, has_invocation, has_oauth_http, created, modified, last_authorized, due_seconds, due_nanos, version FROM eventbridge_connections WHERE due_seconds IS NOT NULL ORDER BY due_seconds,due_nanos,id LIMIT 1
`

func (q *Queries) NextConnectionJob(ctx context.Context) (EventbridgeConnection, error) {
	row := q.db.QueryRowContext(ctx, nextConnectionJob)
	var i EventbridgeConnection
	err := row.Scan(
		&i.Partition,
		&i.Account,
		&i.Region,
		&i.Name,
		&i.ID,
		&i.Description,
		&i.AuthorizationType,
		&i.State,
		&i.StateReason,
		&i.SecretArn,
		&i.KmsKeyIdentifier,
		&i.Username,
		&i.ApiKeyName,
		&i.ClientID,
		&i.AuthorizationEndpoint,
		&i.OauthMethod,
		&i.HasAuth,
		&i.HasInvocation,
		&i.HasOauthHttp,
		&i.Created,
		&i.Modified,
		&i.LastAuthorized,
		&i.DueSeconds,
		&i.DueNanos,
		&i.Version,
	)
	return i, err
}

const putConnection = `-- name: PutConnection :exec
INSERT INTO eventbridge_connections(partition,account,region,name,id,description,authorization_type,state,state_reason,secret_arn,kms_key_identifier,username,api_key_name,client_id,authorization_endpoint,oauth_method,has_auth,has_invocation,has_oauth_http,created,modified,last_authorized,due_seconds,due_nanos,version)
VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(partition,account,region,name) DO UPDATE SET id=excluded.id,description=excluded.description,authorization_type=excluded.authorization_type,state=excluded.state,state_reason=excluded.state_reason,secret_arn=excluded.secret_arn,kms_key_identifier=excluded.kms_key_identifier,username=excluded.username,api_key_name=excluded.api_key_name,client_id=excluded.client_id,authorization_endpoint=excluded.authorization_endpoint,oauth_method=excluded.oauth_method,has_auth=excluded.has_auth,has_invocation=excluded.has_invocation,has_oauth_http=excluded.has_oauth_http,created=excluded.created,modified=excluded.modified,last_authorized=excluded.last_authorized,due_seconds=excluded.due_seconds,due_nanos=excluded.due_nanos,version=excluded.version
`

type PutConnectionParams struct {
	Partition             string
	Account               string
	Region                string
	Name                  string
	ID                    string
	Description           string
	AuthorizationType     string
	State                 string
	StateReason           string
	SecretArn             string
	KmsKeyIdentifier      string
	Username              string
	ApiKeyName            string
	ClientID              string
	AuthorizationEndpoint string
	OauthMethod           string
	HasAuth               bool
	HasInvocation         bool
	HasOauthHttp          bool
	Created               time.Time
	Modified              time.Time
	LastAuthorized        sql.NullTime
	DueSeconds            sql.NullInt64
	DueNanos              int64
	Version               sqlite.Uint64
}

func (q *Queries) PutConnection(ctx context.Context, arg PutConnectionParams) error {
	_, err := q.db.ExecContext(ctx, putConnection,
		arg.Partition,
		arg.Account,
		arg.Region,
		arg.Name,
		arg.ID,
		arg.Description,
		arg.AuthorizationType,
		arg.State,
		arg.StateReason,
		arg.SecretArn,
		arg.KmsKeyIdentifier,
		arg.Username,
		arg.ApiKeyName,
		arg.ClientID,
		arg.AuthorizationEndpoint,
		arg.OauthMethod,
		arg.HasAuth,
		arg.HasInvocation,
		arg.HasOauthHttp,
		arg.Created,
		arg.Modified,
		arg.LastAuthorized,
		arg.DueSeconds,
		arg.DueNanos,
		arg.Version,
	)
	return err
}

const putConnectionParameter = `-- name: PutConnectionParameter :exec
INSERT INTO eventbridge_connection_parameters(connection_id,ordinal,target,location,key,value,secret) VALUES(?,?,?,?,?,?,?)
`

type PutConnectionParameterParams struct {
	ConnectionID string
	Ordinal      int64
	Target       string
	Location     string
	Key          string
	Value        string
	Secret       bool
}

func (q *Queries) PutConnectionParameter(ctx context.Context, arg PutConnectionParameterParams) error {
	_, err := q.db.ExecContext(ctx, putConnectionParameter,
		arg.ConnectionID,
		arg.Ordinal,
		arg.Target,
		arg.Location,
		arg.Key,
		arg.Value,
		arg.Secret,
	)
	return err
}
